import {z} from 'zod';
import {requireProcedureMode} from '../procedure-induction/admission';
import {receiveWork,attachWorkEntity,loadEmployeeConversationThread,appendEmployeeConversationMessage,updateEmployeeConversationThreadContext} from '@finnor/db';
import {getArtifactBytes} from '@finnor/artifacts';
import {loadEnterpriseBeliefView} from '../enterprise-beliefs';
import type {PeMutationContext} from '../types';
import {authorize,codeIdentity,newId,principal,sha,stable,tx,unavailable,schemaIdentity} from '../evidence-execution/store';
import {P1_VERSION,parseHarnessRequest,type HarnessProgram} from './contracts';
import {constructGraph,constructModules,validateAcceptance} from './compiler';
import {selectHarnessPlan} from './plan';
import {assertProgramCurrent,enqueueProgram,readCurrentProgram,requestRow,safePredicate,trace,type ProgramRow} from './store';
import {harnessPorts} from './ports';

export const PROGRAM_OPERATIONS=['program-submit','program-read','program-witness','program-module','program-projection','program-cancel','program-resume','program-artifact','program-ports','program-interface-module'] as const;
const idSchema=z.object({programId:z.string().uuid()}).strict();

export async function submitHarnessProgram(ctx:PeMutationContext,body:unknown){
 const request=parseHarnessRequest(body);if(request.procedure)requireProcedureMode(request.procedure);await authorize(ctx,request.root,request.workId?[{type:'work',id:request.workId}]:[]);validateAcceptance(request);
 if(request.mode!=='ordinary_disposable'||process.env.NODE_ENV==='production'||process.env.FINNOR_P4_PROFILE!=='ordinary_disposable')throw Error('HARNESS_PROTECTED_FUNDING_ADMISSION_AND_RUNTIME_UNAVAILABLE');
 if(request.limits?.requiredAggregateLimits&&Object.keys(request.limits.requiredAggregateLimits).length)throw Error('HARNESS_AGGREGATE_RESOURCE_BOUND_UNAVAILABLE');
 const user=await tx(ctx,async c=>(await c.query('SELECT role,status FROM finnor_os.users WHERE tenant_id=$1 AND id=$2',[ctx.auth.tenantId,principal(ctx)])).rows[0],true);if(user?.status!=='active'||user.role!=='owner')throw unavailable();
 for(const s of request.sources)if(s.source.kind!=='derivation')await authorize(ctx,s.source.subject,s.source.kind==='artifact'?[{type:'document',id:s.source.documentId}]:[]);
 if(request.threadId&&!await loadEmployeeConversationThread({tenantId:ctx.auth.tenantId,ownerEmployeeId:principal(ctx),threadId:request.threadId}))throw unavailable();
 const digest=sha(request),code=await codeIdentity(),schemaDigest=await schemaIdentity(ctx),view=await loadEnterpriseBeliefView(ctx,{root:request.root,validAt:request.validAt,knowledgeAt:request.knowledgeAt,maxClaims:1000});
 const accepted=await tx(ctx,async c=>{
  await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,4401))',[ctx.auth.tenantId+':'+principal(ctx)+':'+request.idempotencyKey]);
  const prior=(await c.query<ProgramRow>('SELECT * FROM finnor_os.p1_requests WHERE tenant_id=$1 AND principal_id=$2 AND idempotency_key=$3',[ctx.auth.tenantId,principal(ctx),request.idempotencyKey])).rows[0];if(prior){if(prior.request_digest!==digest)throw Error('IDEMPOTENCY_REQUEST_CONFLICT');await authorize(ctx,request.root,[{type:'work',id:prior.work_id}]);return {programId:prior.id,workId:prior.work_id,workRevision:prior.work_input_id,status:prior.status,replayed:true};}
  let parent:ProgramRow|null=null;if(!request.parentProgramId&&request.workId)parent=(await c.query<ProgramRow>('SELECT * FROM finnor_os.p1_requests WHERE tenant_id=$1 AND principal_id=$2 AND work_id=$3 ORDER BY created_at DESC,id DESC LIMIT 1',[ctx.auth.tenantId,principal(ctx),request.workId])).rows[0]??null;if(parent&&stable(parent.request.root)!==stable(request.root))throw Error('PARENT_PROGRAM_SCOPE_MISMATCH');if(request.parentProgramId){parent=await requestRow(ctx,request.parentProgramId);await authorize(ctx,parent.request.root,[{type:'work',id:parent.work_id}]);if(request.workId!==parent.work_id||stable(request.root)!==stable(parent.request.root))throw Error('PARENT_PROGRAM_SCOPE_MISMATCH');}
  const intake=request.workId&&request.workInputId?{workId:request.workId,workInputId:request.workInputId}:await receiveWork({tenantId:ctx.auth.tenantId,userId:principal(ctx),workId:request.workId,instruction:request.instruction,channel:'console',idempotencyKey:'p1:'+principal(ctx)+':'+request.idempotencyKey,activeContext:{entityType:request.root.entityType,entityId:request.root.entityId},authorityContext:{principalId:principal(ctx),producer:'P1_ORDINARY_NO_EFFECT_GRANT'}});
  // The selected GoalSpec and immutable request already bind root/Work/input.
  // Optional unversioned Core relationship metadata would invalidate current
  // scientific owner cuts. Preserve those cuts without relaxing S1 completeness.
  if(!request.ownerBindings&&!(request.operations??[]).some(o=>o.op==='design_inquiry'||o.op==='simulate'))await attachWorkEntity(ctx.auth.tenantId,intake.workId,{...request.root,source:'P1:accepted-method-objective'});
  const work=(await c.query<{id:string;body:unknown}>('SELECT id::text,to_jsonb(w) body FROM finnor_os.work_inputs w WHERE tenant_id=$1 AND work_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1',[ctx.auth.tenantId,intake.workId])).rows[0];if(work?.id!==intake.workInputId)throw Error('EXACT_WORK_REVISION_CHANGED');
  const maxSteps=request.limits?.maxSteps??1024,maxAttempts=request.limits?.maxAttempts??4,deadlineAt=new Date(Date.now()+(request.limits?.deadlineMs??300000)).toISOString();
  await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,4402))',[ctx.auth.tenantId+':'+principal(ctx)+':'+intake.workId]);
  const existingEpisode=(await c.query('SELECT * FROM finnor_os.p1_episodes WHERE tenant_id=$1 AND principal_id=$2 AND work_id=$3',[ctx.auth.tenantId,principal(ctx),intake.workId])).rows[0];
  const episode=existingEpisode??{id:newId(),max_steps:maxSteps,max_attempts:maxAttempts,steps_used:0,attempts_used:0,max_candidates:request.limits?.maxCandidates??8,max_depth:request.limits?.maxDepth??12,candidates_used:0,deadline_at:deadlineAt};
  if(parent&&parent.episode_id!==episode.id)throw Error('ORIGINAL_EPISODE_GRANT_MISMATCH');
  if(Number(episode.candidates_used)+2>Number(episode.max_candidates))throw Error('ORIGINAL_CANDIDATE_BOUND_EXHAUSTED');if(validateAcceptance(request).depth>Number(episode.max_depth))throw Error('ORIGINAL_EPISODE_DEPTH_EXHAUSTED');const id=newId(),modules=constructModules(request,code.digest);const parentPlan=(await c.query<{id:string}>('SELECT id::text FROM finnor_os.work_plan_revisions WHERE tenant_id=$1 AND work_id=$2 ORDER BY (status=\'active\') DESC,revision DESC LIMIT 1',[ctx.auth.tenantId,intake.workId])).rows[0];
  const selected=await selectHarnessPlan(ctx,request,{programId:id,workId:intake.workId,inputId:work.id,inputDigest:sha(work.body),parentRevisionId:parentPlan?.id??null,rightsRevision:view.rights.revision,deadlineAt:new Date(episode.deadline_at).toISOString()});
  await c.query('INSERT INTO finnor_os.p1_episodes(id,tenant_id,principal_id,work_id,max_steps,max_attempts,deadline_at,max_candidates,max_depth,candidates_used) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,2) ON CONFLICT(tenant_id,principal_id,work_id) DO NOTHING',[episode.id,ctx.auth.tenantId,principal(ctx),intake.workId,episode.max_steps,episode.max_attempts,episode.deadline_at,episode.max_candidates,episode.max_depth]);if(existingEpisode)await c.query('UPDATE finnor_os.p1_episodes SET candidates_used=candidates_used+2 WHERE id=$1',[episode.id]);
  const program:HarnessProgram={schema:'finnor.harness-program.v1',id,tenantId:ctx.auth.tenantId,principalId:principal(ctx),sharing:{scope:'PRINCIPAL',policy:'CURRENT_S1_AUTHORIZATION'},work:{id:intake.workId,revision:work.id,inputDigest:sha(work.body),planRevisionId:selected.planRevisionId},parents:parent?[parent.id]:[],acceptance:request.acceptance,acceptanceDigest:sha(request.acceptance),goal:selected.goal,
   rights:view.rights,validAt:view.validAt,knowledgeAt:view.knowledgeAt,producer:{version:P1_VERSION,codeDigest:code.digest,schemaDigest},graph:constructGraph(request,modules,new Date(episode.deadline_at).toISOString()),planGraph:selected.planGraph,modules,candidates:modules.map(m=>({id:'candidate:'+m.structureDigest,moduleId:m.id,structureDigest:m.structureDigest,status:'PROPOSED',counterexamples:[]})),semanticBindings:[],observableBranches:[],effectProposals:[],dependencies:[],witnesses:[],bounds:{episodeId:String(episode.id),maxSteps:Number(episode.max_steps),maxDepth:Number(episode.max_depth),maxAttempts:Number(episode.max_attempts),maxCandidates:Number(episode.max_candidates),deadlineAt:new Date(episode.deadline_at).toISOString(),reservation:null},fallback:{status:'UNAVAILABLE',predicate:'CURRENT_ADMITTED_HARNESS_PREDECESSOR_UNAVAILABLE'},result:null,independentChecks:[],costs:{usd:null,status:'UNMETERED',attempts:Number(episode.attempts_used),steps:Number(episode.steps_used),wallMs:0,modelInvocations:[],nativeInvocations:[]},runtime:{node:process.version,imageDigest:null,jobId:null,workerId:null,deliveryAttemptId:null,claimFence:null},status:'PROPOSED',admission:null,funding:null,unavailableBindings:['S4_MANDATE_IF_NOT_OWNER_BOUND','S5_PROTECTED_FUNDING','S8_GENERIC_HARNESS_ADMISSION','P2_COMPARE','P3_HARNESS_RUNTIME','P5_ADMITTED_INTERFACES','P6_PROCEDURE_CAPSULE','M1_P4_DECISION_SUFFICIENCY_UNPASSED','ATTESTED_IMAGE','COMPLETE_BILLING_AND_AGGREGATE_RESOURCES','INDEPENDENT_SEALED_GATE'],projection:{kind:'program_synthesis',workId:intake.workId,inspect:'program-read',run:'program-resume',download:'program-artifact'}};
  // A native steering input cannot race the selection/publication cut.
  await c.query('SELECT id FROM finnor_os.works WHERE tenant_id=$1 AND id=$2 FOR SHARE',[ctx.auth.tenantId,intake.workId]);const current=(await c.query('SELECT id::text FROM finnor_os.work_inputs WHERE tenant_id=$1 AND work_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1',[ctx.auth.tenantId,intake.workId])).rows[0];if(current?.id!==work.id)throw Error('EXACT_WORK_REVISION_CHANGED');
  await c.query('INSERT INTO finnor_os.p1_requests(id,tenant_id,principal_id,work_id,work_input_id,work_input_digest,episode_id,plan_revision_id,idempotency_key,request_digest,request,proposed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb)',[id,ctx.auth.tenantId,principal(ctx),intake.workId,work.id,sha(work.body),episode.id,selected.planRevisionId,request.idempotencyKey,digest,stable(request),stable(program)]);
  for(const module of modules)await c.query('INSERT INTO finnor_os.p1_modules(tenant_id,principal_id,digest,body) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT DO NOTHING',[ctx.auth.tenantId,principal(ctx),module.compiledDigest,stable(module)]);
  const q=await requestRow(ctx,id,c);await trace(ctx,q,'RESOLVE_OUTCOME',{acceptedDigest:program.acceptanceDigest,goal:program.goal,work:program.work,rights:program.rights,capabilityAuthority:false},c);await enqueueProgram(ctx,q,'initial',c);
  return {programId:id,workId:intake.workId,workRevision:work.id,status:'QUEUED',replayed:false};
 });
 if(request.threadId){await appendEmployeeConversationMessage({tenantId:ctx.auth.tenantId,ownerEmployeeId:principal(ctx),threadId:request.threadId,role:'user',channel:'text',originalText:request.instruction,idempotencyKey:'p1:'+request.idempotencyKey,workId:accepted.workId,workInputId:accepted.workRevision,resolutionSnapshot:{producer:'P1',programId:accepted.programId,acceptanceDigest:sha(request.acceptance),qualification:'ANALYTICAL_DRAFT'}});await updateEmployeeConversationThreadContext({tenantId:ctx.auth.tenantId,ownerEmployeeId:principal(ctx),threadId:request.threadId,activeWorkId:accepted.workId,activeReferences:[...((await loadEmployeeConversationThread({tenantId:ctx.auth.tenantId,ownerEmployeeId:principal(ctx),threadId:request.threadId}))?.thread.activeReferences??[]).filter(ref=>stable(ref)!==stable(request.root)),request.root]});}
 return accepted;
}

export async function handleProgramOperation(ctx:PeMutationContext,operation:string,body:unknown):Promise<{status:number;body:unknown}>{
 try{
  if(operation==='program-interface-module')return {status:200,body:{module:await (await import('./interface')).loadProgrammeInterfaceModule(ctx,body),effectAuthority:false,protectedEligible:false}};
  if(operation==='program-submit')return {status:202,body:await submitHarnessProgram(ctx,body)};
  if(operation==='program-projection'){const input=z.object({root:z.object({entityType:z.string(),entityId:z.string().uuid()}).strict(),workId:z.string().uuid()}).strict().parse(body);await authorize(ctx,input.root as any,[{type:'work',id:input.workId}]);const rows=await tx(ctx,async c=>(await c.query<{id:string}>('SELECT id FROM finnor_os.p1_requests WHERE tenant_id=$1 AND principal_id=$2 AND work_id=$3 ORDER BY created_at DESC LIMIT 20',[ctx.auth.tenantId,principal(ctx),input.workId])).rows,true);const programs=[];for(const row of rows){const q=await requestRow(ctx,row.id);if(stable(q.request.root)===stable(input.root))programs.push(await readCurrentProgram(ctx,row.id));}await authorize(ctx,input.root as any,[{type:'work',id:input.workId}]);return {status:200,body:{schema:'finnor.p1.work-projection.v1',workId:input.workId,programs}};}
  if(operation==='program-ports'){const input=z.object({root:z.object({entityType:z.string(),entityId:z.string().uuid()}).strict()}).strict().parse(body);await authorize(ctx,input.root as any);return {status:200,body:{ports:harnessPorts()}};}
  if(operation==='program-read')return {status:200,body:await readCurrentProgram(ctx,idSchema.parse(body).programId)};
  if(operation==='program-cancel'){const q=await requestRow(ctx,idSchema.parse(body).programId);await authorize(ctx,q.request.root,[{type:'work',id:q.work_id}]);
   if(!['TESTED','INVALIDATED','CANCELLED'].includes(q.status)){const loop=await tx(ctx,async c=>(await c.query<{state:string}>('SELECT state FROM finnor_os.work_objective_loops WHERE tenant_id=$1 AND work_id=$2 AND created_by=$3',[q.tenant_id,q.work_id,q.principal_id])).rows[0],true);if(loop&&!['completed','cancelled'].includes(loop.state))await (await import('../../../orchestration/src/objective-loop')).controlWorkObjective({tenantId:q.tenant_id,workId:q.work_id,actorId:principal(ctx),command:'cancel'});}
   return {status:200,body:await tx(ctx,async c=>{const r=await requestRow(ctx,q.id,c,true);if(!['TESTED','INVALIDATED','CANCELLED'].includes(r.status)){await c.query("UPDATE finnor_os.p1_requests SET status='CANCELLED',generation=generation+1,updated_at=clock_timestamp() WHERE tenant_id=$1 AND principal_id=$2 AND id=$3",[q.tenant_id,q.principal_id,q.id]);await trace(ctx,r,'CANCELLED',{requestedBy:principal(ctx),costsRetained:true,possibleExternalMutation:false},c);}return {programId:q.id,status:['TESTED','INVALIDATED','CANCELLED'].includes(r.status)?r.status:'CANCELLED'};})};}
  if(operation==='program-resume'){const current=await readCurrentProgram(ctx,idSchema.parse(body).programId);if(!['WAITING','FAILED','PARTIAL'].includes(current.status))throw Error('CURRENT_RESUMABLE_PROGRAM_REQUIRED');const q=await requestRow(ctx,current.programId);await assertProgramCurrent(ctx,q);await enqueueProgram(ctx,q,'resume-'+Date.now());return {status:202,body:{programId:q.id,workId:q.work_id,status:q.status,originalGrantRetained:true}};}
  if(operation==='program-witness'){const r=await readCurrentProgram(ctx,idSchema.parse(body).programId);if(r.status!=='TESTED'||!r.program?.result)throw Error('CURRENT_CHECKED_PROGRAM_REQUIRED');return {status:200,body:{work:r.program.work,acceptanceDigest:r.program.acceptanceDigest,witnesses:r.program.witnesses,dependencies:r.program.dependencies,checks:r.program.independentChecks,observableBranches:r.program.observableBranches,qualification:'ANALYTICAL_DRAFT_NOT_IC_SELECTION_OR_BUSINESS_TRUTH'}};}
  if(operation==='program-module'){const input=idSchema.extend({moduleId:z.string().min(1).max(100)}).strict().parse(body),r=await readCurrentProgram(ctx,input.programId);const module=r.program?.modules.find(m=>m.id===input.moduleId);if(!module)throw unavailable();if(sha(module.compiled)!==module.compiledDigest)throw Error('MODULE_BYTE_DIGEST_MISMATCH');return {status:200,body:{module}};}
  if(operation==='program-artifact'){const r=await readCurrentProgram(ctx,idSchema.parse(body).programId);if(r.status!=='TESTED'||!r.program?.result)throw Error('CURRENT_CHECKED_PROGRAM_ARTIFACT_REQUIRED');const ref=r.program.result.artifact;const artifact=await getArtifactBytes({...ctx.auth,userId:principal(ctx)},ref.documentId,ref.versionId);if(sha(artifact.bytes)!==ref.sha256||artifact.ir.semanticHash!==ref.semanticHash)throw Error('ARTIFACT_SELECTED_BYTE_OR_SEMANTIC_MISMATCH');const latest=await readCurrentProgram(ctx,r.programId);if(latest.status!=='TESTED'||latest.program?.result?.digest!==r.program.result.digest)throw Error('ARTIFACT_CURRENTNESS_CHANGED_DURING_READ');return {status:200,body:{documentId:ref.documentId,versionId:ref.versionId,mediaType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',fileName:qFile(r.program.acceptance.deliverable.title),sha256:ref.sha256,semanticHash:ref.semanticHash,bytesBase64:artifact.bytes.toString('base64'),qualification:'CURRENT_CHECKED_ANALYTICAL_DRAFT'}};}
  return {status:404,body:{code:'NOT_FOUND'}};
 }catch(error){console.error('[P1 owner operation failed]',{predicate:safePredicate(error),code:(error as any).cause?.code??(error as any).code??null});if((error as Error).message==='Evidence resource is unavailable in the authenticated scope'||(error as any).code==='PE_ENTITY_NOT_FOUND')return {status:404,body:{error:'Programme resource is unavailable in the authenticated scope',code:'PE_ENTITY_NOT_FOUND'}};if(error instanceof z.ZodError)return {status:400,body:{code:'HARNESS_SCHEMA_INVALID',predicate:'BOUNDED_TYPED_PROGRAM_REQUEST_REQUIRED'}};return {status:422,body:{code:'HARNESS_PREDICATE_UNPASSED',predicate:safePredicate(error)}};}
}
function qFile(title:string){return title.replace(/[^\p{L}\p{N} _.-]/gu,'').slice(0,200)+'.docx';}
