import type { HarnessProgram } from './contracts';

/** Wire requests for future owners. These are pending requests, never receipts. */
export function harnessPorts(program?:HarnessProgram){return {
 P2:{schema:'finnor.p1.p2-comparison-request.v1',status:'ORDINARY_EXECUTED_OWNER_READER_JOINED',required:'CURRENT_S4_POLICY_AND_S5_NATIVE_ATTEMPT_ENVELOPE',reader:'compute-search-read',submit:'compute-search-submit',producerSchema:'finnor.compute-search-plan.v1',protectedAdmission:false,candidateModuleIds:program?.modules.map(m=>m.id)??[],nativeFallback:'FIXED_CHECKED_FEWEST_INSTRUCTIONS_V1'},
 P3:{schema:'finnor.p1.p3-harness-request.v1',status:'PENDING_OWNER_CONTRACT',required:'AUTHENTICATED_HARNESS_PROGRAM_PORT_AND_QUALIFIED_RUNTIME',acceptedProducerSchema:'finnor.harness-program.v1',programmeDigest:program?.result?.digest??null,moduleDigests:program?.modules.map(m=>m.compiledDigest)??[],registeredNativeTagIsCompatible:false,outputEvidenceClass:'MODEL_RELATIVE_NOT_FIELD_OBSERVATION',frozenNativeTransport:{status:'JOINED_REGISTERED_NATIVE_ONLY',commit:'684c4f48c93d5f5e8071d3b5c344b9b1668921e1',schema:'finnor.branch-request.v1',darwinIsolation:false,admission:false,harnessPortStatus:424}},
 P5:{schema:'finnor.p1.interface-module-request.v1',status:'CURRENT_TYPED_PURE_INTERFACE_DEPENDENCY_JOINED',reader:'program-interface-module',required:'EXACT_CHECKED_PROGRAMME_WORK_OUTPUT_AND_PRACTICED_INTERFACE',runtime:'P3_REGISTERED_NATIVE_WITH_S6_PURE_BINDING',businessInvocation:'PENDING_CURRENT_S3_S4_S5_S6_AND_INDEPENDENT_S8',nativeCatalogueVersion:'p1-bounded-native-v1'},
 P6:{schema:'finnor.p1.p6-procedure-request.v1',status:'PENDING_OWNER_CONTRACT',required:'CURRENT_ADMITTED_PROCEDURE_CAPSULE_SCHEMA_RIGHTS_PRECONDITIONS',nativeCatalogueIsProcedureCapsule:false},
 M1:{schema:'finnor.p1.m1-decision-slice-request.v1',status:'FROZEN_NATIVE_READER_JOINED',required:'OWNER_DECISION_SUFFICIENCY_AND_TYPED_P4_DEMAND_RESOLUTION_REMAIN_UNPASSED',frozenObservedCommit:'32d7d6ba6e8bfe344a04a63ffee34e4904df654e',genericP4CoverageCertifiesDecisionSufficiency:false},
 S8:{schema:'finnor.p1.s8-admission-request.v1',status:'PENDING_OWNER_CONTRACT',required:'GENERIC_HARNESS_PROGRAM_ADMISSION_DOMAIN_AND_INDEPENDENT_AUTHORITY',owningInterfaceRequested:'p1-bounded-harness-v1',existingS5JointFiniteInterfaceCompatible:false,payload:{schema:'finnor.harness-program.v1',producerCodeDigest:program?.producer.codeDigest??null,acceptanceDigest:program?.acceptanceDigest??null,moduleDigests:program?.modules.map(m=>m.compiledDigest)??[],dependencyRefs:program?.dependencies??[],evaluation:{sealedOracleDigest:null,independentAuthoritySignature:null}},admissionGranted:false},
 M3:{schema:'finnor.p1.m3-input.v1',status:'READY_CONSUMER_CONTRACT',nextDelivery:'phase05-M3',input:'HarnessProgram',outputOwner:'M3_CAPITAL_PROGRAM',capitalOrContingentCommitmentAuthorityGranted:false},
 P7:{schema:'finnor.p1.p7-continuation.v1',status:'PENDING_OWNER_CONTRACT',parents:program?.parents??[],dependencyVector:program?.dependencies??[],localRecompileSupported:true,coordinatedGlobalContinuationClaimed:false},
 P8:{schema:'finnor.p1.p8-producer-evolution.v1',status:'PENDING_OWNER_CONTRACT',evaluationOutputOwnedByIndependentAuthority:true,producerMayPromoteItself:false},
};}
