/** Named Phase 6 certification ledger. A case is PASS only when every executable
 * gate attached to it passes; the runner rejects missing gates, duplicate IDs,
 * skipped tests, pending tests, and empty suites. */

export const P6_GATE_IDS = [
  "architecture",
  "typecheck",
  "planning-unit",
  "runtime-integration",
  "concurrency",
  "performance",
  "migration",
  "pe-regressions",
  "core-regressions",
  "contracts",
  "builds",
] as const;

export type P6GateId = (typeof P6_GATE_IDS)[number];

export interface P6MandatoryCase {
  id: string;
  category: string;
  statement: string;
  gates: readonly P6GateId[];
}

function cases(category: string, gates: readonly P6GateId[], statements: readonly string[]): P6MandatoryCase[] {
  return statements.map((statement, index) => ({
    id: `${category}_${String(index + 1).padStart(2, "0")}`,
    category,
    statement,
    gates,
  }));
}

export const P6_MANDATORY_CASES: readonly P6MandatoryCase[] = Object.freeze([
  ...cases("architecture", ["architecture", "typecheck"], [
    "Planner returns PlanningResult rather than executable DomainAction arrays.",
    "Model output is a bounded CandidatePlan envelope with an absolute maximum of four.",
    "The deterministic compiler is the only candidate validity and selection authority.",
    "Only the PlanGraph execution adapter may materialize DomainAction rows.",
    "GoalSpec is tied to exact Work, WorkInput, targets, deadline, non-goals, and accepted success criteria.",
    "ConstraintSet separates deterministic hard constraints from discardable model preferences.",
    "PlanningWorldSnapshot is bounded provenance over existing truth and contains no raw secret owner.",
    "PlanGraph owns only query, action, wait, and check intent while existing primitives own execution state.",
    "The existing plugin registry and action-hardening manifest remain the capability owners.",
    "PlanRevision is immutable history and replanning creates a child revision.",
    "ObjectiveLoop remains the durable controller for long-running graphs.",
    "ObjectiveSuccessVerification remains the basis of CompletionProof.",
    "Server-side attention uses the existing Operational Query architecture.",
    "The console renders server order and owns no competing priority calculation.",
    "No parallel Work, Authority, BusinessEffect, Receipt, Event, Evidence, recovery, P4, or P5 truth owner was added.",
    "No P7 autonomous workforce or new AWS infrastructure was added.",
  ]),
  ...cases("planning_ir_compiler", ["planning-unit"], [
    "GoalSpec validation rejects empty goals and missing accepted criteria.",
    "ConstraintSet construction and semantic hashing are deterministic.",
    "PlanningWorldSnapshot construction and semantic hashing are deterministic.",
    "Graph semantic hashing is deterministic and excludes labels, prose, random rows, and timestamps.",
    "Candidate semantic hashing is deterministic.",
    "Dependency cycles are rejected.",
    "Missing dependencies are rejected.",
    "Unknown actions and queries are rejected.",
    "Schema-invalid actions are rejected.",
    "Ungrounded references and targets are rejected.",
    "Cross-tenant references are rejected.",
    "Hard-constraint violations are rejected before ranking.",
    "Human-only P5 capabilities are rejected when model-proposed.",
    "Unsupported recovery semantics are rejected.",
    "Candidate, node, edge, action, query, wait, depth, payload, deadline, and cost budgets fail closed.",
    "Missing completion coverage is rejected.",
    "Duplicate consequential effects are rejected.",
    "Verified irreversible effects are rejected for replay.",
  ]),
  ...cases("candidate_selection", ["planning-unit"], [
    "All invalid candidates produce no selected plan.",
    "One valid candidate is selected.",
    "Multiple valid candidates use the deterministic lexicographic score vector.",
    "Candidate input order changes do not change the winner.",
    "The same world snapshot yields the same winner.",
    "Semantic graph hash is the stable final tie-break.",
    "A model-declared winner field is schema-invalid and cannot select itself.",
    "Unknown cost and latency remain unknown instead of becoming invented scores.",
  ]),
  ...cases("execution", ["runtime-integration", "core-regressions"], [
    "A one-action PlanGraph reaches the existing DomainAction execution path.",
    "A multi-node graph advances only when causal dependencies are observed.",
    "Query nodes execute through Operational Query truth.",
    "Action nodes execute through DomainAction, Authority, BusinessEffect, and Executor truth.",
    "Wait nodes execute through durable WorkEventWait truth.",
    "ObjectiveLoop continues one selected graph rather than replanning after every node.",
    "BusinessEffect verification, not plugin return text, satisfies consequential observation.",
    "A finalized DecisionReceipt satisfies the compiled receipt observation path.",
  ]),
  ...cases("replanning", ["planning-unit", "runtime-integration", "concurrency"], [
    "Entity or version drift makes a selected node stale.",
    "Effect mismatch or divergence requires a child replan.",
    "Action failure requires a child replan.",
    "Capability outage fails compilation or live dispatch closed.",
    "Authority denial or authority revision change fails closed.",
    "A new canonical observation changes the snapshot and can create a child revision.",
    "User redirect interrupts the old objective revision before dispatch.",
    "Deadline pressure and wait timeout use bounded recovery or replanning.",
    "Recovery completion is observed through existing recovery truth.",
    "A verified irreversible action is never naively replayed.",
    "The old revision remains immutable and inspectable after replanning.",
  ]),
  ...cases("completion", ["planning-unit", "runtime-integration", "pe-regressions"], [
    "Planner completion prose cannot complete Work while criteria are unsatisfied.",
    "Verified existing success criteria can complete Work.",
    "CompletionProof pins the exact final revision, graph hash, goal hash, success-condition hash, verification, evidence, and time.",
    "Open or unverified effects block criteria that require settled effect truth.",
    "P5 canonical truth criteria remain human-authenticated where applicable.",
  ]),
  ...cases("attention", ["planning-unit", "performance", "pe-regressions"], [
    "Recovery and terminal failure boundaries outrank ordinary assigned Work.",
    "An overdue hard deadline surfaces with exact negative slack.",
    "A blocking approval ranks by exact downstream nodes and completion criteria unblocked.",
    "An employee who cannot act is not shown the item as actionable.",
    "Required P5 Question, Vote, Decision, and Condition human boundaries surface from canonical truth.",
    "Unavailable or partial sources never masquerade as a clear queue.",
    "Identical data in a different row order produces identical attention rank.",
    "The frontend preserves canonical server order without recomputing priority.",
    "Attention reasons, roots, blockers, unblocks, authority, recovery, and evidence are source-backed.",
  ]),
  ...cases("security_concurrency", ["planning-unit", "concurrency", "core-regressions"], [
    "Prompt injection cannot create or weaken a hard constraint.",
    "The planner cannot forge tenant, actor, authority, policy, or canonical ownership.",
    "The planner cannot impersonate a P5 Vote, Dissent, approval, verification, waiver, or final attestation.",
    "Two planner retries for the same Work converge on one durable attempt.",
    "Two identical selection retries converge on one active revision.",
    "Two competing initial selections admit exactly one winner.",
    "World or WorkInput change after snapshot prevents blind materialization or dispatch.",
    "A replan racing action completion cannot replay a verified consequential effect.",
    "Two replans racing the same parent admit one child.",
    "User cancellation racing dispatch prevents a new operation.",
    "User redirect racing dispatch prevents execution under the stale loop revision.",
    "Authority change before a consequential node fails closed.",
    "Provider unavailability before an email or call node fails closed.",
    "An old PlanRevision cannot execute after supersession.",
    "Cross-tenant PlanRevision and DomainAction graph references are rejected.",
    "A crash after planner-attempt creation is retryable without a duplicate attempt.",
    "A crash after candidate generation creates no execution truth.",
    "A crash after revision selection and before DomainAction creation resumes idempotently.",
    "A crash after DomainAction creation does not duplicate the node action.",
    "A crash before observation persistence resumes from canonical action, effect, receipt, query, or wait state.",
    "A crash during replan preserves one active child and immutable history.",
    "A crash after completion verification cannot fabricate or duplicate completion.",
  ]),
  ...cases("migration", ["migration", "concurrency"], [
    "Migration 0128 is a forward migration from the actual post-P5 head.",
    "Fresh migration succeeds.",
    "Populated P1-P5 upgrade succeeds without fabricated historical plans.",
    "PlanRevision RLS and same-tenant foreign-key invariants are enforced.",
    "Revision numbering, one-active selection, exact parent lineage, and graph immutability are database invariants.",
    "Legacy planner attempts remain truthful nullable legacy history.",
  ]),
  ...cases("performance", ["performance"], [
    "Simple one-candidate planning is measured and guarded.",
    "Two-candidate planning is measured and guarded.",
    "Maximum four-candidate planning is measured and guarded.",
    "PlanCompiler latency is measured and guarded.",
    "PlanningWorldSnapshot construction is measured and guarded.",
    "Replanning is measured and guarded.",
    "Causal attention is measured over one thousand current Work rows.",
    "The deterministic fast Work read lane remains measured and guarded.",
  ]),
  ...cases("regressions", ["pe-regressions", "core-regressions", "contracts"], [
    "P1 world-truth regression passes.",
    "P2 Microsoft nervous-system regression passes.",
    "P3 artifact regression passes.",
    "P4 underwriting regression passes.",
    "P5 actions and Investment Committee regression passes.",
    "Core Work regression passes.",
    "Authority regression passes.",
    "BusinessEffect regression passes.",
    "DecisionReceipt regression passes.",
    "BusinessEvent regression passes.",
    "ObjectiveLoop regression passes.",
    "Action manifest and hardening checks pass.",
    "Authorization matrix check passes.",
    "OpenAPI contract check passes.",
    "Private Equity domain boundary check passes.",
  ]),
  ...cases("production_build", ["builds"], [
    "API production build passes.",
    "Console production build passes.",
  ]),
]);

export const P6_MANDATORY_CASE_COUNT = P6_MANDATORY_CASES.length;
