/**
 * Deterministic PE Actions + Investment Committee certification ledger.
 *
 * The roadmap says both "exactly 260" and gives category counts that add to
 * 270.  We preserve every stated category count without pretending the
 * arithmetic agrees: ten cross-boundary invariants are intentionally listed
 * in each of the two categories they protect.  The release runner asserts
 * 260 unique cases, 270 category memberships, and exactly ten dual-tagged
 * cases.  A future edit cannot silently paper over the source contradiction.
 */

export const P5_MANDATORY_CASE_COUNTS = Object.freeze({
  baseline_prerequisite_ownership: 12,
  ic_schema_state_machine: 18,
  memo_artifact_version: 18,
  question_evidence: 24,
  recommendation_versioning: 20,
  committee_membership_quorum_policy: 30,
  vote_dissent: 30,
  condition: 24,
  decision_proposal_p1_decision: 22,
  pe_action_fabric_hardening: 24,
  authority_security: 12,
  concurrency_idempotency_recovery: 12,
  api_frontend_contract: 8,
  migration_regression_release_boundary: 8,
  performance_limits: 8,
} as const);

export type P5MandatoryCaseCategory = keyof typeof P5_MANDATORY_CASE_COUNTS;

const SHARED = Object.freeze({
  p1DecisionOwner: "P1 pe_decision remains the sole canonical PE investment Decision owner.",
  memoAnchor: "An IC memo selection pins an exact tenant- and root-consistent P3 DocumentVersion and ArtifactAnchor.",
  questionArtifact: "A Question source pins an exact canonical P3 ArtifactAnchor without copying artifact truth into P5.",
  recommendationRun: "A Recommendation pins the exact eligible P4 UnderwritingRun it interprets without recalculating finance.",
  authenticatedVoter: "Effective voter identity derives from the authenticated employee and pinned eligible committee membership.",
  quorumSnapshotRace: "Quorum uses the immutable voting snapshot and remains deterministic under concurrent membership changes.",
  dissentImmutable: "Dissent remains immutable, tenant-isolated process evidence after the majority outcome is finalized.",
  conditionBoundary: "An IC Condition remains distinct from the existing transaction closing-condition owner.",
  p1Finalization: "Finalization calls the existing P1 recordDecision and finalizeDecision semantics instead of owning Decision rows.",
  plannerNoVote: "Planner input cannot cast a Vote, create a Dissent, waive governance, close voting, or finalize a Decision.",
});

export const P5_MANDATORY_CASE_GROUPS: Readonly<Record<P5MandatoryCaseCategory, readonly string[]>> = Object.freeze({
  baseline_prerequisite_ownership: [
    "The recorded starting commit and tree identify the verified remote-main P4 baseline.",
    "P1 InvestmentCase remains the canonical PE business context consumed by an ICCase.",
    "P1 temporal Assumption and Evidence semantics remain available without P5 duplication.",
    "P2 remains the owner of Microsoft source identity, observations, meetings, and evidence handoff.",
    "P3 remains the owner of Documents, immutable DocumentVersions, anchors, and publication truth.",
    "P4 remains the sole deterministic underwriting engine and immutable Run owner.",
    "Core Work and BusinessEvent remain the workflow and event owners used by P5.",
    "Core Authority and DecisionReceipt remain the authorization and execution-proof owners used by P5.",
    "The canonical owner registry contains no new P5 owner for Evidence, Artifact, Work, Authority, Receipt, Decision, policy, or finance.",
    "P5 introduces no P6 planning-core redesign, P7 workforce, fund or LP system, or AWS expansion.",
    SHARED.p1DecisionOwner,
    SHARED.conditionBoundary,
  ],
  ic_schema_state_machine: [
    "The migration creates exactly thirteen tenant-scoped P5 IC relations.",
    "Every P5 relation carries tenant_id and participates in same-tenant foreign-key enforcement.",
    "ICCase identity pins one exact P1 InvestmentCase root.",
    "ICCase state vocabulary is exactly DRAFT, PREPARING, READY_FOR_REVIEW, QUESTIONS_OPEN, READY_FOR_VOTE, VOTING, CONDITIONS_PENDING, DECIDED, WITHDRAWN, SUPERSEDED, BLOCKED.",
    "DRAFT transitions only through the explicit begin-preparation or withdrawal commands.",
    "PREPARING reaches READY_FOR_REVIEW only through the named readiness command.",
    "READY_FOR_REVIEW reaches READY_FOR_VOTE only through the named readiness command.",
    "READY_FOR_VOTE reaches VOTING only through the governed open-voting transaction.",
    "VOTING reaches DECIDED only through canonical P1 Decision finalization.",
    "Withdrawal is explicit and cannot masquerade as an investment Decision.",
    "No generic UPDATE_IC or generic PATCH state mutation exists.",
    "Optimistic case-version preconditions reject stale mutations.",
    "Case state timestamps are written by the same transaction as their transition.",
    "ICCase entry rejects missing P1 InvestmentCase prerequisites.",
    "ICCase entry rejects cross-root Deal and InvestmentCase combinations.",
    "ICCase entry rejects cross-tenant prerequisite references.",
    "Append-only IC history and mutable lifecycle rows have separately enforced mutation rules.",
    "Database guards reject invalid state, root, version, and lifecycle combinations independently of the API.",
  ],
  memo_artifact_version: [
    "P5 stores memo selection and review state rather than memo or deck content.",
    "Memo content remains a Core Document with immutable P3 DocumentVersions.",
    "Every selected memo records an exact P3 Document ID and DocumentVersion ID.",
    "Every selected memo records an exact P3 ArtifactAnchor and anchor hash.",
    "Memo selection rejects a DocumentVersion outside the ICCase root.",
    "Memo selection rejects a stale or mismatched ArtifactAnchor.",
    "Memo revisions are append-only selections with explicit predecessor identity.",
    "At most one memo selection is current for an ICCase version.",
    "The selected memo version is frozen into the voting snapshot.",
    "Opening voting fails when no exact memo version is selected.",
    "A memo change during review is visible as a material version change.",
    "A memo change after Votes follows the pinned policy and requires a fresh vote when configured.",
    "Memo generation may draft P3 content but cannot fabricate source-backed claims.",
    "Every memo claim retains links to canonical Evidence, P3, or P4 truth.",
    "P3 editorial approval cannot be interpreted as IC investment approval.",
    "Memo and deck publication stays on the P3 publication and read-back path.",
    SHARED.memoAnchor,
    SHARED.questionArtifact,
  ],
  question_evidence: [
    "A Question belongs to exactly one tenant-consistent ICCase.",
    "Question state vocabulary is OPEN, ANSWERED, RESOLVED, WAIVED, SUPERSEDED.",
    "Question creation records explicit required-before-vote and required-before-Decision flags.",
    "Question creation creates or links canonical Core Work instead of a P5 work system.",
    "Question answering preserves the question text and adds an immutable answer revision.",
    "Question resolution is distinct from merely recording an answer.",
    "Question supersession preserves the prior question and names its successor.",
    "A required Question blocks opening voting while unresolved.",
    "A required-before-Decision Question blocks DecisionProposal eligibility while unresolved.",
    "A Question waiver requires the exact governed Authority decision.",
    "A Question waiver preserves the Question and its waiver provenance.",
    "Question Evidence uses canonical Core Evidence and EvidenceVersion identities.",
    SHARED.memoAnchor,
    "Question Evidence can pin a P4 UnderwritingRun and exact output path.",
    "Question source links are typed and reject ambiguous free-text references.",
    "A Question source rejects cross-tenant EvidenceVersion references.",
    "A Question source rejects cross-InvestmentCase Evidence references.",
    "A Question source rejects a P3 artifact outside the case root.",
    "A Question source rejects a P4 Run outside the case root.",
    "No ic_evidence table or duplicate Evidence owner is created.",
    "Question source lineage remains exact after the canonical source receives a later version.",
    "Question lifecycle changes emit metadata-only BusinessEvents.",
    "The 100-open-Question hard limit is enforced in the database.",
    SHARED.questionArtifact,
  ],
  recommendation_versioning: [
    "A Recommendation belongs to one exact ICCase and recommendation sequence.",
    "Recommendation outcomes are INVEST, DECLINE, DEFER, INVEST_WITH_CONDITIONS, and CONTINUE_DILIGENCE.",
    "Recommendation content records structured rationale references rather than becoming a canonical Decision.",
    "Recommendation revisions are append-only and retain their predecessor identity.",
    "Recommendation revision numbers are unique and monotonic within an ICCase.",
    "A Recommendation pins the selected memo revision.",
    "A Recommendation pins the selected P4 UnderwritingRun.",
    "A Recommendation pins the policy and committee configuration used to assess readiness.",
    "Opening voting requires one exact current Recommendation revision.",
    "The voting snapshot freezes the Recommendation revision.",
    "A Recommendation change before voting leaves no stale Vote attached.",
    "A Recommendation change after Votes follows policy and invalidates the prior voting snapshot when required.",
    "A replacement P4 Run requires a new Recommendation when the pinned policy says so.",
    "An ineligible, failed, stale, or conflicting P4 Run cannot back a final Recommendation.",
    "A Recommendation never translates its outcome into a P1 Decision without committee aggregation.",
    "A DECLINE Recommendation approved by the committee remains a DECLINE proposal.",
    "INVEST_WITH_CONDITIONS requires at least one real IC Condition.",
    "Recommendation creation enforces the twenty-revision hard limit.",
    "Recommendation semantic provenance remains stable across read order.",
    SHARED.recommendationRun,
  ],
  committee_membership_quorum_policy: [
    "Committee configuration is immutable and versioned.",
    "An ICCase pins one exact committee configuration version.",
    "Committee members reference canonical employee identities rather than free-text names.",
    "Membership effective_from participates in eligibility at the voting snapshot time.",
    "Membership effective_until participates in eligibility at the voting snapshot time.",
    "A non-voting member cannot enter the eligible-voter denominator.",
    "Duplicate eligible membership for one employee fails closed.",
    "Committee chair identity is explicit and cannot be inferred from row order.",
    "Committee membership is capped at fifty members.",
    "Meeting attendance never implies committee membership.",
    "Meeting attendance never creates a Vote.",
    "The voting snapshot freezes the eligible member set.",
    "The voting snapshot freezes the exact committee configuration version.",
    "Quorum supports an exact minimum-count rule.",
    "Percentage quorum uses deterministic integer ceiling arithmetic.",
    "Abstention treatment for quorum is explicit in the pinned policy.",
    "Deferral treatment for quorum is explicit in the pinned policy.",
    "Missing Votes never count toward quorum unless the exact policy explicitly permits their choice class.",
    "Simple-majority threshold uses the exact configured denominator.",
    "Supermajority threshold uses exact basis points and deterministic ceiling arithmetic.",
    "Unanimous threshold requires every configured denominator member to approve.",
    "Named-role concurrence is evaluated in addition to its configured base threshold.",
    "Unsupported custom quorum or threshold rules fail as BLOCKED_CONFIG.",
    "Core policy identity and version are pinned into the committee snapshot.",
    "Policy parsing rejects invented rule shapes rather than approximating them.",
    "Policy changes do not rewrite historical voting snapshots.",
    "Material memo, Run, Recommendation, or membership changes follow the exact pinned policy.",
    "Aggregation output records eligible, participating, approve, reject, abstain, and defer counts.",
    SHARED.authenticatedVoter,
    SHARED.quorumSnapshotRace,
  ],
  vote_dissent: [
    "Vote choices are APPROVE, REJECT, ABSTAIN, and DEFER.",
    "A Vote belongs to one exact voting snapshot and Recommendation revision.",
    "Vote actor identity is not accepted from request or planner arguments.",
    "The Vote endpoint resolves the authenticated principal to a canonical employee.",
    "The Vote transaction verifies that employee is eligible in the pinned snapshot.",
    "One effective Vote per member is enforced by a database uniqueness invariant.",
    "An identical Vote retry converges to the original immutable Vote.",
    "A conflicting second Vote from the same member is rejected.",
    "Votes are immutable after insertion.",
    "Votes cannot be deleted by the application role.",
    "A Vote after voting closure is rejected.",
    "A Vote on a superseded Recommendation snapshot is rejected.",
    "A Vote on a different ICCase root is rejected.",
    "A Vote from an ineligible member is rejected and observed.",
    "A member becoming ineligible before snapshot creation is excluded.",
    "A member becoming ineligible after snapshot creation does not rewrite historical eligibility.",
    "Simultaneous distinct member Votes all persist exactly once.",
    "Simultaneous conflicting same-member Votes yield one winner and one explicit conflict.",
    "Vote rationale is protected content and absent from metadata-only events and metrics.",
    "Dissent is a separate append-only process record, not a Vote choice alias.",
    "A Dissent pins the exact Vote and voting snapshot it explains.",
    "Dissent actor identity is derived from the authenticated eligible member.",
    "Dissent cannot be created for another member.",
    "Dissent is preserved after majority approval.",
    "Dissent is preserved after canonical P1 Decision finalization.",
    "Dissent rationale is not copied into telemetry.",
    "A committee-approved Recommendation and its minority rejection Votes coexist without erasure.",
    "Vote totals are independent of database row arrival order.",
    SHARED.authenticatedVoter,
    SHARED.dissentImmutable,
  ],
  condition: [
    "IC Condition types are PRE_DECISION, POST_DECISION_PRE_SIGNING, PRE_CLOSING, and MONITORING.",
    "IC Condition states are PROPOSED, ACTIVE, SATISFIED, WAIVED, FAILED, and SUPERSEDED.",
    "A Condition belongs to exactly one tenant-consistent ICCase.",
    "Condition creation records whether the condition is required.",
    "Condition activation is an explicit state transition.",
    "Condition satisfaction is an explicit state transition with exact supporting truth.",
    "Condition waiver requires governed Authority.",
    "Condition waiver preserves the original Condition and provenance.",
    "Condition failure is explicit and cannot masquerade as satisfaction.",
    "Condition supersession preserves its predecessor and successor identities.",
    "An ACTIVE required PRE_DECISION Condition blocks DecisionProposal eligibility.",
    "A satisfied PRE_DECISION Condition no longer blocks DecisionProposal eligibility.",
    "A governed waived PRE_DECISION Condition remains visible and no longer blocks.",
    "INVEST_WITH_CONDITIONS requires an actual IC Condition row.",
    "POST_DECISION_PRE_SIGNING Conditions may remain active after the investment Decision.",
    "PRE_CLOSING Conditions never imply that the transaction has closed.",
    "MONITORING Conditions remain governance obligations rather than closing state.",
    "Condition fulfillment links canonical Evidence or exact P3/P4 truth.",
    "Condition lifecycle creates or links Core Work instead of a P5 task system.",
    "Condition transitions emit metadata-only BusinessEvents.",
    "At most fifty active or proposed Conditions are allowed per ICCase.",
    "A Condition cannot cross tenant or InvestmentCase roots.",
    "Concurrent Condition creation and Decision finalization serialize to one truthful order.",
    SHARED.conditionBoundary,
  ],
  decision_proposal_p1_decision: [
    "DecisionProposal is immutable aggregated process evidence, not a canonical Decision.",
    "DecisionProposal pins the exact ICCase version used for aggregation.",
    "DecisionProposal pins the committee configuration and policy versions.",
    "DecisionProposal pins the memo, Recommendation, and P4 Run revisions.",
    "DecisionProposal pins the exact voting snapshot and effective Vote set.",
    "DecisionProposal records Question and Condition blockers explicitly.",
    "DecisionProposal records deterministic quorum and threshold results.",
    "DecisionProposal semantic hash is stable across equivalent input row order.",
    "DecisionProposal fails closed for duplicate effective membership or Votes.",
    "DecisionProposal fails closed for an ineligible Vote.",
    "A blocked DecisionProposal cannot create a P1 Decision.",
    "Finalization requires an eligible immutable DecisionProposal.",
    "The canonical P1 Decision uses decision_type investment_committee.",
    "The P1 Decision retains exact provenance links to the DecisionProposal and process snapshot.",
    "Finalization creates one Core DecisionReceipt through the existing execution fabric.",
    "An identical finalization retry returns the one canonical P1 Decision and Receipt.",
    "Two simultaneous identical finalizations converge to one canonical P1 Decision.",
    "P5 never updates or deletes an existing final P1 Decision.",
    "Reconsideration creates a new P1 Decision that supersedes the earlier final Decision.",
    SHARED.p1DecisionOwner,
    SHARED.recommendationRun,
    SHARED.p1Finalization,
  ],
  pe_action_fabric_hardening: [
    "The Private Equity action registry contains exactly twenty-four executable actions.",
    "The nine P5 additions are planner-safe preparation actions only.",
    "open_ic_case is a named durable workflow action with a fixed schema.",
    "begin_ic_preparation is a named transition action with a fixed schema.",
    "select_ic_memo_version requires exact grounded P3 identifiers.",
    "select_ic_underwriting_run requires an exact grounded P4 Run identifier.",
    "create_ic_question creates an explicit typed Question rather than a generic update.",
    "attach_ic_question_evidence accepts only exact canonical source identities.",
    "request_ic_memo_review is a named review-readiness operation.",
    "satisfy_ic_condition requires an exact Condition and supporting truth.",
    "prepare_ic_decision_proposal computes a draft proposal without finalizing a Decision.",
    "Every executable action has exactly one action-hardening specification row.",
    "Every P5 action schema rejects tenantId and actorId selectors.",
    "Action grounding resolves exact tenant-owned canonical entities before mutation.",
    "Action preconditions pin case and referenced object versions.",
    "Action authority checks occur outside presentation/UI code.",
    "Action effects are recorded through existing Core BusinessEffect semantics.",
    "Action verification reads back the postcondition instead of trusting invocation success.",
    "Action completion creates or converges on an existing Core DecisionReceipt.",
    "Action idempotency keys converge retries without duplicate domain effects.",
    "Ambiguous failures trigger read-back recovery before any repeat mutation.",
    "The executable registry and fixed manifest agree on all forty-one global actions.",
    SHARED.p1Finalization,
    SHARED.plannerNoVote,
  ],
  authority_security: [
    "Core Authority decisions authorize operations but are never IC Votes or P1 investment Decisions.",
    "Question waiver requires the exact Authority capability and scoped resource.",
    "Condition waiver requires the exact Authority capability and scoped resource.",
    "Voting open and close require their exact governed capabilities.",
    "P1 Decision finalization requires an Authority decision outside the UI.",
    "Authority denial fails before any P5 or P1 mutation.",
    "All thirteen P5 relations have enabled and forced tenant RLS.",
    "Cross-tenant reads and writes fail under the application role.",
    "Prompt-injected voter, tenant, authority, or finalization instructions cannot alter trusted identity context.",
    "Audit events and metrics contain identifiers and states but no memo, answer, vote, dissent, evidence, or financial content.",
    SHARED.dissentImmutable,
    SHARED.plannerNoVote,
  ],
  concurrency_idempotency_recovery: [
    "Two conflicting Votes from one authenticated member produce one immutable effective Vote.",
    "Voting close racing a new Vote yields either an included Vote or an explicit late-Vote rejection.",
    "Recommendation revision racing a Vote cannot attach the Vote to the wrong revision.",
    "Memo revision selection racing voting-open cannot produce a mixed snapshot.",
    "Question resolution racing voting-open retains a single serializable truth.",
    "Condition creation racing Decision finalization retains a single serializable truth.",
    "Two simultaneous finalization requests converge to one P1 Decision.",
    "P1 Decision supersession racing a Decision proof read returns a coherent before-or-after proof.",
    "Crash after ICCase insertion and before event publication rolls back and replays cleanly.",
    "Crash after Vote insertion and before response replays to one immutable Vote.",
    "Crash between P1 Decision creation, P5 linkage, Receipt creation, and response never leaves a false completed state.",
    SHARED.quorumSnapshotRace,
  ],
  api_frontend_contract: [
    "The P5 API exposes exactly thirty typed routes and no generic mutation route.",
    "The Vote API is a separate authenticated human endpoint with no voter selector.",
    "Every P5 API route is present in generated OpenAPI.",
    "Every P5 API route is present in the generated authorization matrix.",
    "The IC aggregate endpoint returns semantic memo, Question, Recommendation, voting, Condition, and Decision proof sections.",
    "The IC Workspace renders the full lifecycle without raw JSON panels.",
    "The frontend labels P3 editorial state, P4 finance, Authority, and P1 Decision ownership truthfully.",
    "The frontend never presents a planner operation as a human Vote, waiver, voting close, or final Decision.",
  ],
  migration_regression_release_boundary: [
    "A fresh database applies every migration through 0127 and creates empty P5 tables.",
    "A populated P1-P4 database upgrades through 0127 without changing legacy row bytes or identities.",
    "Legacy P1 investment_committee Decisions remain valid without fabricated P5 history.",
    "P1 deterministic certification and integration regressions remain green.",
    "P2 deterministic certification and integration regressions remain green.",
    "P3 deterministic certification and integration regressions remain green.",
    "P4 deterministic certification and integration regressions remain green.",
    "Historical release:pe5 evidence remains intact while release:pe-p5-actions-ic is unambiguous and production release remains gated by literal /GOAL.",
  ],
  performance_limits: [
    "Loading the complete IC aggregate stays inside its measured release guardrail.",
    "Opening one Question stays inside its measured release guardrail.",
    "Fifty authenticated concurrent Votes stay inside their measured release guardrail.",
    "Closing and aggregating a fifty-member Vote set stays inside its measured release guardrail.",
    "Computing and persisting an immutable DecisionProposal stays inside its measured release guardrail.",
    "The canonical P1 Decision finalization transaction stays inside its measured release guardrail.",
    "Loading the authenticated Decision proof stays inside its measured release guardrail.",
    "The exact 100-open-Question and 50-active-Condition limits are enforced and measured.",
  ],
});

const memberships = (Object.keys(P5_MANDATORY_CASE_COUNTS) as P5MandatoryCaseCategory[])
  .flatMap((category) => P5_MANDATORY_CASE_GROUPS[category].map((name) => ({ category, name })));

const unique = new Map<string, P5MandatoryCaseCategory[]>();
for (const membership of memberships) {
  const categories = unique.get(membership.name) ?? [];
  categories.push(membership.category);
  unique.set(membership.name, categories);
}

export const P5_MANDATORY_CASES = Object.freeze([...unique.entries()].map(([name, categories], index) => Object.freeze({
  number: index + 1,
  name,
  categories: Object.freeze(categories),
})));

export const P5_MANDATORY_CATEGORY_MEMBERSHIP_COUNT = memberships.length;
export const P5_MANDATORY_DUAL_TAGGED_CASES = Object.freeze(P5_MANDATORY_CASES.filter((item) => item.categories.length === 2));
