export const P4_MANDATORY_CASE_COUNTS = Object.freeze({
  prerequisite_ownership: 12,
  decimal_unit_serialization: 16,
  model_ir_compiler: 18,
  truth_input_no_hindsight: 18,
  transaction_sources_uses: 20,
  operating_forecast_fcf: 22,
  debt_revolver_interest_circularity: 32,
  exit_returns_irr: 16,
  scenario_sensitivity: 18,
  p3_binding_projection_reconciliation: 16,
  rls_security: 12,
  durability_idempotency: 12,
  api_frontend_contract: 10,
  migration_regression: 10,
  performance_limits: 8,
} as const);

export type P4MandatoryCaseCategory = keyof typeof P4_MANDATORY_CASE_COUNTS;

export const P4_MANDATORY_CASE_GROUPS: Readonly<Record<P4MandatoryCaseCategory, readonly string[]>> = Object.freeze({
  prerequisite_ownership: [
    "P1 canonical PE world and three-root ownership remain available.",
    "P1 temporal state_at and no-hindsight Evidence semantics remain available.",
    "P2 Microsoft source identity, coverage, delta and reconciliation remain one system.",
    "P3 immutable DocumentVersion, SpreadsheetIR and publication truth remain available.",
    "P1 InvestmentCase remains the sole canonical PE business context.",
    "P1 Assumption remains the sole canonical PE business assumption owner.",
    "Core Document and P3 DocumentVersion remain the artifact owners.",
    "Core Evidence and EvidenceVersion remain the evidence owners.",
    "Core Work, BusinessEvent, Authority and DecisionReceipt remain their sole owners.",
    "Historical private-equity Phase 4 action/governance code is not underwriting certification.",
    "The pure underwriting package obeys its architectural import boundary.",
    "No P5 IC semantics, P6 planner actions, P7 workforce or AWS compute expansion was added.",
  ],
  decimal_unit_serialization: [
    "Canonical financial values use exact base-10 decimal strings.",
    "Locale, currency-symbol, percent-symbol and scaled display strings are rejected by the core.",
    "The decimal runtime freezes 34 significant digits.",
    "The decimal runtime freezes ROUND_HALF_EVEN.",
    "Extreme decimal exponents are bounded and rejected.",
    "NaN and positive/negative Infinity cannot enter an InputSnapshot or result.",
    "Exact zero remains distinct from missing, null and UNKNOWN.",
    "Canonical serialization is independent of object insertion order.",
    "Canonical semantic hashing is stable across equivalent object orderings.",
    "Money nodes require explicit currency identity.",
    "Rates are exact fractions and never ambiguous percentages.",
    "Multiple, ratio, rate, money, count, date, period, boolean and text units remain distinct.",
    "Unit-incompatible arithmetic fails model compilation.",
    "Currency-incompatible arithmetic fails without silent FX conversion.",
    "Series values retain stable exact period IDs and ordering.",
    "Input and result canonical payloads persist exact decimal strings rather than JSON floats.",
  ],
  model_ir_compiler: [
    "UnderwritingModelIR pins schema, model, convention and minimum engine versions.",
    "Every model node has a stable deterministic ID.",
    "Input, Constant, Expression, Series, Schedule, Aggregate, Check and Output node kinds are supported.",
    "Duplicate model node IDs fail compilation.",
    "Every declared dependency must exist.",
    "Value-type compatibility is validated before execution.",
    "Unit compatibility is validated before execution.",
    "Currency compatibility is validated before execution.",
    "Period and series-shape compatibility are validated before execution.",
    "Compiler output has a stable deterministic execution order.",
    "Undeclared ordinary dependency cycles fail compilation.",
    "Declared circular blocks require exact membership and iteration order.",
    "Circular solver tolerances and iteration ceilings are compile-time validated.",
    "Expression AST depth and supported operations are bounded.",
    "Model execution cannot use eval, Function, dynamic import, shell, network or user code.",
    "Model node count and canonical ModelVersion byte size are enforced.",
    "Model semantic hash excludes database IDs, timestamps and row order.",
    "ModelVersion diff reports node, dependency, unit, policy, solver, check and convention changes.",
  ],
  truth_input_no_hindsight: [
    "A model input binds to an exact P1 Assumption ID rather than a fuzzy name.",
    "The InputSnapshot pins the exact canonical Assumption history version used.",
    "A factual input pins an exact EvidenceVersion and value path.",
    "Evidence retrieved after worldAt is excluded even when its asOf predates worldAt.",
    "Evidence with eligible asOf and retrievedAt is available at worldAt.",
    "A spreadsheet input pins exact DocumentVersion, ArtifactAnchor and anchor hash.",
    "Formula/cached spreadsheet inputs obey P3 calculation status rather than becoming facts.",
    "Every resolved input carries an explicit financial truth class.",
    "A required UNKNOWN input fails closed with UNKNOWN_INPUT.",
    "A required STALE input fails closed by default.",
    "STALE is allowed only by the exact InputNode policy and remains labeled STALE.",
    "A required CONFLICTING input fails closed without choosing a value.",
    "Missing input never silently coerces to exact zero.",
    "Input policy enforces allowed truth classes.",
    "Input policy enforces exact range bounds without inventing PE judgment.",
    "Every Run distinguishes historical worldAt from current computedAt.",
    "An old worldAt Run reproduces exactly after current P1 Assumptions change.",
    "An obsolete exact Assumption binding fails rather than guessing a replacement revision.",
  ],
  transaction_sources_uses: [
    "Entry valuation date is an explicit typed input.",
    "Metric-times-entry-multiple valuation is explicit and deterministic.",
    "Direct enterprise-value entry is an explicit alternative method.",
    "Entry enterprise value and purchase equity value remain distinct.",
    "Cash acquired is included exactly once in the entry equity bridge.",
    "Existing debt refinancing is a distinct Use.",
    "Other debt-like items are explicit and never hidden in net debt.",
    "Transaction fees are explicit Uses.",
    "Financing fees are explicit Uses.",
    "Minimum-cash funding is an explicit Use.",
    "Rollover equity is an explicit Source and sponsor-equity reduction.",
    "Seller-note financing is an explicit debt Source when configured.",
    "Sponsor equity is a deterministic named plug.",
    "Total Uses is the exact sum of declared Use components.",
    "Total Sources is the exact sum of debt, rollover and sponsor Sources.",
    "Sources equals Uses within the declared exact tolerance.",
    "No unexplained miscellaneous Source or Use is created.",
    "Underfunded Sources/Uses produces a mandatory failed Check.",
    "Overfunded Sources/Uses produces a mandatory failed Check.",
    "Transaction and Sources/Uses outputs retain exact dependency lineage.",
  ],
  operating_forecast_fcf: [
    "Annual financial periods have stable IDs, dates, ordinals and fiscal labels.",
    "Quarterly financial periods have stable IDs, dates, ordinals and fiscal labels.",
    "Monthly financial periods have stable IDs, dates, ordinals and fiscal labels.",
    "Revenue supports an explicit forecast series.",
    "Revenue supports deterministic prior-period growth.",
    "Missing required future revenue fails rather than extrapolating or using zero.",
    "EBITDA supports an explicit forecast series.",
    "EBITDA supports deterministic Revenue-times-margin derivation.",
    "ModelVersion explicitly chooses EBITDA precedence and never silently accepts both methods.",
    "Explicit D&A produces EBIT equal to EBITDA less D&A.",
    "The declared EBITDA-equals-EBIT convention omits D&A without fabricating it.",
    "Capex supports an explicit series.",
    "Capex supports a deterministic percentage-of-revenue driver.",
    "Capex cash-use sign convention remains explicit.",
    "Working capital supports an explicit NWC series.",
    "Working capital supports a deterministic percentage-of-revenue driver.",
    "Change in NWC uses an explicit cash-flow sign convention.",
    "Cash tax uses positive taxable income and an exact zero floor.",
    "Unsupported NOL and complex tax behavior is classified rather than approximated.",
    "Unlevered FCF is a distinct deterministic bridge.",
    "Levered FCF and cash available for sweep remain distinct outputs.",
    "Operating forecast and FCF outputs retain exact upstream dependency lineage.",
  ],
  debt_revolver_interest_circularity: [
    "Each DebtTranche has stable ID, name, seniority and sweep priority.",
    "Fixed-rate debt uses its exact declared fixed rate.",
    "Floating-rate debt consumes an exact base-rate curve plus spread.",
    "Floating-rate floors are applied before adding the spread.",
    "Base-rate curves require exact input provenance and are never fetched by the core.",
    "Beginning-balance cash-interest basis is supported explicitly.",
    "Average-balance cash-interest basis is supported explicitly.",
    "Average-balance interest circularity exists only in a declared solver block.",
    "Circular solver initial state is explicit and deterministic.",
    "Circular solver iteration order, tolerances and maximum iterations are frozen.",
    "Circular non-convergence returns NON_CONVERGENT and never the last iteration as verified.",
    "Cash interest and PIK interest remain separate outputs.",
    "PIK interest capitalizes into ending principal.",
    "Opening plus draws plus PIK less repayments equals ending debt.",
    "Mandatory amortization supports percentage of original principal.",
    "Mandatory amortization supports an explicit amount series.",
    "Applied amortization clamps only to outstanding principal and exposes the applied amount.",
    "Ending debt principal cannot be negative.",
    "Revolver opening principal and commitment are explicit.",
    "Revolver draw restores the declared minimum-cash balance when capacity permits.",
    "Revolver paydown is explicit and cannot exceed principal.",
    "Ending revolver balance cannot exceed commitment.",
    "Required draw above commitment returns LIQUIDITY_SHORTFALL.",
    "Revolver overflow is surfaced as an exact typed failure/check.",
    "Cash sweep uses only exact available cash above the minimum reserve.",
    "Cash sweep percentage is explicit and bounded.",
    "Cash sweep follows configured seniority/priority waterfall.",
    "No debt paydown exceeds outstanding principal.",
    "Debt at maturity follows explicit mandatory-repayment treatment.",
    "Unsupported maturity/refinancing behavior fails honestly.",
    "Multiple fixed/floating/cash/PIK/revolver tranches coexist deterministically.",
    "Debt roll-forward, capacity, cash, sweep, rate and maturity checks are all mandatory.",
  ],
  exit_returns_irr: [
    "Exit period and its exact date are explicit.",
    "Exit metric value is an exact deterministic input or derived output.",
    "Exit multiple is an explicit exact input.",
    "Exit enterprise value equals exit metric times exit multiple.",
    "Exit debt uses the exact ending debt schedule.",
    "Exit cash uses the exact ending cash schedule.",
    "Exit net debt is distinct from enterprise and equity value.",
    "Exit adjustments are explicit and source-traceable.",
    "Exit equity value reconciles EV less debt plus cash and adjustments.",
    "Sponsor proceeds apply exact sponsor ownership rather than assuming 100 percent.",
    "Modeled ownership must reconcile to 100 percent where required.",
    "Sponsor cash-flow timeline pins exact amount, date, period and flow type.",
    "Interim sponsor distributions remain explicit and are not buried in exit proceeds.",
    "Gross sponsor MOIC equals positive distributions divided by absolute invested capital.",
    "Periodic IRR uses a bounded deterministic solver with undefined/ambiguous root truth.",
    "Dated XIRR uses the frozen ACT/365F convention and irregular dates.",
  ],
  scenario_sensitivity: [
    "Base execution uses zero hidden scenario overrides.",
    "Scenario labels have no financial meaning without exact overrides.",
    "Scenario definitions are immutable explicit override sets.",
    "Scenario semantic hash is deterministic.",
    "Scenario revisions preserve explicit parent identity.",
    "Scenario targets must be eligible exact InputNodes.",
    "Scenario application never mutates the sealed base InputSnapshot.",
    "Scenario Run pins exact scenario and result semantic hashes.",
    "Run diff reports exact changed inputs, outputs, checks and scenario identity.",
    "Affected-node analysis traverses deterministic downstream dependencies without rerunning.",
    "One-way sensitivities execute exact axis values.",
    "Two-way sensitivities execute exact Cartesian coordinates.",
    "Sensitivity axes are generic eligible model InputNodes, not hardcoded buttons.",
    "Every sensitivity cell retains exact Run semantic and persisted Run identity.",
    "Sensitivity cell row/column ordering is stable.",
    "A failed sensitivity cell remains in place with exact failure status and no interpolation.",
    "Sensitivity execution rejects more than 2,500 cells.",
    "Sensitivity retries converge without duplicate parent or cell rows.",
  ],
  p3_binding_projection_reconciliation: [
    "P4 consumes P3 SpreadsheetIR directly and never reparses XLSX ZIP/XML.",
    "P4 input bindings pin exact P3 DocumentVersion, node ID and anchor hash.",
    "P4 output bindings pin exact P3 DocumentVersion, OutputNode and anchor hash.",
    "Template edits require an append-only binding version and revalidation.",
    "Stale or missing ArtifactAnchors fail closed.",
    "Projection compiles through P3 typed ArtifactPatch rather than direct workbook bytes.",
    "Projection uses an exact base DocumentVersion precondition.",
    "Successful projection creates a new immutable P3 DocumentVersion.",
    "P3-operation-before-P4-row crash replay converges to one projection.",
    "Artifact comparison supports exact-decimal policy.",
    "Artifact comparison supports declared rounded-value policy.",
    "Artifact comparison supports explicit absolute-tolerance policy.",
    "Artifact comparison supports explicit relative-tolerance policy.",
    "Stale/uncalculated Excel values are never reported as MATCH.",
    "P4-versus-Excel mismatch is retained without overwriting either truth.",
    "Microsoft publication/recalculation remains exclusively in P3 authority and read-back flow.",
  ],
  rls_security: [
    "Every P4 persistence relation carries tenant_id.",
    "RLS is enabled on every P4 tenant relation.",
    "FORCE RLS is enabled on every P4 tenant relation.",
    "The application role receives only required SELECT/INSERT P4 privileges.",
    "The application role cannot UPDATE immutable P4 history.",
    "The application role cannot DELETE immutable P4 history.",
    "UnderwritingModel and InvestmentCase references must share one tenant.",
    "P1 Assumption bindings must share exact tenant and InvestmentCase root.",
    "Cross-tenant EvidenceVersion bindings are rejected.",
    "Cross-tenant DocumentVersion/ArtifactAnchor bindings are rejected.",
    "Run, Scenario, Sensitivity and ModelVersion composite identities cannot cross tenants.",
    "No underwriting row is registered as a duplicate canonical-world owner.",
  ],
  durability_idempotency: [
    "UnderwritingModelVersion rows are immutable after insert.",
    "Final UnderwritingRun rows are immutable after insert.",
    "Run InputSnapshot, outputs, checks, engine and hashes cannot change in place.",
    "UnderwritingScenario rows are immutable revisions.",
    "Sensitivity parent and cell results are immutable and retain Run IDs.",
    "Artifact binding corrections append an incremented binding version.",
    "Artifact projection history is immutable.",
    "A tampered prepared result hash is rejected before any Run row commits.",
    "Failure after calculation before DB commit exposes zero partial completed Run rows.",
    "Retry after Run commit returns the same Run and creates no duplicate.",
    "Sensitivity retry creates no duplicate parent or completed cell.",
    "Underwriting BusinessEvents are bounded metadata and use non-canonical calculation entities.",
  ],
  api_frontend_contract: [
    "API financial values use strict decimal-string contracts.",
    "Model and ModelVersion APIs accept only bounded structured ModelIR.",
    "Run API pins exact InvestmentCase, ModelVersion, worldAt and idempotency key.",
    "Scenario API enforces explicit bounded immutable override definitions.",
    "Sensitivity API enforces exact axes, outputs and 2,500-cell bound.",
    "Artifact APIs require exact DocumentVersion and ArtifactAnchor identities.",
    "OpenAPI publishes every typed underwriting capability route.",
    "Every underwriting route authenticates and ignores payload tenant/actor spoofing.",
    "Workspace renders coherent exact Run, ModelVersion, node, unit, currency and period context.",
    "Workspace distinguishes canonical Assumptions, Scenario overrides, P3 projection and Excel comparison.",
  ],
  migration_regression: [
    "P4 is a forward migration from the exact P3 head 0125.",
    "A fresh database applies all 124 migrations through 0126.",
    "Generated migration bundle exactly matches every disk migration byte.",
    "Populated P1 Deal, InvestmentCase, Assumption and canonical history survive P4 upgrade exactly.",
    "Populated P2 EvidenceVersion, source scope and ExternalRef survive P4 upgrade exactly.",
    "Populated P3 DocumentVersion bytes and SpreadsheetIR semantic hash survive exactly.",
    "Populated P3 binding, template and publication rows survive exactly.",
    "Existing InvestmentCases receive zero fabricated models, scenarios, sensitivities or Runs.",
    "P4 migration installs same-tenant constraints, RLS and immutable guards idempotently.",
    "P1, P2, P3, historical PE action/governance and Core regression suites remain green.",
  ],
  performance_limits: [
    "Measured standard ModelIR compile latency remains within its release guardrail.",
    "Measured single standard LBO runtime remains within its release guardrail.",
    "Measured multi-tranche debt-schedule runtime remains within its release guardrail.",
    "Measured average-balance circular solver remains within its release guardrail.",
    "Measured 100-cell sensitivity remains within its release guardrail.",
    "Measured maximum 2,500-cell sensitivity remains within its release guardrail.",
    "Measured canonical serialization/result-hash latency remains within its release guardrail.",
    "Model, period, debt, scenario, sensitivity, solver and payload hard limits are enforced in code.",
  ],
});

export interface P4MandatoryCase {
  number: number;
  category: P4MandatoryCaseCategory;
  categoryNumber: number;
  name: string;
}

export const P4_MANDATORY_CASES: readonly P4MandatoryCase[] = Object.freeze(
  (Object.keys(P4_MANDATORY_CASE_COUNTS) as P4MandatoryCaseCategory[]).flatMap((category) =>
    P4_MANDATORY_CASE_GROUPS[category].map((name, index) => ({
      number: 0,
      category,
      categoryNumber: index + 1,
      name,
    })),
  ).map((item, index) => ({ ...item, number: index + 1 })),
);
