export const SCOPE2_GATE_IDS = [
  "architecture",
  "migration-security",
  "real-db-concurrency",
  "job-step-runtime",
  "effect-protocol",
  "observation-reconciliation",
  "signals-dlq-controls",
  "version-redeploy",
  "scope1-phase15a",
  "performance",
] as const;

export type Scope2GateId = (typeof SCOPE2_GATE_IDS)[number];

export interface Scope2MandatoryCase {
  ordinal: number;
  id: string;
  statement: string;
  gates: readonly Scope2GateId[];
}

/** Executable acceptance ledger for the 62 Phase-2 requirements plus the user's
 * 13 mandatory corrections. Every entry maps to one or more gates that must execute;
 * architecture text alone never certifies concurrency, effect safety, or recovery. */
export const SCOPE2_MANDATORY_CASES: readonly Scope2MandatoryCase[] = [
  { ordinal: 1, id: "scope2.atomic-command-graph", statement: "Command, run, steps, and first delivery commit atomically.", gates: ["job-step-runtime"] },
  { ordinal: 2, id: "scope2.command-dedup", statement: "Duplicate command submission converges on one command graph.", gates: ["job-step-runtime"] },
  { ordinal: 3, id: "scope2.command-effect-conflict", statement: "One idempotency key cannot authorize conflicting immutable BusinessEffects.", gates: ["job-step-runtime", "effect-protocol"] },
  { ordinal: 4, id: "scope2.hundred-job-claimers", statement: "One hundred real database sessions produce one physical job claim winner.", gates: ["real-db-concurrency", "performance"] },
  { ordinal: 5, id: "scope2.job-heartbeat", statement: "A healthy job heartbeat prevents ownership loss.", gates: ["job-step-runtime"] },
  { ordinal: 6, id: "scope2.expired-job-recovery", statement: "An expired job is classified and safely recovered.", gates: ["job-step-runtime", "version-redeploy"] },
  { ordinal: 7, id: "scope2.expired-effect-job", statement: "Expired side-effect delivery cannot duplicate a provider mutation.", gates: ["job-step-runtime", "effect-protocol"] },
  { ordinal: 8, id: "scope2.hundred-step-claimers", statement: "One hundred real database sessions produce one workflow-step claim winner.", gates: ["real-db-concurrency", "performance"] },
  { ordinal: 9, id: "scope2.stale-dispatch-generation", statement: "A stale dispatch generation cannot claim execution.", gates: ["real-db-concurrency", "job-step-runtime"] },
  { ordinal: 10, id: "scope2.stale-fence-terminal", statement: "A stale token or fence cannot complete a redriven step.", gates: ["job-step-runtime", "signals-dlq-controls"] },
  { ordinal: 11, id: "scope2.step-heartbeat", statement: "A healthy owner heartbeats its workflow-step lease.", gates: ["job-step-runtime"] },
  { ordinal: 12, id: "scope2.lease-transfer-fence", statement: "An old worker cannot commit after durable lease transfer.", gates: ["real-db-concurrency", "job-step-runtime"] },
  { ordinal: 13, id: "scope2.receipt-before-effect", statement: "DecisionReceipt exists before a consequential provider boundary.", gates: ["job-step-runtime", "effect-protocol"] },
  { ordinal: 14, id: "scope2.effect-commit-before-provider", statement: "The durable effect commit point precedes provider mutation.", gates: ["job-step-runtime", "effect-protocol"] },
  { ordinal: 15, id: "scope2.pre-commit-crash", statement: "A crash before the effect commit point can retry safely.", gates: ["job-step-runtime", "version-redeploy"] },
  { ordinal: 16, id: "scope2.post-commit-pre-provider-crash", statement: "A crash after commit but before provider dispatch recovers without fabricating an effect.", gates: ["job-step-runtime", "effect-protocol"] },
  { ordinal: 17, id: "scope2.provider-flight-crash", statement: "A crash during provider flight becomes durable uncertainty and reconciliation.", gates: ["effect-protocol", "observation-reconciliation"] },
  { ordinal: 18, id: "scope2.ack-loss", statement: "Provider acceptance with a lost local response cannot cause blind repetition.", gates: ["effect-protocol"] },
  { ordinal: 19, id: "scope2.stable-operation-redelivery", statement: "Logical provider-operation identity survives physical job redelivery.", gates: ["effect-protocol", "job-step-runtime"] },
  { ordinal: 20, id: "scope2.distinct-legal-attempt", statement: "A legally authorized retry has a distinct durable runtime-attempt identity.", gates: ["effect-protocol"] },
  { ordinal: 21, id: "scope2.attempt-history", statement: "Provider-operation attempt history is append-only and inspectable.", gates: ["effect-protocol", "migration-security"] },
  { ordinal: 22, id: "scope2.provider-key-stability", statement: "Provider idempotency identity remains stable across infrastructure retry.", gates: ["effect-protocol"] },
  { ordinal: 23, id: "scope2.no-fake-idempotency", statement: "A provider without native idempotency uses readback or reconciliation.", gates: ["effect-protocol"] },
  { ordinal: 24, id: "scope2.semantic-operation-key", statement: "Consequential operation identity is invariant to unrelated control-flow changes.", gates: ["architecture", "effect-protocol"] },
  { ordinal: 25, id: "scope2.verified-member-no-refire", statement: "Duplicate delivery cannot re-fire a verified provider-operation member.", gates: ["effect-protocol"] },
  { ordinal: 26, id: "scope2.known-pre-dispatch-retry", statement: "A proven pre-dispatch failure can create a legal new runtime attempt.", gates: ["effect-protocol"] },
  { ordinal: 27, id: "scope2.unknown-no-retry", statement: "An unresolved possible provider effect cannot blindly repeat.", gates: ["effect-protocol", "observation-reconciliation"] },
  { ordinal: 28, id: "scope2.ack-not-verification", statement: "Provider acknowledgement remains distinct from verified external state.", gates: ["effect-protocol", "observation-reconciliation"] },
  { ordinal: 29, id: "scope2.exact-readback", statement: "Read-after-write binds exact operation, tenant, integration, object, and BusinessEffect.", gates: ["effect-protocol", "observation-reconciliation"] },
  { ordinal: 30, id: "scope2.divergent-readback", statement: "Divergent readback enters or maintains reconciliation.", gates: ["observation-reconciliation"] },
  { ordinal: 31, id: "scope2.monotonic-observation", statement: "Duplicate and out-of-order observations cannot regress verified truth.", gates: ["observation-reconciliation"] },
  { ordinal: 32, id: "scope2.integration-pinning", statement: "Provider account and tenant integration remain pinned through operation recovery.", gates: ["effect-protocol", "migration-security"] },
  { ordinal: 33, id: "scope2.reconciliation-evidence", statement: "Consequential uncertainty cannot resolve without actor, outcome, version, and evidence.", gates: ["observation-reconciliation", "signals-dlq-controls"] },
  { ordinal: 34, id: "scope2.reconciler-idempotency", statement: "Repeated reconciliation converges without duplicating effects.", gates: ["observation-reconciliation"] },
  { ordinal: 35, id: "scope2.compensation-history", statement: "Compensation cannot erase or relabel the original effect history.", gates: ["signals-dlq-controls"] },
  { ordinal: 36, id: "scope2.unsupported-compensation", statement: "Unsupported compensation fails closed.", gates: ["signals-dlq-controls"] },
  { ordinal: 37, id: "scope2.inbox-event-dedup", statement: "Duplicate inbox and provider events are idempotent.", gates: ["signals-dlq-controls"] },
  { ordinal: 38, id: "scope2.strong-event-correlation", statement: "Weakly correlated inbound evidence cannot settle the wrong Work or effect.", gates: ["signals-dlq-controls", "observation-reconciliation"] },
  { ordinal: 39, id: "scope2.wait-restart", statement: "A durable wait survives process restart.", gates: ["signals-dlq-controls", "version-redeploy"] },
  { ordinal: 40, id: "scope2.one-logical-wake", statement: "Duplicate physical wake delivery yields one logical continuation.", gates: ["signals-dlq-controls"] },
  { ordinal: 41, id: "scope2.deadline-event-race", statement: "Deadline and event racing one wait have one terminal winner.", gates: ["signals-dlq-controls", "real-db-concurrency"] },
  { ordinal: 42, id: "scope2.stale-wake", statement: "A stale wake cannot revive obsolete orchestration.", gates: ["signals-dlq-controls", "scope1-phase15a"] },
  { ordinal: 43, id: "scope2.unknown-version", statement: "Unknown durable command or envelope versions fail closed before claim.", gates: ["version-redeploy"] },
  { ordinal: 44, id: "scope2.supported-old-version", statement: "A supported older durable protocol remains deterministically interpretable.", gates: ["version-redeploy"] },
  { ordinal: 45, id: "scope2.rolling-deploy", statement: "Mixed-version compatibility is checked before claim.", gates: ["version-redeploy", "real-db-concurrency"] },
  { ordinal: 46, id: "scope2.dlq-effect-safety", statement: "DLQ replay cannot bypass effect or reconciliation safety.", gates: ["signals-dlq-controls", "effect-protocol"] },
  { ordinal: 47, id: "scope2.nonreplayable-dlq", statement: "A non-replayable DLQ entry cannot be blindly replayed.", gates: ["signals-dlq-controls"] },
  { ordinal: 48, id: "scope2.redrive-identity", statement: "Governed redrive preserves the semantic logical-operation identity.", gates: ["signals-dlq-controls", "effect-protocol"] },
  { ordinal: 49, id: "scope2.full-restart", statement: "A full worker restart recovers from PostgreSQL truth alone.", gates: ["version-redeploy", "job-step-runtime"] },
  { ordinal: 50, id: "scope2.no-memory-timer-correctness", statement: "No process-memory timer is required for durable correctness.", gates: ["architecture", "version-redeploy"] },
  { ordinal: 51, id: "scope2.no-provider-bypass", statement: "No production-reachable consequential provider bypass remains.", gates: ["architecture", "effect-protocol"] },
  { ordinal: 52, id: "scope2.tenant-isolation", statement: "Runtime state and controls remain tenant-isolated and fail closed.", gates: ["migration-security", "signals-dlq-controls"] },
  { ordinal: 53, id: "scope2.scope1-green", statement: "Scope-1 orchestration certification remains green.", gates: ["scope1-phase15a"] },
  { ordinal: 54, id: "scope2.planner-compiler-green", statement: "Planner and compiler semantics remain unchanged and green.", gates: ["scope1-phase15a"] },
  { ordinal: 55, id: "scope2.domain-action-green", statement: "DomainAction identity and execution semantics remain green.", gates: ["scope1-phase15a"] },
  { ordinal: 56, id: "scope2.business-effect-green", statement: "BusinessEffect intent and external-truth semantics remain green.", gates: ["scope1-phase15a", "effect-protocol"] },
  { ordinal: 57, id: "scope2.authority-green", statement: "Authority and approval semantics remain green.", gates: ["scope1-phase15a"] },
  { ordinal: 58, id: "scope2.receipt-green", statement: "DecisionReceipt semantics remain green.", gates: ["scope1-phase15a", "job-step-runtime"] },
  { ordinal: 59, id: "scope2.completion-proof-green", statement: "CompletionProof semantics remain green.", gates: ["scope1-phase15a"] },
  { ordinal: 60, id: "scope2.phase15a-green", statement: "Phase 15A governance and release guarantees remain green.", gates: ["scope1-phase15a"] },
  { ordinal: 61, id: "scope2.no-would-deliver", statement: "No production-reachable would-deliver relay path remains.", gates: ["architecture"] },
  { ordinal: 62, id: "scope2.scope-boundary", statement: "Scope 2 does not freeze architecture owned by Scope 3 through 15B.", gates: ["architecture"] },
  { ordinal: 63, id: "scope2.layered-attempt-identity", statement: "Scope-1 semantic attempt, job delivery, provider operation, and physical invocation remain distinct.", gates: ["architecture", "effect-protocol"] },
  { ordinal: 64, id: "scope2.all-retry-layers-audited", statement: "Wrapped-call, SDK, and HTTP retry layers expose every consequential physical invocation.", gates: ["architecture", "effect-protocol"] },
  { ordinal: 65, id: "scope2.partial-members-first-class", statement: "Multi-member BusinessEffects retain partial verification and partial uncertainty without replaying verified members.", gates: ["effect-protocol", "observation-reconciliation"] },
  { ordinal: 66, id: "scope2.idempotency-window", statement: "Expired provider idempotency protection cannot authorize replay.", gates: ["effect-protocol"] },
  { ordinal: 67, id: "scope2.readiness-stages", statement: "Causal readiness, execution eligibility, claim, and attempt are distinct durable stages.", gates: ["architecture", "job-step-runtime"] },
  { ordinal: 68, id: "scope2.real-session-proof", statement: "Concurrency certification records one hundred distinct PostgreSQL backend sessions.", gates: ["real-db-concurrency", "performance"] },
  { ordinal: 69, id: "scope2.provider-layer-separation", statement: "Deterministic runtime provider certification and live-provider conformance are reported separately.", gates: ["architecture", "effect-protocol"] },
  { ordinal: 70, id: "scope2.truthful-effect-invariant", statement: "Unresolved consequential operations never knowingly repeat without legal durable evidence, and possible effects are tracked.", gates: ["effect-protocol"] },
  { ordinal: 71, id: "scope2.preclaim-version-filter", statement: "Known-incompatible workers do not claim durable work merely to fail later.", gates: ["version-redeploy", "real-db-concurrency"] },
  { ordinal: 72, id: "scope2.operator-control-governance", statement: "Redrive, replay, discard, reconciliation, and compensation controls are authorized, fenced, tenant-scoped, and auditable.", gates: ["signals-dlq-controls", "migration-security"] },
  { ordinal: 73, id: "scope2.recovery-owner-boundary", statement: "Runtime mechanics produce retry-safety facts while Scope 1 retains REPLAN, ESCALATE, and CANCEL decisions.", gates: ["architecture", "scope1-phase15a"] },
  { ordinal: 74, id: "scope2.retirement-obligation-guard", statement: "Runtime substrate retirement aborts when unresolved persisted obligations exist and never fabricates settlement.", gates: ["migration-security", "architecture"] },
  { ordinal: 75, id: "scope2.epistemic-provider-truth", statement: "Attempt, possible egress, acknowledgement, readback, verification, and remaining uncertainty remain separately inspectable.", gates: ["effect-protocol", "observation-reconciliation", "migration-security"] },
] as const;

export const SCOPE2_MANDATORY_CASE_COUNT = SCOPE2_MANDATORY_CASES.length;
