/** Registered real owner/queue/process challenges; no production test hooks. */
import {strict as assert} from 'node:assert';
import {randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import pg from 'pg';
import {receiveWork} from '@finnor/db';
import {restateMetricObservation} from '@finnor/private-equity';
import {prepareR1Owners,ok} from './owner-fixture.mts';

const pause=(ms:number)=>new Promise(yes=>setTimeout(yes,ms));
const census=(pid:number)=>{const r=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat=,command='],{encoding:'utf8'});return {pid,exitCode:r.status,output:r.stdout};};
export async function runLifecycle(e:any){
 const {admin,http,test,worker,waitRun,snapshot,artifact,repo}=e;
 const held=new Set<number>();
 async function until(fn:()=>Promise<any>,predicate:(r:any)=>boolean,ms=15000){const start=performance.now();let last:any;while(performance.now()-start<ms){last=await fn();if(predicate(last))return last;await pause(5);}throw Error('Observed boundary was not reached: '+JSON.stringify(last));}
 async function hold(id:string,stage:string){
  const a=await until(async()=>(await admin.query("SELECT * FROM finnor_os.r1_attempts WHERE run_id=$1 AND stage=$2 AND status='SUBMITTED'",[id,stage])).rows[0],r=>r?.child_pid>0);
  process.kill(a.child_pid,'SIGSTOP');held.add(a.child_pid);const processState=census(a.child_pid);assert.equal(processState.exitCode,0);assert(/\bT\S*\s/.test(processState.output),'Child was not physically stopped');await artifact('signals/'+a.id+'.json',{at:new Date().toISOString(),signal:'SIGSTOP',attempt:a,processState});return a;
 }
 const release=(pid:number,signal:NodeJS.Signals='SIGCONT')=>{try{process.kill(pid,signal);}catch{}held.delete(pid);};
 const submit=async(f:any)=>ok(await http.api(f.token,'policies','r1-submit',f.runRequest),202);
 async function stoppedCase(name:string,act:(f:any,id:string,a:any,w:any)=>Promise<unknown>,stage='CHECK',options:any={}){
  const f=await prepareR1Owners(e,{name,...options}),accepted=await submit(f),w=await worker();let a:any;
  try{a=await hold(accepted.runId,stage);return await act(f,accepted.runId,a,w);}finally{if(a)release(a.child_pid);await w.stop();}
 }
 try{
  await test('late-durable-claim-original-deadline','A real original 30-second run expires before any physical claim; current read is terminal UNKNOWN and later actual queue delivery never renews, computes or publishes',async()=>{
   const f=await prepareR1Owners(e,{name:'late-claim-owner'}),accepted=await submit(f),pending=ok(await http.api(f.token,'policies','r1-read',{runId:accepted.runId})),before=await snapshot(f,accepted.runId);
   assert.equal(pending.status,'QUEUED');assert.equal(pending.head,null);assert.equal(before.r1_attempts.length,0);
   const due=Date.parse(pending.decisionDeadlineAt);assert(due-Date.now()<=30000);while(Date.now()<=due)await pause(Math.min(250,due-Date.now()+1));
   const expired=ok(await http.api(f.token,'policies','r1-read',{runId:accepted.runId}));await f.artifact('expired-before-worker-reader.json',{pending,expired,before,observedAt:new Date().toISOString()});
   assert.equal(expired.status,'UNKNOWN',JSON.stringify(expired));assert.equal(expired.predicate,'R1_ORIGINAL_DECISION_DEADLINE_EXHAUSTED');assert.equal(expired.head,null);assert.equal(expired.decisionDeadlineAt,pending.decisionDeadlineAt);assert.equal(expired.originalDeadlineAt,pending.originalDeadlineAt);
   const w=await worker();try{await until(async()=>(await admin.query('SELECT status FROM finnor_os.jobs WHERE id=$1',[before.jobs[0].id])).rows[0],r=>r.status==='completed',10000);}finally{await w.stop();}
   const after=await snapshot(f,accepted.runId);assert.equal(after.r1_runs[0].status,'UNKNOWN');assert.equal(after.r1_runs[0].head_id,null);assert.equal(after.r1_attempts.length,0);assert.equal(after.r1_artifacts.filter((a:any)=>a.kind==='HEAD').length,0);assert.equal(after.episodes[0].attempts_used,before.episodes[0].attempts_used);assert.equal(after.episodes[0].steps_used,before.episodes[0].steps_used);assert.equal(after.r1_runs[0].math_steps_used,before.r1_runs[0].math_steps_used);assert.deepEqual(after.grantUsage,before.grantUsage);assert.equal(after.deliveries.length,1);assert.equal(after.deliveries[0].outcome,'completed');assert(after.r1_events.some((a:any)=>a.kind==='DECISION_DEADLINE_EXHAUSTED'));
   return {runId:accepted.runId,status:expired.status,predicate:expired.predicate,originalEpisode:expired.originalEpisode,decisionDeadlineAt:expired.decisionDeadlineAt,originalDeadlineAt:expired.originalDeadlineAt,physicallyChargedAttempts:0,acceptedDelivery:after.deliveries[0],headAbsent:true,costsRetained:true};
  });
  await test('identity-funded-original-fallback','No merge yields a real unquotiented S4 child under the same episode/grant; complete independent relation grants no effect authority',async()=>{
   const f=await prepareR1Owners(e,{name:'identity-owner',zeroReduction:true}),a=await submit(f),w=await worker();let r:any;try{r=await waitRun(f,a.runId);}finally{await w.stop();}
   const sql=await snapshot(f,a.runId);assert.equal(r.status,'INCOMPLETE',JSON.stringify(r));assert.equal(r.fallback,'ORIGINAL_PATH_EXECUTED');assert.equal(r.head.receipt.relationComplete,true);assert.equal(r.head.candidate.blocks.length,r.head.beforeStates);assert(sql.r1_attempts.some((a:any)=>a.stage==='ORIGINAL_FALLBACK'&&a.status==='RETURNED'));assert.deepEqual(r.head.evaluation.values,f.baseline.exactProfile.evaluation.values);assert.equal(r.originalEpisode,sql.episodes[0].id);return {runId:a.runId,fallback:r.fallback,stages:sql.r1_attempts.map((x:any)=>({stage:x.stage,pid:x.child_pid,status:x.status})),authority:r.executionAuthorityGranted};
  });
  await test('checker-sigkill-funded-original-fallback','A killed real checker retains UNKNOWN charge and cannot certify; the actual original path preserves original decisions within remaining grant',()=>stoppedCase('checker-kill-owner',async(f,id,a)=>{
   release(a.child_pid,'SIGKILL');const r=await waitRun(f,id),sql=await snapshot(f,id);assert.equal(r.status,'INCOMPLETE',JSON.stringify(r));assert.equal(r.head.receipt.status,'UNKNOWN');assert(['CHECKER_PROCESS_TERMINATED','CHECKER_INPUT_TRANSPORT_FAILED'].includes(r.head.receipt.predicate),JSON.stringify(r.head.receipt));assert.equal(r.head.receipt.relationComplete,false);assert.equal(r.fallback,'ORIGINAL_PATH_EXECUTED');assert(sql.r1_attempts.some((x:any)=>x.stage==='CHECK'&&x.status==='UNKNOWN'));assert(sql.r1_attempts.some((x:any)=>x.stage==='ORIGINAL_FALLBACK'&&x.status==='RETURNED'));assert.equal(Number(sql.grantUsage[0].spent),3);assert.deepEqual(r.head.evaluation.optimalActions,f.baseline.exactProfile.evaluation.optimalActions);assert.equal(census(a.child_pid).exitCode,1);return {runId:id,retainedUnknown:r.costs.unknown,fallback:r.fallback,originalEpisode:r.originalEpisode,originalGrant:r.originalGrant};
  }));
  await test('checker-original-deadline','Original response expiry terminates a held checker, retains its costs, grants no new deadline and reports incompatible remaining fallback precisely',()=>stoppedCase('checker-deadline-owner',async(f,id,a)=>{
   const before=(await admin.query('SELECT * FROM finnor_os.r1_runs WHERE id=$1',[id])).rows[0];await until(async()=>census(a.child_pid),r=>r.exitCode===1,10000);held.delete(a.child_pid);
   await pause(3500);const r=ok(await http.api(f.token,'policies','r1-reconcile',{runId:id})),sql=await snapshot(f,id);assert.equal(r.head,null);assert.equal(r.status,'UNKNOWN',JSON.stringify(r));assert(sql.r1_attempts.some((x:any)=>x.stage==='CHECK'&&x.status==='UNKNOWN'));assert.equal(r.decisionDeadlineAt,before.decision_deadline_at.toISOString());assert.equal(sql.episodes[0].attempts_used,2);assert.equal(Number(sql.grantUsage[0].spent),2);assert(!sql.r1_attempts.some((x:any)=>x.stage==='ORIGINAL_FALLBACK'));return {runId:id,decisionDeadlineAt:r.decisionDeadlineAt,originalDeadlineAt:r.originalDeadlineAt,unknown:r.costs.unknown,fallbackAvailable:false,predicate:'ORIGINAL_RESPONSE_DEADLINE_NO_REMAINING_COMPATIBLE_EXECUTION'};
  },'CHECK',{deadlineMs:10000}));
  await test('worker-sigkill-cold-reconciliation','Physical worker death leaves an original durable UNKNOWN attempt; a cold lease reconciliation quarantines the delivery without physical replay',()=>stoppedCase('worker-kill-owner',async(f,id,a,w)=>{
   const heldState=census(a.child_pid),actualParent=Number(heldState.output.trim().split(/\s+/)[1]);await artifact('signals/'+a.id+'-worker-ownership.json',{heldState,actualParent,factoryWorkerPid:w.child.pid});assert.equal(actualParent,w.child.pid,'Physical crash must target the actual held-child parent');const before=census(w.child.pid);w.child.kill('SIGKILL');await w.exited;assert.equal(census(w.child.pid).exitCode,1);release(a.child_pid);await until(async()=>census(a.child_pid),r=>r.exitCode===1,10000);
   await pause(3500);const cold=await worker('RECONCILE');await cold.exited;await cold.log();const r=ok(await http.api(f.token,'policies','r1-reconcile',{runId:id})),sql=await snapshot(f,id);
   assert.equal(r.status,'UNKNOWN',JSON.stringify(r));assert.equal(r.head,null);assert.equal(sql.jobs[0].status,'quarantined');assert.equal(sql.deliveries.length,1);assert.equal(sql.deliveries[0].outcome,'reconciliation_required');assert.equal(sql.r1_attempts.length,2);assert.equal(Number(sql.grantUsage[0].spent),2);assert(sql.r1_attempts.some((x:any)=>x.stage==='CHECK'&&x.status==='UNKNOWN'));return {runId:id,killed:before,coldPid:cold.child.pid,childrenReaped:true,retainedGrantCharge:sql.grantUsage[0].spent,automaticReplay:false};
  }));
  await test('cancel-real-checker','Actual cancellation fences the held checker and later publication while retaining physical attempts, charges and unknown responsibility',()=>stoppedCase('cancel-owner',async(f,id,a)=>{
   const cancelled=ok(await http.api(f.token,'policies','r1-cancel',{runId:id}));assert.equal(cancelled.status,'CANCELLED');release(a.child_pid);await until(async()=>census(a.child_pid),r=>r.exitCode===1);
   await pause(1500);const r=ok(await http.api(f.token,'policies','r1-read',{runId:id})),sql=await snapshot(f,id);assert.equal(r.status,'CANCELLED');assert.equal(r.head,null);assert.equal(sql.r1_artifacts.filter((a:any)=>a.kind==='HEAD').length,0);assert.equal(sql.episodes[0].attempts_used,2);assert.equal(Number(sql.grantUsage[0].spent),2);assert.equal(r.cancellation.unknownResponsibilitiesReleased,false);const commonRequest={schema:'finnor.r1.run.v2',problem_ref:f.runRequest.problem_ref,envelope_inputs:f.runRequest.envelope_inputs,existing_work_revision:f.runRequest.work_rev,domain_profile_ref:f.source.sourceRef,budget_grant_ref:f.runRequest.grant,cancellation_ref:r.cancellation.ref,idempotencyKey:'cancel-replay-'+id};const replay=ok(await http.api(f.token,'policies','r1-submit',commonRequest));assert.equal(replay.id,id);assert.equal(replay.status,'INCOMPLETE');assert.equal(replay.runtime_status,'CANCELLED');assert.equal(replay.originalEpisode,r.originalEpisode);assert.equal(replay.artifact_ref,null);assert.equal(replay.cancellation.unknownResponsibilitiesReleased,false);const changed=await http.api(f.token,'policies','r1-submit',{...commonRequest,cancellation_ref:{...r.cancellation.ref,contentDigest:'0'.repeat(64)}});assert(changed.status>=400);const after=await snapshot(f,id);assert.equal((await admin.query('SELECT count(*)::int n FROM finnor_os.r1_runs WHERE tenant_id=$1',[f.tenant])).rows[0].n,1);assert.deepEqual(after.grantUsage,sql.grantUsage);assert.equal(after.episodes[0].attempts_used,sql.episodes[0].attempts_used);assert.equal(after.r1_attempts.length,sql.r1_attempts.length);await f.artifact('common-cancellation-replay.json',{commonRequest,replay,changed,after});return {runId:id,generation:r.cancellation.generation,unknown:r.costs.unknown,costsRetained:true,cancellationRef:r.cancellation.ref};
  }));
  await test('source-restatement-real-p7','An actual S1 metric restatement invalidates dependent R1/S4 claims; the actual registered P7 worker appends the correct closure under the original episode',()=>stoppedCase('source-revision-owner',async(f,id,a)=>{
   const correction=await restateMetricObservation(f.ctx,{priorObservationId:String(f.observations.debt.row.id),expectedVersion:1,replacement:{value:{type:'number',value:'80'},evidence:f.evidence}});const r=ok(await http.api(f.token,'policies','r1-read',{runId:id}));assert.equal(r.status,'INVALIDATED',JSON.stringify(r));assert.equal(r.head,null);assert.equal(r.predicate,'R1_S1_SOURCE_OR_RIGHTS_REVISED');release(a.child_pid);
   const patch=await until(async()=>(await admin.query("SELECT * FROM finnor_os.r1_artifacts WHERE run_id=$1 AND kind='P7_INVALIDATION_PATCH'",[id])).rows[0],r=>r?.body);
   const sql=await snapshot(f,id);assert(patch.body.closure.affected.includes(id+':SOURCE'));assert(patch.body.closure.affected.includes(id+':S5_DEMAND'));assert.equal(patch.body.originalEpisode,sql.episodes[0].id);assert.equal(patch.body.newComputeGrantGranted,false);assert.equal(patch.body.claimPublication,false);assert.equal(sql.r1_artifacts.filter((a:any)=>a.kind==='HEAD').length,0);const oldPolicy=await http.api(f.token,'policies','read',{policyRef:f.baseline.ref});assert(oldPolicy.status>=400);const h=ok(await http.api(f.token,'policies','r1-history',{runId:id}));assert(h.events.some((x:any)=>x.kind==='P7_INVALIDATION_PATCH_PUBLISHED'));return {runId:id,correction,patch:patch.body,currentHead:null,historyPermitted:true};
  }));
  await test('work-input-revision','A real newer Work input fences the old accepted episode and prevents stale original-input publication',()=>stoppedCase('work-revision-owner',async(f,id,a)=>{
   const input=await receiveWork({tenantId:f.tenant,userId:f.principal,workId:f.work.workId,instruction:'Revised original analysis after a new received instruction.',channel:'console',idempotencyKey:randomUUID()});assert.notEqual(input.workInputId,f.work.workInputId);const r=ok(await http.api(f.token,'policies','r1-read',{runId:id}));assert.equal(r.status,'INVALIDATED',JSON.stringify(r));release(a.child_pid);assert.equal(r.head,null);assert.match(r.predicate,/WORK|INPUT|REVISION|REVISED/);return {runId:id,original:f.work.workInputId,current:input.workInputId,predicate:r.predicate};
  }));
  await test('principal-revoked-during-search','Suspending the actual authenticated owner during accepted physical search denies private reads and fences publication',()=>stoppedCase('principal-revocation-owner',async(f,id,a)=>{
   await admin.query("UPDATE finnor_os.users SET status='suspended' WHERE tenant_id=$1 AND id=$2",[f.tenant,f.principal]);const read=await http.api(f.token,'policies','r1-read',{runId:id}),history=await http.api(f.token,'policies','r1-history',{runId:id});assert(read.status>=400);assert(history.status>=400);release(a.child_pid);await pause(1800);const sql=await snapshot(f,id);assert.equal(sql.r1_artifacts.filter((x:any)=>x.kind==='HEAD').length,0);assert.equal(Number(sql.grantUsage[0].spent),2);return {runId:id,readStatus:read.status,historyStatus:history.status,headAbsent:true,costsRetained:true};
  }));
  await test('principal-row-lock-before-publication','After independent checking, actual principal revocation holds the worker SQL boundary and prevents any certified head or private read',()=>stoppedCase('principal-locked-publication-owner',async(f,id,a)=>{
   const cp=admin.connectionParameters,locker=new pg.Client({host:cp.host,port:cp.port,user:cp.user,password:cp.password,database:cp.database});await locker.connect();let committed=false;
   try{
    const lockerPid=(await locker.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;await locker.query('BEGIN');
    await locker.query('SELECT id FROM finnor_os.users WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[f.tenant,f.principal]);await locker.query("UPDATE finnor_os.users SET status='suspended' WHERE tenant_id=$1 AND id=$2",[f.tenant,f.principal]);
    release(a.child_pid);
    const waits=await until(async()=>(await admin.query('SELECT pid,wait_event_type,wait_event,state,query,pg_blocking_pids(pid) blockers FROM pg_stat_activity WHERE $1=ANY(pg_blocking_pids(pid))',[lockerPid])).rows,r=>r.length>0,10000);
    const before=await snapshot(f,id);assert(before.r1_attempts.some((x:any)=>x.stage==='CHECK'&&x.status==='RETURNED'));assert.equal(before.r1_artifacts.filter((x:any)=>x.kind==='HEAD').length,0);await f.artifact('principal-before-publication-lock.json',{lockerPid,waits,originalDecisionDeadline:before.r1_runs[0].decision_deadline_at,heldEvaluationPid:a.child_pid});
    await locker.query('COMMIT');committed=true;await until(async()=>(await admin.query('SELECT status FROM finnor_os.r1_runs WHERE id=$1',[id])).rows[0],r=>r.status!=='RUNNING',10000);
    const read=await http.api(f.token,'policies','r1-read',{runId:id}),history=await http.api(f.token,'policies','r1-history',{runId:id}),after=await snapshot(f,id);
    assert(read.status>=400);assert(history.status>=400);assert.equal(after.r1_runs[0].head_id,null);assert.equal(after.r1_artifacts.filter((x:any)=>x.kind==='HEAD').length,0);assert.equal(Number(after.grantUsage[0].spent),3);
    return {runId:id,lockerPid,waits,revocationCommitted:true,readStatus:read.status,historyStatus:history.status,headAbsent:true,originalDecisionDeadline:after.r1_runs[0].decision_deadline_at,chargedPhysicalAttempts:3};
   }finally{if(!committed)await locker.query('ROLLBACK');await locker.end();}
  },'S4_EVALUATE'));
  await test('method-replacement-cold-restart','A changed loaded implementation fences old inputs; restored bytes and cold restart do not resurrect the invalidated generation',()=>stoppedCase('method-replacement-owner',async(f,id,a,w)=>{
   const file=join(repo,'finnor-os/packages/private-equity/src/r1/native-child.mts'),original=await readFile(file);let r:any;
   await artifact('method-preimage.json',{path:'finnor-os/packages/private-equity/src/r1/native-child.mts',bytes:original.toString('utf8'),mutation:'append inert source comment'});
   try{await writeFile(file,Buffer.concat([original,Buffer.from('\n// Disposable registered source identity replacement.\n')]));r=ok(await http.api(f.token,'policies','r1-read',{runId:id}));assert.equal(r.status,'INVALIDATED',JSON.stringify(r));assert.match(r.predicate,/METHOD|SOURCE|LOADED/);}finally{await writeFile(file,original);}
   release(a.child_pid);await w.stop();const cold=await worker();await pause(1800);await cold.stop();const after=ok(await http.api(f.token,'policies','r1-read',{runId:id})),sql=await snapshot(f,id);assert.equal(after.status,'INVALIDATED');assert.equal(after.head,null);assert.equal(sql.r1_attempts.length,2);assert.equal(sql.r1_artifacts.filter((x:any)=>x.kind==='HEAD').length,0);return {runId:id,predicate:r.predicate,coldPid:cold.child.pid,sourceRestored:true,originalGenerationNotResurrected:true};
  }));
  await test('duplicate-and-stale-durable-delivery','Duplicated generation1 and stale generation0 jobs reach the actual queue worker without creating another child, episode charge or publication',async()=>{
   const f=await prepareR1Owners(e,{name:'duplicate-owner'}),a=await submit(f),w=await worker();try{assert.equal((await waitRun(f,a.runId)).status,'COMPLETE');}finally{await w.stop();}
   const before=await snapshot(f,a.runId),job=before.jobs[0];for(const generation of [1,0])await admin.query("INSERT INTO finnor_os.jobs(tenant_id,type,payload,idempotency_key,lane,protocol_version,retry_safety) VALUES($1,$2,$3::jsonb,$4,'interactive',1,'reconcilable')",[f.tenant,job.type,JSON.stringify({...job.payload,generation}),'disposable-duplicate:'+randomUUID()]);const cold=await worker();await until(async()=>(await admin.query("SELECT count(*)::int n FROM finnor_os.jobs WHERE payload->>'runId'=$1 AND type='run_certified_state_reduction_v1' AND status NOT IN('completed','failed','quarantined')",[a.runId])).rows[0].n,n=>n===0);await cold.stop();const after=await snapshot(f,a.runId);assert.equal(after.r1_attempts.length,3);assert.equal(after.episodes[0].attempts_used,3);assert.equal(Number(after.grantUsage[0].spent),3);assert.equal(after.r1_artifacts.filter((x:any)=>x.kind==='HEAD').length,1);assert.equal(after.jobs.length,3);return {runId:a.runId,physicalAttempts:3,deliveredJobs:3,headCount:1};
  });
  await test('foreign-tenant-and-principal','Bearer verification and actual forced RLS deny another principal or tenant the accepted run, history and owner-bound submission',async()=>{
   const f=await prepareR1Owners(e,{name:'private-owner'}),a=await submit(f),foreign=await prepareR1Owners(e,{name:'foreign-owner'}),principal=randomUUID();await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status,display_name) VALUES($1,$2,$3,'owner','active','Other actual principal')",[principal,f.tenant,principal+'@r1.example.test']);http.register(principal,principal+'@r1.example.test');const ownOther=await http.login(principal),proof=[];const current=ok(await http.api(f.token,'policies','r1-read',{runId:a.runId})),event=current.lifecycle_event_refs.find((r:any)=>r.kind==='ACCEPTED'),ref={owner:event.owner,id:event.id,version:event.version,contentDigest:event.contentDigest},recordRequest={schema:'finnor.r1.record-read.v1',runId:a.runId,ref};const owned=ok(await http.api(f.token,'policies','r1-record',recordRequest));assert.equal(owned.kind,'ACCEPTED');for(const token of [foreign.token,ownOther])for(const [op,body] of [['r1-read',{runId:a.runId}],['r1-history',{runId:a.runId}],['r1-record',recordRequest],['r1-submit',{...f.runRequest,idempotencyKey:randomUUID()}]] as const){const r=await http.api(token,'policies',op,body);assert(r.status>=400);assert(!JSON.stringify(r.body).includes('modelBytes'));proof.push({identity:token===ownOther?'OTHER_PRINCIPAL_SAME_TENANT':'OTHER_TENANT',op,status:r.status,body:r.body});}await f.artifact('unauthorized.json',proof);ok(await http.api(f.token,'policies','r1-cancel',{runId:a.runId}));return proof;
  });
  await test('two-works-one-issued-grant','Two actual Works/P1 episodes use one original issued S5 certificate and shared native counter; parallel child admission cannot exceed its four attempts',async()=>{
   const f=await prepareR1Owners(e,{name:'shared-grant-owner',grantAttempts:4});const work2=await receiveWork({tenantId:f.tenant,userId:f.principal,instruction:f.programRequest.instruction,channel:'console',idempotencyKey:randomUUID()}),source2=ok(await http.api(f.token,'interventions','exact-control-model',{workId:work2.workId,workRevision:work2.workInputId,modelBytes:JSON.stringify(f.originalModel),mandate:f.mandate}));
   const program2=ok(await http.api(f.token,'company-brain','program-submit',{...f.programRequest,workId:work2.workId,workInputId:work2.workInputId,idempotencyKey:randomUUID()}),202),request2={...f.runRequest,problem_ref:source2.sourceRef,work_rev:program2.workRevision,envelope_inputs:{...f.runRequest.envelope_inputs,programId:program2.programId},idempotencyKey:randomUUID()};
   const accepted=await Promise.all([submit(f),http.api(f.token,'policies','r1-submit',request2).then((r:any)=>ok(r,202))]),workers=await Promise.all([worker(),worker()]);let reads:any[];try{reads=await Promise.all(accepted.map((a:any)=>waitRun(f,a.runId)));}finally{for(const w of workers)await w.stop();}
   const sql=await Promise.all(accepted.map((a:any)=>snapshot(f,a.runId))),attempts=sql.flatMap((s:any)=>s.r1_attempts);assert(attempts.length<=4);assert.equal(Number(sql[0].grantUsage[0].spent),attempts.length);assert.equal(Number(sql[0].grantUsage[0].spent),4);assert(reads.some(r=>r.status!=='COMPLETE'));assert(reads.every(r=>r.originalGrant.contentDigest===f.allocation.certificate.ref.contentDigest));assert.notEqual(sql[0].episodes[0].id,sql[1].episodes[0].id);assert.equal(sql.reduce((n,s)=>n+s.episodes[0].attempts_used,0),4);return {runs:reads.map(r=>({id:r.id,status:r.status,predicate:r.predicate,originalEpisode:r.originalEpisode})),sameGrant:f.allocation.certificate.ref,physicallyChargedAttempts:attempts.length,newReservationForSecondWork:false};
  });
  await test('physical-capacity-refusal-is-not-source-revision','A third real queue delivery while both permitted native processes are held refuses physical capacity without false SOURCE invalidation, new attempt or grant charge',async()=>{
   const fixtures:any[]=[];for(const name of ['capacity-one','capacity-two','capacity-three'])fixtures.push(await prepareR1Owners(e,{name}));const accepted:any[]=[],workers:any[]=[],stopped:any[]=[];
   try{
    accepted.push(await submit(fixtures[0]));workers.push(await worker());stopped.push(await hold(accepted[0].runId,'PRODUCE'));
    accepted.push(await submit(fixtures[1]));workers.push(await worker());stopped.push(await hold(accepted[1].runId,'PRODUCE'));
    const policies=(await admin.query("SELECT resource_key,capacity,per_tenant_capacity FROM finnor_os.compute_resource_policies WHERE resource_key='native:p2'")).rows;
    const occupancy=(await admin.query("SELECT * FROM finnor_os.compute_resource_leases WHERE resource_key='native:p2' AND released_at IS NULL AND expires_at>now()")).rows;
    await artifact('capacity-before-third-delivery.json',{policies,occupancy,heldProcesses:stopped.map(a=>census(a.child_pid))});assert.equal(occupancy.length,2);
    accepted.push(await submit(fixtures[2]));workers.push(await worker());const r=await waitRun(fixtures[2],accepted[2].runId),sql=await snapshot(fixtures[2],accepted[2].runId);
    assert.equal(r.status,'UNKNOWN',JSON.stringify(r));assert.equal(r.predicate,'R1_SHARED_PHYSICAL_CAPACITY_UNAVAILABLE');assert.equal(sql.r1_attempts.length,0);assert(!sql.r1_events.some((x:any)=>x.kind==='P7_DEPENDENCY_HANDOFF'));assert.equal(sql.episodes[0].attempts_used,0);
    return {runId:r.id,status:r.status,predicate:r.predicate,physicalPolicies:policies,occupiedLeases:occupancy,heldPids:stopped.map(a=>a.child_pid),chargedAttempts:0};
   }finally{for(let i=0;i<2;i++)if(accepted[i])ok(await http.api(fixtures[i].token,'policies','r1-cancel',{runId:accepted[i].runId}));for(const a of stopped)release(a.child_pid);for(const w of workers)await w.stop();}
  });
  await test('bounded-arithmetic-original-remaining-grant','A reduced arithmetic allowance accounts for common preparation, remains finite and retains actual original fallback attempts or precise absence without certified publication',async()=>{
   const f=await prepareR1Owners(e,{name:'bounded-owner'}),cost=Number(f.source.preparation.mathSteps)+Number(f.baseline.exactProfile.evaluation.stats.steps);f.runRequest.envelope_inputs.maxMathSteps=cost+4000;const a=await submit(f),w=await worker();let r:any;try{r=await waitRun(f,a.runId);}finally{await w.stop();}const sql=await snapshot(f,a.runId);assert.notEqual(r.status,'COMPLETE');assert(sql.r1_runs[0].math_steps_used<=cost+4000);assert(sql.r1_events.some((x:any)=>x.kind==='COMMON_PREPARATION_CHARGED'));assert.equal(r.executionAuthorityGranted,false);return {runId:a.runId,originalMathAllowance:cost+4000,observedMathUsed:sql.r1_runs[0].math_steps_used,status:r.status,predicate:r.predicate,fallbackStages:sql.r1_attempts.filter((x:any)=>x.stage==='ORIGINAL_FALLBACK').map((x:any)=>({pid:x.child_pid,status:x.status})),originalEpisode:r.originalEpisode};
  });
  await test('s6-unknown-responsibility','The original real local provider loses acknowledgement after one accepted effect; R1 invalidates its current claim and retains genuine S6 UNKNOWN while cold recovery does not replay that effect',async()=>{
   const {prepareS6BeforeR1Source,proveS6R1Response}=await import('./s6-responsibility.mts');
   const f=await prepareR1Owners(e,{name:'s6-response-owner',beforeSource:g=>prepareS6BeforeR1Source(e,g)}),accepted=await submit(f),w=await worker();let a:any,observed:any;
   try{a=await hold(accepted.runId,'CHECK');const proof=await proveS6R1Response(e,f,async unknown=>{
    const r=ok(await http.api(f.token,'policies','r1-read',{runId:accepted.runId}));assert.equal(r.status,'INVALIDATED',JSON.stringify(r));assert.equal(r.predicate,'R1_S6_OUTSTANDING_RESPONSIBILITY_RETAINED');assert.equal(r.head,null);assert(r.responsibility.unresolved.length>0);assert.equal(r.responsibility.responsibilityReleased,false);const native=await snapshot(f,accepted.runId);assert(native.businessEffects.some((x:any)=>!['verified','cancelled','compensated'].includes(x.status)));observed={unknown,current:r,native};await f.artifact('genuine-s6-unknown-r1-response.json',observed);release(a.child_pid);
   });assert(observed);const after=ok(await http.api(f.token,'policies','r1-read',{runId:accepted.runId}));assert.equal(after.status,'INVALIDATED');assert.equal(after.head,null);return {runId:accepted.runId,proof,genuineUnknownObserved:true,originalEpisode:after.originalEpisode,unknownResponsibilityReleased:false};}
   finally{if(a)release(a.child_pid);await w.stop();}
  });
 }finally{for(const pid of held)release(pid,'SIGKILL');}
}
