import {z} from 'zod';
import {ObligationOperationSchemas,prepareEnterpriseDurableObligation,readEnterpriseDurableObligation,readEnterpriseDurableObligationCommitment,validateEnterpriseDurableObligation,compileEnterpriseDurableObligationRequest,assessEnterpriseDurableObligationDispatch,readEnterpriseDurableObligationBudgets,readEnterpriseDurableObligationExecutionHandoff,assessEnterpriseDurableObligationBudget,executeEnterpriseDurableObligationRequest,scheduleEnterpriseDurableObligationRequest,cancelEnterpriseDurableObligationDelivery,PeDomainError} from '@finnor/private-equity';
import {AllocationContractError,ControlContractError,InterventionContractError} from '@finnor/epistemic-runtime';
import {requireContext,errorResponse} from '../../../../lib/auth';
import {LedgerFault} from '../../../../../../packages/governed-execution/src/protocol';
export const runtime='nodejs';
function response(body:unknown,status=200){const bytes=JSON.stringify(body);if(Buffer.byteLength(bytes)>8*1024*1024)return new Response(JSON.stringify({code:'RESPONSE_BOUND_EXCEEDED'}),{status:503,headers:{'content-type':'application/json','cache-control':'private, no-store'}});return new Response(bytes,{status,headers:{'content-type':'application/json','cache-control':'private, no-store'}});}
async function boundedJson(req:Request):Promise<unknown>{
 const limit=2*1024*1024;if(Number(req.headers.get('content-length')??0)>limit){await req.body?.cancel().catch(()=>undefined);throw new AllocationContractError('LIMIT_EXCEEDED','S6 input exceeds 2 MiB');}
 if(!req.body)throw new AllocationContractError('INVALID_REQUEST','Bounded JSON required');const reader=req.body.getReader(),bytes=Buffer.alloc(limit);let size=0;
 try{while(true){const chunk=await reader.read();if(chunk.done)break;if(chunk.value.length>limit-size){await reader.cancel().catch(()=>undefined);throw new AllocationContractError('LIMIT_EXCEEDED','S6 input exceeds 2 MiB');}bytes.set(chunk.value,size);size+=chunk.value.length;}return JSON.parse(bytes.subarray(0,size).toString());}catch(e){if(e instanceof AllocationContractError)throw e;throw new AllocationContractError('INVALID_REQUEST','Bounded JSON required');}finally{reader.releaseLock();}
}
export async function POST(req:Request,{params}:{params:Promise<{operation:string}>}):Promise<Response>{
 try{const [auth,route]=await Promise.all([requireContext(req),params]);if(auth.role!=='owner')return response({code:'OWNER_REQUIRED'},403);const body=await boundedJson(req),ctx={auth};
  switch(route.operation){case 'prepare':return response(await prepareEnterpriseDurableObligation(ctx,ObligationOperationSchemas.prepare.parse(body)));case 'read':return response(await readEnterpriseDurableObligation(ctx,ObligationOperationSchemas.read.parse(body).obligationRef));case 'read-commitment':return response(await readEnterpriseDurableObligationCommitment(ctx,ObligationOperationSchemas['read-commitment'].parse(body).obligationRef));case 'validate':return response(await validateEnterpriseDurableObligation(ctx,ObligationOperationSchemas.validate.parse(body).obligationRef));case 'compile-request':return response(await compileEnterpriseDurableObligationRequest(ctx,body));case 'read-execution-handoff':return response(await readEnterpriseDurableObligationExecutionHandoff(ctx,body));case 'budget-status':return response(await readEnterpriseDurableObligationBudgets(ctx,body));case 'check-budget':return response(await assessEnterpriseDurableObligationBudget(ctx,body));case 'check-dispatch':return response(await assessEnterpriseDurableObligationDispatch(ctx,body));case 'execute-request':return response(await executeEnterpriseDurableObligationRequest(ctx,body));case 'reconcile-request':return response(await executeEnterpriseDurableObligationRequest(ctx,body,true));case 'schedule-request':return response(await scheduleEnterpriseDurableObligationRequest(ctx,body));case 'cancel-delivery':return response(await cancelEnterpriseDurableObligationDelivery(ctx,body));default:return response({code:'NOT_FOUND'},404);}
 }catch(e){if(e instanceof z.ZodError)return response({code:'INVALID_REQUEST'},400);if(e instanceof LedgerFault)return response({code:e.code},e.status);if(e instanceof PeDomainError)return response({code:e.code,error:e.message},/NOT_FOUND/.test(e.code)?404:422);if(e instanceof AllocationContractError||e instanceof ControlContractError||e instanceof InterventionContractError)return response({code:e.code,error:e.message},e.code==='LIMIT_EXCEEDED'?413:e.code==='PERMITTED_CONTEXT_UNAVAILABLE'?404:['STALE_INPUT','IDEMPOTENCY_CONFLICT'].includes(e.code)?409:400);return errorResponse(e);}
}
