/** Generated signed state setup only; never independent future-gain evidence.
 * Shared by native currentness and physical-reconciliation E2E owners. */
import { strict as assert } from 'node:assert';
import { digest } from '../../packages/capability-evolution/src/contracts';
export async function admitGeneratedLifecycleControl(input: { revision: any; wave: string; service: any; command: (actor: string, operation: string, body: any) => Promise<any>; attempts: any[]; costRefs: any[]; searchCost: number; admit?: boolean }) {
        const { revision: r, wave, service, command, attempts, costRefs, searchCost } = input, evaluator = service.policy.evaluatorKeys[0].principalId, admit = input.admit !== false;
        const success = (answer: any) => { assert.equal(answer.status, 200, JSON.stringify(answer)); return answer.body; };
        const categories = ['search', 'training', 'evaluation', 'human', 'computeData', 'integration', 'maintenance', 'recovery', 'deployment'];
        const protocol = { schema: 'finnor.s8.evaluation-protocol.v1', tenantId: r.tenantId, principalId: r.principalId, revisionRef: r.ref, evaluatorId: evaluator, registeredAt: new Date().toISOString(), trainingCutoff: r.experience.knowledgeCut, domain: r.domain, caseCommitments: [digest(wave + ':1'), digest(wave + ':2')], companies: [wave + ':company1', wave + ':company2'], dependenceGroups: [wave + ':group1', wave + ':group2'], chronologicalStart: new Date(Date.parse(r.experience.knowledgeCut) + 1).toISOString(), chronologicalEnd: new Date().toISOString(), strata: r.domain.strata, priorDomains: ['prior-regime'], baselines: ['INCUMBENT', 'STRONG_FIXED', 'INDEPENDENT_EVOLUTION'].map(kind => ({ id: kind, kind, payloadDigest: digest(kind), dependencyDigest: digest(service.policy.sourcePins), resourceEnvelopeDigest: digest(r.envelope) })), scoringAssetsDigest: digest('GENERATED_NATIVE_CURRENTNESS_STATE_SETUP_ONLY'), harnessDigest: digest(service.policy.sourcePins), splitDigest: digest(wave), oracle: 'EXACT_CANONICAL_REFERENCE', materialGain: 0.1, scoreRange: 12, confidence: 0.95, maxSubmissions: 8, maxWaves: 4, minIndependentGroups: 2, floors: { correctness: 0.95, regret: 0.05, calibrationError: 0.02, safetyViolations: 0, maxEpisodeCost: 100, maxHumanSeconds: 900 }, feedback: 'FINAL_AGGREGATE_ONLY_ONE_USE', horizon: 'H1', costAllocation: 'COMPLETE_INCURRED_COST_NO_SPECULATIVE_REUSE' };
        const registered = success(await command('evaluator', 'REGISTER', service.signed(protocol, 'evaluator')));
        const report = { schema: 'finnor.s8.evaluation-summary.v1', protocolRef: registered.ref, revisionRef: r.ref, evaluatorId: evaluator, completedAt: new Date().toISOString(), disposition: 'BENEFICIAL', gain: [1, 2], allFloorsPassed: true, priorDomainsPassed: true, costs: { ...Object.fromEntries(categories.map(c => [c, c === 'search' ? [searchCost, searchCost] : [0, 0]])), costRefs, currency: 'USD', basis: 'REGISTERED_GENERATIVE_MODEL' }, failedCandidates: 0, attemptsDigest: digest(attempts), resultsCommitment: digest('GENERATED_STATE_SETUP_NOT_NATIVE_METHOD_GAIN'), classification: 'PARTIAL', qualification: 'GENERATIVE_H1', reasons: ['GENERATED_SIGNED_STATE_SETUP_ONLY_NOT_FUTURE_VALUE_EVIDENCE'] };
        const evaluated = success(await command('evaluator', 'EVALUATE', service.signed(report, 'evaluator')));
        const admissionBody = { revisionRef: r.ref, evaluationRef: evaluated.ref, payloadDigest: digest(r.payload), dependencyDigest: digest(r.dependencies), domain: r.domain, executionAuthorityGranted: false, horizon: 'H1', evaluatorId: evaluator };
        if (admit) success(await command('evaluator', 'ADMIT', service.signed(admissionBody, 'evaluator')));
        return admissionBody;
    }
