version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Kolkata
    groups:
      release-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
