import type {ContingentPolicy,ControlProblem,ControlObligation,EconomicMandate,ExactControlPolicyProfile,PolicyNode,S4ComputeInvocation} from '@finnor/shared-types';
import {CONTROL_ADMISSION,immutableControl,parseEconomicMandate} from './control-contracts';
import {epistemicHash} from './source-precedence';
import {parseExactInformationModel,ControlFraction as Q,ExactControlError,controlMeter,type ExactControlBudget} from './certified-state-reduction';
export const EXACT_S4_VERSION='s4-finite-contingent-exact-v2' as const;
/** Conversion is for retained legacy UI fields only. All decision arithmetic
 * and canonical S5 demand read the authoritative exact profile. */
export function exactPresentation(value:unknown):number{const q=Q.readDerived(value);if(!q.n)return 0;const digits=(q.n<0n?-q.n:q.n).toString(),den=q.d.toString();const n=(q.n<0n?-1:1)*(Number(digits.slice(0,16))/Number(den.slice(0,16)))*10**((digits.length-Math.min(16,digits.length))-(den.length-Math.min(16,den.length)));if(!Number.isFinite(n))throw new ExactControlError('UNSUPPORTED','EXACT_PRESENTATION_MAGNITUDE');return n;}
export function buildExactControlPolicy(mandate:EconomicMandate,profile:ExactControlPolicyProfile,compute:S4ComputeInvocation,now:string,budget:ExactControlBudget):ContingentPolicy|null {
 budget={...budget,account:budget.account??{steps:0}};const meter=controlMeter(budget);meter.step();
 const m=parseEconomicMandate(mandate),source=parseExactInformationModel(profile.modelBytes,budget),e=profile.evaluation;
 if(e.status!=='COMPLETE'||!e.completeSearch)return null;
 if(epistemicHash(m.ref)!==epistemicHash(source.mandateRef)||m.tenantId!==source.tenantId||m.principalId!==source.principalId||m.rightsRef!==source.rightsRef||epistemicHash(m.horizon)!==epistemicHash(source.horizon)||m.utility.unit!==source.units.utility)throw new ExactControlError('UNSUPPORTED','ORIGINAL_MANDATE_MODEL_BINDING');
 const actions=source.actions.map(a=>({...a,cost:exactPresentation(a.cost),resources:Object.fromEntries(Object.entries(a.resources).map(([k,v])=>[k,exactPresentation(v)])),occupancy:Object.fromEntries(Object.entries(a.occupancy).map(([k,v])=>[k,exactPresentation(v)])),tailLiability:exactPresentation(a.tailLiability),humanSeconds:exactPresentation(a.humanSeconds),exposures:Object.fromEntries(Object.entries(a.exposures).map(([k,v])=>[k,v.map(exactPresentation)]))}));
 const vector=(v:unknown)=>v===null?null:Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([k,q])=>[k,exactPresentation(q)]));
 const obligations:ControlObligation[]=source.states.find(s=>s.id===e.root)!.semantics.obligations.map(o=>{
  if(!Object.hasOwn(o,'actionId')||!Object.hasOwn(o,'exposures')||!Object.hasOwn(o,'resources')||!Object.hasOwn(o,'occupancy')||!Array.isArray(o.lockedExposureIds)||!Number.isSafeInteger(o.occupationUntilPeriod)||!Object.hasOwn(o,'terminalLiability'))throw new ExactControlError('UNSUPPORTED','S4_COMPLETE_EXACT_OBLIGATION_PROJECTION_REQUIRED');
  return {ref:o.ref,effectRef:o.effectRef,status:o.status,actionId:o.actionId as string|null,exposures:o.exposures===null?null:Object.fromEntries(Object.entries(o.exposures as Record<string,unknown[]>).map(([k,v])=>[k,v.map(exactPresentation)])),resources:vector(o.resources),occupancy:vector(o.occupancy),lockedExposureIds:o.lockedExposureIds as string[],occupationUntilPeriod:o.occupationUntilPeriod as number,terminalLiability:o.terminalLiability===null?null:exactPresentation(o.terminalLiability)};
 });
 const problem:ControlProblem={schema:'finnor.control-problem.exact.v2',id:source.id,episodeId:m.episodeId,modelRef:profile.sourceRef,context:'SUPPLIED_EXACT_INFORMATION_TABLE',regime:'FINITE_MODEL_RELATIVE',baselineExposures:{},actions,observations:source.observationInstruments.map(i=>({schema:'finnor.s2.control-observation.exact.v2',id:i.id,sourceRef:i.sourceRef,variableId:i.measurement?.seriesId??i.id,unit:i.measurement?.unit??'registered-category',delayPeriods:i.delayPeriods,afterActionIds:i.afterActionIds,bins:i.measurement?.bins.map(bin=>({category:bin.token,lowerInclusive:exactPresentation(bin.lowerInclusive),upperExclusive:exactPresentation(bin.upperExclusive)}))??[],qualification:'SUPPLIED_EXACT_INFORMATION_TOKENS_UNVERIFIED',exact:{tokens:i.tokens,measurement:i.measurement??null,numericProjection:'PRESENTATION_ONLY'}})),obligations,validUntil:m.validUntil,exactSource:{modelDigest:profile.modelDigest,sourceRef:profile.sourceRef,quantityEncoding:'NORMALIZED_RATIONAL_PAIRS',numericProjection:'PRESENTATION_ONLY'}};
 const nodeIds=Object.fromEntries(Object.entries(e.selectedActions).map(([sid,action])=>[sid,'policy-node:'+epistemicHash({source:profile.sourceRef,sid,action})]));
 const nodes:PolicyNode[]=Object.entries(e.selectedActions).map(([sid,actionId])=>{
  meter.step();
  const s=source.states.find(s=>s.id===sid)!,a=s.transitions.find(a=>a.actionId===actionId)!,value=e.family[sid]![e.selectedFamily[sid]!]!.worldValues;
  const lower=Object.values(value).map(Q.readDerived).reduce((a,b)=>a.compare(b)<0?a:b).wire(),n=exactPresentation(lower);
  return {id:nodeIds[sid]!,period:s.period,actionHistory:s.history,observations:s.observations,actionId,valueBounds:[n,n],branches:[...new Set(a.outcomes.map(o=>o.successor))].filter(child=>nodeIds[child]).map(child=>({observationKey:JSON.stringify(source.states.find(s=>s.id===child)!.observations),childId:nodeIds[child]!})),
   alternatives:s.transitions.map(t=>({actionId:t.actionId,status:e.family[sid]?.some(a=>a.actionId===t.actionId)?'POLICY_AVAILABLE':'INFEASIBLE',valueBounds:null,reasons:[e.optimalActions[sid]?.includes(t.actionId)?'ATTAINABLE_EXACT_GLOBAL_OPTIMAL_CHOICE':e.family[sid]?.some(a=>a.actionId===t.actionId)?'FEASIBLE_NOT_GLOBAL_OPTIMAL':'COMPLETE_ORIGINAL_CONTINUATION_INFEASIBLE']}))};
 });
 const parent=(node:PolicyNode)=>nodes.find(p=>p.branches.some(b=>b.childId===node.id))??null;
 const siblings=(node:PolicyNode)=>(parent(node)?.branches??[]).filter(b=>b.childId!==node.id).map(b=>b.childId);
 const exactVector=(v:Record<string,unknown>)=>Object.fromEntries(Object.entries(v).map(([id,q])=>[id,Q.read(q).wire()]));
 const demandBody={schema:'finnor.contingent-resource-demand.exact.v2' as const,semanticOwner:'S4' as const,mandateRef:m.ref,rightsRef:m.rightsRef,existingObligations:problem.obligations,dimensions:m.resources.dimensions,couplings:m.resources.couplings,
  branches:nodes.map(n=>{const a=actions.find(a=>a.id===n.actionId)!;return {nodeId:n.id,parentNodeId:parent(n)?.id??null,actionId:n.actionId,period:n.period,total:a.resources,occupancy:a.occupancy,occupationPeriods:a.occupationPeriods,mutuallyExclusiveSiblings:siblings(n)};}),reservationGranted:false as const,portfolioFeasibilityEstablished:false as const,
  exact:{modelDigest:profile.modelDigest,sourceRef:profile.sourceRef,quantityEncoding:'NORMALIZED_RATIONAL_PAIRS' as const,numericProjection:'PRESENTATION_ONLY' as const,units:source.units,discountFactors:source.economics.discountFactors.map(q=>Q.read(q).wire()),existingObligations:source.states.find(s=>s.id===e.root)!.semantics.obligations,
   branches:nodes.map(n=>{const a=source.actions.find(a=>a.id===n.actionId)!;return {nodeId:n.id,parentNodeId:parent(n)?.id??null,actionId:a.id,period:n.period,total:exactVector(a.resources),occupancy:exactVector(a.occupancy),occupationPeriods:a.occupationPeriods,cost:Q.read(a.cost).wire(),humanSeconds:Q.read(a.humanSeconds).wire(),terminalLiability:Q.read(a.tailLiability).wire(),exposures:Object.fromEntries(Object.entries(a.exposures).map(([id,v])=>[id,v.map(q=>Q.read(q).wire())])),mutuallyExclusiveSiblings:siblings(n)};})}};
 const value=exactPresentation(e.values[e.root]),body:Omit<ContingentPolicy,'ref'>={schema:'finnor.contingent-policy.exact.v2',semanticOwner:'S4',version:EXACT_S4_VERSION,tenantId:m.tenantId,principalId:m.principalId,episodeId:m.episodeId,knowledgeAt:now,validUntil:m.validUntil,mandateRef:m.ref,mandate:m,problem,priorPolicyRef:null,resultState:'POLICY_AVAILABLE',
  bindings:{modelRef:profile.sourceRef,dynamicsRef:profile.sourceRef,rightsRef:m.rightsRef,beliefPins:profile.beliefPins,protocolRefs:source.observationInstruments.map(i=>i.sourceRef),inputArtifactRef:profile.sourceRef,methodVersion:EXACT_S4_VERSION,obligationsDigest:epistemicHash(problem.obligations),allocationRefs:[]},
  rootNodeId:nodeIds[e.root]!,nodes,demand:{...demandBody,contentDigest:epistemicHash(demandBody)},exactProfile:profile,
  certificate:{basis:'MODEL_RELATIVE_EXACT_INFORMATION_TABLE',ambiguity:'FIXED_COMPLETE_SCENARIOS_NO_PROBABILITIES',valueBounds:[value,value],optimalBounds:[value,value],normalizedRegretBounds:[0,0],completeSearch:true,finiteScenarioGapOnly:true,distributionAndIdentificationGap:'UNKNOWN',numericalTolerance:0,feasibleIncumbentChecked:true,worlds:source.uncertainty.worlds.length,riskSemantics:m.risk},
  compute,limitations:['Supplied exact finite model; source completeness and causal adequacy remain unqualified.','Authoritative values and ties are in exactProfile; canonical rational demands are in demand.exact and bind the original bytes. Numeric fields are presentation only.','No effect, reservation, protected admission, settlement or economic release authority.'],admission:CONTROL_ADMISSION};
 const digest=epistemicHash(body);return immutableControl({...body,ref:{owner:'S4',id:'contingent-policy:'+digest,version:EXACT_S4_VERSION,contentDigest:digest}});
}
