/** Ordinary practice broker. S6 remains the sole consequential dispatch owner. */
import {randomUUID} from 'node:crypto';
import {launchIsolatedNodeExecutor} from '../../../governed-execution/src/executor';
import {fail,hash,canonical,parseOperation,readModule,type HttpModule,type GeneratedInterface,type Operation,type Attempt,type PracticeResult,type Observation} from './contracts';
export interface PracticePort {
 origin:string;account:string;expiresAt:string;disposable:true;
 authorize:()=>Promise<boolean>;
 record:(event:{stage:'INTENT'|'POSSIBLE_EGRESS'|'ACKNOWLEDGED'|'OBSERVATION'|'COMPLETED';attempt:Attempt;body?:unknown})=>Promise<void>;
}
export function permittedOrigin(port:PracticePort,operation:Operation){
 let url:URL;try{url=new URL(port.origin);}catch{fail('P5_DISPOSABLE_RUNTIME_REQUIRED');}
 if(process.env.NODE_ENV==='production'||port.disposable!==true||url.protocol!=='http:'||url.hostname!=='127.0.0.1'||url.origin!==port.origin||url.username||url.password||
  port.account!==operation.account||!Number.isFinite(Date.parse(port.expiresAt))||Date.parse(port.expiresAt)<=Date.now())fail('P5_DISPOSABLE_RUNTIME_REQUIRED');
 return url;
}
export async function requireAccess(port:PracticePort,operation:Operation){
 permittedOrigin(port,operation);if(!await port.authorize())fail('P5_CURRENT_PRACTICE_ACCESS_UNAVAILABLE');
}
export async function boundedFetch(url:URL,method:'GET'|'PATCH',body?:string,headers:Record<string,string>={}):Promise<unknown>{
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3000);
 let reader:ReadableStreamDefaultReader<Uint8Array>|undefined;
 try{
  const response=await fetch(url,{method,redirect:'error',credentials:'omit',cache:'no-store',signal:controller.signal,headers,body});
  if(!response.ok){await response.body?.cancel();fail('P5_TARGET_RESPONSE_UNAVAILABLE');}
  if(!response.body)fail('P5_TARGET_RESPONSE_MISSING');
  reader=response.body.getReader();let bytes=0;const chunks:Uint8Array[]=[];
  for(;;){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>65536)fail('P5_TARGET_RESPONSE_BOUND');chunks.push(chunk.value);}
  try{return JSON.parse(Buffer.concat(chunks).toString());}catch{fail('P5_TARGET_RESPONSE_JSON');}
 }finally{clearTimeout(timer);await reader?.cancel().catch(()=>{});reader?.releaseLock();}
}
// Audited fixed interpreter. The generated bytes are JSON IR, never JavaScript.
// The child receives no origin, token, database, evaluator assets or host imports.
const BIND_SCRIPT=`
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const frame=JSON.parse(readFileSync(0,'utf8'));
if(createHash('sha256').update(frame.module.bytes).digest('hex')!==frame.module.digest)throw Error('P5_MODULE_CHILD_DIGEST');
const ir=JSON.parse(frame.module.bytes),op=frame.operation;
if(ir.schema!=='finnor.p5.http-module.v1'||ir.imports.length!==0)throw Error('P5_MODULE_CHILD_CONTRACT');
const path=ir.path.replace('{'+ir.parameters.account+'}',encodeURIComponent(op.account)).replace('{'+ir.parameters.entity+'}',encodeURIComponent(op.entity));
let value=null;
if(op.value!==null){
 const negative=op.value.startsWith('-'),[whole,fraction='']=op.value.replace(/^-/,'').split('.');
 if(!/^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$/.test(op.value)||fraction.length>ir.decimalPlaces)throw Error('P5_DECIMAL_CHILD_DOMAIN');
 const minor=BigInt(whole)*10n**BigInt(ir.decimalPlaces)+BigInt(fraction.padEnd(ir.decimalPlaces,'0')||'0');
 if(minor>BigInt(Number.MAX_SAFE_INTEGER))throw Error('P5_DECIMAL_CHILD_RANGE');
 value=ir.encoding==='minor_integer'?Number(negative?-minor:minor):(negative&&minor!==0n?'-':'')+BigInt(whole).toString()+(ir.decimalPlaces?'.'+fraction.padEnd(ir.decimalPlaces,'0'):'');
}
const body=ir.kind==='ADAPTER'?JSON.stringify({[ir.valueField]:value}):null;
process.stdout.write(JSON.stringify({moduleDigest:frame.module.digest,path,method:ir.method,body,
 headers:ir.kind==='ADAPTER'?{'content-type':'application/json',[ir.revisionHeader]:op.priorRevision,[ir.operationHeader]:op.operationId}:{}}));
`;
export async function bindModule(generated:GeneratedInterface,operation:Operation,kind:'ADAPTER'|'OBSERVER'){
 const module=kind==='ADAPTER'?generated.adapterModule:generated.observerModule,ir=readModule(module);
 if(ir.schema!=='finnor.p5.http-module.v1'||ir.kind!==kind)fail('P5_MODULE_KIND');
 if(generated.bindingDigest!==hash(operation))fail('P5_BINDING_SUBSTITUTION');
 if(ir.meaning!==operation.meaning||ir.field!==operation.field||ir.unit!==operation.unit||ir.currency!==operation.currency)fail('P5_MODULE_SEMANTIC_SUBSTITUTION');
 const result=await launchIsolatedNodeExecutor({script:BIND_SCRIPT,input:{module,operation},wallTimeMs:3000});
 if(result.exitCode!==0||result.termination!=='EXITED')throw Object.assign(Error('P5_ISOLATED_MODULE_EXECUTION_FAILED'),{receipt:result.provenance,diagnosticDigest:hash(result.stderr)});
 const bound=JSON.parse(result.stdout) as {moduleDigest:string;path:string;method:'PATCH'|'GET';body:string|null;headers:Record<string,string>};
 const expectedPath=ir.path.replace('{'+ir.parameters.account+'}',encodeURIComponent(operation.account)).replace('{'+ir.parameters.entity+'}',encodeURIComponent(operation.entity));
 if(bound.moduleDigest!==module.digest||bound.path!==expectedPath||bound.method!==ir.method||bound.path.startsWith('//')||bound.path.includes('..'))fail('P5_MODULE_OUTPUT_SUBSTITUTION');
 if(kind==='ADAPTER'){
  const payload=JSON.parse(bound.body??'{}');
  if(Object.keys(payload).length!==1||!Object.hasOwn(payload,ir.valueField)||canonical(bound.headers)!==canonical({'content-type':'application/json','If-Match':operation.priorRevision,'X-Operation-Id':operation.operationId}))fail('P5_MODULE_REQUEST_SHAPE');
 }else if(bound.body!==null||Object.keys(bound.headers).length)fail('P5_OBSERVER_MUST_BE_READ_ONLY');
 return {bound,ir,receipt:result.provenance};
}
function exactValue(observed:unknown,operation:Operation,ir:HttpModule):boolean{
 if(operation.value===null)return observed===null&&ir.nullable;
 // Independent rational comparison, not the adapter's decimal-to-wire routine.
 if(!/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/.test(operation.value))return false;
 const sign=operation.value[0]==='-'?-1n:1n,[whole,fraction='']=operation.value.replace(/^-/,'').split('.');
 const requestedNumerator=sign*BigInt(whole+fraction),requestedDenominator=10n**BigInt(fraction.length);
 if(ir.encoding==='minor_integer'){
  return typeof observed==='number'&&Number.isSafeInteger(observed)&&BigInt(observed)*requestedDenominator===requestedNumerator*10n**BigInt(ir.decimalPlaces);
 }
 if(typeof observed!=='string'||!/^[-]?(?:0|[1-9]\d*)(?:\.\d+)?$/.test(observed))return false;
 const [integer,decimals='']=observed.replace(/^-/,'').split('.');
 if(decimals.length>ir.decimalPlaces)return false;
 const actual=(observed[0]==='-'?-1n:1n)*BigInt(integer+decimals);
 return actual*requestedDenominator===requestedNumerator*10n**BigInt(decimals.length);
}
export function originalAttempt(generated:GeneratedInterface,operation:Operation,prior?:Attempt):Attempt{
 if(generated.bindingDigest!==hash(operation))fail('P5_BINDING_SUBSTITUTION');
 for(const module of [generated.adapterModule,generated.observerModule])readModule(module);
 if(prior){
  if(prior.schema!=='finnor.p5.attempt.v1'||prior.operationId!==operation.operationId||prior.bindingDigest!==generated.bindingDigest||prior.sourceDigest!==generated.sourceDigest||prior.adapterDigest!==generated.adapterModule.digest||prior.observerDigest!==generated.observerModule.digest)fail('P5_RECOVERY_IDENTITY_CONFLICT');
  return structuredClone(prior);
 }
 return {schema:'finnor.p5.attempt.v1',id:randomUUID(),operationId:operation.operationId,bindingDigest:generated.bindingDigest,sourceDigest:generated.sourceDigest,adapterDigest:generated.adapterModule.digest,
  observerDigest:generated.observerModule.digest,possibleEgress:false,acknowledged:false,startedAt:new Date().toISOString()};
}
export async function observeHttp(generated:GeneratedInterface,operation:Operation,port:PracticePort,attempt:Attempt,receipts:unknown[]=[]):Promise<PracticeResult>{
 const begun=performance.now();
 const result:PracticeResult={status:'UNKNOWN',attempt,observation:null,historyDigest:null,reason:'P5_OBSERVATION_REQUIRED',admission:null,runtimeReceipts:receipts,cost:{usd:null,status:'LOCAL_COST_UNMETERED',wallMs:0}};
 try{
  await requireAccess(port,operation);
  const {bound,ir,receipt}=await bindModule(generated,operation,'OBSERVER');receipts.push(receipt);
  await port.record({stage:'OBSERVATION',attempt,body:{moduleDigest:generated.observerModule.digest}});
  const raw=await boundedFetch(new URL(bound.path,port.origin),'GET');
  if(!raw||typeof raw!=='object'||Array.isArray(raw))fail('P5_OBSERVER_TRUNCATED');
  const data=raw as Record<string,unknown>,fields=ir.readFields;
  const keys=Object.values(fields),exact=Object.keys(data).length===keys.length&&keys.every(key=>Object.hasOwn(data,key));
  const account=data[fields.account],entity=data[fields.entity],unit=data[fields.unit],currency=data[fields.currency],
   revision=data[fields.revision],operationId=data[fields.operationId];
  if(!exact||typeof account!=='string'||typeof entity!=='string'||typeof unit!=='string'||typeof currency!=='string'||
   typeof revision!=='string'||operationId!==null&&typeof operationId!=='string'){
   result.status='DISCREPANCY';result.reason='P5_OBSERVER_IDENTITY_CODEC_MISMATCH';return result;
  }
  const observation:Observation={account,entity,field:operation.field,unit,currency,value:data[fields.value],revision,
   operationId,observedAt:new Date().toISOString(),rawDigest:hash(raw)};
  result.observation=observation;
  if(!exact||observation.account!==operation.account||observation.entity!==operation.entity||observation.unit!==operation.unit||observation.currency!==operation.currency||
   observation.operationId!==operation.operationId||!/^"[^"\\\r\n]{1,120}"$/.test(observation.revision)||observation.revision===operation.priorRevision||!exactValue(data[fields.value],operation,ir)){
   result.status='DISCREPANCY';result.reason='P5_EXACT_REQUEST_OBSERVATION_MISMATCH';return result;
  }
  if(!ir.history){result.reason='P5_INDEPENDENT_EFFECT_HISTORY_UNAVAILABLE';return result;}
  await requireAccess(port,operation);
  const historyPath=ir.history.path.replace('{'+ir.history.accountParameter+'}',encodeURIComponent(operation.account)).replace('{'+ir.history.operationParameter+'}',encodeURIComponent(operation.operationId));
  if(historyPath.startsWith('//')||historyPath.includes('..'))fail('P5_HISTORY_PATH_UNPERMITTED');
  await port.record({stage:'OBSERVATION',attempt,body:{kind:'INDEPENDENT_EFFECT_HISTORY',pathDigest:hash(historyPath)}});
  const rawHistory=await boundedFetch(new URL(historyPath,port.origin),'GET') as Record<string,any>;result.historyDigest=hash(rawHistory);
  if(!rawHistory||rawHistory.account!==operation.account||rawHistory.operationId!==operation.operationId||!Array.isArray(rawHistory.writes)||rawHistory.writes.length!==1){
   result.status='DISCREPANCY';result.reason='P5_WRONG_OR_MULTIPLE_PHYSICAL_EFFECTS';return result;
  }
  const write=rawHistory.writes[0];
  if(write.account!==operation.account||write.entity!==operation.entity||write.field!==operation.field||write.unit!==operation.unit||write.currency!==operation.currency||write.operationId!==operation.operationId||
   write.revision!==observation.revision||!exactValue(write.value,operation,ir)||!Number.isFinite(Date.parse(write.at))||Date.parse(write.at)<Date.parse(attempt.startedAt)||Date.parse(write.at)>Date.parse(observation.observedAt)){
   result.status='DISCREPANCY';result.reason='P5_EFFECT_ASSOCIATION_OR_TARGET_MISMATCH';return result;
  }
  await requireAccess(port,operation);result.status='VERIFIED';result.reason=null;return result;
 }catch{result.reason='P5_OBSERVATION_UNAVAILABLE_RETAIN_RESPONSIBILITY';return result;}
 finally{result.cost.wallMs=performance.now()-begun;}
}
export async function practiceHttp(generated:GeneratedInterface,requested:unknown,port:PracticePort,prior?:Attempt):Promise<PracticeResult>{
 const operation=parseOperation(requested),attempt=originalAttempt(generated,operation,prior);
 // Validate bytes/runtime/target before acquiring any possible-egress responsibility.
 readModule(generated.adapterModule);readModule(generated.observerModule);permittedOrigin(port,operation);
 const receipts:unknown[]=[];
 if(!attempt.possibleEgress){
  await requireAccess(port,operation);const {bound,receipt}=await bindModule(generated,operation,'ADAPTER');receipts.push(receipt);
  await port.record({stage:'INTENT',attempt,body:{moduleDigest:generated.adapterModule.digest}});
  await requireAccess(port,operation);
  attempt.possibleEgress=true;
  await port.record({stage:'POSSIBLE_EGRESS',attempt,body:{requestDigest:hash(bound),runtimeReceiptDigest:hash(receipt)}});
  try{
   await boundedFetch(new URL(bound.path,port.origin),'PATCH',bound.body??undefined,bound.headers);attempt.acknowledged=true;
   await port.record({stage:'ACKNOWLEDGED',attempt,body:{acknowledgementIsVerification:false}});
  }catch{/* Response loss is not non-submission. No mutation retry. */}
 }
 const result=await observeHttp(generated,operation,port,attempt,receipts);
 await port.record({stage:'COMPLETED',attempt,body:result});
 return result;
}
