/** Disposable local bearer verification service + generic actual API route host.
 * No business API, authorizer, queue, or financial result is mocked here.
 * This is a named LOCAL_AUTH_SERVICE profile, not hosted Supabase qualification.
 */
import {createServer} from 'node:http';
import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {readdir,mkdir,writeFile,appendFile} from 'node:fs/promises';
import {join,relative} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createDeal,restateMetricObservation} from '@finnor/private-equity';
import {createEmployeeConversationThread} from '@finnor/db';
export async function browserFixture(e:any){
 const {f,queue,repo,admin,evidence}=e,tenant=f.f.tenant,actor=f.f.principal,ctx=f.f.ctx;
 const delayedOperation=e.delayedOperation??'compute-search-projection';
 const companies={A:f.f.root.entityId},observations={'A.debt':f.f.p2Observations.debt.row.id};
 const observation=f.f.p2Observations.debt.row;const sourceRef={evidenceSourceId:String(observation.evidenceSourceId),evidenceVersionId:String(observation.evidenceVersionId)};
 const output=join(evidence,'browser');await mkdir(output,{recursive:true});
 const identity=(await admin.query('SELECT email,status FROM finnor_os.users WHERE tenant_id=$1 AND id=$2',[tenant,actor])).rows[0];
 if(!identity||identity.status!=='active'||typeof identity.email!=='string')throw Error('CANONICAL_FIXTURE_IDENTITY_UNAVAILABLE');
 const secret=randomBytes(32),email=identity.email,password='p2-disposable-only';
 const user={id:actor,aud:'authenticated',role:'authenticated',email,email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:new Date().toISOString()};
 function issue(){const encode=(o:unknown)=>Buffer.from(JSON.stringify(o)).toString('base64url');const now=Math.floor(Date.now()/1000),body=encode({alg:'HS256',typ:'JWT'})+'.'+encode({sub:actor,email,aud:'authenticated',role:'authenticated',iat:now,exp:now+3600,iss:'http://127.0.0.1:4692/auth/v1'});return body+'.'+createHmac('sha256',secret).update(body).digest('base64url');}
 function verify(token:string){try{const [h,p,s]=token.split('.');if(!h||!p||!s)return false;const signature=createHmac('sha256',secret).update(h+'.'+p).digest();const actual=Buffer.from(s,'base64url');const claims=JSON.parse(Buffer.from(p,'base64url').toString());return actual.length===signature.length&&timingSafeEqual(signature,actual)&&claims.sub===actor&&claims.exp>Date.now()/1000;}catch{return false;}}
 const auth=createServer(async(req,res)=>{res.setHeader('access-control-allow-origin','http://127.0.0.1:4690');res.setHeader('access-control-allow-headers','authorization,apikey,content-type,x-client-info,x-supabase-api-version');res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('content-type','application/json');if(req.method==='OPTIONS'){res.end();return;}let text='';for await(const b of req){text+=b;if(text.length>16384){res.writeHead(413);res.end('{}');return;}}let body:any;try{body=JSON.parse(text||'{}');}catch{res.writeHead(400);res.end('{}');return;}
  if(req.url?.startsWith('/auth/v1/token')){if(body.email===email&&body.password===password){res.end(JSON.stringify({access_token:issue(),token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,refresh_token:'disposable-refresh',user}));}else{res.writeHead(400);res.end(JSON.stringify({error:'invalid_credentials',msg:'Invalid local fixture credentials'}));}return;}
  if(req.url==='/auth/v1/user'){if(!verify(String(req.headers.authorization??'').replace(/^Bearer /,''))){res.writeHead(401);res.end(JSON.stringify({msg:'Invalid JWT'}));return;}res.end(JSON.stringify(user));return;}
  if(req.url?.includes('logout')){res.end('{}');return;}res.writeHead(404);res.end('{}');
 });await new Promise<void>(yes=>auth.listen(4692,'127.0.0.1',yes));
 process.env.AUTH_DEV_BYPASS='0';process.env.SUPABASE_URL='http://127.0.0.1:4692';process.env.SUPABASE_SERVICE_ROLE_KEY='disposable-local-auth-key';process.env.RATE_LIMIT_PER_MINUTE='10000';process.env.RATE_LIMIT_IP_PER_MINUTE='10000';
 const {thread,otherThread,canvasRoot}=f.f.browser;
 const checks:any[]=[];
 const {readEnterpriseContingentPolicy}=await import('../../packages/private-equity/src/enterprise-control');
 const {validateBeliefViewPin,loadEnterpriseBeliefView}=await import('../../packages/private-equity/src/enterprise-beliefs');
 await f.artifact('browser-after-P1-view.json',await loadEnterpriseBeliefView(ctx,{root:f.f.root,validAt:f.policy.bindings.beliefPins[0].validAt}));
 for(const [name,identityCtx] of [['fixture',ctx],['bearer',{auth:await (await import('@finnor/security')).resolveTenantFromBearerToken(issue())}]] as const){
  try{const policy=await readEnterpriseContingentPolicy(identityCtx,f.policy.ref);checks.push({name,status:'CURRENT',policyRef:policy.ref});}
  catch(error){checks.push({name,status:'REFUSED',error:String(error),code:(error as any).code,pins:await Promise.all(f.policy.bindings.beliefPins.map(async(pin:any)=>({pin,validation:await validateBeliefViewPin(identityCtx,pin)})))});}
 }
 await writeFile(join(output,'owner-currentness-before-ui.json'),JSON.stringify(checks,null,2));
 const apiRoot=join(repo,'finnor-os/apps/api/app/api');const routes:Array<{file:string;parts:string[];dynamic:number}>=[];
 async function scan(directory:string){for(const item of await readdir(directory,{withFileTypes:true})){const path=join(directory,item.name);if(item.isDirectory())await scan(path);else if(item.name==='route.ts'){const parts=relative(apiRoot,directory).split('/');routes.push({file:path,parts,dynamic:parts.filter(p=>p.startsWith('[')).length});}}}await scan(apiRoot);routes.sort((a,b)=>a.dynamic-b.dynamic);
 const programRoot=f.f.root,other={threadId:otherThread.id,url:`http://127.0.0.1:4690/centropy/investigations/${otherThread.id}?root=${encodeURIComponent(JSON.stringify(canvasRoot))}`};
 let delayed:{workId:string;waiting:boolean;promise:Promise<void>;release:()=>void}|null=null;
 const traffic:any[]=[];
 let sampleInFlight:Promise<unknown>|null=null,observationCount=0;
 const observer=setInterval(()=>{if(sampleInFlight||observationCount>=600)return;observationCount++;sampleInFlight=(async()=>{
  const rows=(await admin.query("SELECT pid,state,wait_event_type,wait_event,extract(epoch FROM clock_timestamp()-query_start)::float8 elapsed_seconds,left(query,256) query FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid() AND state<>'idle' ORDER BY pid")).rows;
  await appendFile(join(output,'database-and-runtime-observer.jsonl'),JSON.stringify({at:new Date().toISOString(),rows,memory:process.memoryUsage(),cpuMicros:process.cpuUsage(),qualification:'ACTUAL_LOCAL_SAMPLES_NOT_AGGREGATE_OS_ENFORCEMENT_OR_BILLING'})+'\n');
 })().catch(error=>traffic.push({observerError:String(error)})).finally(()=>{sampleInFlight=null;});},1000);
 const api=createServer(async(req,res)=>{const started=Date.now();try{const url=new URL(req.url??'/','http://127.0.0.1:4691');const parts=url.pathname.replace(/^\/api\//,'').split('/').map(decodeURIComponent);let matched:any;for(const route of routes){const params:Record<string,unknown>={};let ok=true,j=0;for(const segment of route.parts){if(segment.startsWith('[...')){params[segment.slice(4,-1)]=parts.slice(j);j=parts.length;break;}if(j>=parts.length){ok=false;break;}if(segment.startsWith('['))params[segment.slice(1,-1)]=parts[j];else if(segment!==parts[j]){ok=false;break;}j++;}if(ok&&j===parts.length){matched={...route,params};break;}}if(!matched){res.writeHead(404);res.end('{}');return;}
   let body='';for await(const b of req){body+=b;if(body.length>8388608)throw Error('BODY_BOUND');}const module=await import(pathToFileURL(matched.file).href),handler=module[req.method??'GET'];if(!handler){res.writeHead(405);res.end('{}');return;}const headers=new Headers();for(const [key,value] of Object.entries(req.headers))if(typeof value==='string')headers.set(key,value);const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method??'GET')?{body}: {})});const response:Response=await handler(request,{params:Promise.resolve(matched.params)});if(delayed&&url.pathname==='/api/company-brain/'+delayedOperation&&JSON.parse(body).workId===delayed.workId&&!delayed.waiting){delayed.waiting=true;await delayed.promise;}res.writeHead(response.status,(()=>{const out:Record<string,string>={};response.headers.forEach((value,key)=>{out[key]=value;});return out;})());res.end(Buffer.from(await response.arrayBuffer()));traffic.push({path:url.pathname,method:req.method,status:response.status,ms:Date.now()-started,bearer:Boolean(req.headers.authorization),at:new Date().toISOString()});
  }catch(error){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({error:'Local route host failed'}));traffic.push({path:req.url,status:500,diagnostic:String(error),at:new Date().toISOString()});}await writeFile(join(output,'traffic.json'),JSON.stringify(traffic,null,2));
 });await new Promise<void>(yes=>api.listen(4691,'127.0.0.1',yes));
 let stopped=false;let stopFixture!:()=>void;const stoppedPromise=new Promise<void>(yes=>{stopFixture=()=>{stopped=true;yes();};});
 const control=createServer(async(req,res)=>{try{if(req.method==='POST'&&req.url==='/delay-read'){let body='';for await(const bytes of req)body+=bytes;const parsed=JSON.parse(body);let release!:()=>void;const promise=new Promise<void>(yes=>{release=yes;});delayed={workId:parsed.workId,waiting:false,promise,release};res.end('{}');return;}if(req.url==='/delay-status'){res.end(JSON.stringify({waiting:delayed?.waiting??false,workId:delayed?.workId??null}));return;}if(req.method==='POST'&&req.url==='/release-read'){delayed?.release();delayed=null;res.end('{}');return;}if(req.method==='POST'&&req.url==='/stop'){delayed?.release();res.end('{}');stopFixture();return;}if(req.method==='POST'&&req.url==='/correct'){const correction=await restateMetricObservation(ctx,{priorObservationId:observations['A.debt'],expectedVersion:1,replacement:{value:{type:'number',value:'80'},evidence:sourceRef}});res.end(JSON.stringify({correction,expected:{netEquity:'33',leverage:'4'}}));return;}if(req.method==='POST'&&req.url==='/revoke'){await admin.query("UPDATE finnor_os.users SET status='suspended' WHERE tenant_id=$1 AND id=$2",[tenant,actor]);res.end('{}');return;}if(req.url==='/observation'){const oracle=(await admin.query('SELECT 120::numeric-70::numeric-7::numeric equity,70::numeric/20::numeric leverage')).rows[0],plans=(await admin.query('SELECT s.id,s.status,s.head_id,s.revision,p.work_id,p.work_input_id FROM finnor_os.p2_requests s JOIN finnor_os.p1_requests p ON p.id=s.program_id WHERE s.program_id=$1',[f.p.programId])).rows;res.end(JSON.stringify({oracle,plans}));return;}if(req.url==='/health'){res.end('ready');return;}res.writeHead(404);res.end('{}');}catch(error){res.writeHead(500);res.end(String(error));}});await new Promise<void>(yes=>control.listen(4693,'127.0.0.1',yes));
 const data={profile:'DISPOSABLE_LOCAL_AUTH_SERVICE_ACTUAL_BEARER_RLS_AND_OWNER_GRANT',hostedSupabaseQualified:false,email,password,tenant,actor,companyRoot:programRoot,canvasRoot,threadId:thread.id,workId:f.p.workId,programId:f.p.programId,url:`http://127.0.0.1:4690/centropy/investigations/${thread.id}?root=${encodeURIComponent(JSON.stringify(canvasRoot))}`,expected:{netEquity:'43',leverage:'3.5'},other};await writeFile(join(output,'fixture.json'),JSON.stringify(data,null,2));await writeFile(join(output,'frontend-env.json'),JSON.stringify({NEXT_PUBLIC_OS_API_URL:'http://127.0.0.1:4691',NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:4692',NEXT_PUBLIC_SUPABASE_ANON_KEY:'disposable-local-auth-key'},null,2));console.log(JSON.stringify({browserFixture:'READY',fixture:join(output,'fixture.json'),url:data.url}));
 let tickWork:Promise<unknown>|null=null;const tick=async()=>{if(stopped)return;tickWork=queue.tick().catch((error:unknown)=>traffic.push({workerError:String(error)}));await tickWork;tickWork=null;if(!stopped)setTimeout(tick,200);};void tick();
 const onSignal=()=>{delayed?.release();stopFixture();};process.once('SIGINT',onSignal);process.once('SIGTERM',onSignal);await stoppedPromise;if(tickWork)await tickWork;process.off('SIGINT',onSignal);process.off('SIGTERM',onSignal);
 clearInterval(observer);if(sampleInFlight)await sampleInFlight;
 await writeFile(join(output,'terminal-database-observer.json'),JSON.stringify({observedAt:new Date().toISOString(),program:(await admin.query('SELECT q.id,q.status,q.failure,q.generation,e.attempts_used,e.steps_used,e.deadline_at FROM finnor_os.p1_requests q JOIN finnor_os.p1_episodes e ON e.id=q.episode_id WHERE q.id=$1',[f.p.programId])).rows,searches:(await admin.query('SELECT id,status,reason,generation,revision FROM finnor_os.p2_requests WHERE program_id=$1',[f.p.programId])).rows,jobs:(await admin.query("SELECT id,type,status,attempts,last_error,run_at FROM finnor_os.jobs WHERE payload->>'programId'=$1 OR payload->>'workId'=$2 OR payload->>'searchId' IN(SELECT id::text FROM finnor_os.p2_requests WHERE program_id=$1::uuid)",[f.p.programId,f.p.workId])).rows},null,2));
 await Promise.all([new Promise<void>(yes=>auth.close(()=>yes())),new Promise<void>(yes=>api.close(()=>yes())),new Promise<void>(yes=>control.close(()=>yes()))]);
}
