/** P1 real-boundary cases; failure predicates are registered before repairs. No reconstructed API,
 * queue, authorizer or expected-answer generator. See preregistered-protocol. */
import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';
import {strict as assert} from 'node:assert';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,appendFile,readFile,rm,readdir,realpath} from 'node:fs/promises';
import {appendFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {createServer} from 'node:net';
import {performance} from 'node:perf_hooks';
import {spawn,spawnSync} from 'node:child_process';
import {migrate} from '../../packages/db/migrate';
import {closePool,configureTenantVertical,withTenantTransaction} from '@finnor/db';
import {createEvidenceSource,appendEvidenceVersion} from '@finnor/memory';
import {createMetricSeries,recordMetricObservation,restateMetricObservation,type PeMutationContext} from '@finnor/private-equity';

const repo=resolve(import.meta.dirname,'../../..');
const evidence=resolve(process.env.FINNOR_M2_EVIDENCE_DIR??join(repo,'scope-pm/phase-08-m2-deliberation-controller/scope-evidence',`run-${new Date().toISOString().replace(/[:.]/g,'-')}`));
await mkdir(evidence,{recursive:true});
const productionIdentity=await (await import('../../packages/private-equity/src/evidence-execution/store')).currentCodeIdentity();
const testPaths=(await readdir(import.meta.dirname)).filter(p=>/\.(mts|mjs|py|json)$/.test(p)).sort();
const tests=await Promise.all(testPaths.map(async path=>({path:'finnor-os/scripts/m2/'+path,sha256:createHash('sha256').update(await readFile(join(import.meta.dirname,path))).digest('hex')})));
const installedPackages=await Promise.all(['next','tsx','pg','embedded-postgres','typescript','playwright'].map(async name=>{try{const file=join(repo,'finnor-os/node_modules',name,'package.json'),bytes=await readFile(file);return {name,version:JSON.parse(bytes.toString()).version,packageJsonSha256:createHash('sha256').update(bytes).digest('hex'),resolvedPath:await realpath(file)};}catch{return {name,status:'UNAVAILABLE_IN_BACKEND_RESOLUTION'};}}));
await writeFile(join(evidence,'pre-run-freeze.json'),JSON.stringify({schema:'finnor.m2.run-freeze.v1',frozenAt:new Date().toISOString(),command:'node --import=tsx scripts/m2/run-e2e.mts',cwd:process.cwd(),environmentNames:Object.keys(process.env).filter(k=>/^(FINNOR_P1_|FINNOR_P4_|AUTH_DEV_BYPASS|DATABASE_URL|NODE_ENV)/.test(k)).sort(),productionIdentity,tests,installedPackages,node:{version:process.version,executable:await realpath(process.execPath),sha256:createHash('sha256').update(await readFile(process.execPath)).digest('hex')},imageAttestation:null,oracle:'Predeclared public A/B/C constants and separate SQL numeric source path; no independent sealed split',inputCorpus:'fixture/constants below; generated byte fixtures retained with actual source SHA witnesses',qualification:'Installed package manifest identities and real linked paths, not a clean-install or transitive dependency byte attestation'},null,2)+'\n');
const results:any[]=[]; const startedAt=new Date().toISOString();
const start=performance.now();
const tenant=randomUUID(),actor=randomUUID(),foreignTenant=randomUUID(),foreignActor=randomUUID();
const companies={A:'11111111-1111-4111-8111-111111111111',B:randomUUID(),C:randomUUID(),foreign:randomUUID()};
const ctx:PeMutationContext={auth:{tenantId:tenant,userId:actor,employeeId:actor,role:'owner'},provenance:{sourceSystem:'p4:e2e',createdBy:actor}};
const periodStart='2025-01-01T00:00:00.000Z',periodEnd='2025-12-31T00:00:00.000Z',validAt='2026-01-01T00:00:00.000Z';
const root=(name:keyof typeof companies)=>({entityType:'external_organization',entityId:companies[name]});
const series:Record<string,string>={},observations:Record<string,string>={};
const fixture={A:{EV:'120',EBITDA:'20',debt:'70'},B:{EV:'100',EBITDA:'25',debt:'50'},C:{EV:'90',EBITDA:'15',debt:'45'}};
const expected={A:{equity:'50',leverage:'3.5'},B:{equity:'50',leverage:'2'},C:{equity:'45',leverage:'3'}};
let postgres!:EmbeddedPostgres,admin!:pg.Client,post:any,queue:any,handler:any,migrationCount=0;
const directory=await mkdtemp(join(tmpdir(),'finnor-p1-'));
const save=async()=>writeFile(join(evidence,'results.json'),JSON.stringify({schema:'finnor.m2.e2e.v1',startedAt,generatedAt:new Date().toISOString(),durationMs:performance.now()-start,
 status:results.some(x=>x.status==='FAIL')?'FAIL':results.some(x=>x.status==='PASS')?'PASS_LOCAL':'NOT_EXECUTED',runtime:process.version,migrationCount,profile:'disposable actual PostgreSQL ordinary finnor_app / existing nonproduction auth bypass / actual Company Brain POST / actual JobQueue',
 independentAdmission:false,billingUSD:null,costStatus:'LOCAL_COST_UNMETERED',fixture,expected,results,rerun:'cd finnor-os && node --import=tsx scripts/m2/run-e2e.mts'},null,2)+'\n');
async function test(id:string,input:unknown,predicate:string,fn:()=>Promise<unknown>){if(process.env.FINNOR_M2_CASE_FILTER&&!process.env.FINNOR_M2_CASE_FILTER.split(',').some(filter=>id.includes(filter))){results.push({id,status:'NOT_RUN',predicate,input});await save();return;}const t=performance.now();try{results.push({id,input,predicate,status:'PASS',observed:await fn(),durationMs:performance.now()-t});}catch(e){results.push({id,input,predicate,status:'FAIL',observed:{message:String((e as Error).message),cause:(e as any).cause?{message:(e as any).cause.message,code:(e as any).cause.code,constraint:(e as any).cause.constraint}:null,stack:(e as Error).stack},durationMs:performance.now()-t});}await save();}
async function api(operation:string,body:unknown,identity={tenant,actor}){const response=await post(new Request('http://localhost/api/company-brain/'+operation,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':identity.tenant,'x-user-id':identity.actor},body:JSON.stringify(body)}),{params:Promise.resolve({operation})});return {status:response.status,body:await response.json()};}
const descriptor=(name:keyof typeof companies,metricKey:string,overrides:any={})=>({kind:'metric',subject:root(name),metricKey,periodStart,periodEnd,unit:'currency',currencyCode:'USD',frequency:'annual',calendar:'OWNER_RECORDED',consolidation:'OWNER_SUBJECT_ONLY',instrument:'UNSPECIFIED',scale:'1',sign:'AS_RECORDED',...overrides});
const program={schema:'finnor.derivation-ir.v1',nodes:[{id:'evrows',op:'source',inputId:'EV'},{id:'ev',op:'unique',input:'evrows'},{id:'drows',op:'source',inputId:'debt'},{id:'debt',op:'unique',input:'drows'},{id:'erows',op:'source',inputId:'EBITDA'},{id:'ebitda',op:'unique',input:'erows'},{id:'equity',op:'subtract',left:'ev',right:'debt'},{id:'leverage',op:'ratio',left:'debt',right:'ebitda',decimalPlaces:18}],outputs:['equity','leverage']};
async function handles(name:keyof typeof companies,descriptors:any[]=['EV','debt','EBITDA'].map(m=>({inputId:m,source:descriptor(name,m)}))){const h=await api('evidence-handles',{root:root(name),validAt,inputs:descriptors});assert.equal(h.status,200,JSON.stringify(h.body));return h.body.handles;}
async function submit(name:keyof typeof companies,options:any={}){const hs=options.handles??await handles(name);const request={schema:'finnor.evidence-request.v1',question:'Calculate equity as EV minus debt and leverage as debt divided by EBITDA for the exact registered annual subject.',root:root(name),validAt,idempotencyKey:randomUUID(),mode:'ordinary_disposable',inputs:hs.map((h:any)=>({inputId:h.inputId,handleId:h.id})),program,acceptance:{selectedUniverse:'COMPLETE',absoluteTolerance:'0',materialOutputs:['equity','leverage']},...options};delete request.handles;const response=await api('evidence-submit',request);assert.equal(response.status,202,JSON.stringify(response.body));return response.body;}
async function finish(submitted:any){for(let i=0;i<12;i++){await queue.tick();const r=await api('evidence-read',{queryId:submitted.queryId});assert.equal(r.status,200,JSON.stringify(r.body));if(['TESTED','FAILED','INVALIDATED','CANCELLED','PARTIAL'].includes(r.body.status)){const events=(await admin.query('SELECT kind,body FROM finnor_os.p4_attempt_events WHERE query_id=$1 ORDER BY created_at',[submitted.queryId])).rows;await writeFile(join(evidence,'trace-'+submitted.queryId+'.json'),JSON.stringify(events,null,2));return r.body;}await new Promise(r=>setTimeout(r,25));}throw new Error('Real queue did not complete bounded query');}
const value=(result:any,key:string)=>result.derivation?.result?.outputs?.[key]?.value;
try{
 process.env.FINNOR_TEST_MANAGED_EXTENSIONS='omit'; process.env.AUTH_DEV_BYPASS='1';process.env.NODE_ENV='test'; process.env.FINNOR_P4_PROFILE='ordinary_disposable';
 const port=await new Promise<number>((yes,no)=>{const s=createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const a=s.address();if(!a||typeof a==='string')return no(Error('port'));s.close(()=>yes(a.port));});});
 let databaseLogBytes=0;
 postgres=new EmbeddedPostgres({databaseDir:directory,user:'finnor',password:'finnor',port,persistent:false,onLog:(message:string)=>{const bounded=String(message).slice(0,65536);databaseLogBytes+=Buffer.byteLength(bounded);if(databaseLogBytes<=4194304)appendFileSync(join(evidence,'actual-postgres.log'),bounded+'\n');}});
 await postgres.initialise();await appendFile(join(directory,'postgresql.conf'),'\ntrack_commit_timestamp='+(process.env.FINNOR_P4_TRACK_COMMITS==='off'?'off':'on')+'\n');await postgres.start();await postgres.createDatabase('p4_e2e');
 const adminUrl=`postgres://finnor:finnor@127.0.0.1:${port}/p4_e2e`;migrationCount=(await migrate(adminUrl)).length;
 admin=new pg.Client({connectionString:adminUrl});await admin.connect();await admin.query("INSERT INTO finnor_os.compute_resource_policies(resource_key,capacity,per_tenant_capacity,interactive_reserve,lease_seconds,source) VALUES('native:p4',2,2,0,60,'explicit disposable P4 fixture; unmetered engineering capacity, not protected funding')");await admin.query("INSERT INTO finnor_os.compute_resource_policies(resource_key,capacity,per_tenant_capacity,interactive_reserve,lease_seconds,source) VALUES('native:p2',2,2,0,60,'predeclared local P2 fixture capacity; not S5 funding'),('model:global',2,2,0,120,'local fixture model capacity'),('model-provider:LOCAL_HTTP_FIXTURE',2,2,0,120,'loopback observer capacity; endpoint cap1 is independently contested') ON CONFLICT(resource_key) DO NOTHING");await admin.query("ALTER ROLE finnor_app LOGIN PASSWORD 'finnor_app'");await admin.query("SET app.test_vertical_mode='explicit'");
 await admin.query("INSERT INTO finnor_os.tenants(id,client_key,name) VALUES($1,$2,'P4 ordinary'),($3,$4,'P4 foreign')",[tenant,randomUUID(),foreignTenant,randomUUID()]);
 await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status,display_name) VALUES($1,$2,$3,'owner','active','P4 ordinary'),($4,$5,$6,'owner','active','P4 foreign')",[actor,tenant,`${actor}@test.invalid`,foreignActor,foreignTenant,`${foreignActor}@test.invalid`]);
 process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/p4_e2e`;await closePool();
 await configureTenantVertical({tenantId:tenant,verticalKey:'private_equity',expectedVersion:0,createdBy:actor,sourceSystem:'p4:e2e'});await configureTenantVertical({tenantId:foreignTenant,verticalKey:'private_equity',expectedVersion:0,createdBy:foreignActor,sourceSystem:'p4:e2e'});
 const executionProfile=await (await import('../../packages/orchestration/src/workforce-runtime')).configureAgentProfile(tenant,(await import('../../packages/orchestration/src/plugin-registry')).createDefaultPluginRegistry(),{key:'p1-disposable-native',name:'Explicit disposable P1 query/check executor',actor:ctx.auth as any,capabilityGrants:[{kind:'query',capability:'query:harness_program_v1'},{kind:'check',capability:'check:objective_success'},{kind:'wait',capability:'wait:event'}],autonomyLimits:{maxActions:1,maxQueries:8,maxReplans:6,maxPlannerCalls:8,maxWallClockMs:3600000},planningHints:{qualification:'DISPOSABLE_ORDINARY_UNMETERED_NO_PROTECTED_ADMISSION'}});
 await writeFile(join(evidence,'native-execution-profile.json'),JSON.stringify(executionProfile,null,2));
 for(const name of ['A','B','C'] as const)await admin.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,$3,$4,'other')",[companies[name],tenant,'p4-'+name.toLowerCase(),'P4 '+name]);
 await admin.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,'p4-foreign','P4 FOREIGN SECRET','other')",[companies.foreign,foreignTenant]);
 const evidenceSource=await createEvidenceSource(tenant,{sourceKey:'p4-original',sourceType:'manual',title:'Predeclared source fixture'});
 const evidenceVersion=await appendEvidenceVersion(tenant,evidenceSource.id,{content:'A EV120 EBITDA20 debt70; B EV100 EBITDA25 debt50; C EV90 EBITDA15 debt45',snapshot:fixture,asOf:new Date(periodStart)});
 const sourceRef={evidenceSourceId:evidenceSource.id,evidenceVersionId:evidenceVersion.versionId};
 for(const [name,metrics] of Object.entries(fixture))for(const [metric,val] of Object.entries(metrics)){const key=name+'.'+metric;series[key]=String((await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:companies[name as 'A'],metricKey:metric,name:metric,unit:'currency',currencyCode:'USD',frequency:'annual'})).row.id);observations[key]=String((await recordMetricObservation(ctx,{metricSeriesId:series[key],periodStart:new Date(periodStart),periodEnd:new Date(periodEnd),value:{type:'number',value:val},evidence:sourceRef})).row.id);}
 post=(await import('../../apps/api/app/api/company-brain/[operation]/route')).POST;

 const source=(key:string)=>({key,source:descriptor('A',key)});
 const ref=(key:string)=>({kind:'input',key});
 const sub=(left:any,right:any)=>({kind:'subtract',left,right});
 const request=()=>({schema:'finnor.harness-request.v1',instruction:'Produce a source-cited analytical draft of equity after debt and all recorded liabilities, with leverage. No IC approval or external effect is requested.',root:root('A'),validAt,mode:'ordinary_disposable',idempotencyKey:randomUUID(),sources:['EV','debt','EBITDA','liability'].map(source),acceptance:{requiredSourceKeys:['EV','debt','EBITDA','liability'],targets:[{key:'netEquity',expression:sub(sub(ref('EV'),ref('debt')),ref('liability')),unit:'currency',currencyCode:'USD'},{key:'leverage',expression:{kind:'ratio',left:ref('debt'),right:ref('EBITDA')},unit:'multiple',currencyCode:null}],deliverable:{kind:'analytical_draft',title:'Liability complete analytical draft'}}});
 const liabilities=String((await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:companies.A,metricKey:'liability',name:'Material liability',unit:'currency',currencyCode:'USD',frequency:'annual'})).row.id);
 await recordMetricObservation(ctx,{metricSeriesId:liabilities,periodStart:new Date(periodStart),periodEnd:new Date(periodEnd),value:{type:'number',value:'7'},evidence:sourceRef});
 const {JobQueue}=await import('../../apps/worker/src/queue'); queue=new JobQueue('p1-e2e-worker',3);
 // Observe the actual durable queue after its unmodified tick. Failed physical
 // deliveries must survive teardown even when a story fails before its own
 // post-assertion artifact. This changes no dispatch or acceptance behaviour.
 const queueTick=queue.tick.bind(queue);let queueDiagnosticBytes=0;
 queue.tick=async(...args:any[])=>{
  const result=await queueTick(...args);
  const faults=(await admin.query("SELECT id,type,status,attempts,claim_fence,last_error FROM finnor_os.jobs WHERE status IN('quarantined','dead_letter') ORDER BY id LIMIT 257")).rows;
  if(faults.length){const record=JSON.stringify({observedAt:new Date().toISOString(),readOnlyObserver:true,faults})+'\n';queueDiagnosticBytes+=Buffer.byteLength(record);if(queueDiagnosticBytes<=1048576)await appendFile(join(evidence,'actual-queue-failures.jsonl'),record);}
  return result;
 };
 queue.register('run_evidence_derivation_v1',(await import('../../packages/private-equity/src/evidence-execution/worker')).runEvidenceDerivationJob,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_evidence_derivation_v1);
 try{const h=await import('../../packages/private-equity/src/program-synthesis/worker');queue.register('run_harness_program_v1',h.runHarnessProgramJob,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_harness_program_v1);}catch(error){results.push({id:'producer-module-resolution',status:'NOT_RUN',observed:String(error),qualification:'Baseline before production implementation'});}
 async function create(body:any=request()){const r=await api('program-submit',body);assert.equal(r.status,202,JSON.stringify(r));return r.body;}
 async function complete(p:any){for(let i=0;i<30;i++){await queue.tick();const r=await api('program-read',{programId:p.programId});assert.equal(r.status,200,JSON.stringify(r));if(['TESTED','FAILED','PARTIAL','INVALIDATED','CANCELLED','WAITING'].includes(r.body.status))return r.body;await new Promise(r=>setTimeout(r,30));}throw Error('Programme queue did not reach terminal/suspended predicate');}
 queue.register('run_objective_iteration',(await import('../../apps/worker/src/handlers/run-objective-iteration')).runObjectiveIteration,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_objective_iteration);
 queue.register('run_workforce_assignment',(await import('../../apps/worker/src/handlers/run-workforce-assignment')).runWorkforceAssignment,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_workforce_assignment);
 queue.register('process_work_event_wait_deadline',(await import('../../apps/worker/src/handlers/process-work-event-wait-deadline')).processWorkEventWaitDeadlineHandler,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.process_work_event_wait_deadline);

 try { const p2=await import('../../packages/private-equity/src/compute-search/worker'); queue.register('run_compute_search_unit_v1',p2.runComputeSearchUnitJob,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_compute_search_unit_v1); } catch (error) { await writeFile(join(evidence,'producer-resolution.json'),JSON.stringify({error:String(error),qualification:'Failure-first baseline'},null,2)); }
 const story=await import('./stories.mts');
 const environment={admin,queue,evidence,repo,api,request,create,complete,ctx,tenant,actor,foreignTenant,foreignActor,companies,sourceRef,periodStart,periodEnd,validAt};
 await story.runRegisteredCases(environment,test);
} catch(e) { results.push({id:'setup',status:'FAIL',observed:{message:String(e),stack:(e as Error).stack}}); }
finally {
 if(admin)try{
  const boundary:any={schema:'finnor.m2.actual-terminal-boundary.v1',observedAt:new Date().toISOString(),assertionsChanged:false};
  for(const [key,table,order]of [['searches','p2_requests','id'],['units','p2_units','created_at,id'],['attempts','p2_attempts','created_at,id'],['moduleRuns','m2_module_runs','created_at,id'],['episodes','p1_episodes','id']] as const){
   boundary[key]=(await admin.query(`SELECT * FROM finnor_os.${table} ORDER BY ${order} LIMIT 257`)).rows;
   if(boundary[key].length===257)throw Error('M2_TERMINAL_OBSERVER_ROW_BOUND');
  }
  boundary.jobs=(await admin.query("SELECT id,type,status,attempts,claim_fence,last_error,payload FROM finnor_os.jobs WHERE type IN('run_compute_search_unit_v1','run_harness_program_v1','run_evidence_derivation_v1') ORDER BY id LIMIT 257")).rows;
  const bytes=JSON.stringify(boundary,null,2);if(Buffer.byteLength(bytes)>67108864)throw Error('M2_TERMINAL_OBSERVER_BYTE_BOUND');
  await writeFile(join(evidence,'actual-terminal-boundary.json'),bytes+'\n');
 }catch(error){await writeFile(join(evidence,'terminal-boundary-capture-error.json'),JSON.stringify({error:String(error)}));}
 if(admin)try{await writeFile(join(evidence,'m2-executable-module-preimages.json'),JSON.stringify((await admin.query('SELECT tenant_id,principal_id,digest,body FROM finnor_os.m2_modules ORDER BY digest')).rows,null,2));}catch(error){await writeFile(join(evidence,'module-preimage-capture-error.json'),JSON.stringify({error:String(error)}));}
 await save(); await closePool(); await admin?.end(); await postgres?.stop(); await rm(directory,{recursive:true,force:true});
}
process.exitCode=results.some(r=>r.status==='FAIL')?1:results.some(r=>r.status==='PASS')?0:1;
