import {OfficePackage,NS,children,descendants,node,finishIR,ensure,replaceXml,innerReplacement,xmlEscape,type XmlNode,type SemanticIR,type SemanticNode,type XmlReplacement} from '@finnor/ooxml';
const revisionKinds=new Set(['ins','del','moveFrom','moveTo','pPrChange','rPrChange','tblPrChange','tblGridChange','trPrChange','tcPrChange','sectPrChange','numberingChange']);
const opaqueKinds=new Set(['txbxContent','fldSimple','sdt']);
const kinds:Record<string,string>={sectPr:'section',p:'paragraph',r:'run',tbl:'table',tr:'tableRow',tc:'tableCell',hyperlink:'hyperlink',bookmarkStart:'bookmark',footnote:'footnote',endnote:'endnote',hdr:'header',ftr:'footer',comment:'comment',ins:'revision',del:'revision',moveFrom:'revision',moveTo:'revision',pPrChange:'revision',rPrChange:'revision',tblPrChange:'revision',tblGridChange:'revision',trPrChange:'revision',tcPrChange:'revision',sectPrChange:'revision',numberingChange:'revision',sdt:'contentControl',drawing:'image',txbxContent:'unsupported'};
function texts(n:XmlNode):string[]{return descendants(n,'t',NS.word).map(x=>x.text);}
export function parseDocument(pkg:OfficePackage):SemanticIR {
 ensure(pkg.format==='docx','NOT_DOCUMENT');const nodes:SemanticNode[]=[],warnings:string[]=[],interpreted:string[]=[];
 for(const [part]of pkg.parts){if(!/^word\/.*\.xml$/.test(part)||/styles|settings|theme|fontTable|numbering|webSettings/.test(part))continue;const root=pkg.xml(part);if(![NS.word,NS.drawing].includes(root.uri))continue;interpreted.push(part);
 const visit=(n:XmlNode,opaque=false)=>{const blocked=opaque||revisionKinds.has(n.local)||opaqueKinds.has(n.local)||descendants(n,'fldChar',NS.word).length>0||[...revisionKinds].some(local=>descendants(n,local,NS.word).length>0);const kind=kinds[n.local];if(kind&&n.uri===NS.word){const style=descendants(n,n.local==='p'?'pStyle':'rStyle',NS.word)[0]?.attrs['w:val']??null;nodes.push(node(part,n,kind,{text:texts(n).join(''),style,attributes:n.attrs,editable:!blocked,revision:n.local==='ins'||n.local==='moveTo'?'inserted':n.local==='del'||n.local==='moveFrom'?'deleted':revisionKinds.has(n.local)?'property_change':null,numbering:descendants(n,'numPr',NS.word).map(x=>x.children.map(c=>({kind:c.local,attributes:c.attrs}))),sourceId:n.attrs['w14:paraId']??n.attrs['w:id']??null}));}if(blocked)warnings.push('TRACKED_FIELD_OR_OPAQUE_STRUCTURE_PRESERVED');for(const c of n.children)visit(c,blocked);};visit(root);
 }
 return finishIR(pkg,'document-ir.v1',nodes,warnings,interpreted);
}
export type DocumentOperation={type:'replace_text'|'insert_paragraph'|'delete_paragraph'|'replace_table_cell';anchor:string;expectedHash:string;text?:string}|{type:'set_run_style';anchor:string;expectedHash:string;bold?:boolean;italic?:boolean}|{type:'insert_table_row';anchor:string;expectedHash:string;values:string[]};
function find(root:XmlNode,path:string):XmlNode|undefined {if(root.path===path)return root;for(const c of root.children){const n=find(c,path);if(n)return n;}return undefined;}
export function patchDocument(pkg:OfficePackage,operations:DocumentOperation[]):Buffer {
 const ir=parseDocument(pkg),changes=new Map<string,XmlReplacement[]>();const add=(part:string,r:XmlReplacement)=>changes.set(part,[...(changes.get(part)??[]),r]);
 for(const op of operations){const target=ir.nodes.find(n=>n.id===op.anchor);ensure(target&&target.hash===op.expectedHash,'STALE_ANCHOR');ensure(target.data.editable,'UNSUPPORTED_DOCUMENT_TARGET');const root=pkg.xml(target.part),n=find(root,target.path)!;const source=pkg.text(target.part);
 ensure(!descendants(n,'fldChar',NS.word).length&&!descendants(n,'fldSimple',NS.word).length&&!descendants(n,'txbxContent',NS.word).length&&!descendants(n,'sdt',NS.word).length&&![...revisionKinds].some(local=>descendants(n,local,NS.word).length),'REVISION_OR_FIELD_WRITE_UNSUPPORTED');
 if(op.type==='replace_text'||op.type==='replace_table_cell'){ensure(['paragraph','run','tableCell'].includes(target.kind),'UNSUPPORTED_TEXT_TARGET');const slots=descendants(n,'t',NS.word);ensure(slots.length>0&&op.text!==undefined&&op.text.length<=100000,'EMPTY_OR_OVERSIZED_TEXT_TARGET');slots.forEach((slot,i)=>add(target.part,innerReplacement(source,slot,xmlEscape(i===0?op.text!:''))));}
 else if(op.type==='insert_paragraph'){ensure(target.kind==='paragraph'&&root.attrs['xmlns:w']===NS.word,'UNSUPPORTED_PARAGRAPH_TARGET');add(target.part,{start:n.end,end:n.end,value:'<w:p><w:r><w:t xml:space="preserve">'+xmlEscape(op.text??'')+'</w:t></w:r></w:p>'});}
 else if(op.type==='delete_paragraph'){ensure(target.kind==='paragraph'&&!descendants(n,'sectPr',NS.word).length,'UNSUPPORTED_PARAGRAPH_DELETE');add(target.part,{start:n.start,end:n.end,value:''});}
 else if(op.type==='insert_table_row'){ensure(target.kind==='tableRow'&&op.values.length>0&&op.values.length<=100&&root.attrs['xmlns:w']===NS.word,'UNSUPPORTED_TABLE_ROW');ensure(!descendants(n,'vMerge',NS.word).length&&!descendants(n,'gridSpan',NS.word).length,'MERGED_TABLE_UNSUPPORTED');add(target.part,{start:n.end,end:n.end,value:'<w:tr>'+op.values.map(v=>'<w:tc><w:p><w:r><w:t xml:space="preserve">'+xmlEscape(v)+'</w:t></w:r></w:p></w:tc>').join('')+'</w:tr>'});}
 else if(op.type==='set_run_style'){ensure(target.kind==='run'&&root.attrs['xmlns:w']===NS.word,'UNSUPPORTED_STYLE_TARGET');const props=children(n,'rPr',NS.word)[0];let value=props?source.slice(props.openEnd,props.closeStart):'';for(const [key,v]of [['b',op.bold],['i',op.italic]] as const)if(v!==undefined){ensure(!props||!children(props,key,NS.word).length,'EXISTING_STYLE_REPLACEMENT_UNSUPPORTED');value+='<w:'+key+' w:val="'+(v?'1':'0')+'"/>';}
 if(props)add(target.part,innerReplacement(source,props,value));else add(target.part,{start:n.openEnd,end:n.openEnd,value:'<w:rPr>'+value+'</w:rPr>'});}
 }
 const parts=new Map([...changes].map(([p,c])=>[p,Buffer.from(replaceXml(pkg.text(p),c))]));return pkg.patch(parts,[...parts.keys()]);
}
