-- Production compatibility objects that are managed by the Supabase database
-- but are not part of the application schema generated by the fresh project.
-- This is additive: the source project remains untouched and the canonical
-- communications_log table continues to be the application write/read model.

CREATE TABLE IF NOT EXISTS finnor_os._migrations (
  name text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS finnor_os.communications_log_legacy (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id uuid NOT NULL REFERENCES finnor_os.households(id),
  channel text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  content text NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  tenant_id uuid NOT NULL DEFAULT finnor_os.request_tenant_id()
    REFERENCES finnor_os.tenants(id)
);

CREATE INDEX IF NOT EXISTS communications_log_legacy_household_timestamp_id_idx
  ON finnor_os.communications_log_legacy (household_id, "timestamp" DESC, id);
CREATE INDEX IF NOT EXISTS communications_log_legacy_tenant_household_time_idx
  ON finnor_os.communications_log_legacy (tenant_id, household_id, "timestamp" DESC, id);

ALTER TABLE finnor_os.communications_log_legacy ENABLE ROW LEVEL SECURITY;
ALTER TABLE finnor_os.communications_log_legacy FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON finnor_os.communications_log_legacy;
CREATE POLICY tenant_isolation ON finnor_os.communications_log_legacy
  USING (tenant_id = finnor_os.request_tenant_id())
  WITH CHECK (tenant_id = finnor_os.request_tenant_id());

-- These extensions are present on the source project and available on the new
-- FREE project. Supabase may expose a newer compatible patch version on the
-- target; extension names and schemas are the compatibility contract.
CREATE SCHEMA IF NOT EXISTS graphql;
CREATE SCHEMA IF NOT EXISTS pgmq;
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS pg_graphql WITH SCHEMA graphql;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgmq WITH SCHEMA pgmq;
