/** Pre-implementation owner-boundary challenges. Independent generator/reference,
 * actual S1/PE owners and handlers. No production simulator is the truth oracle.
 * This is generated/retrospective local H1, never prospective field evidence. */
import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';
import { strict as assert } from 'node:assert';
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile, mkdtemp, appendFile, rm, chmod, readdir } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createServer } from 'node:net';
import { migrate } from '../../packages/db/migrate';
import { closePool, configureTenantVertical, withTenantTransaction } from '@finnor/db';
import { createMetricSeries, loadEnterpriseBeliefView, restateMetricObservation, attachCanonicalEvidenceToWorld, type PeMutationContext } from '@finnor/private-equity';
import { createEvidenceSource } from '@finnor/memory';
import { POST } from '../../apps/api/app/api/interventions/[operation]/route';

const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const output=resolve(process.env.FINNOR_S3_EVIDENCE_DIR ?? join(repo,'scope-3/scope-evidence',`run-${Date.now()}-${randomUUID().slice(0,8)}`));
await mkdir(output,{recursive:true});
const cases:any[]=[], workloads:any[]=[], startedAt=new Date().toISOString();
const paths=['finnor-os/scripts/s3/run-s3-e2e.mts','finnor-os/scripts/s3/run-s3-cold.mts','finnor-os/scripts/s3/reference.py','finnor-os/scripts/s3/run-local.py','finnor-os/scripts/s3/instrument-design.json',
 'scope-3/scope-plan.md','scope-3/scope-evidence/failure-model.md','finnor-os/packages/shared-types/src/interventions.ts',
 'finnor-os/packages/epistemic-runtime/src/interventions.ts','finnor-os/packages/epistemic-runtime/src/intervention-backend.ts',
 'finnor-os/packages/epistemic-runtime/src/intervention-numerics.py','finnor-os/packages/private-equity/src/enterprise-interventions.ts',
 'finnor-os/apps/api/app/api/interventions/[operation]/route.ts','finnor-os/packages/shared-types/src/experiments.ts',
 'finnor-os/packages/private-equity/src/enterprise-beliefs.ts','package-lock.json','finnor-os/package-lock.json'];
const manifest=await Promise.all(paths.map(async path=>{const b=await readFile(resolve(repo,path));const dst=join(output,'source-snapshot',path);await mkdir(dirname(dst),{recursive:true});await writeFile(dst,b);return {path,sha256:createHash('sha256').update(b).digest('hex')};}));
const python=process.env.FINNOR_S3_PYTHON!;
const versions={node:process.version,python:spawnSync(python,['-c','import sys,importlib.metadata as m,json;print(json.dumps({"python":sys.version,**{p:m.version(p) for p in ["numpy","scipy","statsmodels","arch","pandas"]}}))'],{encoding:'utf8'}).stdout.trim()};
const harnessPackages=Object.fromEntries(await Promise.all(['tsx','typescript','next','zod','embedded-postgres','pg'].map(async name=>[name,JSON.parse(await readFile(resolve(repo,'finnor-os/node_modules',name,'package.json'),'utf8')).version])));
let migrationCount=0;let databaseVersion='unknown';
async function save(){await writeFile(join(output,'results.json'),JSON.stringify({schema:'finnor.s3.e2e.v1',startedAt,generatedAt:new Date().toISOString(),status:cases.some(x=>x.status==='FAIL')?'FAIL':'PASS_LOCAL',manifest,versions,harnessPackages,migrationCount,databaseVersion,cases,workloads,
 evidenceBoundary:'Generated laws and owner-record fixtures; ordinary-role S1 and actual header-auth handlers. No field intervention, independent scientific admission, protected ledger receipt or H2 credit.',rerun:'FINNOR_S3_PYTHON=/tmp/finnor-s3-python/bin/python python3 finnor-os/scripts/s3/run-local.py'},null,2)+'\n');}
async function challenge(id:string,input:any,expected:string,fn:()=>Promise<any>){const start=performance.now();try{cases.push({id,input,expected,status:'PASS',observed:await fn(),elapsedMs:performance.now()-start});}catch(e){cases.push({id,input,expected,status:'FAIL',observed:e instanceof Error?{message:e.message,stack:e.stack}:String(e),elapsedMs:performance.now()-start});}await save();}
function oracle(input:any){const r=spawnSync(python,[resolve(repo,'finnor-os/scripts/s3/reference.py')],{input:JSON.stringify(input),encoding:'utf8',maxBuffer:8*1024*1024});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
const tenant=randomUUID(),actor=randomUUID(),foreignTenant=randomUUID(),foreignActor=randomUUID(),a=randomUUID(),b=randomUUID();
const roots=[{entityType:'external_organization',entityId:a},{entityType:'external_organization',entityId:b}];
const ctx:PeMutationContext={auth:{tenantId:tenant,userId:actor,employeeId:actor,role:'owner'}};
const ref=(id:string)=>({owner:'SUPPLIED',id,version:'fixture-v1',contentDigest:createHash('sha256').update(id).digest('hex')});
const f=(kind:string,id:string,lag:number)=>({kind,id,lag});const constant={kind:'CONSTANT'};
const eqs=[
 {variableId:'revenue',features:[constant,f('STATE','revenue',1),f('EXPOSURE','price',0),f('EXPOSURE','price',2),f('STATE','actor',1),f('STATE','inventory',1),{kind:'PRODUCT',left:f('EXPOSURE','price',0),right:f('STATE','inventory',1)}]},
 {variableId:'inventory',features:[constant,f('STATE','inventory',1),f('EXPOSURE','price',1),f('STATE','revenue',1)]},
 {variableId:'actor',features:[constant,f('STATE','actor',1),f('EXPOSURE','price',1),f('EXPOSURE','disclosure',0),f('EXPOSURE','price',2)]},
 {variableId:'peer',features:[constant,f('STATE','peer',1),f('EXPOSURE','price',0),f('STATE','actor',1)]}];
const assumptions=['SEQUENTIAL_EXCHANGEABILITY','POSITIVITY','CONSISTENCY','MEASUREMENT','SELECTION','INTERFERENCE','STATIONARITY','FUNCTIONAL_FORM','ACTOR_INFORMATION'].map(category=>({id:category,category,status:'DECLARED',meaning:`Generated subclass assumes ${category}; not field evidence`,evidenceRefs:[ref(category)]}));
let request:any, modelRef:any, model:any, query:any, evidence:any, ambiguityModelRef:any, ambiguityRoot:any, admin:pg.Client|undefined;
const rows=oracle({operation:'generate'});await writeFile(join(output,'hidden-truth.json'),JSON.stringify(rows));
const periodMs=86400000,startAt=new Date(Math.floor(Date.now()/periodMs)*periodMs-129*periodMs).toISOString();
const series:any={}, observationIds:any={};let emptyExposureSeries:string;
async function api(operation:string,body:any,t=tenant,u=actor){const response=await POST(new Request(`http://localhost/api/interventions/${operation}`,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':t,'x-user-id':u},body:JSON.stringify(body)}),{params:Promise.resolve({operation})});return {status:response.status,body:await response.json() as any};}
function makeQuery(id='q1',horizon=8){const dose=(value:number,op:string,exposureId:string)=>({exposureId,operation:op,unit:'fraction',target:roots[0],doses:Array.from({length:horizon},(_,i)=>exposureId==='price'&&i>=4?-value:value),intendedExposure:'REGISTERED_DOSE',permittedRefinements:[]});
 const specification=(value:number)=>({schema:'finnor.intervention-specification.v1',vocabularyVersion:'s3-intervention-v1',targets:roots,context:'public-price',timing:{startAt:new Date(Date.parse(startAt)+128*periodMs).toISOString(),periodMs,durationMs:horizon*periodMs},channels:[dose(value,'PRICE_CHANGE','price'),dose(0,'DISCLOSURE','disclosure')]});
 return {schema:'finnor.s3.response-query.v1',id,episodeId:'s3-e2e',kind:'POPULATION_INTERVENTION',targets:roots,context:'public-price',regime:'operating-v1',horizon,intervention:specification(.15),comparator:specification(0),simulations:1024,seed:20261003};}
const dir=await mkdtemp(join(tmpdir(),'finnor-s3-e2e-'));const port=await new Promise<number>((yes,no)=>{const s=createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const address=s.address();if(!address||typeof address==='string')return no(Error('port'));s.close(()=>yes(address.port));});});
const postgres=new EmbeddedPostgres({databaseDir:dir,user:'finnor',password:'finnor',port,persistent:false,onLog:()=>undefined});
try{
 process.env.FINNOR_TEST_MANAGED_EXTENSIONS='omit';await postgres.initialise();await appendFile(join(dir,'postgresql.conf'),'\ntrack_commit_timestamp=on\n');await postgres.start();await postgres.createDatabase('s3_e2e');
 const url=`postgres://finnor:finnor@127.0.0.1:${port}/s3_e2e`;migrationCount=(await migrate(url)).length;admin=new pg.Client({connectionString:url});await admin.connect();databaseVersion=(await admin.query('SELECT version() version')).rows[0].version;
 await admin.query("ALTER ROLE finnor_app LOGIN PASSWORD 'finnor_app'");await admin.query("SET app.test_vertical_mode='explicit'");
 await admin.query("INSERT INTO finnor_os.tenants(id,client_key,name) VALUES($1,$2,'S3 A'),($3,$4,'S3 B')",[tenant,randomUUID(),foreignTenant,randomUUID()]);
 await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status) VALUES($1,$2,$3,'owner','active'),($4,$5,$6,'owner','active')",[actor,tenant,`${actor}@test.invalid`,foreignActor,foreignTenant,`${foreignActor}@test.invalid`]);
 process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/s3_e2e`;await closePool();for(const [t,u]of[[tenant,actor],[foreignTenant,foreignActor]])await configureTenantVertical({tenantId:t!,verticalKey:'private_equity',expectedVersion:0,createdBy:u!,sourceSystem:'s3:e2e'});
 await admin.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,'s3-a','S3 A','other'),($3,$2,'s3-b','S3 B','other')",[a,tenant,b]);
 // Actual canonical history triggers, independently supplied generated fixtures.
 const source=(await createEvidenceSource(tenant,{sourceKey:`s3-generated:${randomUUID()}`,sourceType:'pe_document_claim',title:'Generated S3 evidence'})).id,version=randomUUID();
 await admin.query("INSERT INTO finnor_os.evidence_source_versions(id,source_id,scope,tenant_id,version_number,content_hash,content,snapshot,as_of,retrieved_at,created_at) VALUES($1,$2,'tenant',$3,1,$4,'Generated evaluator fixtures',$5::jsonb,$6,clock_timestamp(),clock_timestamp())",[version,source,tenant,ref('generated').contentDigest,JSON.stringify({worldRoot:roots[0],claims:[{propositionId:'s3-generated-input',predicate:'reported',value:'Generated numerical observations; not field evidence'}]}),startAt]);evidence={evidenceSourceId:source,evidenceVersionId:version};
 for(const id of['revenue','inventory','actor','peer','price','disclosure']){const root=['actor','peer'].includes(id)?roots[1]!:roots[0]!;const s=await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:root.entityId,metricKey:`s3-${id}`,name:`Generated ${id}`,unit:['price','disclosure'].includes(id)?'fraction':'normalized-value',frequency:'daily'});series[id]=s.row.id;
  await attachCanonicalEvidenceToWorld(ctx,{worldRoot:root as any,entity:{entityType:'pe_metric_series',entityId:series[id]},evidenceSourceId:source,evidenceVersionId:version,relationship:'supports'});
  for(const row of rows){const obs=randomUUID(),at=new Date(Date.parse(startAt)+row.period*periodMs).toISOString(),end=new Date(Date.parse(at)+periodMs).toISOString();observationIds[`${id}:${row.period}`]=obs;
   await admin.query("INSERT INTO finnor_os.pe_metric_observations(id,tenant_id,metric_series_id,period_start,period_end,value_type,value_numeric,evidence_source_id,evidence_version_id,source_system,created_by) VALUES($1,$2,$3,$4,$5,'number',$6,$7,$8,'s3:generated',$9)",[obs,tenant,series[id],at,end,String(row[['price','disclosure'].includes(id)?'exposures':'states'][id]),source,version,actor]);}}
 const empty=await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:a,metricKey:'s3-missing-actual',name:'Unobserved actual exposure',unit:'fraction',frequency:'daily'});emptyExposureSeries=String(empty.row.id);await attachCanonicalEvidenceToWorld(ctx,{worldRoot:roots[0] as any,entity:{entityType:'pe_metric_series',entityId:emptyExposureSeries},evidenceSourceId:source,evidenceVersionId:version,relationship:'supports'});
 request={schema:'finnor.s3.fit-request.v1',modelKey:'pricing-delayed-churn-competitive-response',episodeId:'s3-e2e',roots,
  stateVariables:['revenue','inventory','actor','peer'].map(id=>({id,root:['actor','peer'].includes(id)?roots[1]:roots[0],seriesId:series[id],unit:'normalized-value',range:[-6,6],role:id==='actor'?'COUNTERPARTY':'ENTERPRISE_STATE'})),
  exposures:['price','disclosure'].map(id=>({id,root:roots[0],seriesId:series[id],unit:'fraction',operation:id==='price'?'PRICE_CHANGE':'DISCLOSURE',measurement:{status:'MEASURED_ACTUAL',methodRef:ref('generated-measurement'),qualification:'SUPPLIED_OWNER_MEASUREMENT_UNVERIFIED'}})),
  time:{startAt,endAt:new Date(Date.parse(startAt)+128*periodMs).toISOString(),periodMs,trainingThrough:new Date(Date.parse(startAt)+96*periodMs).toISOString()},
  validity:{validUntil:new Date(Date.now()+3600000).toISOString(),maxBeliefAgeMs:3600000,regimes:['operating-v1'],contexts:['public-price'],maximumHorizon:24},
  measurementPolicy:{selection:'COMPLETE_RECORDED_GRID_ASSUMED',missingness:'NONE',instrumentError:'ASSUMED_NEGLIGIBLE'},
  mechanisms:[{id:'dynamic-identified-conditional',meaning:'Lagged pricing, churn, working-capital feedback, competitive disclosure response and shared shocks',origin:'SUPPLIED_HYPOTHESIS',assumptions,equations:eqs,counterparties:[{variableId:'actor',actorRef:ref('counterparty'),objectives:['Market-share objective is a supplied interpretation'],informationExposureIds:['price','disclosure'],constraints:['Observed action range'],responseAssumption:'LEARNED_LAGGED_RESPONSE'}]}],
  numerical:{bootstrapDraws:128,blockLength:4,seed:20261003}};
 async function seedFixture(root:any,ids:string[],fixture:any[],anchor=startAt){
  const ownerSeries:any={};
  await admin!.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,$3,'Additional generated S3 owner','other')",[root.entityId,tenant,`s3-${root.entityId}`]);
  for(const id of ids){const exposure=id==='price'||id==='disclosure';const s=await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:root.entityId,metricKey:`s3-${id}`,name:`Generated ${id}`,unit:exposure?'fraction':'normalized-value',frequency:'daily'});ownerSeries[id]=s.row.id;
   await attachCanonicalEvidenceToWorld(ctx,{worldRoot:root,entity:{entityType:'pe_metric_series',entityId:String(s.row.id)},evidenceSourceId:source,evidenceVersionId:version,relationship:'supports'});
   for(const row of fixture){const at=new Date(Date.parse(anchor)+row.period*periodMs).toISOString();await admin!.query("INSERT INTO finnor_os.pe_metric_observations(id,tenant_id,metric_series_id,period_start,period_end,value_type,value_numeric,evidence_source_id,evidence_version_id,source_system,created_by) VALUES($1,$2,$3,$4,$5,'number',$6,$7,$8,'s3:generated',$9)",[randomUUID(),tenant,s.row.id,at,new Date(Date.parse(at)+periodMs).toISOString(),String(row[exposure?'exposures':'states'][id]),source,version,actor]);}}
  return ownerSeries;
 }
 function ownerQuery(ownerRoots:any[],exposureRoots:Record<string,any>,ids=['price','disclosure']){const q=makeQuery();q.targets=ownerRoots;for(const spec of[q.intervention,q.comparator]){spec.targets=ownerRoots;spec.channels=spec.channels.filter((c:any)=>ids.includes(c.exposureId));for(const c of spec.channels)c.target=exposureRoots[c.exposureId];}return q;}
 await writeFile(join(output,'preregistered-inputs.json'),JSON.stringify({request,query:makeQuery(),seed:20261003,manifest},null,2));
 await challenge('actual-owner-s1-fit-api',request,'Learn parameters from qualified ordinary-role S1, retain all source versions, match independent QR coefficients; no grant',async()=>{const r=await api('fit',{request});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.status,'FITTED');model=r.body.model;modelRef=model.ref;assert(modelRef);assert.equal(model.admission.receipt,null);assert.equal(model.admission.executionAuthorityGranted,false);assert.equal(model.beliefBindings.length,2);assert.equal(model.history.periods,128);const expected=oracle({operation:'least_squares',rows,equations:eqs});for(const eq of model.fits[0].equations)eq.coefficients.forEach((x:number,i:number)=>assert(Math.abs(x-expected[eq.variableId][i])<1e-8));return r.body;});
 query=makeQuery();
 await challenge('delayed-repeated-adaptive-joint-response',query,'Population conditional scenario matches independent hidden-law recurrence; extrapolated path mass must yield explicit bounds, shared covariance and actor history retained',async()=>{const r=await api('query',{modelRef,query});assert.equal(r.status,200,JSON.stringify(r.body));assert(['CONDITIONALLY_IDENTIFIED','BOUNDED'].includes(r.body.identification.status));const outcome=r.body.responses[0];if(r.body.identification.status==='BOUNDED')assert(outcome.periods.some((p:any)=>p.unsupportedFraction>0));const treatment=query.intervention.channels[0].doses.map((price:number)=>({price,disclosure:0})),comparator=treatment.map(()=>({price:0,disclosure:0}));const truth=oracle({operation:'reference',history:rows.slice(-3),treatment,comparator});await writeFile(join(output,'independent-trajectories.json'),JSON.stringify(truth));for(let t=0;t<query.horizon;t++)for(const id of ['revenue','actor','peer']){assert(Math.abs(outcome.periods[t].effectMean[id]-truth.effects[t][id])<=.10*12);const bounds=outcome.periods[t].effectBounds[id];assert(bounds[0]<=truth.effects[t][id]&&bounds[1]>=truth.effects[t][id]);}assert(outcome.periods[0].stateCovariance[0][3]>.01);assert(outcome.periods[2].effectMean.actor!==0);assert.equal(r.body.lineage.attributionGranted,false);assert.equal(r.body.lineage.authorityRef,null);return {result:r.body,truth:{means:truth.means,effects:truth.effects}};});
 await challenge('calibration-heldout-usefulness',{},'Independent generated future observations fall in useful model-conditional 90% intervals at preregistered rate',async()=>{const r=await api('query',{modelRef,query});const truth=oracle({operation:'reference',history:rows.slice(-3),treatment:query.intervention.channels[0].doses.map((price:number)=>({price,disclosure:0})),comparator:Array.from({length:query.horizon},()=>({price:0,disclosure:0}))});const metrics=[];for(const id of['revenue','inventory','actor','peer']){let covered=0,total=0,width=0;for(let t=0;t<query.horizon;t++){const interval=r.body.responses[0].periods[t].stateIntervals[id]['0.9'];width+=interval[1]-interval[0];for(const path of truth.paths){total++;if(path[t][id]>=interval[0]&&path[t][id]<=interval[1])covered++;}}const coverage=covered/total;assert(coverage>=.82&&coverage<=.98,`${id}:${coverage}`);assert(width/query.horizon<=.5*12);metrics.push({id,coverage,meanWidth:width/query.horizon});}return {metrics,qualification:'Generated subclass only; parameter/mechanism/measurement assumptions unverified in field'};});
 await challenge('equivalent-hidden-confounding-and-invalid-instrument',{equivalent:oracle({operation:'equivalent'})},'Actual identical observational law supports incompatible do-effects 1 and 0; usable fits cannot manufacture causal selection or invalid-IV identification',async()=>{
  const truth=oracle({operation:'equivalent'});ambiguityRoot={entityType:'external_organization',entityId:randomUUID()};const s=await seedFixture(ambiguityRoot,['outcome','price'],truth.rows);
  const req=structuredClone(request);req.roots=[ambiguityRoot];req.stateVariables=[{id:'outcome',root:ambiguityRoot,seriesId:s.outcome,unit:'normalized-value',range:[-6,6],role:'ENTERPRISE_STATE'}];req.exposures=[{...req.exposures[0],root:ambiguityRoot,seriesId:s.price}];
  const first={...req.mechanisms[0],id:'causal-A-to-Y',meaning:'Y=A+noise with supplied exchangeability; population dose 0 to 1 effect 1',equations:[{variableId:'outcome',features:[constant,f('EXPOSURE','price',0)]}],counterparties:[]};const alt=structuredClone(first);alt.id='latent-U-causes-A-and-Y';alt.meaning='A=U and Y=U+noise give the identical observed law but do-effect 0; exchangeability and overlap conditional on U unresolved';alt.assumptions.find((a:any)=>a.category==='SEQUENTIAL_EXCHANGEABILITY').status='UNKNOWN';alt.assumptions.find((a:any)=>a.category==='POSITIVITY').status='UNKNOWN';req.mechanisms=[first,alt];
  const fitted=await api('fit',{request:req});assert.equal(fitted.body.status,'FITTED',JSON.stringify(fitted.body));for(const fit of fitted.body.model.fits){assert.equal(fit.status,'FITTED');assert(fit.refutations.every((r:any)=>r.status==='NOT_FALSIFIED'));}assert.deepEqual(fitted.body.model.fits[0].equations[0].coefficients,fitted.body.model.fits[1].equations[0].coefficients);ambiguityModelRef=fitted.body.model.ref;
  const response=await api('query',{modelRef:ambiguityModelRef,query:ownerQuery([ambiguityRoot],{price:ambiguityRoot},['price'])});assert.equal(response.status,200);assert.equal(response.body.identification.status,'UNRESOLVED');assert(response.body.identification.reasons.length);assert(response.body.responses.some((r:any)=>r.mechanismId===alt.id&&r.periods.every((p:any)=>p.unsupportedMassUpper95===1)));
  const invalid=structuredClone(request);invalid.mechanisms[0].assumptions.find((a:any)=>a.category==='MEASUREMENT').status='UNKNOWN';invalid.mechanisms[0].meaning='Proposed instrument exclusion and actual exposure unresolved; no IV identification method registered';const ivfit=await api('fit',{request:invalid});assert.equal(ivfit.body.status,'FITTED');const ivquery=await api('query',{modelRef:ivfit.body.model.ref,query});assert.equal(ivquery.body.identification.status,'UNRESOLVED');return {request:req,truth:{causalEffect:truth.causalEffect,confoundedEffect:truth.confoundedEffect},fit:fitted.body,response:response.body,invalidInstrument:ivquery.body};});
 await challenge('changed-adaptive-actor-law',{seed:20261003,changeAt:96,actorPriceLag1:[.7,1.4]},'Training sees original law; withheld actor response shift falsifies applicability and cannot yield a conditionally identified transported effect',async()=>{
  const shifted=oracle({operation:'generate',shifted:true});const root={entityType:'external_organization',entityId:randomUUID()},s=await seedFixture(root,['revenue','inventory','actor','peer','price','disclosure'],shifted);
  const req=structuredClone(request);req.roots=[root];for(const v of[...req.stateVariables,...req.exposures]){v.root=root;v.seriesId=s[v.id];}const fitted=await api('fit',{request:req});assert.equal(fitted.body.status,'FITTED');const diagnostic=fitted.body.model.fits[0].refutations.find((r:any)=>r.test==='actor:holdout-error-scale');assert.equal(diagnostic.status,'FALSIFIED',JSON.stringify(diagnostic));const q=ownerQuery([root],{price:root,disclosure:root});const response=await api('query',{modelRef:fitted.body.model.ref,query:q});assert.equal(response.body.identification.status,'UNRESOLVED');return {request:req,heldoutLaw:'Actor lagged pricing coefficient changes only after training cut',fit:fitted.body,response:response.body};});
 await challenge('missing-selection-noncompliance-posttreatment',{},'No silent complete-case fit or intended-exposure causal substitution; post-treatment adjustment unsupported',async()=>{const results=[];for(const mutation of['INTENDED','INFORMATIVE','POST_TREATMENT']){const req=structuredClone(request);if(mutation==='INTENDED')req.exposures[0].measurement.status='INTENDED';else if(mutation==='INFORMATIVE')req.measurementPolicy.missingness='INFORMATIVE';else req.mechanisms[0].equations[0].features.push(f('STATE','actor',0));const r=await api('fit',{request:req});assert(r.status>=400||r.body.status==='REJECTED');results.push(r);}const missing=structuredClone(request);missing.exposures[0].seriesId=emptyExposureSeries;const unobserved=await api('fit',{request:missing});assert.equal(unobserved.status,200);assert.equal(unobserved.body.status,'REJECTED');assert.equal(unobserved.body.compute,null);assert(unobserved.body.reasons.some((r:string)=>r.includes('Missing, duplicated or censored')));results.push(unobserved);for(const type of['UNKNOWN','INFORMATION_CONTRADICTION']){const req=structuredClone(request);if(type==='UNKNOWN')req.mechanisms[0].counterparties[0].responseAssumption='UNKNOWN';else req.mechanisms[0].counterparties[0].informationExposureIds=['disclosure'];const fitted=await api('fit',{request:req});assert.equal(fitted.body.status,'FITTED');const q=await api('query',{modelRef:fitted.body.model.ref,query});assert.equal(q.body.identification.status,'UNRESOLVED');assert(q.body.identification.reasons.some((r:string)=>r.includes(type==='UNKNOWN'?'COUNTERPARTY_RESPONSE_UNKNOWN':'ACTOR_INFORMATION_ASSUMPTION_CONTRADICTS_FEATURES')));results.push(q);}return results;});
 await challenge('unsupported-company-regime-context-dose',{},'No label-based transport, novel regime/context or joint dose extrapolation',async()=>{const out=[];for(const mutation of['company','regime','context','dose','counterfactual']){const q=structuredClone(query);if(mutation==='company'){q.targets.push(ambiguityRoot);for(const spec of[q.intervention,q.comparator])spec.targets=structuredClone(q.targets);}if(mutation==='regime')q.regime='changed-response';if(mutation==='context'){q.context='private-negotiation';q.intervention.context=q.context;q.comparator.context=q.context;}if(mutation==='dose')q.intervention.channels[0].doses=q.intervention.channels[0].doses.map(()=>5);if(mutation==='counterfactual')q.kind='UNIT_COUNTERFACTUAL';const r=await api('query',{modelRef,query:q});assert.equal(r.status,200,JSON.stringify(r.body));if(mutation==='dose'){assert.equal(r.body.identification.status,'BOUNDED');assert(r.body.responses[0].periods.some((p:any)=>p.unsupportedFraction>0));}else{assert.equal(r.body.identification.status,'UNRESOLVED');const reason=mutation==='company'?'COMPANY_POPULATION_TRANSPORT_UNQUALIFIED':mutation==='counterfactual'?'UNIT_SPECIFIC_COUNTERFACTUAL_NOT_IDENTIFIED':'REGIME_OR_CONTEXT_TRANSPORT_UNQUALIFIED';assert(r.body.identification.reasons.includes(reason),JSON.stringify(r.body.identification));assert.equal(r.body.responses.length,0);}out.push({mutation,input:q,...r});}return out;});
 await challenge('semantic-tamper-foreign-and-request-limits',{},'Immutable artifact/lineage rejects changed commitments and foreign actor; bounded streaming independent of Content-Length',async()=>{const foreign=await api('query',{modelRef,query},foreignTenant,foreignActor);assert(foreign.status>=400);const tampered={...modelRef,contentDigest:'0'.repeat(64)};const altered=await api('query',{modelRef:tampered,query});assert(altered.status>=400);const changed=structuredClone(query);changed.intervention.channels[0].unit='USD';const units=await api('query',{modelRef,query:changed});assert(units.status>=400);const huge=await POST(new Request('http://localhost/api/interventions/fit',{method:'POST',headers:{'x-tenant-id':tenant,'x-user-id':actor,'content-length':'1'},body:' '.repeat(2*1024*1024+1)}),{params:Promise.resolve({operation:'fit'})});assert.equal(huge.status,413);const prefix=new TextEncoder().encode(JSON.stringify({modelRef}));let count=0;const streamed=new Request('http://localhost/api/interventions/validate',{method:'POST',headers:{'x-tenant-id':tenant,'x-user-id':actor},body:new ReadableStream<Uint8Array>({pull(controller){if(count===0)controller.enqueue(prefix);else if(count<=65536)controller.enqueue(new Uint8Array(16).fill(32));else controller.close();count++;}}),duplex:'half'} as any);const readback=await POST(streamed,{params:Promise.resolve({operation:'validate'})});assert.equal(readback.status,200);assert.equal((await readback.json()).status,'CURRENT');return {foreign,altered,units,oversized:huge.status,tinyChunks:65536,streamedReadback:readback.status};});
 await challenge('restart-and-source-artifact-identity',{},'Ordinary artifact survives actual fresh-process use with no protected history claim; loaded backend version is bound',async()=>{const input=join(output,'cold-model-use.json');await writeFile(input,JSON.stringify({operation:'validate',tenantId:tenant,principalId:actor,body:{modelRef}}));const cold=spawnSync(resolve(repo,'finnor-os/node_modules/.bin/tsx'),[resolve(repo,'finnor-os/scripts/s3/run-s3-cold.mts'),input],{env:process.env,encoding:'utf8',timeout:10000,maxBuffer:1024*1024});assert.equal(cold.status,0,cold.stderr);const validation=JSON.parse(cold.stdout);assert.equal(validation.status,200);assert.equal(validation.body.status,'CURRENT');assert.equal(validation.body.executionAuthorityGranted,false);assert.equal(model.compute.backend.versions.statsmodels,'0.14.5');assert.equal(model.compute.cost.money,null);assert.equal(model.compute.cost.externalCalls,0);return validation;});
 await challenge('artifact-corruption-and-backend-recovery',{},'Tampered ordinary artifact and unavailable numerical backend cannot yield a completed fit; failure costs/events remain, retry restores service',async()=>{const file=join(process.env.FINNOR_S3_MODEL_STORE!,tenant,actor,'models',`${modelRef.contentDigest}.json`),original=await readFile(file);assert.equal((await api('validate',{modelRef})).body.status,'CURRENT');await chmod(file,0o600);await writeFile(file,'{}');const corrupt=await api('query',{modelRef,query});await writeFile(file,original);await chmod(file,0o400);assert.equal(corrupt.status,404);const previous=process.env.FINNOR_S3_PYTHON;process.env.FINNOR_S3_PYTHON='/nonexistent/finnor-s3-python';let failed:any;try{failed=await api('fit',{request});}finally{process.env.FINNOR_S3_PYTHON=previous;}assert.equal(failed.status,200);assert.equal(failed.body.status,'FAILED');assert.equal(failed.body.model,null);assert.equal(failed.body.compute.attempts[0].status,'FAILED');assert.equal(failed.body.compute.cost.money,null);assert(failed.body.experience.some((e:any)=>e.type==='REJECTION'));const recovery=await api('query',{modelRef,query});assert.equal(recovery.status,200);return {corrupt,failed,recoveredResponse:recovery.body.ref};});
 await challenge('s2-boundary-and-downstream-handoff',{},'Temporal dependent response never supplies a fictional IID likelihood or commission/execute/credit owner',async()=>{const r=await api('experiment-projection',{modelRef});assert.equal(r.status,200);assert.equal(r.body.status,'UNSUPPORTED');assert(r.body.inquiryNeeds.length);const result=await api('query',{modelRef,query});assert.equal(result.body.handoffs.S4.executionAuthorityGranted,false);assert.equal(result.body.handoffs.S5.reservationGranted,false);assert.equal(result.body.handoffs.S7.creditGranted,false);for(const operation of['execute','append','promote'])assert.equal((await api(operation,{modelRef})).status,404);return {projection:r.body,handoffs:result.body.handoffs};});
 await challenge('actual-s2-instrument-design-bridge',{},'Independently supplied conditional IID instrument reaches real S2 with exact S3 hypothesis binding; outsider roots and temporal calibration upgrades rejected',async()=>{
  const projection=await api('experiment-projection',{modelRef:ambiguityModelRef});assert.equal(projection.body.hypotheses.length,2);const input=JSON.parse(await readFile(resolve(repo,'finnor-os/scripts/s3/instrument-design.json'),'utf8'));input.hypotheses=projection.body.hypotheses.map((h:any)=>({...h,prior:'0.5'}));const now=new Date().toISOString(),until=new Date(Date.now()+3600000).toISOString();input.validUntil=until;input.decisionContext.horizonEnd=until;for(const c of input.candidates){c.timing.startAt=now;c.timing.endAt=until;}
  const r=await api('design-experiment',{modelRef:ambiguityModelRef,root:ambiguityRoot,request:input});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.s3Binding.methodAdmitted,false);const protocol=r.body.bundle.designs.find((d:any)=>d.candidateId==='informative').protocol;assert(protocol);assert.equal(protocol.metrics.empiricallyCalibrated,false);assert.equal(protocol.admission.executionAuthorityGranted,false);assert.deepEqual(protocol.hypotheses.map((h:any)=>h.ref),input.hypotheses.map((h:any)=>h.ref));const outside=await api('design-experiment',{modelRef:ambiguityModelRef,root:roots[0],request:input});assert.equal(outside.status,400);return {input,result:r.body,outsideRoot:outside};});
 await challenge('large-registered-numerical-domain',{periods:512,features:24,parameterDraws:256,simulations:4096,horizon:24,deadlineMs:30000},'Largest registered individual numerical dimensions stay within original budgets; high-dimensional support is explicitly unavailable and all unsupported mass retained',async()=>{
  const fixture=oracle({operation:'generate',n:512}),begin=new Date(Math.floor(Date.now()/periodMs)*periodMs-513*periodMs).toISOString();const rs=[{entityType:'external_organization',entityId:randomUUID()},{entityType:'external_organization',entityId:randomUUID()}];const ys=await seedFixture(rs[0],['revenue'],fixture,begin),as=await seedFixture(rs[1],['price'],fixture,begin);const req=structuredClone(request);req.roots=rs;req.stateVariables=[{...req.stateVariables[0],root:rs[0],seriesId:ys.revenue}];req.exposures=[{...req.exposures[0],root:rs[1],seriesId:as.price}];req.time={startAt:begin,endAt:new Date(Date.parse(begin)+512*periodMs).toISOString(),periodMs,trainingThrough:new Date(Date.parse(begin)+480*periodMs).toISOString()};const atoms=[...Array.from({length:4},(_,i)=>f('EXPOSURE','price',i)),...Array.from({length:3},(_,i)=>f('STATE','revenue',i+1))],features:any[]=[constant,...atoms];for(let i=0;i<atoms.length&&features.length<24;i++)for(let j=i;j<atoms.length&&features.length<24;j++)features.push({kind:'PRODUCT',left:atoms[i],right:atoms[j]});req.mechanisms=[{...req.mechanisms[0],id:'high-dimensional-proposal',counterparties:[],equations:[{variableId:'revenue',features}]}];req.numerical.bootstrapDraws=256;
  const before=performance.now(),fit=await api('fit',{request:req});assert.equal(fit.body.status,'FITTED',JSON.stringify(fit.body));assert(performance.now()-before<=30000);const q=ownerQuery(rs,{price:rs[1]},['price']);q.horizon=24;q.simulations=4096;for(const spec of[q.intervention,q.comparator]){spec.timing.startAt=req.time.endAt;spec.timing.durationMs=24*periodMs;spec.channels[0]!.doses=Array(24).fill(spec===q.intervention ? .15 : 0);}const t=performance.now(),result=await api('query',{modelRef:fit.body.model.ref,query:q});assert.equal(result.status,200,JSON.stringify(result.body));assert(performance.now()-t<=30000);assert(result.body.responses[0].support.equations.some((e:any)=>e.status==='UNAVAILABLE'&&e.reason==='FULL_FEATURE_HULL_COMPLEXITY_UNQUALIFIED'));assert(result.body.responses[0].periods.every((p:any)=>p.unsupportedFraction===1));for(const c of[fit.body.compute,result.body.compute])assert(c.usage.childMaxRssBytes<=536870912);return {request:req,query:q,fit:fit.body,result:result.body};});
 await challenge('cold-warm-concurrent-budgets',{deadlineMs:30000,maxChildRssBytes:536870912},'Actual fitting and simulation attempts/versions/resources recorded and bounded; concurrency does not cross-contaminate',async()=>{const before=process.memoryUsage().rss;let peak=before;for(let i=0;i<3;i++){if(i===0)await closePool();const t=performance.now(),r=await api('fit',{request});assert.equal(r.status,200);assert.equal(r.body.status,'FITTED');const elapsed=performance.now()-t;peak=Math.max(peak,process.memoryUsage().rss);assert(elapsed<=30000);assert(r.body.compute.usage.childMaxRssBytes<=536870912);workloads.push({mode:i===0?'cold':'warm',elapsedMs:elapsed,compute:r.body.compute});}const concurrent=await Promise.all([api('query',{modelRef,query:{...query,id:'concurrent-a'}}),api('query',{modelRef,query:{...query,id:'concurrent-b'}})]);for(const r of concurrent)assert.equal(r.status,200);assert(peak-before<=268435456);return {workloads,sampledIncrementalParentRss:peak-before,concurrent:concurrent.map(r=>r.body.ref)};});
 await challenge('suspended-and-revised-source-invalidation',{},'Suspension revokes earlier rights even after reactivation; fresh fit binds new rights before independent source correction challenge',async()=>{assert.equal((await api('validate',{modelRef})).body.status,'CURRENT');await admin!.query("UPDATE finnor_os.users SET status='suspended' WHERE id=$1",[actor]);const suspended=await api('query',{modelRef,query});assert(suspended.status>=400);await admin!.query("UPDATE finnor_os.users SET status='active' WHERE id=$1",[actor]);const restoredOld=await api('validate',{modelRef});assert.equal(restoredOld.body.status,'INVALIDATED');const refreshed=await api('refit',{request,priorRef:modelRef});assert.equal(refreshed.body.status,'FITTED');model=refreshed.body.model;modelRef=model.ref;assert.equal((await api('validate',{modelRef})).body.status,'CURRENT');await restateMetricObservation(ctx,{priorObservationId:observationIds['revenue:127'],expectedVersion:1,replacement:{value:{type:'number',value:'1.5'},evidence}});const changed=await api('query',{modelRef,query});assert(changed.status>=400);return {suspended,restoredOld,refreshed:refreshed.body.model.ref,changed};});
 await challenge('no-consequences-and-retained-failures',{},'S3 produces H1 references only, zero external effects/receipts; all prepared records unadmitted',async()=>{const result=await withTenantTransaction(tenant,{userId:actor,readOnly:true},(_db,c)=>c.query('SELECT (SELECT count(*) FROM finnor_os.business_effects WHERE tenant_id=$1)::int effects,(SELECT count(*) FROM finnor_os.decision_receipts WHERE tenant_id=$1)::int receipts',[tenant]));assert.equal(result.rows[0].effects,0);assert.equal(result.rows[0].receipts,0);return result.rows[0];});
}catch(e){cases.push({id:'setup-or-unhandled',input:{},expected:'All preregistered cases execute, no hidden skips',status:'FAIL',observed:e instanceof Error?{message:e.message,stack:e.stack}:String(e)});}finally{await save();await closePool().catch(()=>undefined);await admin?.end().catch(()=>undefined);await postgres.stop().catch(()=>undefined);await rm(dir,{recursive:true,force:true});}
console.log(JSON.stringify({output,passed:cases.filter(x=>x.status==='PASS').length,failed:cases.filter(x=>x.status==='FAIL').length}));if(cases.some(x=>x.status==='FAIL'))process.exit(1);
