import {spawnSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {OfficePackage,NS,children,descendants,textContent,sha256} from '@finnor/ooxml';
import {parseWorkbook} from '@finnor/spreadsheet-ir';
import {EvidenceSourceSchema,FinancialSemanticsSchema,type EvidenceSource,type FinancialRow,type EvidenceWitness} from '@finnor/shared-types';
import {canonicalExact,exactScale} from './exact';
type Source=Extract<EvidenceSource,{kind:'artifact'}>;
export interface DocumentPayload {bytes:string;source:Source;digest:string;version:string}
export interface DocumentExtraction {rows:FinancialRow[];witnesses:EvidenceWitness[];reasons:string[];sourceCounts:Array<{id:string;expected:number;actual:number}>;nativeOperations:unknown[]}
const HEADERS=['entityId','metricKey','value','periodStart','periodEnd','currencyCode','frequency','unit','calendar','consolidation','instrument','scale','sign'] as const;
export async function parseDocumentPayload(input:DocumentPayload):Promise<DocumentExtraction>{
 const source=EvidenceSourceSchema.parse(input.source);if(source.kind!=='artifact')throw Error('ARTIFACT_SOURCE_REQUIRED');const bytes=Buffer.from(input.bytes,'base64');if(bytes.length>6_000_000||sha256(bytes)!==input.digest)throw Error('DOCUMENT_BYTES_DIGEST_OR_BOUND_MISMATCH');
 const rows:FinancialRow[]=[],witnesses:EvidenceWitness[]=[],reasons:string[]=[],nativeOperations:unknown[]=[];let allRecords=0;let records:Array<{values:Record<string,string>;anchor:EvidenceWitness['anchor'];formula:boolean;rawValue:string;ordinal:number}>=[];
 if(source.layout.format==='xlsx'){
  if(bytes.readUInt32LE(0)!==0x04034b50)throw Error('XLSX_MAGIC_REQUIRED');const pkg=new OfficePackage(bytes),ir=parseWorkbook(pkg);const sheet=ir.sheets.find(s=>s.name===source.layout.sheet);if(!sheet)throw Error('REGISTERED_XLSX_SHEET_UNAVAILABLE');
  const stringsPart=pkg.relationships(pkg.mainPart).find(r=>r.type.endsWith('/sharedStrings'))?.resolved;const strings=stringsPart?children(pkg.xml(stringsPart),'si',NS.sheet).map(n=>descendants(n,'t',NS.sheet).map(textContent).join('')):[];
  const cells=new Map<string,{value:string;formula:boolean}>();for(const c of descendants(pkg.xml(sheet.part),'c',NS.sheet)){const address=c.attrs.r;if(!address)throw Error('XLSX_CELL_ADDRESS_UNAVAILABLE');const v=children(c,'v',NS.sheet)[0]?.text??'';let value=v;if(c.attrs.t==='inlineStr')value=descendants(c,'t',NS.sheet).map(textContent).join('');else if(c.attrs.t==='s'){const i=Number(v);if(!Number.isInteger(i)||!strings[i])throw Error('XLSX_SHARED_STRING_UNAVAILABLE');value=strings[i]!;}cells.set(address,{value,formula:children(c,'f',NS.sheet).length>0});}
  const columns=source.layout.columns;if(!columns)throw Error('REGISTERED_XLSX_COLUMN_LAYOUT_REQUIRED');for(const h of HEADERS){if(!/^[A-Z]{1,3}$/.test(columns[h]))throw Error('XLSX_COLUMN_ADDRESS_REQUIRED');const header=cells.get(columns[h]+source.layout.headerRow);if(header?.value!==h||header.formula)throw Error('XLSX_HEADER_SCHEMA_MISMATCH');}
  const numbers=[...new Set([...cells.keys()].map(a=>Number(a.replace(/^[A-Z]+/,''))).filter(n=>n>source.layout.headerRow))].sort((a,b)=>a-b);if(numbers.length>1000)throw Error('XLSX_SOURCE_ROW_BOUND');
  for(const ordinal of numbers){const values=Object.fromEntries(HEADERS.map(h=>[h,cells.get(columns[h]+ordinal)?.value??'']));if(HEADERS.every(h=>!values[h]))continue;allRecords++;const material=cells.get(columns.value+ordinal);records.push({values,anchor:{sheet:sheet.name,cell:columns.value+ordinal},formula:HEADERS.some(h=>cells.get(columns[h]+ordinal)?.formula),rawValue:material?.value??'',ordinal});}
 }else if(source.layout.format==='pdf'){
  if(bytes.subarray(0,5).toString()!=='%PDF-')throw Error('PDF_MAGIC_REQUIRED');const {interpret}=await import('@finnor/artifacts');const ir=await interpret(bytes,{timeoutMs:25000});if(ir.nodes.some(n=>n.data.status!=='TEXT_AVAILABLE'))reasons.push('PDF_OCR_REQUIRED_OR_PARTIAL_TEXT');let headerSeen=false;
  for(const page of ir.nodes){const pageNum=Number(page.data.page),text=String(page.data.text??'');for(const quote of text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)){if(quote===HEADERS.join('|')){headerSeen=true;continue;}if(/^--\s*\d+\s+of\s+\d+\s*--$/.test(quote))continue;if(!headerSeen||quote.split('|').length!==HEADERS.length){reasons.push('PDF_UNPARSED_MATERIAL_TEXT');continue;}const values=Object.fromEntries(HEADERS.map((h,i)=>[h,quote.split('|')[i]!.trim()]));allRecords++;records.push({values,anchor:{page:pageNum,quote},formula:false,rawValue:values.value!,ordinal:allRecords});}}
  if(!headerSeen)throw Error('PDF_REGISTERED_TABLE_HEADER_UNAVAILABLE');
 }else{
  const png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpeg=bytes[0]===255&&bytes[1]===216;if(!png&&!jpeg)throw Error('SUPPORTED_IMAGE_MAGIC_REQUIRED');
  const executable=process.env.FINNOR_P4_OCR_BINARY,expected=process.env.FINNOR_P4_OCR_SHA256;if(!executable||!expected)throw Error('ACTUAL_IMAGE_OCR_RUNTIME_UNAVAILABLE');if(createHash('sha256').update(readFileSync(executable)).digest('hex')!==expected)throw Error('OCR_EXECUTABLE_DIGEST_MISMATCH');
  const result=spawnSync(executable,[],{input:bytes,timeout:20000,maxBuffer:1048576,env:{PATH:'/usr/bin:/bin',LANG:'en_US.UTF-8',NODE_ENV:'production'}});if(result.status!==0)throw Error('ACTUAL_IMAGE_OCR_FAILED');const parsed=JSON.parse(result.stdout.toString());nativeOperations.push({route:'APPLE_VISION_FIXED_NATIVE_OCR',binaryDigest:expected,usage:parsed.usage??null,costUSD:null,status:'LOCAL_COST_UNMETERED'});const lines=parsed.lines as Array<{text:string;confidence:number;region:number[]}>;if(!Array.isArray(lines)||lines.length>1000)throw Error('OCR_LINE_BOUND');
  let headerSeen=false;for(const line of lines.sort((a,b)=>a.region[1]!-b.region[1]!)){const quote=line.text.trim();if(quote.split('|').map(h=>h.trim().toLowerCase()).join('|')===HEADERS.map(h=>h.toLowerCase()).join('|')){headerSeen=true;continue;}if(!headerSeen||quote.split('|').length!==HEADERS.length){reasons.push('OCR_UNPARSED_MATERIAL_REGION');continue;}const values=Object.fromEntries(HEADERS.map((h,i)=>[h,quote.split('|')[i]!.trim()]));allRecords++;records.push({values,anchor:{page:1,quote,region:line.region},formula:false,rawValue:values.value!,ordinal:allRecords});if(line.confidence<0.95)reasons.push('OCR_LOW_CONFIDENCE_NOT_CALIBRATED');}
  if(!headerSeen)throw Error('OCR_REGISTERED_TABLE_HEADER_UNAVAILABLE');
 }
 for(const record of records){const v=record.values;if(HEADERS.some(h=>!v[h])){reasons.push('INCOMPLETE_TABULAR_ROW');continue;}if(record.formula){reasons.push('XLSX_MATERIAL_FORMULA_CACHE_UNVERIFIED');continue;}
  const explicitDate=(raw:string)=>/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T00:00:00.000Z':raw;
  const startText=FinancialSemanticsSchema.shape.periodStart.safeParse(explicitDate(v.periodStart!)),endText=FinancialSemanticsSchema.shape.periodEnd.safeParse(explicitDate(v.periodEnd!));
  if(!startText.success||!endText.success){reasons.push('DOCUMENT_PERIOD_INTERPRETATION_UNAVAILABLE');continue;}
  const start=new Date(startText.data),end=new Date(endText.data);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start.getTime()>end.getTime()){reasons.push('DOCUMENT_PERIOD_INTERPRETATION_UNAVAILABLE');continue;}
  const parsed=FinancialSemanticsSchema.safeParse({entityType:source.subject.entityType,entityId:v.entityId,periodStart:start.toISOString(),periodEnd:end.toISOString(),unit:v.unit,currencyCode:v.currencyCode==='NONE'?null:v.currencyCode,frequency:v.frequency,calendar:v.calendar,consolidation:v.consolidation,instrument:v.instrument,scale:v.scale,sign:v.sign});if(!parsed.success){reasons.push('DOCUMENT_FINANCIAL_SEMANTICS_OR_IDENTITY_INTERPRETATION_UNAVAILABLE');continue;}const semantics=parsed.data;
  if(semantics.entityId!==source.subject.entityId||v.metricKey!==source.metricKey||semantics.periodStart!==source.periodStart||semantics.periodEnd!==source.periodEnd)continue;
  if(semantics.unit!==source.unit||semantics.currencyCode!==source.currencyCode||semantics.frequency!==source.frequency||semantics.calendar!==source.calendar||semantics.consolidation!==source.consolidation||semantics.instrument!==source.instrument||semantics.scale!==source.scale||semantics.sign!==source.sign){reasons.push('DOCUMENT_FINANCIAL_SEMANTICS_MISMATCH');continue;}
  const value=exactScale(canonicalExact(v.value!),semantics.scale,semantics.sign),normalized={...semantics,scale:'1' as const,sign:'AS_RECORDED' as const};const id=source.layout.format+':'+input.version+':'+record.ordinal+':value';
  const witness:EvidenceWitness={id,sourceKind:source.layout.format,owner:'S1_BOUND_DOCUMENT_VERSION',recordId:source.documentId,version:input.version,contentDigest:input.digest,field:'value',rawValue:record.rawValue,anchor:record.anchor,semantics,modulePath:['DocumentVersion:immutable-bytes',source.layout.format==='xlsx'?'SpreadsheetIR:raw-xml-value':source.layout.format==='pdf'?'PDFParse:actual-page-text':'AppleVision:actual-image-regions',...(source.layout.format==='image'?['AppleVision:binary:'+process.env.FINNOR_P4_OCR_SHA256]:[]),'P4:registered-table-layout','P4:exact-scale-sign'],uncertainty:['SOURCE_ASSERTION_NOT_CANONICAL_TRUTH',...(source.layout.format==='image'?['OCR_CONFIDENCE_NOT_CALIBRATED']:[])]};
  witnesses.push(witness);rows.push({recordId:source.documentId+':'+record.ordinal,metricKey:v.metricKey!,value,semantics:normalized,witnessIds:[id],fields:{...v,value,entityType:normalized.entityType,scale:'1',sign:'AS_RECORDED'}});
 }
 if(!rows.length)reasons.push('EXACT_REGISTERED_DOCUMENT_VALUE_UNAVAILABLE');return {rows,witnesses,nativeOperations,reasons:[...new Set(reasons)],sourceCounts:[{id:'parsed-tabular-records',expected:allRecords,actual:records.length}]};
}
