import {createHash,randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {withTenantTransaction,type Db} from '@finnor/db';
import type {PoolClient} from 'pg';
import type {EvidenceDependency,EvidenceDerivation} from '@finnor/shared-types';
import {authorizeBeliefResources,authorizeBeliefSourceScopes} from '../enterprise-beliefs';
import {PeDomainError,type PeMutationContext,type PeWorldRootRef} from '../types';
export function stable(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stable).join(',')+']';return '{'+Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+stable(v)).join(',')+'}';}
export const sha=(value:unknown)=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:stable(value)).digest('hex');
export const principal=(ctx:PeMutationContext)=>ctx.auth.employeeId??ctx.auth.userId;
export const unavailable=()=>new PeDomainError('PE_ENTITY_NOT_FOUND','Evidence resource is unavailable in the authenticated scope');
export const tx=<T>(ctx:PeMutationContext,fn:(client:PoolClient,db:Db)=>Promise<T>,readOnly=false)=>withTenantTransaction(ctx.auth.tenantId,{userId:principal(ctx),readOnly},(db,client)=>fn(client,db));
export async function authorize(ctx:PeMutationContext,root:PeWorldRootRef,resources:Array<{type:string;id:string}>=[],sources:string[]=[]){try{const rights=await authorizeBeliefResources(ctx,[{type:root.entityType,id:root.entityId},...resources]);await authorizeBeliefSourceScopes(ctx,root,sources);return rights;}catch{throw unavailable();}}
export async function revisions(ctx:PeMutationContext,keys:string[],client?:PoolClient,lock=false):Promise<EvidenceDependency[]>{const unique=[...new Set(keys)].sort();const action=async(c:PoolClient)=>{if(lock)await c.query('INSERT INTO finnor_os.p4_source_revisions(tenant_id,key,revision) SELECT $1,k,0 FROM unnest($2::text[]) k ON CONFLICT DO NOTHING',[ctx.auth.tenantId,unique]);const rows=(await c.query<{key:string;revision:string}>('SELECT key,revision::text FROM finnor_os.p4_source_revisions WHERE tenant_id=$1 AND key=ANY($2::text[]) ORDER BY key'+(lock?' FOR UPDATE':''),[ctx.auth.tenantId,unique])).rows;const map=new Map(rows.map(r=>[r.key,Number(r.revision)]));return unique.map(key=>({key,revision:map.get(key)??0,nodeIds:[],digest:null}));};return client?action(client):tx(ctx,action,true);}
export function sameRevisions(a:EvidenceDependency[],b:EvidenceDependency[]):boolean{const byKey=new Map(b.map(d=>[d.key,d.revision]));return a.every(d=>byKey.get(d.key)===d.revision);}
export async function assertDependencies(ctx:PeMutationContext,dependencies:EvidenceDependency[],client?:PoolClient,lock=false){if(!sameRevisions(dependencies,await revisions(ctx,dependencies.map(d=>d.key),client,lock)))throw Error('SOURCE_RIGHTS_MEMBERSHIP_OR_WORK_CHANGED');}
const base=resolve(dirname(fileURLToPath(import.meta.url)),'../../../../..');
export const CODE_FILES=['contracts.ts','store.ts','exact.ts','operators.ts','sources.ts','documents.ts','documents-parser.ts','vision-ocr.m','backend.ts','native-child.mts','checks.ts','api.ts','worker.ts','consumer.ts'].map(p=>'finnor-os/packages/private-equity/src/evidence-execution/'+p).concat(['finnor-os/packages/shared-types/src/evidence-execution.ts','finnor-os/packages/private-equity/src/enterprise-beliefs.ts','finnor-os/packages/private-equity/src/world-state.ts','finnor-os/packages/authority/src/index.ts','finnor-os/packages/private-equity/src/underwriting-repository.ts','finnor-os/packages/underwriting/src/types.ts','finnor-os/packages/underwriting/src/compiler.ts','finnor-os/packages/underwriting/src/executor.ts','finnor-os/packages/underwriting/src/decimal.ts','finnor-os/packages/underwriting/src/canonical.ts','finnor-os/packages/spreadsheet-ir/src/formula.ts','finnor-os/apps/api/app/api/company-brain/[operation]/route.ts','finnor-os/packages/db/compute-governor.ts','finnor-os/packages/db/compute-contract.ts','finnor-os/apps/worker/src/queue.ts','finnor-os/packages/ooxml/src/index.ts','finnor-os/packages/spreadsheet-ir/src/index.ts','finnor-os/packages/artifacts/src/service.ts','package-lock.json','finnor-os/package-lock.json']);
CODE_FILES.push('finnor-os/packages/source-custody/index.cjs');
async function productionFiles(directory:string):Promise<string[]>{const found:string[]=[];for(const entry of await readdir(resolve(base,directory),{withFileTypes:true})){if(entry.name==='node_modules'||entry.name.startsWith('.'))continue;const path=directory+'/'+entry.name;if(entry.isDirectory())found.push(...await productionFiles(path));else if(/\.(?:ts|mts|m|sql)$/.test(entry.name)&&!entry.name.includes('.test.')||entry.name==='package.json')found.push(path);}return found;}
export async function currentCodeIdentity(){const paths=[...new Set([...CODE_FILES,...await productionFiles('finnor-os/packages')])].sort();const files=await Promise.all(paths.map(async path=>({path,sha256:sha(await readFile(resolve(base,path)))})));return {digest:sha({files,node:process.version,platform:process.platform,arch:process.arch}),files,node:process.version};}
// Pinned on actual module load, compared with current source before publication.
const loadedIdentity=currentCodeIdentity();
export async function codeIdentity(){const pinned=await loadedIdentity;if(pinned.digest!==(await currentCodeIdentity()).digest)throw Error('LOADED_RUNTIME_SOURCE_IDENTITY_CHANGED');return pinned;}
/** Real catalog identity, separate from source identity. Data corrections do not
 * change this fingerprint; column/index/trigger/policy changes do. */
export async function schemaIdentity(ctx:PeMutationContext){return tx(ctx,async c=>{const rows=(await c.query(`SELECT c.relname,c.relrowsecurity,c.relforcerowsecurity,c.relacl::text privileges,
 (SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull) ORDER BY a.attnum) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped) columns,
 (SELECT jsonb_agg(pg_get_indexdef(i.indexrelid) ORDER BY i.indexrelid::regclass::text) FROM pg_index i WHERE i.indrelid=c.oid) indexes,
 (SELECT jsonb_agg(jsonb_build_array(t.tgname,pg_get_triggerdef(t.oid),pg_get_functiondef(t.tgfoid)) ORDER BY t.tgname) FROM pg_trigger t WHERE t.tgrelid=c.oid AND NOT t.tgisinternal) triggers,
 (SELECT jsonb_agg(jsonb_build_array(p.polname,pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid=c.oid) policies
 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='finnor_os' AND c.relkind='r' ORDER BY c.relname`)).rows;return sha(rows);},true);}
export interface QueryRow {id:string;tenant_id:string;principal_id:string;root:PeWorldRootRef;work_id:string;work_input_id:string;work_input_digest:string;generation:number;status:string;derivation_id:string|null;request:import('@finnor/shared-types').EvidenceRequest;active_claim_token:string|null;active_claim_fence:number|null}
export async function query(ctx:PeMutationContext,id:string,lock=false,client?:PoolClient):Promise<QueryRow>{const action=async(c:PoolClient)=>{const r=(await c.query<QueryRow>('SELECT * FROM finnor_os.p4_queries WHERE tenant_id=$1 AND principal_id=$2 AND id=$3'+(lock?' FOR UPDATE':''),[ctx.auth.tenantId,principal(ctx),id])).rows[0];if(!r)throw unavailable();return r;};return client?action(client):tx(ctx,action,true);}
export async function event(ctx:PeMutationContext,queryId:string,attemptId:string,kind:string,body:unknown,client?:PoolClient){const action=(c:PoolClient)=>c.query('INSERT INTO finnor_os.p4_attempt_events(tenant_id,principal_id,query_id,attempt_id,kind,body) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[ctx.auth.tenantId,principal(ctx),queryId,attemptId,kind,stable(body)]);return client?action(client):tx(ctx,action);}
export async function storedDerivation(ctx:PeMutationContext,id:string):Promise<EvidenceDerivation>{return tx(ctx,async c=>{const row=(await c.query<{body:EvidenceDerivation;digest:string}>('SELECT body,digest FROM finnor_os.p4_derivations WHERE tenant_id=$1 AND principal_id=$2 AND id=$3',[ctx.auth.tenantId,principal(ctx),id])).rows[0];if(!row)throw unavailable();if(sha(row.body)!==row.digest)throw Error('IMMUTABLE_DERIVATION_DIGEST_MISMATCH');return row.body;},true);}
export async function currentDerivation(ctx:PeMutationContext,id:string):Promise<EvidenceDerivation>{const d=await storedDerivation(ctx,id);await authorize(ctx,d.beliefView.root as PeWorldRootRef,[{type:'work',id:d.work.id},...d.sourceHandles.filter(h=>h.source.kind==='artifact').map(h=>({type:'document',id:(h.source as Extract<typeof h.source,{kind:'artifact'}>).documentId}))]);
 if(d.witnesses.some(w=>w.sourceKind==='image')){const binary=process.env.FINNOR_P4_OCR_BINARY,expected=process.env.FINNOR_P4_OCR_SHA256;if(!binary||!expected||sha(await readFile(binary))!==expected||d.witnesses.some(w=>w.sourceKind==='image'&&!w.modulePath.includes('AppleVision:binary:'+expected)))throw Error('DERIVATION_OCR_RUNTIME_CHANGED');}
 const q=await query(ctx,d.queryId);if(q.derivation_id!==id||q.status!=='TESTED'||d.status!=='TESTED'||!d.result)throw Error('DERIVATION_NOT_CURRENT_COMPLETE_TESTED');if(d.code.digest!==(await codeIdentity()).digest)throw Error('DERIVATION_RUNTIME_CHANGED');if(d.code.schemaDigest!==await schemaIdentity(ctx))throw Error('DERIVATION_SCHEMA_CHANGED');await assertDependencies(ctx,d.invalidationKeys);for(const h of d.sourceHandles)if(h.source.kind!=='derivation')await authorize(ctx,h.source.subject as PeWorldRootRef);await authorize(ctx,d.beliefView.root as PeWorldRootRef,[{type:'work',id:d.work.id}]);return d;}
export const newId=()=>randomUUID();
