import {recordBusinessEvent} from '@finnor/data-platform';
import type {JobExecutionContext} from '../../../../apps/worker/src/queue';
import {EvidenceRequestSchema,type EvidenceDependency,type EvidenceDerivation,type EvidenceHandle} from '@finnor/shared-types';
import {loadEnterpriseBeliefView} from '../enterprise-beliefs';
import type {PeMutationContext} from '../types';
import {materializeHandle,loadHandle,type LoadedSource} from './sources';
import {nativeBackend,NativeFailure,type BackendReceipt} from './backend';
import type {NativeExecution} from './operators';
import {nodeCacheKeys,type ReusableNode} from './node-reuse';
import {independentChecks} from './checks';
import {assertDependencies,authorize,codeIdentity,event,newId,principal,query,revisions,sha,stable,tx,schemaIdentity,type QueryRow} from './store';
const predicate=(e:unknown)=>String((e as Error).message).match(/^[A-Z][A-Z0-9_]{0,159}$/)?.[0]??'NATIVE_OR_SOURCE_PREDICATE_UNPASSED';
export async function runEvidenceDerivationJob(payload:Record<string,unknown>,execution?:Readonly<JobExecutionContext>):Promise<void>{
 if(!execution||typeof payload.tenantId!=='string'||typeof payload.principalId!=='string'||typeof payload.queryId!=='string'||execution.protocolVersion!==1||execution.tenantId!==payload.tenantId)throw Error('ACTUAL_DURABLE_JOB_CLAIM_REQUIRED');
 const ctx:PeMutationContext={auth:{tenantId:payload.tenantId,userId:payload.principalId,employeeId:payload.principalId,role:'owner'},provenance:{sourceSystem:'P4:ordinary-native-worker',createdBy:payload.principalId}};
 const actor=await tx(ctx,async c=>(await c.query<{role:string;status:string}>('SELECT role,status FROM finnor_os.users WHERE tenant_id=$1 AND id=$2',[ctx.auth.tenantId,principal(ctx)])).rows[0],true);
 if(actor?.status!=='active'||actor.role!=='owner')throw Error('CURRENT_AUTHENTICATED_PRINCIPAL_UNAVAILABLE');
 const q=await query(ctx,payload.queryId);await authorize(ctx,q.root,[{type:'work',id:q.work_id}]);if(['TESTED','PARTIAL','FAILED','INVALIDATED','CANCELLED'].includes(q.status))return;
 const attemptId=newId(),started=Date.now(),request=EvidenceRequestSchema.parse(q.request);if(q.generation!==payload.generation)throw Error('QUERY_GENERATION_FENCED');
 if(request.mode!=='ordinary_disposable'||process.env.NODE_ENV==='production'||process.env.FINNOR_P4_PROFILE!=='ordinary_disposable')throw Error('PROTECTED_FUNDING_ADMISSION_AND_RUNTIME_BINDINGS_UNAVAILABLE');
 await tx(ctx,async c=>{const current=await query(ctx,q.id,true,c);const claimed=(await c.query('SELECT id FROM finnor_os.jobs WHERE id=$1 AND tenant_id=$2 AND status=\'running\' AND claim_token=$3 AND claim_fence=$4 AND protocol_version=1 FOR SHARE',[execution.jobId,ctx.auth.tenantId,execution.claimToken,execution.claimFence])).rows[0];if(!claimed||current.generation!==q.generation||['CANCELLED','INVALIDATED'].includes(current.status))throw Error('JOB_OR_QUERY_CLAIM_FENCED');await c.query("UPDATE finnor_os.p4_queries SET status='RUNNING',active_claim_token=$4,active_claim_fence=$5,updated_at=clock_timestamp() WHERE tenant_id=$1 AND principal_id=$2 AND id=$3",[ctx.auth.tenantId,principal(ctx),q.id,execution.claimToken,execution.claimFence]);const orphaned=(await c.query<{attempt_id:string;body:unknown}>("SELECT DISTINCT ON(e.attempt_id) e.attempt_id::text,e.body FROM finnor_os.p4_attempt_events e WHERE e.tenant_id=$1 AND e.principal_id=$2 AND e.query_id=$3 AND e.kind='STARTED' AND NOT EXISTS(SELECT 1 FROM finnor_os.p4_attempt_events f WHERE f.tenant_id=e.tenant_id AND f.query_id=e.query_id AND f.attempt_id=e.attempt_id AND f.kind IN('FINISHED','FAILED','FENCED')) ORDER BY e.attempt_id,e.created_at DESC",[ctx.auth.tenantId,principal(ctx),q.id])).rows;for(const lost of orphaned)await event(ctx,q.id,lost.attempt_id,'FAILED',{predicate:'PRIOR_DURABLE_JOB_CLAIM_LOST',lastObserved:lost.body,finalPhysicalCostUnknown:true,costUSD:null,usableResult:false},c);await event(ctx,q.id,attemptId,'STARTED',{jobId:execution.jobId,deliveryAttemptId:execution.deliveryAttemptId,claimFence:execution.claimFence,workerId:execution.workerId,generation:q.generation,costUSD:null},c);});
 let loaded:Array<{handle:EvidenceHandle;loaded:LoadedSource}>=[],receipt:BackendReceipt|null=null,native:NativeExecution|null=null,failure:string|null=null,checks:EvidenceDerivation['independentChecks']=[];
 const schemaDigest=await schemaIdentity(ctx),executionCode=await codeIdentity();let view=await loadEnterpriseBeliefView(ctx,{root:q.root,validAt:request.validAt,knowledgeAt:request.knowledgeAt,maxClaims:1000});let dependencies:EvidenceDependency[]=[];
 try{
  for(const input of request.inputs){if(Date.now()-started>(request.limits?.deadlineMs??30000))throw Error('NATIVE_DEADLINE_EXCEEDED');const handle=await loadHandle(ctx,input.handleId,q.root);const source=await materializeHandle(ctx,handle);loaded.push({handle,loaded:source});}
  const map=new Map<string,EvidenceDependency>();for(const entry of loaded)for(const d of entry.handle.dependencies){const prior=map.get(d.key);if(prior&&prior.revision!==d.revision)throw Error('MULTI_SOURCE_CUT_CHANGED');map.set(d.key,{...d,nodeIds:[...new Set([...(prior?.nodeIds??[]),...request.program.nodes.filter(n=>n.op==='source'&&n.inputId===entry.handle.inputId).map(n=>n.id)])]});}
  const workDeps=await revisions(ctx,['work-inputs:'+q.work_id]);for(const d of workDeps)map.set(d.key,{...d,digest:q.work_input_digest,nodeIds:request.program.nodes.map(n=>n.id)});dependencies=[...map.values()];
  const workInput=await tx(ctx,async c=>(await c.query<{id:string;body:unknown}>('SELECT id::text,to_jsonb(w) body FROM finnor_os.work_inputs w WHERE tenant_id=$1 AND work_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1',[ctx.auth.tenantId,q.work_id])).rows[0],true);if(workInput?.id!==q.work_input_id||sha(workInput.body)!==q.work_input_digest)throw Error('EXACT_WORK_REVISION_CHANGED');
  if(loaded.flatMap(e=>e.loaded.rows).length>(request.limits?.maxRows??1000))throw Error('COMBINED_SELECTED_SOURCE_ROW_BOUND');
  if(loaded.some(e=>e.loaded.coverage.status!=='COMPLETE'))throw Error('SELECTED_SOURCE_COVERAGE_PARTIAL');
  const deadline=request.limits?.deadlineMs??30000,remaining=deadline-(Date.now()-started);if(remaining<=0)throw Error('NATIVE_DEADLINE_EXCEEDED');
  const namespace=sha({tenant:ctx.auth.tenantId,principal:principal(ctx),root:q.root,code:executionCode.digest,schemaDigest,maxRows:request.limits?.maxRows??1000,maxBytes:request.limits?.maxBytes??8388608});
  const sourceIdentities=Object.fromEntries(loaded.map(e=>[e.handle.inputId,sha({selector:e.handle.source,validAt:e.handle.validAt,selectedDigest:e.handle.digest,dependencies:e.handle.dependencies.map(d=>({key:d.key,revision:d.revision,digest:d.digest}))})]));
  const cacheKeys=nodeCacheKeys(request.program,sourceIdentities,namespace),reusable:Record<string,ReusableNode>={};
  if(process.env.FINNOR_P4_DISABLE_NODE_REUSE!=='1'){
   const cached=await tx(ctx,async c=>(await c.query<{cache_key:string;node_id:string;derivation_id:string;body:import('@finnor/shared-types').EvidenceValue;digest:string}>(`SELECT DISTINCT ON(n.cache_key) n.cache_key,n.node_id,n.derivation_id::text,n.body,n.digest FROM finnor_os.p4_nodes n JOIN finnor_os.p4_derivations d ON d.tenant_id=n.tenant_id AND d.principal_id=n.principal_id AND d.id=n.derivation_id WHERE n.tenant_id=$1 AND n.principal_id=$2 AND n.cache_key=ANY($3::text[]) AND d.body->>'status'='TESTED' ORDER BY n.cache_key,d.created_at DESC LIMIT 64`,[ctx.auth.tenantId,principal(ctx),Object.values(cacheKeys)])).rows,true);
   let cacheBytes=0;for(const old of cached){if(sha(old.body)!==old.digest)throw Error('IMMUTABLE_NODE_CACHE_DIGEST_MISMATCH');const size=Buffer.byteLength(stable(old.body));if(cacheBytes+size>(request.limits?.maxBytes??8388608)/2)continue;cacheBytes+=size;reusable[old.cache_key]={value:old.body,digest:old.digest,originDerivationId:old.derivation_id,originNodeId:old.node_id};}
  }
  const result=await nativeBackend<NativeExecution>(ctx.auth.tenantId,'program',{program:request.program,sources:Object.fromEntries(loaded.map(e=>[e.handle.inputId,e.loaded.rows])),maxRows:request.limits?.maxRows??1000,maxBytes:request.limits?.maxBytes??8388608,cacheKeys,reusable},deadline-(Date.now()-started),async()=>{const current=await query(ctx,q.id);return current.status!=='RUNNING'||current.generation!==q.generation||current.active_claim_token!==execution.claimToken;},r=>event(ctx,q.id,attemptId,'STARTED',{phase:'NATIVE_STARTED',receipt:r,deliveryAttemptId:execution.deliveryAttemptId}));native=result.data;receipt=result.receipt;
  checks=await independentChecks(ctx,request.program,loaded,native);if(Date.now()-started>(request.limits?.deadlineMs??30000))throw Error('NATIVE_DEADLINE_EXCEEDED');if(checks.some(c=>c.status==='FAIL'))throw Error('INDEPENDENT_NUMERIC_SEMANTIC_OR_COVERAGE_CHECK_FAILED');
 }catch(error){failure=predicate(error);if(error instanceof NativeFailure)receipt=error.receipt;}
 try{await authorize(ctx,q.root,[{type:'work',id:q.work_id}]);for(const entry of loaded)if(entry.handle.source.kind!=='derivation')await authorize(ctx,entry.handle.source.subject as any,entry.handle.source.kind==='artifact'?[{type:'document',id:entry.handle.source.documentId}]:[]);}catch{await tx(ctx,async c=>{await event(ctx,q.id,attemptId,'FAILED',{predicate:'RIGHTS_REVOKED_AFTER_NATIVE_EXECUTION',receipt,costUSD:null,usableResult:false},c);await c.query("UPDATE finnor_os.p4_queries SET status='INVALIDATED' WHERE tenant_id=$1 AND principal_id=$2 AND id=$3 AND status='RUNNING' AND active_claim_token=$4",[ctx.auth.tenantId,principal(ctx),q.id,execution.claimToken]);});return;}
 if(schemaDigest!==await schemaIdentity(ctx))failure='SCHEMA_CHANGED_DURING_EXECUTION';const code=await codeIdentity();const attempts=await tx(ctx,async c=>{const a=(await c.query<{attempt_id:string;body:any}>("SELECT attempt_id::text,body FROM finnor_os.p4_attempt_events WHERE tenant_id=$1 AND principal_id=$2 AND query_id=$3 AND (kind='STARTED' OR body->>'finalPhysicalCostUnknown'='true')",[ctx.auth.tenantId,principal(ctx),q.id])).rows;return {count:new Set(a.map(x=>x.attempt_id)).size,unknown:[...new Set(a.filter(x=>x.body.finalPhysicalCostUnknown).map(x=>x.attempt_id))]};},true);const invocations=[...loaded.flatMap(e=>e.handle.acquisitionInvocations??[]),...loaded.flatMap(e=>e.loaded.nativeInvocations),...(receipt?[receipt]:[])];let status:EvidenceDerivation['status']=failure?(failure.includes('COVERAGE_PARTIAL')?'PARTIAL':'FAILED'):'TESTED';
 if(!dependencies.length)dependencies=(await revisions(ctx,['rights:tenant','work-inputs:'+q.work_id])).map(d=>({...d,nodeIds:request.program.nodes.map(n=>n.id)}));
 const witnesses=[...new Map(loaded.flatMap(e=>e.loaded.witnesses).map(w=>[w.id,{...w,modulePath:[...w.modulePath,...request.program.nodes.filter(n=>native?.nodes[n.id]?.witnessIds.includes(w.id)).map(n=>'P4:node:'+n.id)]}])).values()];
 const d:EvidenceDerivation={schema:'finnor.evidence-derivation.v1',id:newId(),queryId:q.id,generation:q.generation,tenantId:ctx.auth.tenantId,principalId:principal(ctx),sharing:{scope:'PRINCIPAL',policy:'CURRENT_S1_AUTHORIZATION'},rights:view.rights,work:{id:q.work_id,revision:q.work_input_id,inputDigest:q.work_input_digest},mandate:null,
 parents:loaded.filter(e=>e.handle.source.kind==='derivation').map(e=>(e.handle.source as Extract<EvidenceHandle['source'],{kind:'derivation'}>).derivationId),inputsDigest:sha(loaded.map(e=>({handle:e.handle.id,digest:e.handle.digest}))),validAt:view.validAt,knowledgeAt:view.knowledgeAt,
 code:{version:'p4-native-v1',digest:code.digest,schemaDigest},capability:{kind:'BOUNDED_FINANCIAL_DERIVATION',admission:null},runtime:{node:process.version,imageDigest:null,fabricInvocationId:receipt?.invocationId??null,workerId:execution.workerId,jobId:execution.jobId,deliveryAttemptId:execution.deliveryAttemptId,claimFence:execution.claimFence,childPid:receipt?.childPid??null,leases:receipt?.leases??[]},
 domain:{entityScope:[...new Set(loaded.flatMap(e=>e.loaded.rows.map(r=>r.semantics.entityType+':'+r.semantics.entityId)))],financialSemantics:'OWNER_RECORDED_AND_EXPLICIT_TABULAR',horizon:'H0',businessTruthCertified:false},dependencyRefs:dependencies.map(d=>d.key+':'+d.revision),
 costs:{wallMs:Date.now()-started,cpuMicros:receipt?.cpuMicros??null,peakRSSBytes:receipt?.peakRSSBytes??null,inputBytes:receipt?.inputBytes??0,outputBytes:receipt?.outputBytes??0,modelCalls:0,usd:null,status:'LOCAL_COST_UNMETERED',attempts:attempts.count,nativeInvocations:invocations,unreconciledAttemptIds:attempts.unknown},status,admission:null,funding:null,unavailableBindings:['S4_ECONOMIC_MANDATE','S5_PROTECTED_FUNDING','S8_CAPABILITY_ADMISSION','ATTESTED_RUNTIME_IMAGE','BILLING_RECONCILIATION','INDEPENDENT_ADMISSION_AUTHORITY'],
 recomputation:{mode:process.env.FINNOR_P4_DISABLE_NODE_REUSE==='1'?'FULL':'INCREMENTAL',nodes:native?.recomputation??[]},beliefView:view,queryProgram:request.program,sourceHandles:loaded.map(e=>e.handle),result:failure?null:{outputs:native!.outputs,digest:sha(native!.outputs)},witnesses,coverage:{status:failure?'PARTIAL':'COMPLETE_SELECTED_UNIVERSE',globalAbsenceClaimsPermitted:false,reasons:[...new Set(loaded.flatMap(e=>e.loaded.coverage.reasons)),...view.coverage.omittedScope,...(failure?[failure]:[])]},contradictions:loaded.flatMap(e=>e.loaded.contradictions),invalidationKeys:dependencies,independentChecks:checks,failure:failure?{predicate:failure,detail:'No material output is usable for this failed predicate.'}:null};
 try{await tx(ctx,async (c,db)=>{await assertDependencies(ctx,dependencies,c,true);const current=await query(ctx,q.id,true,c);const claim=(await c.query('SELECT id FROM finnor_os.jobs WHERE id=$1 AND tenant_id=$2 AND status=\'running\' AND claim_token=$3 AND claim_fence=$4 FOR UPDATE',[execution.jobId,ctx.auth.tenantId,execution.claimToken,execution.claimFence])).rows[0];if(!claim||current.generation!==q.generation||current.active_claim_token!==execution.claimToken||current.status!=='RUNNING')throw Error('PUBLICATION_JOB_OR_QUERY_FENCED');
   await c.query('INSERT INTO finnor_os.p4_runtime_manifests(tenant_id,principal_id,digest,body) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT DO NOTHING',[d.tenantId,d.principalId,code.digest,stable(code)]);
   await c.query('INSERT INTO finnor_os.p4_derivations(id,tenant_id,principal_id,query_id,generation,body,digest) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)',[d.id,d.tenantId,d.principalId,d.queryId,d.generation,stable(d),sha(d)]);
   for(const dep of dependencies)await c.query('INSERT INTO finnor_os.p4_dependencies(tenant_id,principal_id,derivation_id,key,revision,node_ids,digest) VALUES($1,$2,$3,$4,$5,$6,$7)',[d.tenantId,d.principalId,d.id,dep.key,dep.revision,dep.nodeIds,dep.digest]);
   for(const [id,node] of Object.entries(native?.nodes??{}))await c.query('INSERT INTO finnor_os.p4_nodes(tenant_id,principal_id,derivation_id,node_id,cache_key,body,digest) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)',[d.tenantId,d.principalId,d.id,id,native!.recomputation.find(n=>n.id===id)!.cacheKey,stable(node),sha(node)]);
   for(const w of witnesses)await c.query('INSERT INTO finnor_os.p4_witnesses(tenant_id,principal_id,derivation_id,witness_id,body,digest) VALUES($1,$2,$3,$4,$5::jsonb,$6)',[d.tenantId,d.principalId,d.id,w.id,stable(w),sha(w)]);
   for(const check of checks)await c.query('INSERT INTO finnor_os.p4_checks(tenant_id,principal_id,derivation_id,check_id,body) VALUES($1,$2,$3,$4,$5::jsonb)',[d.tenantId,d.principalId,d.id,check.id,stable(check)]);
   if(!failure&&native?.recomputation.some(n=>n.state==='KEPT'))await event(ctx,q.id,attemptId,'KEPT_VALIDITY',{derivationId:d.id,envelopeRebound:true,workRevision:d.work.revision,currentDependencyDigest:sha(dependencies),nodes:native.recomputation.filter(n=>n.state==='KEPT')},c);
   await c.query('UPDATE finnor_os.p4_queries SET status=$4,derivation_id=$5,updated_at=clock_timestamp() WHERE tenant_id=$1 AND principal_id=$2 AND id=$3',[d.tenantId,d.principalId,q.id,d.status,d.id]);await recordBusinessEvent(db,{tenantId:d.tenantId,entityType:'p4_evidence_derivation',entityId:d.id,eventType:'p4_evidence_derivation_recorded',payload:{queryId:d.queryId,workId:d.work.id,workRevision:d.work.revision,derivationId:d.id,status:d.status,resultDigest:d.result?.digest??null,dependencyDigest:sha(dependencies),capabilityAdmission:null,costStatus:d.costs.status},source:'@finnor/private-equity'});await event(ctx,q.id,attemptId,failure?'FAILED':'FINISHED',{derivationId:d.id,status:d.status,receipt,runtimeManifest:{digest:code.digest,fileCount:code.files.length},costs:d.costs,failure:d.failure},c);
  });
 }catch(error){await tx(ctx,async c=>{await event(ctx,q.id,attemptId,'FENCED',{predicate:predicate(error),receipt,computedResultDigest:d.result?.digest??null,usableResult:false,costs:d.costs},c);await c.query("UPDATE finnor_os.p4_queries SET status='INVALIDATED',updated_at=clock_timestamp() WHERE tenant_id=$1 AND principal_id=$2 AND id=$3 AND generation=$4 AND status='RUNNING' AND active_claim_token=$5",[d.tenantId,d.principalId,q.id,q.generation,execution.claimToken]);});}
}
