import {createHash} from 'node:crypto';
import {ECONOMIC_COST_CATEGORIES} from '../../packages/shared-types/src/economic-attribution';
const R=(id:string,owner='S2')=>({owner,id,version:'generated-source-v1',contentDigest:createHash('sha256').update(id).digest('hex')});
const era={registeredAt:'2020-01-01T00:00:00.000Z',assignmentAt:'2021-01-01T00:00:00.000Z',endpointAt:'2024-01-01T00:00:00.000Z',outcomeAccessNotBefore:'2024-01-01T00:00:00.000Z'};
export function economicFixture(n:number,effect:number,mask?:number,random?:()=>number){
 const weights=Array.from({length:n},(_,i)=>i===n-1?(1000000000000n-BigInt(n-1)*(1000000000000n/BigInt(n))).toString():(1000000000000n/BigInt(n)).toString()).map(s=>(Number(s)/1e12).toFixed(12));
 const estimand:any={schema:'finnor.outcome-estimand.v1',version:'s7-bounded-owner-value-v1',semanticOwner:'S7',key:'generated-itt-'+n,episodeId:'generated',mandateRef:R('mandate','BUSINESS_OWNER'),ownerBoundaryRef:R('owner','BUSINESS_OWNER'),ownershipWaterfallRef:R('waterfall','BUSINESS_OWNER'),populationRef:R('population'),currency:'USD',...era,horizonMonths:36,
 clusters:weights.map((weight,i)=>({id:'cluster-'+i,weight,openingWealth:'0',wealthSupport:{lower:'0',upper:'100'},sourceManifestRef:R('manifest-'+i,'FINANCIAL_SOURCE')})),controllers:['bau','finnor'].map(id=>({id,role:id==='bau'?'BUSINESS_AS_USUAL':'FINNOR',programmeRef:R('programme-'+id,'S4'),policyRefs:[R('policy-'+id,'S4')],interventionRefs:[R('intervention-'+id,'S3')],adaptationRuleRef:R('adapt-'+id,'S4')})),businessAsUsualId:'bau',assignment:{kind:'INDEPENDENT_CLUSTER_RANDOMIZATION',protocolRef:R('protocol'),probabilities:{bau:'0.5',finnor:'0.5'},independenceRef:R('independence'),exposureMappingRef:R('exposure'),noBetweenClusterInterferenceRef:R('no-interference')},discountSchedule:[{at:era.endpointAt,factor:'1'}],capitalCarryRef:R('carry','BUSINESS_OWNER'),valuationProtocol:{ref:R('valuation-protocol','BUSINESS_OWNER'),authorityRefs:[R('valuer','INDEPENDENT_VALUER')],methodRefs:[R('method','INDEPENDENT_VALUER')],independenceRef:R('value-independent','INDEPENDENT_VALUER'),conflictsBlindingRef:R('blinding','INDEPENDENT_VALUER'),maxAsOfAgeMs:86400000},analysis:{method:'BOUNDED_HT_HOEFFDING_V1',alpha:'0.05',registeredLooks:[era.endpointAt],minimumProbability:'0.1',powerRegistrationRef:R('power')},allocationRef:R('allocation','S5'),requiredSourceRefs:[],assumptions:['CONSISTENCY','NO_BETWEEN_CLUSTER_INTERFERENCE','ALIGNED_TIME_ZERO','BOUNDED_POTENTIAL_WEALTH','FIXED_ELIGIBLE_POPULATION'].map(id=>({id,meaning:id,status:'SUPPORTED',evidenceRefs:[R('assumption-'+id)]})),budgets:{maximumClusters:4096,maximumItemsPerCluster:256,maximumElapsedMs:30000,maximumInputBytes:8388608},correctionOf:null};
 const eref=R('estimand','S7'),assignments:any[]=[],accounting:any[]=[],truth:number[]=[],potential:any[]=[];
 for(let i=0;i<n;i++){const treated=mask===undefined?random!()<.5:((mask>>i)&1)===1;const controllerId=treated?'finnor':'bau';const base=45+(i%3)*3,delta=effect;const y=base+(treated?delta:0);truth.push(Number(weights[i])*delta);potential.push({clusterId:'cluster-'+i,bau:base,finnor:base+delta,assigned:controllerId});
 assignments.push({clusterId:'cluster-'+i,controllerId,assignedAt:era.assignmentAt,assignmentRef:R('assignment-'+i),protocolRef:estimand.assignment.protocolRef,stages:[{stage:i%4===0?'FAILED':'OBSERVED',ref:R('stage-'+i,'S6')}],actualExposureRefs:[]});
 const itemId='cash-'+i,residualId='residual-'+i;
 const items=[{canonicalId:itemId,sourceRef:R(itemId,'FINANCIAL_SOURCE'),ownerBoundaryRef:estimand.ownerBoundaryRef,currency:'USD',at:era.endpointAt,destination:'CASH_OWNER',amount:{lower:String(y),upper:String(y)},costCategory:null,embeddedIn:null,reconciliationRefs:[R('conservation-'+i,'FINANCIAL_SOURCE')]},{canonicalId:residualId,sourceRef:R(residualId,'INDEPENDENT_VALUER'),ownerBoundaryRef:estimand.ownerBoundaryRef,currency:'USD',at:era.endpointAt,destination:'RESIDUAL_EQUITY',amount:{lower:'0',upper:'0'},costCategory:null,embeddedIn:null,reconciliationRefs:[R('conservation-'+i,'FINANCIAL_SOURCE')]}];
 accounting.push({schema:'finnor.economic-accounting.v1',estimandRef:eref,clusterId:'cluster-'+i,controllerId,knowledgeAt:era.endpointAt,asOf:era.endpointAt,closedLoopDays:90,sourceManifestRef:estimand.clusters[i].sourceManifestRef,items,sourceTotals:items.map(v=>({sourceRef:v.sourceRef,destination:v.destination,itemIds:[v.canonicalId],total:v.amount})),costCoverage:ECONOMIC_COST_CATEGORIES.map(category=>({category,status:'COMPLETE',itemIds:[],zeroCostEvidenceRef:R('zero-'+category+'-'+i,'FINANCIAL_SOURCE')})),valuations:[{itemId:residualId,authorityRef:estimand.valuationProtocol.authorityRefs[0],methodRef:estimand.valuationProtocol.methodRefs[0],asOf:era.endpointAt,signedAssessmentRef:items[1]!.sourceRef,inputRefs:[R('value-input-'+i,'FINANCIAL_SOURCE')],ownershipDebtRef:estimand.ownershipWaterfallRef,independenceRef:estimand.valuationProtocol.independenceRef}],liabilityCoverageRef:R('liability-'+i,'FINANCIAL_SOURCE'),conservationRef:R('conservation-'+i,'FINANCIAL_SOURCE'),correctionOf:null});}
 const input:any={schema:'finnor.economic-assessment-request.v1',tenantId:'00000000-0000-4000-8000-000000000001',principalId:'00000000-0000-4000-8000-000000000002',estimand,estimandRef:eref,assessedAt:era.endpointAt,lookAt:era.endpointAt,assignments,accounting,evidence:[],priorAssessmentRef:null,computeCost:{amount:{lower:'0',upper:'0'},pricebookRef:R('generated-pricebook','FINANCIAL_SOURCE'),meteringRef:R('generated-meter','FINANCIAL_SOURCE')}};
 const refs=new Map<string,any>();function collect(v:any){if(v&&typeof v==='object'){if(typeof v.owner==='string'&&typeof v.contentDigest==='string'&&typeof v.version==='string'&&typeof v.id==='string')refs.set(v.id,v);for(const x of Object.values(v))collect(x);}}collect(input);input.evidence=[...refs.values()].map(ref=>({ref,status:'RESOLVED_AUTHENTICATED',tenantId:input.tenantId,knowledgeAt:era.registeredAt,protectedReceiptRef:R('receipt-'+ref.id,'S6'),signatureVerified:true,independent:true,sourceOrigin:'GENERATED_CHALLENGE',protectionDomain:'DISPOSABLE_TEST_AUTHORITY'}));return {input,truth:truth.reduce((a,b)=>a+b,0),potential};
}
