/** Preauthored independent known-potential-outcome statistical system challenge.
 * Supplied resolution descriptors isolate inference; owner E2E separately owns
 * their authentication. Generated episodes cannot qualify field H2. */
import {strict as assert} from 'node:assert';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import {ECONOMIC_COST_CATEGORIES} from '../../packages/shared-types/src/economic-attribution';
const output=resolve(process.env.FINNOR_S7_EVIDENCE_DIR??'../scope-7/scope-evidence/statistical-'+Date.now());await mkdir(output,{recursive:true});
const sources=['packages/epistemic-runtime/src/economic-attribution.ts','packages/shared-types/src/economic-attribution.ts','scripts/s7/run-statistical-e2e.mts','scripts/s7/economic-fixtures.mts'];
const snapshots=()=>Promise.all(sources.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')})));
const before=await snapshots();const runtime=await import('../../packages/epistemic-runtime/src/economic-attribution');
import {economicFixture as fixture} from './economic-fixtures.mjs';
const R=(id:string,owner='S2')=>({owner,id,version:'generated-source-v1',contentDigest:createHash('sha256').update(id).digest('hex')});
const results:any[]=[];function prng(seed:number){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
async function record(id:string,fn:()=>any){try{results.push({id,status:'PASS',observed:await fn()});}catch(error){results.push({id,status:'FAIL',error:String(error)});}await writeFile(join(output,'partial-results.json'),JSON.stringify({results,before,qualification:'INCOMPLETE_RUN_UNTIL_FINAL_SOURCE_FREEZE'},null,2));console.log(JSON.stringify({id,status:results.at(-1).status,error:results.at(-1).error}));}
const covered=(a:any,truth:number)=>a.contrasts[0]!.interval&&Number(a.contrasts[0]!.interval!.lower)<=truth&&Number(a.contrasts[0]!.interval.upper)>=truth;
for(const effect of [0,30,-30])await record('exact-256-assignments-effect-'+effect,()=>{let coverage=0,meanScore=0;const rows=[];for(let mask=0;mask<256;mask++){const f=fixture(8,effect,mask),a=runtime.assessEconomicAttribution(f.input);assert.equal(a.population.excludedClusters,0);assert.equal(a.population.retainedClusters,8);assert.equal(a.contrasts[0]!.identification,'DESIGN_BASED_CONDITIONAL');assert.equal(a.supportedHorizon,'H1');const oracle=f.potential.reduce((total:number,row:any,i:number)=>total+Number(f.input.estimand.clusters[i].weight)*(row.assigned==='finnor'?row.finnor/.5:-row.bau/.5),0),score=(Number(a.contrasts[0]!.scoreInterval!.lower)+Number(a.contrasts[0]!.scoreInterval!.upper))/2;assert(Math.abs(score-oracle)<1e-9,'Independent assignment-score oracle disagreed');meanScore+=score;coverage+=covered(a,f.truth)?1:0;rows.push({mask,interval:a.contrasts[0]!.interval,truth:f.truth,score,independentScore:oracle});}assert(Math.abs(meanScore/256-effect)<1e-9);assert(coverage/256>=.95);return {coverage:coverage/256,meanScore:meanScore/256,exactAssignmentBias:meanScore/256-effect,assignments:256,rows};});
await record('observational-confounding-never-becomes-positive-credit',()=>{const f=fixture(8,0,255);f.input.estimand.assignment={kind:'OBSERVATIONAL_UNIDENTIFIED',protocolRef:{...f.input.estimand.assignment.protocolRef,id:'observational'},exposureMappingRef:f.input.estimand.assignment.exposureMappingRef,reasons:['TREATMENT_SELECTED_BY_HIDDEN_U']};f.input.assignments.forEach((a:any)=>a.protocolRef=f.input.estimand.assignment.protocolRef);const a=runtime.assessEconomicAttribution(f.input);assert.equal(a.contrasts[0]!.identification,'UNIDENTIFIED');assert(Number(a.contrasts[0]!.interval!.lower)<=0);return a;});
await record('informative-missingness-retains-adverse-cohort',()=>{const f=fixture(8,-30,15);f.input.accounting=f.input.accounting.slice(4);const a=runtime.assessEconomicAttribution(f.input);assert.equal(a.population.retainedClusters,8);assert(!a.completeCosts);assert(covered(a,f.truth));return a;});
await record('financial-conservation-independent-statement-oracle',()=>{const f=fixture(8,0,15),s=f.input.accounting[0],e=f.input.estimand;e.clusters[0].openingWealth='1000';const prototype=s.items[0];s.items=[['cash','CASH_OWNER','200','200'],['capital','ADDITIONAL_CAPITAL','50','50'],['equity','RESIDUAL_EQUITY','1100','1140'],['liability','EXTRA_LIABILITY','10','20'],['cost','COST_ONCE','15','25']].map(([canonicalId,destination,lower,upper])=>({...prototype,canonicalId,destination,sourceRef:R(canonicalId!,destination==='RESIDUAL_EQUITY'?'INDEPENDENT_VALUER':'FINANCIAL_SOURCE'),amount:{lower,upper},costCategory:destination==='COST_ONCE'?'INTERVENTION':null}));s.sourceTotals=s.items.map((v:any)=>({sourceRef:v.sourceRef,destination:v.destination,itemIds:[v.canonicalId],total:v.amount}));s.costCoverage[0].itemIds=['cost'];s.costCoverage[0].zeroCostEvidenceRef=null;s.valuations[0].itemId='equity';s.valuations[0].signedAssessmentRef=s.items[2].sourceRef;const refs:any[]=[];const add=(v:any)=>{if(v&&typeof v==='object'){if(v.owner&&v.contentDigest&&v.id)refs.push(v);for(const x of Object.values(v))add(x);}};add(s);for(const ref of refs)if(!f.input.evidence.some((v:any)=>v.ref.id===ref.id))f.input.evidence.push({...f.input.evidence[0],ref});const a=runtime.reconcileEconomicAccounting(e,s,f.input.evidence,f.input.tenantId);assert.deepEqual(a.wealth,{lower:'205',upper:'265'});s.items[0].amount={lower:'0',upper:'0'};s.items[2].amount={lower:'1300',upper:'1340'};s.sourceTotals=s.items.map((v:any)=>({sourceRef:v.sourceRef,destination:v.destination,itemIds:[v.canonicalId],total:v.amount}));const b=runtime.reconcileEconomicAccounting(e,s,f.input.evidence,f.input.tenantId);assert.deepEqual(b.wealth,a.wealth);return {distributed:a,retained:b,oracle:'independent frozen equation [205,265]'};});
await record('interacting-contingent-regime-is-not-additive-action-credit',()=>{const f=fixture(8,30,15);f.input.assignments.forEach((a:any,i:number)=>a.stages=[{stage:i%2?'OVERRIDDEN':'FAILED',ref:R('joint-stage-'+i,'S6')}]);const a=runtime.assessEconomicAttribution(f.input);assert(covered(a,f.truth));assert.equal(a.population.excludedClusters,0);assert.equal(a.aggregateCredit.actionCreditsIdentified,false);return {truth:f.truth,assessment:a,oracle:'Complete two-decision regime effect +30; within-cluster interaction retained, no individual action effect identified'};});
await record('unsupported-interference-and-horizon-forgery-cannot-earn-H2',()=>{const f=fixture(8,30,15);f.input.estimand.assumptions.find((a:any)=>a.id==='NO_BETWEEN_CLUSTER_INTERFERENCE').status='UNKNOWN';const a=runtime.assessEconomicAttribution(f.input);assert.equal(a.contrasts[0]!.identification,'UNIDENTIFIED');assert.equal(a.supportedHorizon,'H1');assert.equal(a.population.retainedClusters,8);return a;});
await record('registered-looks-wide-support-and-budget-refusals',()=>{const f=fixture(8,0,15);assert.throws(()=>runtime.assessEconomicAttribution({...f.input,lookAt:'2023-12-01T00:00:00.000Z'}),/UNREGISTERED_OR_EARLY_LOOK/);f.input.estimand.budgets.maximumInputBytes=1024;assert.throws(()=>runtime.assessEconomicAttribution(f.input),/INPUT_BUDGET_EXCEEDED/);return {unregisteredLookRefused:true,inputExhaustionRefused:true};});
await record('self-value-missing-cost-and-duplicate-items-do-not-become-wealth',()=>{const f=fixture(8,30,15);for(const v of f.input.evidence)if(v.ref.owner==='INDEPENDENT_VALUER')v.independent=false;let a=runtime.assessEconomicAttribution(f.input);assert(a.accounting.every((v:any)=>v.wealth===null));assert.equal(a.supportedHorizon,'H1');const g=fixture(8,30,15);g.input.accounting[0].costCoverage=g.input.accounting[0].costCoverage.filter((c:any)=>c.category!=='HUMAN');a=runtime.assessEconomicAttribution(g.input);assert.equal(a.completeCosts,false);assert.equal(a.accounting[0]!.wealth,null);const h=fixture(8,30,15);h.input.accounting[0].items.push(structuredClone(h.input.accounting[0].items[0]));assert.throws(()=>runtime.assessEconomicAttribution(h.input),/DUPLICATE_ECONOMIC_ITEM/);return {selfValuationMissing:true,missingHumanCostPropagates:true,duplicateRefused:true};});
await record('registered-medium-population-compute-domain',()=>{const seed=2026100403,f=fixture(256,30,undefined,prng(seed)),start=performance.now(),a=runtime.assessEconomicAttribution(f.input),elapsedMs=performance.now()-start;assert.equal(a.population.retainedClusters,256);assert(covered(a,f.truth));assert(elapsedMs<=f.input.estimand.budgets.maximumElapsedMs);return {seed,clusters:256,elapsedMs,inputBytes:Buffer.byteLength(JSON.stringify(f.input)),rss:process.memoryUsage().rss,interval:a.contrasts[0]!.interval,qualification:'ONE_BOUNDED_GENERATED_LOAD_CASE_NOT_SYSTEM_REACH_GATE'};});
for(const n of [24,64])for(const effect of [0,30,-30])await record('monte-carlo-'+n+'-'+effect,()=>{const seed=n===24?2026100401:2026100402,random=prng(seed);let coverage=0,positiveCredit=0,width=0,scoreTotal=0;const trials=2000;for(let t=0;t<trials;t++){const f=fixture(n,effect,undefined,random),a=runtime.assessEconomicAttribution(f.input);assert.equal(a.contrasts[0]!.identification,'DESIGN_BASED_CONDITIONAL');const oracle=f.potential.reduce((total:number,row:any,i:number)=>total+Number(f.input.estimand.clusters[i].weight)*(row.assigned==='finnor'?row.finnor/.5:-row.bau/.5),0),score=(Number(a.contrasts[0]!.scoreInterval!.lower)+Number(a.contrasts[0]!.scoreInterval!.upper))/2;assert(Math.abs(score-oracle)<1e-9,'Independent assignment-score oracle disagreed');scoreTotal+=score;coverage+=covered(a,f.truth)?1:0;const interval=a.contrasts[0]!.interval!;positiveCredit+=Number(interval.lower)>0?1:0;width+=Number(interval.upper)-Number(interval.lower);}const p=coverage/trials;const clopperPearson=coverage===trials?{lower:Math.pow(.025,1/trials),upper:1,method:'EXACT_BINOMIAL_INVERSION_ALL_SUCCESSES_TWO_SIDED_95',numeric:'IEEE754_DISPLAY_OF_CLOSED_FORM_0.025_POW_1_OVER_N'}:null;/* Conservative Hoeffding Monte Carlo interval, explicitly reported. */const r=Math.sqrt(Math.log(40)/(2*trials));assert(p-r>=.93);if(clopperPearson)assert(clopperPearson.lower>=.93);return {seed,n,effect,trials,coverage:p,clopperPearson95:clopperPearson,monteCarlo95:{lower:Math.max(0,p-r),upper:Math.min(1,p+r),method:'HOEFFDING_BINOMIAL_CONSERVATIVE'},meanScore:scoreTotal/trials,empiricalBias:scoreTotal/trials-effect,biasMonteCarlo95Radius:400*r,averageWidth:width/trials,positiveCreditRate:positiveCredit/trials,truth:'withheld generated potential outcomes; no field evidence'};});
const after=await snapshots(),unchanged=JSON.stringify(before)===JSON.stringify(after);await writeFile(join(output,'results.json'),JSON.stringify({results,before,after,sourcesUnchanged:unchanged,resources:process.resourceUsage(),node:process.version,qualification:'GENERATED_KNOWN_EFFECT_DESIGN_CONDITIONAL_INFERENCE_ONLY',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-statistical-e2e.mts'},null,2)+'\n');process.exitCode=results.some(v=>v.status==='FAIL')||!unchanged?1:0;
