/** Preregistered S7 transport contract through the real separate ledger process. */
import {strict as assert} from 'node:assert';
import {createHash,generateKeyPairSync,randomUUID,sign,verify} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import {spawn,type ChildProcess} from 'node:child_process';
const out=resolve(process.env.FINNOR_S7_EVIDENCE_DIR??'../scope-7/scope-evidence/protected-'+Date.now());await mkdir(out,{recursive:true});
const root=await realpath(await mkdtemp(join(tmpdir(),'finnor-s7-ledger-')));
const encode=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(encode).join(',')+']':'{'+Object.keys(v).sort((a,b)=>a.localeCompare(b)).map(k=>JSON.stringify(k)+':'+encode(v[k])).join(',')+'}';
const hash=(v:unknown)=>createHash('sha256').update(encode(v)).digest('hex');
const fsExt=dirname(createRequire(import.meta.url).resolve('fs-ext/package.json'));
const paths=['ledger.ts','ledger-server.mts','protocol.ts','request-verifier.ts','adapter-contract.ts'].map(n=>resolve('packages/governed-execution/src',n)).concat(['fs-ext.js','build/Release/fs_ext.node','package.json'].map(n=>join(fsExt,n)));
const snapshotPaths=[...paths,resolve('packages/governed-execution/src/owner-transport.ts'),resolve('scripts/s7/run-protected-e2e.mts')];
const snapshot=()=>Promise.all(snapshotPaths.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')})));
const before=await snapshot(),sourceDigests=before.slice(0,paths.length),signer=generateKeyPairSync('ed25519'),reviewer=generateKeyPairSync('ed25519');
const pub=signer.publicKey.export({type:'spki',format:'pem'}).toString(),reviewPub=reviewer.publicKey.export({type:'spki',format:'pem'}).toString();
const tenant=randomUUID(),principal=randomUUID(),rights='s7-disposable-rights',tokens={S7:randomUUID()+randomUUID(),S5:randomUUID()+randomUUID(),READER:randomUUID()+randomUUID()};
const byteHash=(v:string)=>createHash('sha256').update(v).digest('hex');
const owners=[{owner:'S7',tokenHash:byteHash(tokens.S7),append:true},{owner:'S5',tokenHash:byteHash(tokens.S5),append:true},{owner:'S7',tokenHash:byteHash(tokens.READER),append:false}].map(o=>({...o,tenantId:tenant,principalId:principal,rightsRefs:[rights],read:true,sealedAppend:false,sealedRead:false}));
const policy={schema:'finnor.s6.ledger-policy.v1',domain:'DISPOSABLE_TEST_AUTHORITY',owners,signerPublicKey:pub,maxEntries:100000};
const releaseBody={schema:'finnor.s6.ledger-release.v2',releaseId:'s7-disposable-candidate',sourceDigests,runtime:{node:process.version,nodeAbi:process.versions.modules,platform:process.platform,arch:process.arch},policyDigest:hash(policy),validUntil:new Date(Date.now()+3600000).toISOString()};
const release={...releaseBody,signature:sign(null,Buffer.from(encode(releaseBody)),reviewer.privateKey).toString('base64')};
await writeFile(join(root,'signer.pem'),signer.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});await mkdir(join(root,'protected'),{mode:0o700});await mkdir(join(root,'ordinary'),{mode:0o700});
const config={policy,release,signerPath:join(root,'signer.pem'),protectedDirectory:join(root,'protected'),contentDirectory:join(root,'ordinary'),port:0},configPath=join(root,'config.json');await writeFile(configPath,JSON.stringify(config),{mode:0o600});
let child:ChildProcess|null=null,base='',logs='';
async function start(){logs='';child=spawn(process.execPath,['--import=tsx','packages/governed-execution/src/ledger-server.mts'],{env:{...process.env,FINNOR_S6_LEDGER_CONFIG:configPath,FINNOR_S6_LEDGER_RELEASE_ROOT:reviewPub},stdio:['ignore','pipe','pipe']});await new Promise<void>((ok,fail)=>{const timer=setTimeout(()=>fail(Error('ledger boot timeout:'+logs)),15000);child!.stdout!.on('data',b=>{logs+=b;for(const line of logs.split('\n'))try{const state=JSON.parse(line);if(state.status==='READY'){base='http://127.0.0.1:'+state.port;clearTimeout(timer);ok();}}catch{}});child!.stderr!.on('data',b=>{logs+=b;});child!.once('exit',()=>{clearTimeout(timer);fail(Error('ledger exited:'+logs));});});}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise<void>(ok=>{child!.once('close',()=>ok());child!.kill('SIGKILL');});}
async function call(path:string,payload?:any,token=tokens.S7){const r=await fetch(base+path,{method:payload===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(payload===undefined?{}:{body:encode(payload)}),signal:AbortSignal.timeout(10000)});return {status:r.status,body:await r.json() as any};}
function event(owner='S7',horizon='H2',detail:any={statement:'typed-byte-challenge',qualification:'GENERATED_NO_FIELD_MATURITY'}){const body={schema:'finnor.'+owner.toLowerCase()+'.experience.v1',semanticOwner:owner,type:'COST',episodeId:'s7-test',tenantId:tenant,principalId:principal,rightsRef:rights,revisionRef:'subject:'+randomUUID(),contentDigest:hash(detail),knowledgeAt:new Date().toISOString(),validAt:new Date().toISOString(),preparedParentRefs:[],causalParents:[],dependencyRefs:[],horizon,uncertainty:'SOURCE_OR_COST_GAPS',detail,protectedReceipt:null,appendAuthorityGranted:false};return {...body,eventId:owner.toLowerCase()+'-event:'+hash(body)};}
const results:any[]=[];let first:any;
async function check(id:string,fn:()=>Promise<any>){try{results.push({id,status:'PASS',observed:await fn()});}catch(e){results.push({id,status:'FAIL',error:String(e)});}await writeFile(join(out,'results.json'),JSON.stringify({results,before,node:process.version,qualification:'DISPOSABLE_TEST_AUTHORITY_BYTE_CONTRACT_ONLY',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-protected-e2e.mts'},null,2));console.log(JSON.stringify({id,status:results.at(-1).status,error:results.at(-1).error}));}
try{await start();
await check('s7-h2-exact-immutable-commitment',async()=>{const e=event(),input={event:e,parents:[],references:[{id:e.revisionRef,owner:'S7',version:'test-v1',contentDigest:hash(e.detail),content:e.detail}]};const a=await call('/append',input);assert.equal(a.status,200,JSON.stringify(a));const {signature,...body}=a.body.receipt;assert(verify(null,Buffer.from(encode(body)),pub,Buffer.from(signature,'base64')));const concurrent=await Promise.all(Array.from({length:16},()=>call('/append',input)));assert(concurrent.every(v=>v.status===200&&hash(v.body.receipt)===hash(a.body.receipt)));const read=await call('/events/'+encodeURIComponent(e.eventId),undefined,tokens.READER);assert.equal(read.status,200);assert.deepEqual(read.body.event,e);first={input,receipt:a.body.receipt};return {input,a,read,sequences:concurrent.map(v=>v.body.receipt.sequence)};});
await check('foreign-owner-h2-cannot-borrow-s7-permission',async()=>{const e=event('S5'),a=await call('/append',{event:e,parents:[],references:[{id:e.revisionRef,owner:'S5',version:'test-v1',contentDigest:hash(e.detail),content:e.detail}]},tokens.S5);assert.equal(a.status,400);assert.equal(a.body.error,'UNSUPPORTED_PREPARED_EVENT');return a;});
await check('s7-detail-cannot-borrow-other-subject-digest',async()=>{const e=event(),subject={authority:'different-subject'},changed={...e,detail:{forged:'changed'},contentDigest:hash(subject)};const {eventId,...body}=changed;changed.eventId='s7-event:'+hash(body);const a=await call('/append',{event:changed,parents:[],references:[{id:e.revisionRef,owner:'S7',version:'test-v1',contentDigest:hash(subject),content:subject}]});assert.equal(a.status,409,JSON.stringify(a));assert.equal(a.body.error,'EVENT_CONTENT_PREIMAGE_INVALID');return {changed,a};});
await check('restart-exact-history-and-tenant-refusal',async()=>{assert(first,'missing original successful commitment');await stop();await start();const a=await call('/events/'+encodeURIComponent(first.input.event.eventId),undefined,tokens.READER);assert.equal(a.status,200);assert.deepEqual(a.body.receipt,first.receipt);const e=event();e.tenantId=randomUUID();const wrong=await call('/append',{event:e,parents:[],references:[]});assert.equal(wrong.status,403);return {a,wrong};});
}finally{await stop();}
const after=await snapshot(),unchanged=encode(before)===encode(after);await writeFile(join(out,'results.json'),JSON.stringify({results,before,after,sourcesUnchanged:unchanged,node:process.version,logs,qualification:'DISPOSABLE_TEST_AUTHORITY_SEPARATE_PROCESS_NO_H2_ECONOMIC_OR_PRODUCTION_ADMISSION',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-protected-e2e.mts'},null,2)+'\n');process.exitCode=results.some(v=>v.status==='FAIL')||!unchanged?1:0;console.log(JSON.stringify({out,failed:results.filter(v=>v.status==='FAIL').length,sourcesUnchanged:unchanged}));
