/** Preregistered native owner/API storage challenges, real ordinary-role SQL. */
import {strict as assert} from 'node:assert';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,readFile,appendFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {resolve,join} from 'node:path';import {createServer} from 'node:net';
import EmbeddedPostgres from 'embedded-postgres';import pg from 'pg';
import {createEconomicLedger} from './ledger-fixture.mjs';
import {economicFixture} from './economic-fixtures.mjs';
const out=resolve(process.env.FINNOR_S7_EVIDENCE_DIR??'../scope-7/scope-evidence/owner-'+Date.now());await mkdir(out,{recursive:true});
const sourcePaths=['packages/private-equity/src/economic-store.ts','packages/private-equity/src/enterprise-economic-attribution.ts','packages/epistemic-runtime/src/economic-attribution.ts','packages/shared-types/src/economic-attribution.ts','packages/db/migrations/0156_economic_attribution.sql','packages/db/migration-head.ts','apps/api/app/api/economic-outcomes/[operation]/route.ts','scripts/s7/run-integrated-e2e.mts','scripts/s7/ledger-fixture.mts','packages/private-equity/src/enterprise-economic-assignments.ts','packages/private-equity/src/enterprise-economic-consumers.ts','packages/governed-execution/src/owner-transport.ts','packages/governed-execution/src/owner-delivery-store.ts','scripts/s7/economic-fixtures.mts'];
const snapshot=()=>Promise.all(sourcePaths.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')})));const before=await snapshot();
const directory=await mkdtemp(join(tmpdir(),'finnor-s7-db-'));const port=await new Promise<number>(ok=>{const s=createServer();s.listen(0,'127.0.0.1',()=>{const a=s.address() as any;s.close(()=>ok(a.port));});});
const postgres=new EmbeddedPostgres({databaseDir:directory,user:'finnor',password:'finnor',port,persistent:false,onLog:()=>undefined});await postgres.initialise();await appendFile(join(directory,'postgresql.conf'),'\ntrack_commit_timestamp=on\n');await postgres.start();await postgres.createDatabase('finnor');
const admin=new pg.Client({connectionString:`postgres://finnor:finnor@127.0.0.1:${port}/finnor`});await admin.connect();process.env.DATABASE_URL=`postgres://finnor:finnor@127.0.0.1:${port}/finnor`;process.env.FINNOR_TEST_MANAGED_EXTENSIONS='omit';const {migrate}=await import('../../packages/db/migrate');const migrations=await migrate(process.env.DATABASE_URL);process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/finnor`;process.env.NODE_ENV='test';process.env.AUTH_DEV_BYPASS='1';process.env.LOG_LEVEL='silent';delete process.env.FINNOR_S6_OWNER_TRANSPORT_CONFIG;
const tenant=randomUUID(),principal=randomUUID(),otherTenant=randomUUID(),otherPrincipal=randomUUID();for(const [t,p] of [[tenant,principal],[otherTenant,otherPrincipal]]){await admin.query('INSERT INTO finnor_os.tenants(id,name) VALUES($1,$2)',[t,'S7 disposable']);await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status) VALUES($1,$2,$3,'owner','active')",[p,t,p+'@generated.invalid']);}
const db=await import('../../packages/db/index'),owner=await import('../../packages/private-equity/src/enterprise-economic-attribution'),route=await import('../../apps/api/app/api/economic-outcomes/[operation]/route');
const ledger=await createEconomicLedger(tenant,principal,otherPrincipal);const transport=await import('../../packages/governed-execution/src/owner-delivery-store');const engine=await import('../../packages/epistemic-runtime/src/economic-attribution');
const ctx:any={auth:{tenantId:tenant,userId:principal,employeeId:principal,role:'owner'}},results:any[]=[];let first:any;
async function api(operation:string,body:any,context=ctx){return route.POST(new Request('http://localhost/api/economic-outcomes/'+operation,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':context.auth.tenantId,'x-user-id':context.auth.userId,'x-user-role':context.auth.role},body:JSON.stringify(body)}),{params:Promise.resolve({operation})});}
async function check(id:string,fn:()=>Promise<any>){try{results.push({id,status:'PASS',observed:await fn()});}catch(error){results.push({id,status:'FAIL',error:String(error)});}await writeFile(join(out,'partial-results.json'),JSON.stringify({results,before,qualification:'DISPOSABLE_LOCAL_OWNER_NOT_PROTECTED_SOURCE_AUTHORITY'},null,2));console.log(JSON.stringify({id,status:results.at(-1).status,error:results.at(-1).error}));}
let e:any,protocol:any,assigned:any,assessment:any,benchmark:any;const inputs:any={};
async function deliver(semanticOwner:string){const r=await transport.deliverOwnerTransportBatch({semanticOwner,tenantId:tenant,principalId:principal},{limit:32});assert.equal(r.failures.length,0,JSON.stringify(r));return r;}
async function make(ref:any,content:any){ref.contentDigest=engine.economicHash(content);await ledger.publish({...ref,content});return ref;}
try{
await check('protected-prospective-question-and-S2-owned-law',async()=>{
 e=structuredClone(economicFixture(8,0,15).input.estimand);const now=Date.now();e.registeredAt=new Date(now).toISOString();e.assignmentAt=new Date(now+15000).toISOString();e.outcomeAccessNotBefore=new Date(now+35000).toISOString();e.endpointAt=new Date(now+35000).toISOString();e.horizonMonths=1;e.analysis.registeredLooks=[e.endpointAt];e.discountSchedule=[{at:e.endpointAt,factor:'1'}];for(const [id,role] of [['pinned','PINNED_CURRENT_FINNOR'],['specialist','FRONTIER_SPECIALIST'],['muse','MUSE'],['dots','DOTS'],['expert','EXPERT_PE']]){const c=structuredClone(e.controllers[1]);c.id=id;c.role=role;for(const r of [c.programmeRef,...c.policyRefs,...c.interventionRefs,c.adaptationRuleRef])r.id+='-'+id;e.controllers.push(c);}e.assignment.probabilities=Object.fromEntries(e.controllers.map((c:any)=>[c.id,c.id==='bau'?'0.16':'0.14']));e.valuationProtocol.authorityRefs[0].id=otherPrincipal;e.assumptions.forEach((a:any)=>a.evidenceRefs.forEach((r:any)=>r.owner='INDEPENDENT_VALUER'));
 for(const ref of engine.collectEconomicRefs(e)){if(ref.id==='protocol'||ref.id.startsWith('manifest-'))continue;let content:any={schema:'finnor.generated-source.v1',id:ref.id,sourceOrigin:'GENERATED_CHALLENGE',independent:true};if(ref.id==='mandate')content={schema:'finnor.economic-mandate.v1',tenantId:tenant,principalId:principal,rightsRef:ledger.rights,economicProgrammeAssignment:true,validUntil:new Date(now+3600000).toISOString(),sourceOrigin:'GENERATED_CHALLENGE'};if(ref.id===otherPrincipal)content={schema:'finnor.independent-valuation-authority.v1',principalId:otherPrincipal,economicNoticeResolution:true,sourceOrigin:'GENERATED_CHALLENGE'};const digest=engine.economicHash(content);const update=(v:any)=>{if(v&&typeof v==='object'){if(v.id===ref.id&&v.contentDigest)v.contentDigest=digest;for(const x of Object.values(v))update(x);}};update(e);await ledger.publish({...ref,contentDigest:digest,content});}
 for(const c of e.clusters)await make(c.sourceManifestRef,{schema:'finnor.economic-source-manifest.v1',ownerBoundaryRef:e.ownerBoundaryRef,currency:e.currency,clusterId:c.id,openingWealth:c.openingWealth,ownershipWaterfallRef:e.ownershipWaterfallRef,sourceOrigin:'GENERATED_CHALLENGE'});
 const p={schema:'finnor.s2.economic-assignment-protocol.v1',key:'prospective-law',mandateRef:e.mandateRef,populationRef:e.populationRef,clusterIds:e.clusters.map((c:any)=>c.id),controllerIds:e.controllers.map((c:any)=>c.id),probabilityUnits:Object.fromEntries(e.controllers.map((c:any)=>[c.id,c.id==='bau'?160000:140000])),assignmentNotBefore:e.assignmentAt,outcomeAccessNotBefore:e.outcomeAccessNotBefore,randomization:'INDEPENDENT_CRYPTO_CATEGORICAL_V1'};
 const r=await api('register-assignment-protocol',{protocol:p,rightsRef:ledger.rights});const b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));protocol=b.record;await deliver('S2');e.assignment.protocolRef=protocol.ref;
 const question={estimand:e,rightsRef:ledger.rights,mode:'PROSPECTIVE',idempotencyKey:'protected-question'};const q=await api('register',question),qb:any=await q.json();assert.equal(q.status,200,JSON.stringify(qb));first=qb.record;await deliver('S7');const read=await api('read',{id:first.ref.id,protectedReadback:true}),rb:any=await read.json();assert.equal(read.status,200,JSON.stringify(rb));assert.equal(rb.protectedReadback.receipt.semanticOwner,'S7');assert.equal(rb.protectedReadback.protectionDomain,'DISPOSABLE_TEST_AUTHORITY');const registration={schema:'finnor.economic-benchmark-registration.v1',key:'generated-seven-arm-comparison',registeredAt:new Date().toISOString(),protocolRef:protocol.ref,estimandRef:first.ref,matchedEnvelopeRef:e.allocationRef,controllers:e.controllers.map((c:any)=>({id:c.id,role:c.role,pinnedVersionRef:c.programmeRef,required:true})),epsilon:'1',absoluteValueFloor:'100',minimumDecisionPayoff:'1',downsideLimit:'100',primaryHorizonMonths:36,minimumClosedLoopDays:90,multiplicityRef:e.analysis.powerRegistrationRef,powerStoppingRef:e.analysis.powerRegistrationRef,pricebookRef:e.capitalCarryRef,capabilityFrontierRef:e.analysis.powerRegistrationRef,refreshAsOf:new Date().toISOString(),nextRefreshAt:new Date(Date.now()+86400000).toISOString()};const br=await api('register-benchmark',{registration,rightsRef:ledger.rights,idempotencyKey:'benchmark-registration'}),bb:any=await br.json();assert.equal(br.status,200,JSON.stringify(bb));benchmark=bb.record;await deliver('S7');return {protocol,question:qb.record,readback:rb,benchmark};
});
await check('S2-independent-draws-concurrent-retry-and-no-rerandomization',async()=>{assert.ok(first,'Previous question setup required');const early=await api('assign-programme',{estimandId:first.ref.id,protocolId:protocol.ref.id,idempotencyKey:'assignment'});assert.equal(early.status,400,JSON.stringify(await early.clone().json()));await new Promise(r=>setTimeout(r,Math.max(0,Date.parse(e.assignmentAt)-Date.now()+10)));const body={estimandId:first.ref.id,protocolId:protocol.ref.id,idempotencyKey:'assignment'},rs=await Promise.all(Array.from({length:8},()=>api('assign-programme',body))),bs:any[]=await Promise.all(rs.map(r=>r.json()));assert(rs.every(r=>r.status===200),JSON.stringify(bs));assigned=bs[0].record;assert(bs.every(b=>b.record.ref.id===assigned.ref.id));assert.equal(assigned.assignments.length,8);assert(assigned.assignments.every((a:any)=>e.controllers.some((c:any)=>c.id===a.controllerId)&&a.actualExposureRefs.length===0));const retry=await api('assign-programme',{...body,idempotencyKey:'new-seed'});assert.equal(retry.status,409,JSON.stringify(await retry.clone().json()));const rows=(await admin.query("SELECT count(*)::int n FROM finnor_os.s2_economic_assignment_records WHERE kind='ASSIGNMENT'")).rows[0].n;assert.equal(rows,1);await deliver('S2');return {assignment:assigned,rows,early:early.status,newKey:retry.status};});
await check('signed-financial-joins-and-generated-programme-ITT-not-field-H2',async()=>{assert.ok(assigned,'Previous assignment setup required');const f=economicFixture(8,0,15),accounting=structuredClone(f.input.accounting);for(let i=0;i<accounting.length;i++){const s=accounting[i],a=assigned.assignments[i];s.estimandRef=first.ref;s.controllerId=a.controllerId;s.asOf=e.endpointAt;s.knowledgeAt=new Date(Date.now()+5000).toISOString();s.closedLoopDays=0;s.sourceManifestRef=e.clusters[i].sourceManifestRef;
 s.items.forEach((item:any)=>{item.ownerBoundaryRef=e.ownerBoundaryRef;item.at=e.endpointAt;});const v=s.valuations[0];v.authorityRef=e.valuationProtocol.authorityRefs[0];v.methodRef=e.valuationProtocol.methodRefs[0];v.independenceRef=e.valuationProtocol.independenceRef;v.ownershipDebtRef=e.ownershipWaterfallRef;v.asOf=e.endpointAt;
 await make(v.inputRefs[0],{schema:'finnor.generated-source.v1',sourceOrigin:'GENERATED_CHALLENGE'});
 await make(s.items[0].sourceRef,{schema:'finnor.economic-financial-statement.v1',items:s.items.filter((i:any)=>i.destination==='CASH_OWNER').map((i:any)=>({canonicalId:i.canonicalId,ownerBoundaryRef:i.ownerBoundaryRef,currency:i.currency,at:i.at,destination:i.destination,amount:i.amount,costCategory:i.costCategory,embeddedIn:i.embeddedIn})),totals:[{destination:'CASH_OWNER',itemIds:[s.items[0].canonicalId],total:s.items[0].amount}],sourceOrigin:'GENERATED_CHALLENGE'});
 await make(s.items[1].sourceRef,{schema:'finnor.independent-owner-valuation.v1',itemId:v.itemId,asOf:v.asOf,authorityRef:v.authorityRef,methodRef:v.methodRef,ownershipDebtRef:v.ownershipDebtRef,independenceRef:v.independenceRef,inputRefs:v.inputRefs,conflictsBlindingRef:e.valuationProtocol.conflictsBlindingRef,equityBounds:s.items[1].amount,ownerBoundaryRef:e.ownerBoundaryRef,currency:e.currency,sourceOrigin:'GENERATED_CHALLENGE'});v.signedAssessmentRef=s.items[1].sourceRef;
 await make(s.conservationRef,{schema:'finnor.owner-conservation.v1',ownerBoundaryRef:e.ownerBoundaryRef,ownershipWaterfallRef:e.ownershipWaterfallRef,asOf:s.asOf,distributionsRemovedFromResidual:true,residualIncludesEntityDebt:true,internalTransfersEliminated:true,economicItemIds:s.items.map((i:any)=>i.canonicalId),sourceOrigin:'GENERATED_CHALLENGE'});s.items.forEach((i:any)=>i.reconciliationRefs=[s.conservationRef]);
 await make(s.liabilityCoverageRef,{schema:'finnor.owner-liability-coverage.v1',ownerBoundaryRef:e.ownerBoundaryRef,asOf:s.asOf,allOwnerLiabilitiesExamined:true,extraLiabilityIds:[],sourceOrigin:'GENERATED_CHALLENGE'});
 const zero=s.costCoverage[0].zeroCostEvidenceRef;await make(zero,{schema:'finnor.economic-cost-coverage.v1',clusterId:s.clusterId,controllerId:s.controllerId,asOf:s.asOf,zeroCostCategories:s.costCoverage.map((c:any)=>c.category),ownerBoundaryRef:e.ownerBoundaryRef,sourceOrigin:'GENERATED_CHALLENGE'});s.costCoverage.forEach((c:any)=>c.zeroCostEvidenceRef=zero);
 s.sourceTotals=s.items.map((i:any)=>({sourceRef:i.sourceRef,destination:i.destination,itemIds:[i.canonicalId],total:i.amount}));}
 const computeCost=structuredClone(f.input.computeCost);await make(computeCost.pricebookRef,{schema:'finnor.generated-pricebook.v1',sourceOrigin:'GENERATED_CHALLENGE'});await make(computeCost.meteringRef,{schema:'finnor.economic-compute-meter.v1',estimandRef:first.ref,lookAt:e.endpointAt,methodVersion:e.version,amount:computeCost.amount,currency:e.currency,ownerBoundaryRef:e.ownerBoundaryRef,pricebookRef:computeCost.pricebookRef,sourceOrigin:'GENERATED_CHALLENGE'});
 await new Promise(r=>setTimeout(r,Math.max(0,Date.parse(e.endpointAt)-Date.now()+10)));accounting.forEach((s:any)=>s.knowledgeAt=new Date().toISOString());inputs.assess={estimandId:first.ref.id,lookAt:e.endpointAt,assignments:assigned.assignments,accounting,idempotencyKey:'qualified-generated-assessment',computeCost};const r=await api('assess',inputs.assess),b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));assessment=b.record;const a=assessment.payload.assessment;assert.equal(a.contrasts[0].identification,'DESIGN_BASED_CONDITIONAL',JSON.stringify(a.reasons));assert(a.accounting.every((a:any)=>a.wealth!==null),JSON.stringify(a.accounting));assert.equal(a.completeCosts,true);assert.equal(a.supportedHorizon,'H1');assert.equal(a.population.retainedClusters,8);await deliver('S7');return assessment;
});
await check('authentic-but-unrelated-money-is-rejected-as-economic-support',async()=>{assert.ok(assessment,'Previous accounting setup required');const changed=structuredClone(inputs.assess);changed.idempotencyKey='money-substitution';changed.accounting[0].items[0].amount={lower:'99',upper:'99'};changed.accounting[0].sourceTotals[0].total={lower:'99',upper:'99'};const r=await api('assess',changed),b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));assert.equal(b.record.payload.assessment.accounting[0].wealth,null);assert.equal(b.record.payload.assessment.completeCosts,true);assert.equal(b.record.payload.assessment.supportedHorizon,'H1');return b.record;});
await check('company-portfolio-and-S8-readback-preserve-uncertainty-no-action-reward',async()=>{assert.ok(assessment,'Previous accounting setup required');const r=await api('reconcile-aggregate',{level:'PORTFOLIO',ownerBoundaryRef:e.ownerBoundaryRef,assessmentIds:[assessment.ref.id],idempotencyKey:'portfolio'}),b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));assert.equal(b.record.payload.aggregateCausalCreditIdentified,false);assert.equal(b.record.payload.jointProgrammeContrasts,null);assert.deepEqual(b.record.payload.actionRewards,[]);await deliver('S7');const consumer=await api('learning-assessment',{assessmentId:assessment.ref.id,protectedReadback:true}),c:any=await consumer.json();assert.equal(consumer.status,200,JSON.stringify(c));assert.equal(c.protectedReadback.receipt.semanticOwner,'S7');assert.equal(c.causalActionCreditsGranted,false);assert.equal(c.estimatorPromotionGranted,false);assert.equal((await ledger.appendDenied()).status,403);return {aggregate:b.record,consumer:c};});
await check('atomic-owner-record-origin-rollback',async()=>{await admin.query("CREATE FUNCTION finnor_os.s7_test_origin_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'registered rollback challenge'; END $$");await admin.query('CREATE TRIGGER s7_test_origin_failure BEFORE INSERT ON finnor_os.s6_owner_delivery_origins FOR EACH ROW EXECUTE FUNCTION finnor_os.s7_test_origin_failure()');const r=await api('append',{kind:'COST',estimandRefId:first.ref.id,record:{unobserved:'challenge'},sourceRefs:[],validAt:e.endpointAt,idempotencyKey:'must-roll-back'});assert.equal(r.status,500);const n=(await admin.query("SELECT count(*)::int n FROM finnor_os.s7_economic_records WHERE idempotency_key='must-roll-back'")).rows[0].n;assert.equal(n,0);await admin.query('DROP TRIGGER s7_test_origin_failure ON finnor_os.s6_owner_delivery_origins');await admin.query('DROP FUNCTION finnor_os.s7_test_origin_failure()');return {status:r.status,committedRows:n};});
await check('S7-full-source-manifest-survives-event-bound',async()=>{const refs=Array.from({length:300},(_,i)=>({owner:'FINANCIAL_SOURCE',id:'extra-'+i,version:'generated-v1',contentDigest:engine.economicHash({i})}));const store=await import('../../packages/private-equity/src/economic-store');const r=await store.persistEconomicRecord(ctx,{kind:'SOURCE',payload:{references:refs},rightsRef:ledger.rights,idempotencyKey:'full-manifest',estimandId:first.ref.id,validAt:e.endpointAt,horizon:'H1',uncertainty:'SOURCE_GAPS',dependencies:refs});assert.equal((r.record.event.dependencyRefs as any[]).length,2);await deliver('S7');const b:any=await (await api('read',{id:r.record.ref.id,protectedReadback:true})).json();assert.equal(b.protectedReadback.receipt.references.length,3);return b;});
await check('native-benchmark-keeps-required-unrun-and-H1-comparisons-inconclusive',async()=>{assert.ok(benchmark,'Registered benchmark required');const r=await api('benchmark',{registrationId:benchmark.ref.id,assessments:[],gates:[],idempotencyKey:'all-comparators-unrun'}),b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));assert.equal(b.record.payload.assessment.economic100x,'INCONCLUSIVE');assert(b.record.payload.assessment.comparisons.every((c:any)=>c.status==='UNMEASURED'));const evaluator={owner:'INDEPENDENT_VALUER',id:'generated-evaluator',version:'generated-v1',contentDigest:'0'.repeat(64)};await make(evaluator,{schema:'finnor.independent-economic-evaluation.v1',controllerId:'finnor',assessmentRef:assessment.payload.assessment.ref,registrationRef:benchmark.ref,pinnedVersionRef:e.controllers.find((c:any)=>c.id==='finnor').programmeRef,sourceOrigin:'GENERATED_CHALLENGE',independent:true});const one=await api('benchmark',{registrationId:benchmark.ref.id,assessments:[{controllerId:'finnor',recordId:assessment.ref.id,matchedEnvelopeRef:e.allocationRef,protocolRef:protocol.ref,independentEvaluatorRef:evaluator}],gates:[],idempotencyKey:'H1-cannot-win'}),o:any=await one.json();assert.equal(one.status,200,JSON.stringify(o));assert.equal(o.record.payload.assessment.claimGranted,false);assert.equal(o.record.payload.assessment.named10x.Muse,'INCONCLUSIVE');assert.equal(o.record.payload.assessment.named10x.dots,'INCONCLUSIVE');const knownRows=[];for(const c of e.controllers){const ref={owner:'INDEPENDENT_VALUER',id:'benchmark-evaluator-'+c.id,version:'generated-v1',contentDigest:'0'.repeat(64)};await make(ref,{schema:'finnor.independent-economic-evaluation.v1',controllerId:c.id,assessmentRef:assessment.payload.assessment.ref,registrationRef:benchmark.ref,pinnedVersionRef:c.programmeRef,sourceOrigin:'GENERATED_CHALLENGE',independent:true});knownRows.push({controllerId:c.id,recordId:assessment.ref.id,matchedEnvelopeRef:e.allocationRef,protocolRef:protocol.ref,independentEvaluatorRef:ref});}const full=await api('benchmark',{registrationId:benchmark.ref.id,assessments:knownRows,gates:[],idempotencyKey:'all-known-H1-bounds'}),fb:any=await full.json();assert.equal(full.status,200,JSON.stringify(fb));assert.equal(fb.record.payload.assessment.strongestBaselineUpper,'100');assert.equal(fb.record.payload.assessment.strongestBaselineLower,'0');assert.equal(fb.record.payload.assessment.ratioInterval,null);assert.equal(fb.record.payload.assessment.claimGranted,false);return {unrun:b.record,H1:o.record,allKnownBounds:fb.record};});
await check('late-economic-notice-cannot-be-ignored-by-fresh-assessment',async()=>{const note=await api('append',{kind:'COST',estimandRefId:first.ref.id,record:{amount:'25',category:'HUMAN',reason:'Unresolved adverse invoice'},sourceRefs:[],validAt:e.endpointAt,idempotencyKey:'late-cost-notice'}),nb:any=await note.json();assert.equal(note.status,200,JSON.stringify(nb));await deliver('S7');inputs.notice=nb.record;const r=await api('assess',{...inputs.assess,idempotencyKey:'unresolved-cost-reassessment'}),b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));assert.equal(b.record.payload.assessment.completeCosts,false,'A late unresolved cost was silently ignored');assert.equal(b.record.payload.assessment.contrasts[0].interval,null);const consumer=await api('learning-assessment',{assessmentId:assessment.ref.id}),c:any=await consumer.json();assert.equal(c.qualification,'NEW_ECONOMIC_NOTICES_REQUIRE_REASSESSMENT');const staleAggregate=await api('reconcile-aggregate',{level:'PORTFOLIO',ownerBoundaryRef:e.ownerBoundaryRef,assessmentIds:[assessment.ref.id],idempotencyKey:'stale-portfolio'}),ag:any=await staleAggregate.json();assert.equal(staleAggregate.status,200,JSON.stringify(ag));assert.equal(ag.record.payload.observedOwnerWealth,null);const resolution={owner:'INDEPENDENT_VALUER',id:'independent-notice-resolution',version:'generated-v1',contentDigest:'0'.repeat(64)};await make(resolution,{schema:'finnor.independent-economic-notice-resolution.v1',authorityRef:e.valuationProtocol.authorityRefs[0],noticeRef:nb.record.ref,estimandRef:first.ref,ownerBoundaryRef:e.ownerBoundaryRef,currency:e.currency,lookAt:e.endpointAt,disposition:'REFUTED',correctedSourceRefs:[],independent:true,sourceOrigin:'GENERATED_CHALLENGE'});await deliver('S7');const resolved=await api('assess',{...inputs.assess,noticeResolutionRefs:[resolution],idempotencyKey:'independently-resolved-cost-notice'}),rb:any=await resolved.json();assert.equal(resolved.status,200,JSON.stringify(rb));assert.equal(rb.record.payload.assessment.completeCosts,true,JSON.stringify(rb.record.payload.noticeQualification));assert.equal(rb.record.payload.assessment.contrasts[0].identification,'DESIGN_BASED_CONDITIONAL');assert.equal(rb.record.payload.assessment.supportedHorizon,'H1');assert.deepEqual(rb.record.payload.unresolvedNotices,[]);return {notice:nb.record,assessment:b.record,consumer:c,staleAggregate:ag,independentlyResolved:rb.record};});
await check('late-invalidation-retained-and-propagated-to-S8',async()=>{assert.ok(assessment,'Previous accounting setup required');const r=await api('append',{kind:'INVALIDATION',estimandRefId:first.ref.id,record:{reason:'generated independent source withdrawn'},sourceRefs:[],revisionOf:first.ref.id,validAt:e.endpointAt,idempotencyKey:'invalidated'});assert.equal(r.status,200);const next=await api('assess',{...inputs.assess,idempotencyKey:'after-invalidation'}),b:any=await next.json();assert.equal(next.status,200,JSON.stringify(b));assert.equal(b.record.payload.assessment.contrasts[0].identification,'UNIDENTIFIED');const consumer=await api('learning-assessment',{assessmentId:assessment.ref.id}),c:any=await consumer.json();assert.equal(c.qualification,'INVALIDATED_REQUIRES_NEW_QUALIFICATION');return {assessment:b.record,consumer:c};});
}finally{await ledger.stop();await admin.end();await db.getPool().end();await postgres.stop();}
const after=await snapshot(),unchanged=JSON.stringify(before)===JSON.stringify(after);await writeFile(join(out,'results.json'),JSON.stringify({results,before,after,sourcesUnchanged:unchanged,node:process.version,postgres:{directory,port,migrations},ledgerSources:ledger.before,resources:process.resourceUsage(),qualification:'REAL_OWNER_SQL_AND_PROTECTED_SEPARATE_PROCESS_WITH_DISPOSABLE_GENERATED_AUTHORITY; NO_FIELD_H2_OR_ADMISSION',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-integrated-e2e.mts'},null,2)+'\n');const failed=results.some(v=>v.status==='FAIL')||!unchanged;console.log(JSON.stringify({out,failed,sourcesUnchanged:unchanged}));process.exit(failed?1:0);
