/** Preregistered native owner/API storage challenges, real ordinary-role SQL. */
import {strict as assert} from 'node:assert';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,readFile,appendFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {resolve,join} from 'node:path';import {createServer} from 'node:net';
import EmbeddedPostgres from 'embedded-postgres';import pg from 'pg';
import {economicFixture} from './economic-fixtures.mjs';
const out=resolve(process.env.FINNOR_S7_EVIDENCE_DIR??'../scope-7/scope-evidence/owner-'+Date.now());await mkdir(out,{recursive:true});
const sourcePaths=['packages/private-equity/src/economic-store.ts','packages/private-equity/src/enterprise-economic-attribution.ts','packages/epistemic-runtime/src/economic-attribution.ts','packages/shared-types/src/economic-attribution.ts','packages/db/migrations/0156_economic_attribution.sql','packages/db/migration-head.ts','apps/api/app/api/economic-outcomes/[operation]/route.ts','scripts/s7/run-owner-e2e.mts','scripts/s7/economic-fixtures.mts'];
const snapshot=()=>Promise.all(sourcePaths.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')})));const before=await snapshot();
const directory=await mkdtemp(join(tmpdir(),'finnor-s7-db-'));const port=await new Promise<number>(ok=>{const s=createServer();s.listen(0,'127.0.0.1',()=>{const a=s.address() as any;s.close(()=>ok(a.port));});});
const postgres=new EmbeddedPostgres({databaseDir:directory,user:'finnor',password:'finnor',port,persistent:false,onLog:()=>undefined});await postgres.initialise();await appendFile(join(directory,'postgresql.conf'),'\ntrack_commit_timestamp=on\n');await postgres.start();await postgres.createDatabase('finnor');
const admin=new pg.Client({connectionString:`postgres://finnor:finnor@127.0.0.1:${port}/finnor`});await admin.connect();process.env.DATABASE_URL=`postgres://finnor:finnor@127.0.0.1:${port}/finnor`;process.env.FINNOR_TEST_MANAGED_EXTENSIONS='omit';const {migrate}=await import('../../packages/db/migrate');const migrations=await migrate(process.env.DATABASE_URL);process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/finnor`;process.env.NODE_ENV='test';process.env.AUTH_DEV_BYPASS='1';process.env.LOG_LEVEL='silent';delete process.env.FINNOR_S6_OWNER_TRANSPORT_CONFIG;
const tenant=randomUUID(),principal=randomUUID(),otherTenant=randomUUID(),otherPrincipal=randomUUID();for(const [t,p] of [[tenant,principal],[otherTenant,otherPrincipal]]){await admin.query('INSERT INTO finnor_os.tenants(id,name) VALUES($1,$2)',[t,'S7 disposable']);await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status) VALUES($1,$2,$3,'owner','active')",[p,t,p+'@generated.invalid']);}
const db=await import('../../packages/db/index'),owner=await import('../../packages/private-equity/src/enterprise-economic-attribution'),route=await import('../../apps/api/app/api/economic-outcomes/[operation]/route');
const ctx:any={auth:{tenantId:tenant,userId:principal,employeeId:principal,role:'owner'}},results:any[]=[];let first:any;
async function api(operation:string,body:any,context=ctx){return route.POST(new Request('http://localhost/api/economic-outcomes/'+operation,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':context.auth.tenantId,'x-user-id':context.auth.userId,'x-user-role':context.auth.role},body:JSON.stringify(body)}),{params:Promise.resolve({operation})});}
async function check(id:string,fn:()=>Promise<any>){try{results.push({id,status:'PASS',observed:await fn()});}catch(error){results.push({id,status:'FAIL',error:String(error)});}await writeFile(join(out,'partial-results.json'),JSON.stringify({results,before,qualification:'DISPOSABLE_LOCAL_OWNER_NOT_PROTECTED_SOURCE_AUTHORITY'},null,2));console.log(JSON.stringify({id,status:results.at(-1).status,error:results.at(-1).error}));}
try{
await check('authenticated-native-register-and-sql-independent-readback',async()=>{const f=economicFixture(8,0,15),input={estimand:f.input.estimand,rightsRef:'generated-owner-rights',mode:'RETROSPECTIVE' as const,idempotencyKey:'original'};const r=await api('register',input);const body=await r.json();assert.equal(r.status,200,JSON.stringify(body));first={input,record:(body as any).record};const row=(await admin.query('SELECT * FROM finnor_os.s7_economic_records WHERE tenant_id=$1 AND principal_id=$2 AND record_id=$3',[tenant,principal,first.record.ref.id])).rows[0];assert.deepEqual(row.body,first.record);assert.equal(row.kind,'PREREGISTRATION');assert.equal(first.record.protectedReceipt,null);return {input,record:first.record,sql:row};});
await check('immutable-read-and-concurrent-idempotent-semantic-retry',async()=>{assert(first);try{await owner.readEnterpriseEconomicRecord(ctx,{id:first.record.ref.id});}catch(error:any){await writeFile(join(out,'native-read-failure.json'),JSON.stringify({code:error.code,message:error.message,stack:error.stack},null,2));}const read=await api('read',{id:first.record.ref.id});assert.equal(read.status,200,JSON.stringify(await read.clone().json()));const replies=await Promise.all(Array.from({length:16},()=>api('register',first.input)));const bodies=await Promise.all(replies.map(r=>r.json()));assert(replies.every(r=>r.status===200),JSON.stringify(bodies));assert(bodies.every((b:any)=>b.record.ref.id===first.record.ref.id));const n=(await admin.query("SELECT count(*)::int n FROM finnor_os.s7_economic_records WHERE tenant_id=$1 AND kind='PREREGISTRATION'",[tenant])).rows[0].n;assert.equal(n,1);const changed=structuredClone(first.input);changed.estimand.currency='EUR';const conflict=await api('register',changed);assert.equal(conflict.status,409,JSON.stringify(await conflict.json()));return {replies:replies.map(r=>r.status),rows:n};});
await check('unprotected-retrospective-owner-attribution-retains-all-unknowns',async()=>{assert(first);const f=economicFixture(8,-30,15);f.input.accounting.forEach((s:any)=>s.estimandRef=first.record.ref);const r=await api('assess',{estimandId:first.record.ref.id,lookAt:f.input.lookAt,assignments:f.input.assignments,accounting:f.input.accounting,idempotencyKey:'assessment-1',computeCost:{amount:null,pricebookRef:null,meteringRef:null}});const b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));const a=b.record.payload.assessment;assert.equal(a.population.retainedClusters,8);assert.equal(a.population.excludedClusters,0);assert.equal(a.supportedHorizon,'H1');assert.equal(a.contrasts[0].identification,'UNIDENTIFIED');assert.equal(a.completeCosts,false);assert(a.accounting.every((v:any)=>v.wealth===null));return {input:f.input,record:b.record};});
await check('late-correction-keeps-original-and-knowledge-cut',async()=>{assert(first);const oldCut=new Date().toISOString();await new Promise(r=>setTimeout(r,15));const r=await api('append',{kind:'CORRECTION',estimandRefId:first.record.ref.id,record:{reason:'late adverse bill',amount:'25'},sourceRefs:[],validAt:'2023-01-01T00:00:00.000Z',revisionOf:first.record.ref.id,idempotencyKey:'correction-1'});const b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));const original=await api('read',{id:first.record.ref.id});assert.deepEqual(await original.json(),first.record);const beforeCut=await api('history',{estimandId:first.record.ref.id,knowledgeAt:oldCut});const h:any=await beforeCut.json();assert.equal(beforeCut.status,200,JSON.stringify(h));assert(!h.records.some((v:any)=>v.ref.id===b.record.ref.id));await assert.rejects(admin.query('UPDATE finnor_os.s7_economic_records SET valid_at=clock_timestamp() WHERE tenant_id=$1',[tenant]),/append-only/);return {correction:b.record,priorHistory:h};});
await check('commit-after-cut-cannot-be-backdated-into-economic-history',async()=>{assert(first);await admin.query("CREATE FUNCTION finnor_os.s7_test_commit_delay() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.kind='COST' THEN PERFORM pg_sleep(1); END IF; RETURN NEW; END $$");await admin.query("CREATE TRIGGER s7_test_commit_delay BEFORE INSERT ON finnor_os.s7_economic_records FOR EACH ROW EXECUTE FUNCTION finnor_os.s7_test_commit_delay()");const pending=api('append',{kind:'COST',estimandRefId:first.record.ref.id,record:{amount:'17',unmetered:false},sourceRefs:[],validAt:'2023-01-01T00:00:00.000Z',idempotencyKey:'held-commit'});await new Promise(r=>setTimeout(r,400));const cut=new Date().toISOString();const r=await pending,b:any=await r.json();assert.equal(r.status,200,JSON.stringify(b));const hResponse=await api('history',{estimandId:first.record.ref.id,knowledgeAt:cut}),h:any=await hResponse.json();const evidence={record:b.record,cut,history:h,commit:(await admin.query('SELECT pg_xact_commit_timestamp(xmin) AS committed_at FROM finnor_os.s7_economic_records WHERE record_id=$1',[b.record.ref.id])).rows[0]};await writeFile(join(out,'commit-cut.json'),JSON.stringify(evidence,null,2));assert(!h.records.some((v:any)=>v.ref.id===b.record.ref.id),'A record committed after the cut appeared as known history');await admin.query('DROP TRIGGER s7_test_commit_delay ON finnor_os.s7_economic_records');await admin.query('DROP FUNCTION finnor_os.s7_test_commit_delay()');return evidence;});
await check('tenant-principal-role-and-HTTP-evidence-authority-attacks',async()=>{assert(first);const foreign=await api('read',{id:first.record.ref.id},{auth:{tenantId:otherTenant,userId:otherPrincipal,employeeId:otherPrincipal,role:'owner'}});assert.equal(foreign.status,404);const denied=await api('register',first.input,{auth:{...ctx.auth,role:'technician'}});assert.equal(denied.status,404);const injection=await api('assess',{estimandId:first.record.ref.id,lookAt:'2024-01-01T00:00:00.000Z',assignments:[],accounting:[],idempotencyKey:'forged',computeCost:{amount:null,pricebookRef:null,meteringRef:null},evidence:[{signatureVerified:true}]});assert.equal(injection.status,400);const rls=await db.withTenantTransaction(otherTenant,{userId:otherPrincipal,readOnly:true},async(_db,c)=>(await c.query('SELECT record_id FROM finnor_os.s7_economic_records')).rows);assert.equal(rls.length,0);return {foreign:foreign.status,role:denied.status,forged:injection.status,ordinaryRlsRows:rls};});
await check('same-tenant-principal-isolation-at-ordinary-SQL-boundary',async()=>{const peer=randomUUID();await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status) VALUES($1,$2,$3,'owner','active')",[peer,tenant,peer+'@generated.invalid']);const rows=await db.withTenantTransaction(tenant,{userId:peer,readOnly:true},async(_db,c)=>(await c.query('SELECT record_id,principal_id FROM finnor_os.s7_economic_records')).rows);await writeFile(join(out,'same-tenant-principal-readback.json'),JSON.stringify({peer,tenant,rows},null,2));assert.equal(rows.length,0,'Another principal could read private economic records through ordinary-role SQL');return {peer,rows};});
await check('post-assignment-question-cannot-be-called-prospective',async()=>{const f=economicFixture(8,0,15),r=await api('register',{estimand:f.input.estimand,rightsRef:'generated-owner-rights',idempotencyKey:'hindsight',mode:'PROSPECTIVE'});assert.equal(r.status,400);return {status:r.status,body:await r.json()};});
}finally{await admin.end();await db.getPool().end();await postgres.stop();}
const after=await snapshot(),unchanged=JSON.stringify(before)===JSON.stringify(after);await writeFile(join(out,'results.json'),JSON.stringify({results,before,after,sourcesUnchanged:unchanged,node:process.version,postgres:{directory,port,migrations},resources:process.resourceUsage(),qualification:'REAL_ORDINARY_ROLE_POSTGRESQL_AND_DEV_AUTH_HANDLER_ONLY; GENERATED_UNPROTECTED_INPUTS; NO_FIELD_H2',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-owner-e2e.mts'},null,2)+'\n');const failed=results.some(v=>v.status==='FAIL')||!unchanged;console.log(JSON.stringify({out,failed,sourcesUnchanged:unchanged}));process.exit(failed?1:0);
