/** Negative maturity challenge of the public inference owner. Synthetic resolver
 * descriptors exercise temporal qualification, never supply a field certificate. */
import {strict as assert} from 'node:assert';
import {mkdir,writeFile,readFile} from 'node:fs/promises';import {resolve,join} from 'node:path';import {createHash} from 'node:crypto';
import {economicFixture} from './economic-fixtures.mjs';
import {assessEconomicAttribution} from '../../packages/epistemic-runtime/src/economic-attribution';
const out=resolve(process.env.FINNOR_S7_EVIDENCE_DIR??'../scope-7/scope-evidence/maturity-'+Date.now());await mkdir(out,{recursive:true});const paths=['packages/epistemic-runtime/src/economic-attribution.ts','packages/shared-types/src/economic-attribution.ts','scripts/s7/economic-fixtures.mts','scripts/s7/run-maturity-e2e.mts'];const snapshot=()=>Promise.all(paths.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')})));const before=await snapshot(),f=economicFixture(8,30,15);
// A source cannot have observed a 2024 endpoint in 2020, irrespective of labels.
f.input.evidence.forEach((v:any)=>{v.sourceOrigin='FIELD';v.protectionDomain='REVIEWED_PROTECTED_DOMAIN';});const a=assessEconomicAttribution(f.input);let failure:string|null=null;try{assert.equal(a.supportedHorizon,'H1','An endpoint commitment made before the endpoint was promoted to H2');}catch(e){failure=String(e);}const after=await snapshot(),unchanged=JSON.stringify(before)===JSON.stringify(after);await writeFile(join(out,'results.json'),JSON.stringify({id:'preendpoint-source-cannot-become-field-H2-through-age-or-labels',status:failure||!unchanged?'FAIL':'PASS',failure,input:f.input,observed:a,before,after,sourcesUnchanged:unchanged,qualification:'ISOLATED_NEGATIVE_TEMPORAL_MATURITY_CHALLENGE_WITH_SYNTHETIC_RESOLVER_DESCRIPTORS; NOT_FIELD_PROOF',rerun:'FINNOR_S7_EVIDENCE_DIR=<new-dir> node --import=tsx scripts/s7/run-maturity-e2e.mts'},null,2)+'\n');console.log(JSON.stringify({status:failure?'FAIL':'PASS',failure,observed:a.supportedHorizon,out}));process.exitCode=failure||!unchanged?1:0;
