/**
 * B7.T1: keep the API authorization inventory derived from the route source rather
 * than a hand-maintained security document that can silently drift.
 *
 * This intentionally reports the guard *pattern*, not an inferred permission. A
 * route using a bespoke guard is therefore visible as `custom` for review instead
 * of being incorrectly presented as public or role-gated.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const appRoot = join(import.meta.dirname, "..", "apps", "api", "app", "api");
const output = join(import.meta.dirname, "..", "docs", "authz-matrix.md");

async function routeFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return routeFiles(path);
    return entry.name === "route.ts" ? [path] : [];
  }));
  return nested.flat();
}

function methods(source: string): string {
  const found = [...source.matchAll(/export\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE|OPTIONS)\b/g)].map((match) => match[1]);
  return found.length > 0 ? found.join(", ") : "—";
}

function guard(source: string, path: string): string {
  if (path.includes("/webhooks/")) return "webhook signature / provider verification";
  if (path.includes("/admin/")) return "ADMIN_SECRET";
  if (/(?:requireContext|requireIcContext|handleIcPost|handleIcGet)\s*\(/.test(source)) {
    if (/ctx\.role\s*!==\s*["']owner["']|role\s*!==\s*["']owner["']|requireOwner\s*\(/.test(source)) return "JWT + tenant context + owner";
    if (/\/api\/(?:actions|operations|queries)(?:\/|$)/.test(path)) return "JWT + tenant context + employee authority runtime";
    return "JWT + tenant context";
  }
  return "custom / review required";
}

export async function renderAuthzMatrix(): Promise<string> {
  const files = await routeFiles(appRoot);
  const rows = await Promise.all(files.sort().map(async (file) => {
    const source = await readFile(file, "utf8");
    const apiPath = "/api/" + relative(appRoot, file).replace(/\/route\.ts$/, "").replaceAll("\\", "/").replace(/\/\[([^\]]+)\]/g, "/:$1");
    return `| \`${methods(source)}\` | \`${apiPath === "/api/" ? "/api" : apiPath}\` | ${guard(source, file)} |`;
  }));
  return [
    "# API Authorization Matrix",
    "",
    "Generated by `npm run authz:matrix`. Do not edit by hand; CI rejects drift.",
    "",
    "| Methods | Route | Guard pattern |",
    "|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const rendered = await renderAuthzMatrix();
  if (check) {
    const current = await readFile(output, "utf8").catch(() => "");
    if (current !== rendered) {
      console.error("Authorization matrix is stale. Run: npm run authz:matrix");
      process.exitCode = 1;
    }
  } else {
    await writeFile(output, rendered);
  }
}

if (process.argv[1]?.endsWith("generate-authz-matrix.ts")) void main();
