/** Native-owner E2E extension. Local TLS contract and disposable independent roots. */
import {strict as assert} from 'node:assert';
import {createHash,generateKeyPairSync,sign,verify,randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,realpath,chmod} from 'node:fs/promises';
import {createServer as httpServer} from 'node:http';
import {createServer as httpsServer} from 'node:https';
import {spawn,spawnSync,type ChildProcess} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';

const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort((a,b)=>a.localeCompare(b)).map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const hash=(v:any)=>createHash('sha256').update(canonical(v)).digest('hex');
const bytesHash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const publicPem=(k:any)=>k.publicKey.export({type:'spki',format:'pem'}).toString();
const privatePem=(k:any)=>k.privateKey.export({type:'pkcs8',format:'pem'}).toString();
const listen=(server:any)=>new Promise<number>(done=>server.listen(0,'127.0.0.1',()=>done(server.address().port)));
const close=(server:any)=>new Promise<void>(done=>{server.closeAllConnections?.();server.close(()=>done());});

export async function proveGovernedDispatch(f:any,obligation:any,api:any,admin:any,artifact:any,revokeBeforeDispatch=false,workflowProof?:'delivery'|'cancel'|'crash'|'stale',recoveryBudgetProof=false,observer?:{onUnresolved?:(value:any)=>Promise<void>}){
 const root=await realpath(await mkdtemp(join(tmpdir(),'finnor-s6-dispatch-'))),requests:any[]=[],authorityCalls:any[]=[],steps:any[]=[];
 const ownerKey=generateKeyPairSync('ed25519'),methodKey=generateKeyPairSync('ed25519'),businessKey=generateKeyPairSync('ed25519'),ledgerKey=generateKeyPairSync('ed25519'),reviewer=generateKeyPairSync('ed25519');
 const controlToken=randomUUID()+randomUUID(),protectedToken=randomUUID()+randomUUID(),s5Token=randomUUID()+randomUUID(),consumerToken=randomUUID()+randomUUID(),providerToken=randomUUID()+randomUUID(),authorityToken=randomUUID()+randomUUID();
 const originalEnvironment={FINNOR_S6_CURRENT_OWNER_SIGNER:process.env.FINNOR_S6_CURRENT_OWNER_SIGNER,FINNOR_S6_OWNER_TRANSPORT_CONFIG:process.env.FINNOR_S6_OWNER_TRANSPORT_CONFIG,FINNOR_S6_OWNER_TRANSPORT_ROOT:process.env.FINNOR_S6_OWNER_TRANSPORT_ROOT};
 const pathOf=(name:string)=>join(root,name);
 async function secret(name:string,value:string){const path=pathOf(name);await writeFile(path,value,{mode:0o600});return path;}
 await secret('owner.pem',privatePem(ownerKey));process.env.FINNOR_S6_CURRENT_OWNER_SIGNER=pathOf('owner.pem');
 const certificate=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',pathOf('tls.key'),'-out',pathOf('tls.crt'),'-days','1','-subj','/CN=127.0.0.1','-addext','subjectAltName=IP:127.0.0.1'],{encoding:'utf8'});assert.equal(certificate.status,0,certificate.stderr);
 await chmod(pathOf('tls.crt'),0o600);
 const ca=await readFile(pathOf('tls.crt'),'utf8'),account=randomUUID(),recordKey='price/'+f.root.entityId;
 const recordKeys=obligation.intervention.channels.map((channel:any,index:number)=>index===0?recordKey:channel.exposureId+'/'+f.root.entityId);
 const providerRecords=new Map<string,any>(recordKeys.map((key:string)=>[key,{applicationAccountId:account,recordKey:key,version:'"v1"',fields:{priceAdjustmentFraction:0},lastOperationId:null}]));
 let current=providerRecords.get(recordKey)!;
 let readFault:'NONE'|'WRONG_RECORD'|'NULL'='NONE',lostResponse=true,activeWorkerPid:number|undefined,killWorkerOnPatch=workflowProof==='crash',scheduledRunId:string|undefined;
 const provider=httpsServer({key:await readFile(pathOf('tls.key')),cert:ca},async(req,res)=>{
  let raw='';for await(const chunk of req)raw+=chunk;requests.push({method:req.method,url:req.url,authorizationMatched:req.headers.authorization==='Bearer '+providerToken,ifMatch:req.headers['if-match'],body:raw?JSON.parse(raw):null,readFault,at:new Date().toISOString()});
  const key=recordKeys.find((key:string)=>req.url===`/accounts/${account}/records/${encodeURIComponent(key)}`);let record=key?providerRecords.get(key):null;
  if(req.headers.authorization!=='Bearer '+providerToken||!record){res.writeHead(403);res.end('{}');return;}
  if(req.method==='PATCH'){
   if(req.headers['if-match']!==record.version){res.writeHead(412);res.end('{}');return;}
   const input=JSON.parse(raw);assert.deepEqual(Object.keys(input).sort(),['changes','operationId']);assert.deepEqual(input.changes,{priceAdjustmentFraction:0.15});
   record={...record,version:'"v2"',fields:{...record.fields,...input.changes},lastOperationId:input.operationId};providerRecords.set(key!,record);current=providerRecords.get(recordKey)!;
   if(killWorkerOnPatch){assert(activeWorkerPid);process.kill(activeWorkerPid,'SIGKILL');if(recordKeys.length>1){assert(processHandle?.pid);processHandle.kill('SIGKILL');}killWorkerOnPatch=false;}
   if(lostResponse){req.socket.destroy();return;}
  }
  let value:any=record;if(req.method==='GET'&&readFault==='WRONG_RECORD')value={...record,recordKey:'unrelated-record'};
  if(req.method==='GET'&&readFault==='NULL')value={...record,fields:{priceAdjustmentFraction:null}};
  res.writeHead(200,{'content-type':'application/json','etag':record.version,'cache-control':'no-store'});res.end(JSON.stringify(value));
 });
 const providerPort=await listen(provider),origin=`https://127.0.0.1:${providerPort}`;
 const {POST}=await import('../../apps/api/app/api/obligations/[operation]/route.js');
 const authority=httpServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const input=JSON.parse(raw),operation=req.url?.split('/').at(-1),call:any={input,operation,at:new Date().toISOString()};authorityCalls.push(call);if(req.headers.authorization!=='Bearer '+authorityToken){res.writeHead(401);res.end('{}');return;}if(!['check-dispatch','check-budget'].includes(operation??'')){res.writeHead(404);res.end('{}');return;}const answer=await POST(new Request('http://localhost/api/obligations/'+operation,{method:'POST',headers:{'content-type':'application/json',...(f.token?{authorization:'Bearer '+f.token}:{'x-tenant-id':f.tenant,'x-user-id':f.principal})},body:raw}),{params:Promise.resolve({operation:operation!})});const bytes=await answer.text();call.assessment=JSON.parse(bytes);if(input.delivery){call.leases=(await admin.query('SELECT s.lease_expires_at AS step_lease,j.lease_expires_at AS job_lease FROM finnor_os.workflow_steps s JOIN finnor_os.workflow_step_claims sc ON sc.tenant_id=s.tenant_id AND sc.workflow_step_id=s.id AND sc.claim_token=s.claim_token JOIN finnor_os.job_delivery_attempts a ON a.tenant_id=sc.tenant_id AND a.id=sc.job_delivery_attempt_id JOIN finnor_os.jobs j ON j.tenant_id=a.tenant_id AND j.id=a.job_id WHERE s.tenant_id=$1 AND s.id=$2',[f.tenant,input.delivery.workflowStepId])).rows[0];}
  if(input.delivery?.kind==='RECOVERY')call.leases=(await admin.query('SELECT s.lease_expires_at AS step_lease,j.lease_expires_at AS job_lease FROM finnor_os.workflow_steps s JOIN finnor_os.jobs j ON j.tenant_id=s.tenant_id AND j.id=$3 WHERE s.tenant_id=$1 AND s.id=$2',[f.tenant,input.delivery.workflowStepId,input.delivery.jobId])).rows[0];
  if(workflowProof==='stale'&&operation==='check-dispatch'&&authorityCalls.filter(c=>c.operation==='check-dispatch').length===1){assert.equal(call.assessment.status,'CURRENT');assert(scheduledRunId);call.cancellation=await api(f,'cancel-delivery',{obligationRef:obligation.ref,workflowRunId:scheduledRunId,expectedVersion:input.delivery.runVersion},POST);assert.equal(call.cancellation.status,200);assert.equal(call.cancellation.body.ok,true);}
  res.writeHead(answer.status,{'content-type':'application/json'});res.end(bytes);});
 const authorityPort=await listen(authority);
 const ownerSources=['packages/private-equity/src/enterprise-obligations.ts','packages/private-equity/src/enterprise-allocation.ts','packages/private-equity/src/enterprise-control.ts','packages/private-equity/src/enterprise-beliefs.ts','packages/private-equity/src/allocation-store.ts','packages/private-equity/src/obligation-contracts.ts','apps/api/app/api/obligations/[operation]/route.ts'];
 const digests=async(paths:string[])=>Promise.all(paths.map(async path=>({path:resolve(path),sha256:bytesHash(await readFile(path))})));
 const fsExt=dirname(createRequire(import.meta.url).resolve('fs-ext/package.json'));
 const sourcePaths=['packages/governed-execution/src/ledger.ts','packages/governed-execution/src/ledger-server.mts','packages/governed-execution/src/protocol.ts','packages/governed-execution/src/request-verifier.ts','packages/governed-execution/src/adapter-contract.ts','packages/governed-execution/src/dispatch-broker.ts','packages/governed-execution/src/broker-io.ts',join(fsExt,'fs-ext.js'),join(fsExt,'build/Release/fs_ext.node'),join(fsExt,'package.json')];
 let processHandle:ChildProcess|undefined,base='',logs='';
 const start=async()=>{logs='';processHandle=spawn(process.execPath,['--import=tsx','packages/governed-execution/src/ledger-server.mts'],{cwd:process.cwd(),env:{PATH:process.env.PATH!,HOME:root,FINNOR_S6_LEDGER_CONFIG:pathOf('ledger.json'),FINNOR_S6_LEDGER_RELEASE_ROOT:publicPem(reviewer),FINNOR_S6_DISPATCH_RELEASE_ROOT:publicPem(reviewer)},stdio:['ignore','pipe','pipe']});await new Promise<void>((done,no)=>{const timer=setTimeout(()=>{processHandle?.kill('SIGKILL');no(Error('BROKER_BOOT_TIMEOUT'));},15000);processHandle!.stdout!.on('data',bytes=>{logs+=bytes.toString();for(const line of logs.split('\n'))try{const parsed=JSON.parse(line);if(parsed.status==='READY'){base=`http://127.0.0.1:${parsed.port}`;clearTimeout(timer);done();}}catch{}});processHandle!.stderr!.on('data',bytes=>logs+=bytes.toString());processHandle!.once('exit',(code,signal)=>{clearTimeout(timer);no(Error(`BROKER_EXIT:${code}:${signal}:${logs}`));});});};
 const stop=async(signal:NodeJS.Signals='SIGTERM')=>{const p=processHandle;if(!p||p.exitCode!==null||p.signalCode!==null)return;await new Promise<void>(done=>{p.once('exit',()=>done());p.kill(signal);});};
  const call=async(path:string,body?:any,token=controlToken)=>{const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,body:await response.json() as any};};
 const protectedHistory=async()=>{
  const journal=(await readFile(pathOf('protected/commitments.jsonl'),'utf8')).trim().split('\n').map(line=>JSON.parse(line));
  const events=[];
  for(const receipt of journal.filter((r:any)=>r.kind==='EVENT'&&r.protectedExecution===true)){
   const read=await call('/events/'+encodeURIComponent(receipt.identity));assert.equal(read.status,200,JSON.stringify(read));assert.deepEqual(read.body.receipt,receipt);events.push(read.body);
  }
  return events;
 };
 try{
  const sourceDigests=await digests(sourcePaths);
  const ledgerPolicy={schema:'finnor.s6.ledger-policy.v1',domain:'DISPOSABLE_TEST_AUTHORITY',signerPublicKey:publicPem(ledgerKey),methodAdmissionPublicKey:publicPem(methodKey),maxEntries:100000,owners:[
   {owner:'S6',tenantId:f.tenant,principalId:f.principal,rightsRefs:[obligation.rightsRef],tokenHash:bytesHash(controlToken),append:true,read:true,sealedAppend:false,sealedRead:false,dispatch:true},
   {owner:'S6',tenantId:f.tenant,principalId:f.principal,rightsRefs:[obligation.rightsRef],tokenHash:bytesHash(protectedToken),append:true,read:true,sealedAppend:false,sealedRead:false,protectedExecution:true},
   {owner:'S5',tenantId:f.tenant,principalId:f.principal,rightsRefs:[obligation.rightsRef],tokenHash:bytesHash(s5Token),append:true,read:true,sealedAppend:false,sealedRead:false},
   {owner:'S7',tenantId:f.tenant,principalId:f.principal,rightsRefs:[obligation.rightsRef],tokenHash:bytesHash(consumerToken),append:false,read:true,sealedAppend:false,sealedRead:false}
  ]};
  const releaseBody={schema:'finnor.s6.ledger-release.v3',releaseId:'disposable-governed-dispatch',sourceDigests,runtime:{node:process.version,nodeAbi:process.versions.modules,platform:process.platform,arch:process.arch},policyDigest:hash(ledgerPolicy),validUntil:new Date(Date.now()+3600000).toISOString()};
  const brokerPolicy={schema:'finnor.s6.dispatch-policy.v1',domain:'DISPOSABLE_TEST_AUTHORITY',validUntil:releaseBody.validUntil,protectedTokenPath:await secret('protected.token',protectedToken),protectedTokenSha256:bytesHash(protectedToken),businessOwnerPublicKey:publicPem(businessKey),authority:{endpoint:`http://127.0.0.1:${authorityPort}`,tokenPath:await secret('authority.token',authorityToken),tokenSha256:bytesHash(authorityToken),publicKey:publicPem(ownerKey),sourceDigests:await digests(ownerSources)},routes:[{providerOrigin:origin,applicationAccountId:account,contract:'CONDITIONAL_JSON_RECORD_V1',tokenPath:await secret('provider.token',providerToken),tokenSha256:bytesHash(providerToken),caPath:pathOf('tls.crt'),caSha256:bytesHash(ca)}]};
  await secret('broker.json',JSON.stringify({policy:brokerPolicy,signature:sign(null,Buffer.from(canonical(brokerPolicy)),reviewer.privateKey).toString('base64')}));
  await secret('ledger-key.pem',privatePem(ledgerKey));
  await secret('ledger.json',JSON.stringify({policy:ledgerPolicy,release:{...releaseBody,signature:sign(null,Buffer.from(canonical(releaseBody)),reviewer.privateKey).toString('base64')},signerPath:pathOf('ledger-key.pem'),protectedDirectory:pathOf('protected'),contentDirectory:pathOf('ordinary'),dispatchConfigPath:pathOf('broker.json'),port:0}));
  await start();
  const {ref,...content}=obligation;const originReceipt=await call('/references',{reference:{...ref,content},rightsRefs:[obligation.rightsRef]});assert.equal(originReceipt.status,200,JSON.stringify(originReceipt));
  const channels=obligation.intervention.channels;for(const channel of channels){assert.equal(channel.doses[0],0.15);assert.equal(channel.operation,'PRICE_CHANGE');assert.equal(channel.unit,'fraction');}
  const proposalInput={obligationRef:ref,bindings:channels.map((channel:any,index:number)=>({exposureId:channel.exposureId,methodRef:{owner:'S8',id:'method:'+'1'.repeat(64),version:'json-field-replace-v1',contentDigest:'1'.repeat(64)},providerOrigin:origin,applicationAccountId:account,recordKey:recordKeys[index],field:'priceAdjustmentFraction',expectedVersion:'"v1"'}))};
  const proposed=await api(f,'compile-request',proposalInput,POST);assert.equal(proposed.status,200);
  const admissions=channels.map((channel:any,index:number)=>{
   const body={schema:'finnor.s8.method-admission.v1',domain:'DISPOSABLE_TEST_AUTHORITY',tenantId:f.tenant,principalId:f.principal,rightsRef:obligation.rightsRef,obligationRef:ref,effectRef:obligation.effectRef,compiler:proposed.body.ir.compiler,verifierSourceDigests:sourceDigests,validAfter:new Date(Date.now()-1000).toISOString(),validUntil:releaseBody.validUntil,semantic:{exposureId:channel.exposureId,target:channel.target,operation:channel.operation,unit:channel.unit,intendedExposure:channel.intendedExposure,permittedRefinements:[],doseRange:[-1,1]},request:{kind:'CONDITIONAL_JSON_FIELDS_REPLACE',providerOrigin:origin,applicationAccountId:account,recordKey:recordKeys[index],field:'priceAdjustmentFraction',expectedVersion:'"v1"'},qualification:'DISPOSABLE_MAPPING_ONLY'};
   const methodRef={owner:'S8',id:'method:'+hash(body),version:'json-field-replace-v1',contentDigest:hash(body)};proposalInput.bindings[index]!.methodRef=methodRef;
   return {ref:methodRef,body,signature:sign(null,Buffer.from(canonical(body)),methodKey.privateKey).toString('base64')};
  });
  const compiled=await api(f,'compile-request',proposalInput,POST);assert.equal(compiled.status,200);
  const request={ref:compiled.body.ref,ir:compiled.body.ir,admissions};
  const grantBody={schema:'finnor.business-owner.effect-authorization.v1',domain:'DISPOSABLE_TEST_AUTHORITY',tenantId:f.tenant,principalId:f.principal,rightsRef:obligation.rightsRef,obligationRef:ref,requestRef:request.ref,effectRef:obligation.effectRef,mandateRef:obligation.mandateRef,allocationRef:obligation.allocationRef,consumptionRef:obligation.consumptionRef,resourceEnvelope:obligation.resourceEnvelope,validAfter:new Date(Date.now()-1000).toISOString(),validUntil:releaseBody.validUntil};
  const input={request,authorization:{body:grantBody,signature:sign(null,Buffer.from(canonical(grantBody)),businessKey.privateKey).toString('base64')}};
  const origin5=generateKeyPairSync('ed25519');await secret('s5-origin.pem',privatePem(origin5));await secret('s5.token',s5Token);await secret('control.token',controlToken);
  const originValidAfter=new Date(Date.now()-1000).toISOString();
  const configureTransport=async()=>{const transportPolicy={schema:'finnor.s6.owner-transport-policy.v1',domain:'DISPOSABLE_TEST_AUTHORITY',validAfter:new Date(Date.now()-1000).toISOString(),validUntil:releaseBody.validUntil,routes:['S6','S5'].map(semanticOwner=>({semanticOwner,tenantId:f.tenant,principalId:f.principal,rightsRefs:[obligation.rightsRef],originKeys:[{id:'owner-origin',publicKey:publicPem(origin5),validAfter:originValidAfter,validUntil:releaseBody.validUntil,revoked:false}],originSigner:{keyId:'owner-origin',path:pathOf('s5-origin.pem')},tokenPath:pathOf(semanticOwner==='S6'?'control.token':'s5.token'),tokenSha256:bytesHash(semanticOwner==='S6'?controlToken:s5Token),ledger:{endpoint:base,acceptedReceipts:[{signerPublicKey:publicPem(ledgerKey),releaseId:releaseBody.releaseId,verifierDigest:hash(sourceDigests),policyDigest:hash(ledgerPolicy)},...((releaseBody as any).compatibleHistory??[]).map((pin:any)=>({...pin,signerPublicKey:publicPem(ledgerKey)}))]},requestTimeoutMs:10000,leaseMs:30000}))};await secret('transport.json',JSON.stringify({policy:transportPolicy,signature:sign(null,Buffer.from(canonical(transportPolicy)),reviewer.privateKey).toString('base64')}));process.env.FINNOR_S6_OWNER_TRANSPORT_CONFIG=pathOf('transport.json');process.env.FINNOR_S6_OWNER_TRANSPORT_ROOT=publicPem(reviewer);};
  await configureTransport();
  if(!workflowProof&&!revokeBeforeDispatch&&!recoveryBudgetProof){
   const budgets=await api(f,'budget-status',{obligationRef:obligation.ref},POST);
   const handoff=await call('/execution-handoff/'+encodeURIComponent(obligation.ref.id),undefined,consumerToken);
   await artifact('contract-lifecycle-before-dispatch.json',{budgets,handoff,requests});
   assert.equal(budgets.status,200,JSON.stringify({budgets,handoff}));
   assert.equal(handoff.status,200,JSON.stringify(handoff));assert.equal(handoff.body.handoff.schema,'finnor.s6.consumer-handoff.v1');assert.equal(handoff.body.handoff.attributionGranted,false);
   const overdraw=await api(f,'check-budget',{obligationRef:obligation.ref,requestRef:request.ref,memberId:request.ir.members[0].memberId,phase:'EXECUTION',ordinal:1,units:1000,nonce:randomUUID()},POST);
   assert.equal(overdraw.status,409,JSON.stringify(overdraw));assert.equal(requests.length,0,'Budget refusal allowed provider egress');
  }
  if(workflowProof){
   const scheduled=await api(f,'schedule-request',input,POST);assert.equal(scheduled.status,200,JSON.stringify(scheduled));assert.equal(scheduled.body.executionAuthorityGranted,false);assert.equal(scheduled.body.status,'QUEUED_REQUIRES_PROTECTED_REVALIDATION');
   scheduledRunId=scheduled.body.workflowRunId;
   const replay=await api(f,'schedule-request',input,POST);assert.equal(replay.status,200);assert.equal(replay.body.commandId,scheduled.body.commandId);assert.equal(replay.body.workflowStepId,scheduled.body.workflowStepId);
   const graph=async()=>(await admin.query('SELECT s.*,r.status AS run_status,r.version AS run_version,c.payload AS command_payload,c.authorized_effect_hash,j.type AS job_type,j.protocol_version AS job_protocol,j.run_at,j.status AS job_status,j.attempts AS job_attempts FROM finnor_os.workflow_steps s JOIN finnor_os.workflow_runs r ON r.tenant_id=s.tenant_id AND r.id=s.workflow_run_id JOIN finnor_os.commands c ON c.tenant_id=r.tenant_id AND c.id=r.command_id JOIN finnor_os.jobs j ON j.tenant_id=s.tenant_id AND j.payload->>\'workflowStepId\'=s.id::text WHERE s.tenant_id=$1 AND s.id=$2',[f.tenant,scheduled.body.workflowStepId])).rows;
   const queued=await graph();assert.equal(queued.length,1);assert.equal(queued[0].job_type,'run_workflow_step_v3');assert.equal(queued[0].job_protocol,3);assert.equal(queued[0].status,'pending');assert.equal(queued[0].run_at.toISOString(),obligation.deadline.businessStartAt);assert.equal(queued[0].business_effect_id,obligation.effectRef.id);assert.equal(queued[0].authorized_effect_hash,obligation.effectRef.semanticHash);assert.deepEqual(queued[0].payload.execution,input);
   const changed=structuredClone(input);changed.request.ir.members[0].request.recordKey='different-record';changed.request.ref={...request.ref,id:'request-ir:'+hash(changed.request.ir),contentDigest:hash(changed.request.ir)};
   const conflict=await api(f,'schedule-request',changed,POST);assert(conflict.status>=400);assert.equal((await graph()).length,1);assert.equal(requests.length,0);
   const workers:any[]=[];
   const worker=async(expectKilled=false,allowIdle=false)=>{
    const env:any={};for(const key of ['PATH','HOME','TMPDIR','NODE_ENV','DATABASE_URL','FINNOR_TEST_MANAGED_EXTENSIONS','FINNOR_S3_PYTHON','FINNOR_S4_POLICY_STORE','FINNOR_S3_MODEL_STORE','FINNOR_S5_PYTHON','FINNOR_S6_OWNER_TRANSPORT_CONFIG','FINNOR_S6_OWNER_TRANSPORT_ROOT'])if(process.env[key])env[key]=process.env[key];
    env.LOG_LEVEL='silent';env.CI='1';env.FINNOR_S6_TEST_TENANT_ID=f.tenant;if(workflowProof==='crash'){env.FINNOR_STEP_LEASE_SECONDS='5';env.WORKER_JOB_LEASE_SECONDS='5';}
    const p=spawn(process.execPath,['--import=tsx','scripts/s6/governed-workflow-worker.mts'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});activeWorkerPid=p.pid;let log='';p.stdout!.on('data',b=>log+=b.toString());p.stderr!.on('data',b=>log+=b.toString());
    const terminal=await new Promise<any>((done,no)=>{const timer=setTimeout(()=>{p.kill('SIGKILL');no(Error('WORKFLOW_PROCESS_TIMEOUT:'+log));},60000);p.once('error',no);p.once('exit',(exitCode,signal)=>{clearTimeout(timer);done({pid:p.pid,exitCode,signal,log,role:allowIdle?'LEASE_SWEEPER':'DELIVERY'});});});workers.push(terminal);
    if(expectKilled){assert.equal(terminal.signal,'SIGKILL');const census=spawnSync('ps',['-p',String(p.pid),'-o','pid=,ppid=,pgid=,uid=,stat=,command='],{encoding:'utf8'});assert.equal(census.status,1);terminal.reaped={exitCode:census.status,output:census.stdout};}
    else{assert.equal(terminal.exitCode,0,log);assert.match(log,allowIdle?/"worked":false/:/"worked":true/);}return terminal;
   };
   if(workflowProof==='cancel'){
    const cancelled=await api(f,'cancel-delivery',{obligationRef:ref,workflowRunId:scheduled.body.workflowRunId,expectedVersion:queued[0].run_version},POST);assert.equal(cancelled.status,200,JSON.stringify(cancelled));assert.equal(cancelled.body.ok,true);
    await worker();const after=await graph();assert.equal(after[0].run_status,'cancelled');assert.equal(after[0].execution_state,'cancelled_before_effect');assert.equal(requests.length,0);
    const bypass=await api(f,'execute-request',input,POST);assert(bypass.status>=400);assert.equal(requests.length,0);
    const liabilities=(await admin.query('SELECT st.status,r.status AS reservation_status,r.envelopes FROM finnor_os.s5_consumption_states st JOIN finnor_os.s5_consumptions co USING(tenant_id,consumption_id) JOIN finnor_os.s5_reservations r USING(tenant_id,reservation_id) WHERE st.tenant_id=$1',[f.tenant])).rows;assert.deepEqual(liabilities[0].envelopes,obligation.resourceEnvelope);assert.notEqual(liabilities[0].reservation_status,'RELEASED');
    const proof={scheduled,replay,queued,conflict,cancelled,after,bypass,workers,liabilities,requests,authorityCalls,sourceDigests,qualification:'ACTUAL_QUEUE_AND_NATIVE_CANCELLATION; DISPOSABLE_LOCAL_TLS_AUTHORITY'};await artifact('workflow-cancel.json',proof);return proof;
   }
   await worker(workflowProof==='crash');const waiting=await graph();
   if(workflowProof==='stale'){assert.equal(authorityCalls.filter(c=>c.operation==='check-dispatch')[0].assessment.status,'CURRENT');assert.equal(authorityCalls.filter(c=>c.operation==='check-dispatch')[1].assessment.status,'STALE_INPUT');assert(authorityCalls.filter(c=>c.operation==='check-dispatch')[1].assessment.reasons.includes('WORKFLOW_DELIVERY_FENCE_NOT_CURRENT'));assert.equal(waiting[0].run_status,'cancelled');assert.equal(waiting[0].status,'waiting_observation');assert.equal(requests.length,0);const proof={scheduled,replay,queued,conflict,waiting,workers,requests,authorityCalls,sourceDigests};await artifact('workflow-stale.json',proof);return proof;}
   if(workflowProof==='crash'){
    await artifact('workflow-crash-before-recovery.json',{scheduled,waiting,workers,requests,authorityCalls,current});assert.equal(waiting[0].status,'leased');assert.equal(waiting[0].job_status,'running');assert(waiting[0].effect_commit_at);
    for(const a of authorityCalls.filter(a=>a.assessment.status==='CURRENT')){assert(a.leases);assert(Date.parse(a.assessment.validUntil)<=a.leases.step_lease.getTime(),'OWNER_ASSESSMENT_EXCEEDS_STEP_LEASE');assert(Date.parse(a.assessment.validUntil)<=a.leases.job_lease.getTime(),'OWNER_ASSESSMENT_EXCEEDS_JOB_LEASE');}
    await new Promise(done=>setTimeout(done,5600));const swept=await worker(false,true);assert.match(swept.log,/"recovered":1/);const parked=(await graph())[0];assert.equal(parked.status,'waiting_observation');assert.equal(parked.dispatch_generation,queued[0].dispatch_generation);assert.equal(parked.job_status,'queued');assert(parked.run_at.getTime()>Date.now());
   }
   else{assert.equal(waiting[0].status,'waiting_observation',JSON.stringify(waiting));assert.equal(waiting[0].job_status,'queued');assert.equal(waiting[0].evidence.settlementEstablished,false);}assert.equal(requests.filter(r=>r.method==='PATCH').length,1);assert.equal(current.fields.priceAdjustmentFraction,0.15);
   const previous=processHandle!,killedPid=previous.pid;await stop('SIGKILL');assert.equal(previous.signalCode,'SIGKILL');const reaped=spawnSync('ps',['-p',String(killedPid),'-o','pid='],{encoding:'utf8'});assert.equal(reaped.status,1);await start();await configureTransport();
   let partialRead:any=null;
   if(workflowProof==='crash'){
    assert.equal(request.ir.members.length,2);const before=await protectedHistory();assert.equal(before.filter((r:any)=>r.event.type==='ATTEMPT').length,1);
    partialRead=await api(f,'reconcile-request',input,POST);assert.equal(partialRead.status,200,JSON.stringify(partialRead));assert.equal(partialRead.body.status,'UNRESOLVED');assert.equal(requests.filter(r=>r.method==='PATCH').length,1,'Read-only reconciliation dispatched an unattempted member');
    const row=(await graph())[0],old=(await admin.query('SELECT * FROM finnor_os.job_delivery_attempts WHERE tenant_id=$1 ORDER BY started_at LIMIT 1',[f.tenant])).rows[0];assert(old);
    const staleDelivery={kind:'RECOVERY',workflowStepId:scheduled.body.workflowStepId,claimFence:Number(row.claim_fence),dispatchGeneration:row.dispatch_generation,runVersion:row.run_version,jobId:old.job_id,jobDeliveryAttemptId:old.id,jobClaimToken:old.claim_token,jobClaimFence:Number(old.claim_fence)};
    const stale=await api(f,'execute-request',{...input,delivery:staleDelivery},POST);assert.equal(stale.status,200,JSON.stringify(stale));assert.equal(stale.body.status,'UNRESOLVED');assert(authorityCalls.filter(c=>c.operation==='check-dispatch').at(-1).assessment.reasons.includes('PHYSICAL_JOB_DELIVERY_NOT_CURRENT'));assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
    const replaced=await api(f,'execute-request',{...input,delivery:{...staleDelivery,runVersion:staleDelivery.runVersion+1}},POST);assert.equal(replaced.status,200,JSON.stringify(replaced));assert(authorityCalls.filter(c=>c.operation==='check-dispatch').at(-1).assessment.reasons.includes('WORKFLOW_DELIVERY_FENCE_NOT_CURRENT'));assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
    await artifact('workflow-partial-before-continuation.json',{input,before,partialRead,stale,replaced,staleDelivery,requests,providerRecords:[...providerRecords.values()],workers});
   }
   for(const fault of ['WRONG_RECORD','NULL','NONE'] as const){readFault=fault;const next=(await graph())[0];await new Promise(done=>setTimeout(done,Math.max(1100,next.run_at.getTime()-Date.now()+100)));await worker();const row=(await graph())[0];assert.equal(requests.filter(r=>r.method==='PATCH').length,request.ir.members.length,'A never-attempted original member was stranded or a possibly attempted member replayed');if(fault!=='NONE'){assert.equal(row.status,'waiting_observation');assert.equal(row.run_status,'running');}else{assert.equal(row.status,'completed',JSON.stringify(row));assert.equal(row.run_status,'completed');}}
   const finalHistory=await protectedHistory();
   for(const member of request.ir.members){const attempts=finalHistory.filter((r:any)=>r.event.type==='ATTEMPT'&&r.event.detail.memberId===member.memberId),wire=requests.filter(r=>r.method==='PATCH'&&r.url.endsWith(encodeURIComponent(member.request.recordKey)));assert.equal(attempts.length,1);assert.equal(wire.length,1);assert.equal(providerRecords.get(member.request.recordKey).fields.priceAdjustmentFraction,0.15);assert.equal(providerRecords.get(member.request.recordKey).lastOperationId,attempts[0].event.detail.operationId);}
   const finalVerification=finalHistory.find((r:any)=>r.event.type==='VERIFICATION'&&r.event.detail.status==='VERIFIED');assert(finalVerification);assert.equal(finalVerification.event.detail.memberCount,request.ir.members.length);assert.equal(finalVerification.event.detail.observationEventIds.length,request.ir.members.length);
   if(workflowProof==='crash'){
    const continuation=finalHistory.find((r:any)=>r.event.type==='RECONCILIATION'&&r.event.detail.kind==='CURRENT_AUTHORITY'&&r.event.detail.memberId===request.ir.members[1].memberId);assert(continuation,'Continued member has no durable final current-authority witness');
    const assessment=continuation.event.detail.assessment,{signature,...body}=assessment;assert(verify(null,Buffer.from(canonical(body)),publicPem(ownerKey),Buffer.from(signature,'base64')));assert.equal(assessment.delivery.kind,'RECOVERY');assert.equal(assessment.reservationRevision,obligation.preconditions.reservationRevision+1);assert.equal(assessment.reservationAttemptEventId,finalHistory.find((r:any)=>r.event.type==='ATTEMPT').event.eventId);
    const call=authorityCalls.find(c=>c.assessment.nonce===assessment.nonce),wire=requests.find(r=>r.method==='PATCH'&&r.url.endsWith(encodeURIComponent(request.ir.members[1].request.recordKey)));assert(call?.leases?.job_lease);assert(Date.parse(assessment.validUntil)<=call.leases.job_lease.getTime());assert(Date.parse(continuation.receipt.appendAt)<=Date.parse(wire.at));assert(Date.parse(assessment.validUntil)>Date.parse(wire.at));
   }
   const claims=(await admin.query('SELECT * FROM finnor_os.workflow_step_claims WHERE tenant_id=$1 AND workflow_step_id=$2',[f.tenant,scheduled.body.workflowStepId])).rows;assert.equal(claims.length,1);assert(claims[0].job_delivery_attempt_id);const deliveries=(await admin.query('SELECT * FROM finnor_os.job_delivery_attempts WHERE tenant_id=$1 ORDER BY started_at',[f.tenant])).rows;assert.equal(deliveries.length,4);assert.equal(new Set(workers.map(w=>w.pid)).size,workflowProof==='crash'?5:4);
   const native=(await admin.query('SELECT st.status,r.status AS reservation_status,r.envelopes,e.status AS effect_status,d.status AS action_status FROM finnor_os.s5_consumption_states st JOIN finnor_os.s5_consumptions co USING(tenant_id,consumption_id) JOIN finnor_os.s5_reservations r USING(tenant_id,reservation_id) JOIN finnor_os.s6_obligation_origins o ON o.tenant_id=st.tenant_id AND o.consumption_id=st.consumption_id JOIN finnor_os.business_effects e ON e.tenant_id=o.tenant_id AND e.id=o.effect_id JOIN finnor_os.domain_actions d ON d.tenant_id=o.tenant_id AND d.id=o.domain_action_id WHERE st.tenant_id=$1',[f.tenant])).rows;assert.equal(native[0].status,'RECONCILED');assert.equal(native[0].effect_status,'verified');assert.equal(native[0].action_status,'completed');assert.notEqual(native[0].reservation_status,'RELEASED');assert.deepEqual(native[0].envelopes,obligation.resourceEnvelope);
   const proof={scheduled,replay,queued,conflict,waiting,killedPid,reaped:{exitCode:reaped.status,output:reaped.stdout},restartedPid:processHandle!.pid,workers,claims,deliveries,after:await graph(),requests,authorityCalls,current,providerRecords:[...providerRecords.values()],partialRead,finalHistory,native,sourceDigests,qualification:'ACTUAL_NATIVE_QUEUE_WORKER_PROCESSES_AND_PROTECTED_READBACK; DISPOSABLE_LOCAL_TLS_PROVIDER_AND_AUTHORITY'};await artifact(`workflow-${workflowProof}.json`,proof);return proof;
  }
  if(revokeBeforeDispatch){
   const mechanicallyVerified=await call('/verify-request',request);assert.equal(mechanicallyVerified.status,200,JSON.stringify(mechanicallyVerified));
   const before=await api(f,'check-dispatch',{obligationRef:obligation.ref,requestRef:request.ref,memberId:request.ir.members[0].memberId,nonce:randomUUID()},POST);assert.equal(before.status,200);assert.equal(before.body.status,'CURRENT',JSON.stringify(before));
   const allocationHandler=(await import('../../apps/api/app/api/allocations/[operation]/route.js')).POST;
   const issued=await api(f,'read',{allocationRef:obligation.allocationRef},allocationHandler);assert.equal(issued.status,200);const original=issued.body.problem.resources[0],{ref:oldRef,revision,priorRef,...resource}=original;
   const revised=await api(f,'resource',{resource:{...resource,knowledgeAt:new Date().toISOString()},expectedRef:oldRef},allocationHandler);assert.equal(revised.status,200,JSON.stringify(revised));
   const credential=await readFile(pathOf('provider.token'));await writeFile(pathOf('provider.token'),'credential-deliberately-unavailable');
   const refused=await api(f,'execute-request',input,POST);await writeFile(pathOf('provider.token'),credential);assert.equal(refused.status,503,JSON.stringify(refused));assert.equal(refused.body.code,'CURRENT_OWNER_ASSESSMENT_INVALID');assert.equal(requests.length,0);
   const after=await api(f,'check-dispatch',{obligationRef:obligation.ref,requestRef:request.ref,memberId:request.ir.members[0].memberId,nonce:randomUUID()},POST);assert.equal(after.status,200);assert.equal(after.body.status,'STALE_INPUT');assert(after.body.reasons.includes('RESOURCE_REVISION_CHANGED'));
   const proof={mechanicallyVerified,before,original,revised,refused,after,requests,authorityCalls,root,sourceDigests,qualification:'ACTUAL_CURRENT_S5_REVISION_REFUSAL_BEFORE_PROVIDER_CREDENTIAL_USE; DISPOSABLE_AUTHORITY'};await artifact('governed-dispatch-revocation.json',proof);return proof;
  }
  const falseRequest=structuredClone(input);falseRequest.request.ir.members[0].request.changes.priceAdjustmentFraction=999;falseRequest.request.ref={...request.ref,id:'request-ir:'+hash(falseRequest.request.ir),contentDigest:hash(falseRequest.request.ir)};
  const substituted=await call('/dispatch',falseRequest);assert(substituted.status>=400,JSON.stringify(substituted));assert.equal(requests.length,0);
  const foreign=await call('/dispatch',input,'foreign-token');assert.equal(foreign.status,401);assert.equal(requests.length,0);
  const producerAppend=await call('/append',{event:{schema:'finnor.s6.experience.v1',semanticOwner:'S6',tenantId:f.tenant,principalId:f.principal,rightsRef:obligation.rightsRef,detail:{schema:'finnor.s6.protected-execution.v1'}},parents:[],references:[]});assert.equal(producerAppend.status,403);
  const accepted=await api(f,'execute-request',input,POST);await artifact('dispatch-before-crash.json',{input,originReceipt,substituted,foreign,producerAppend,accepted,requests,authorityCalls,current,pid:processHandle!.pid});
  assert.equal(accepted.status,200,JSON.stringify(accepted));assert.equal(accepted.body.status,'UNRESOLVED');assert.equal(requests.filter(r=>r.method==='PATCH').length,1);assert.equal(current.fields.priceAdjustmentFraction,0.15);assert(current.lastOperationId);
  const uncertain=(await admin.query('SELECT st.status,r.status AS reservation_status,r.envelopes FROM finnor_os.s5_consumption_states st JOIN finnor_os.s5_consumptions co USING(tenant_id,consumption_id) JOIN finnor_os.s5_reservations r USING(tenant_id,reservation_id) WHERE st.tenant_id=$1',[f.tenant])).rows;assert.equal(uncertain.length,1);assert.equal(uncertain[0].status,'UNKNOWN_OUTCOME');assert.equal(uncertain[0].reservation_status,'UNKNOWN_OUTCOME');assert.deepEqual(uncertain[0].envelopes,obligation.resourceEnvelope);
  await observer?.onUnresolved?.({accepted,uncertain,requests:structuredClone(requests),authorityCalls:structuredClone(authorityCalls),current:structuredClone(current),obligation});
  if(recoveryBudgetProof){
   readFault='WRONG_RECORD';const responses=[];
   for(let n=0;n<64;n++){const response=await call('/reconcile',input);assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.body.status,'UNRESOLVED');responses.push(response);}
   const exhaustedBeforeRestart=await protectedHistory();const before=processHandle!,killedPid=before.pid;await stop('SIGKILL');const census=spawnSync('ps',['-p',String(killedPid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});assert.equal(before.signalCode,'SIGKILL');assert.equal(census.status,1);await start();await configureTransport();
   for(let n=0;n<3;n++){const response=n===0?await api(f,'reconcile-request',input,POST):await call('/reconcile',input);assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.body.status,'UNRESOLVED');responses.push(response);}
   const after=await protectedHistory(),native=(await admin.query('SELECT st.status,r.status AS reservation_status,r.envelopes FROM finnor_os.s5_consumption_states st JOIN finnor_os.s5_consumptions co USING(tenant_id,consumption_id) JOIN finnor_os.s5_reservations r USING(tenant_id,reservation_id) WHERE st.tenant_id=$1',[f.tenant])).rows;
   const proof={input,accepted,uncertain,responses,requests,authorityCalls,exhaustedBeforeRestart,after,killedPid,restartedPid:processHandle!.pid,census:{exitCode:census.status,output:census.stdout},native,sourceDigests,qualification:'64_ACTUAL_LOCAL_TLS_READS_AND_COLD_PROTECTED_RECOVERY; NO_S5_MONETARY_METERING_OR_PRODUCTION_ADMISSION'};await artifact('protected-recovery-budget.json',proof);
   assert.equal(requests.filter(r=>r.method==='GET').length,64,'Protected recovery exceeded 64 actual provider observations');assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
   const claims=after.filter((r:any)=>r.event.type==='RECONCILIATION'&&r.event.detail.kind==='OBSERVATION_ATTEMPT');assert.equal(claims.length,64);assert.equal(new Set(claims.map((r:any)=>r.event.detail.observationOrdinal)).size,64);
   const exhausted=after.filter((r:any)=>r.event.type==='RECONCILIATION'&&r.event.detail.kind==='OBSERVATION_BUDGET_EXHAUSTED');assert.equal(exhausted.length,1);assert.equal(exhausted[0].event.detail.status,'REQUIRES_OPERATOR');
   assert.equal(native[0].status,'UNKNOWN_OUTCOME');assert.notEqual(native[0].reservation_status,'RELEASED');assert.deepEqual(native[0].envelopes,obligation.resourceEnvelope);
   for(const [index,request] of requests.filter(r=>r.method==='GET').entries()){assert.equal(claims[index].event.detail.observationOrdinal,index+1);assert(Date.parse(claims[index].receipt.appendAt)<=Date.parse(request.at),'An observation left without its durable protected claim');}
   return proof;
  }
  const killedProcess=processHandle!,killedPid=killedProcess.pid,beforeKill=spawnSync('ps',['-p',String(killedPid),'-o','pid=,ppid=,pgid=,uid=,stat=,command='],{encoding:'utf8'});assert.equal(beforeKill.status,0);await stop('SIGKILL');const afterKill=spawnSync('ps',['-p',String(killedPid),'-o','pid=,ppid=,pgid=,uid=,stat=,command='],{encoding:'utf8'});assert.equal(killedProcess.signalCode,'SIGKILL');assert.equal(afterKill.status,1);const originalHistory=await readFile(pathOf('protected/commitments.jsonl'),'utf8'),priorPin={releaseId:releaseBody.releaseId,verifierDigest:hash(sourceDigests),policyDigest:hash(ledgerPolicy)};
  Object.assign(releaseBody,{releaseId:'disposable-governed-dispatch-recovery'});
  const saveDeployment=async()=>secret('ledger.json',JSON.stringify({policy:ledgerPolicy,release:{...releaseBody,signature:sign(null,Buffer.from(canonical(releaseBody)),reviewer.privateKey).toString('base64')},signerPath:pathOf('ledger-key.pem'),protectedDirectory:pathOf('protected'),contentDirectory:pathOf('ordinary'),dispatchConfigPath:pathOf('broker.json'),port:0}));
  await saveDeployment();await assert.rejects(start(),/HISTORICAL_RELEASE_UNADMITTED_HISTORY_RETAINED/);const incompatibleBoot=logs;assert.equal(await readFile(pathOf('protected/commitments.jsonl'),'utf8'),originalHistory);
  Object.assign(releaseBody,{compatibleHistory:[priorPin]});await saveDeployment();await start();await configureTransport();assert.notEqual(processHandle!.pid,killedPid);assert.equal(await readFile(pathOf('protected/commitments.jsonl'),'utf8'),originalHistory);await artifact('deployment-history-compatibility.json',{priorPin,currentRelease:releaseBody,incompatibleBoot,originalHistorySha256:bytesHash(originalHistory),historyRetained:true,qualification:'ACTUAL_COLD_PROCESS_WITH_SIGNED_RELEASE_CHANGE_AND_EXPLICIT_ORIGINAL_HISTORY_PINS'});
  const beforeTakeover=await protectedHistory(),takeoverInput={obligationId:obligation.ref.id,requestRef:request.ref,expectedCheckpoint:beforeTakeover.at(-1).receipt.checkpointDigest,idempotencyKey:randomUUID(),humanSeconds:2,reason:'Authenticated cold-recovery ownership; preserve all original liabilities'};
  const forbiddenTakeover=await call('/takeover',takeoverInput,consumerToken);assert.equal(forbiddenTakeover.status,403);
  const takeover=await call('/takeover',takeoverInput);await artifact('operator-takeover.json',{beforeTakeover,takeoverInput,forbiddenTakeover,takeover,requests});assert.equal(takeover.status,200,JSON.stringify(takeover));assert.equal(takeover.body.responsibilityRetained,true);assert.equal(takeover.body.automaticMutationRetry,false);
  const takeoverReplay=await call('/takeover',takeoverInput);assert.equal(takeoverReplay.status,200);assert.equal(takeoverReplay.body.semanticReplay,true);assert.deepEqual(takeoverReplay.body.receipt,takeover.body.receipt);
  const alteredTakeover=await call('/takeover',{...takeoverInput,reason:'Changed original claim'});assert.equal(alteredTakeover.status,409);
  const beforeHumanOverdraw=await protectedHistory(),overdrawHuman=await call('/takeover',{...takeoverInput,idempotencyKey:randomUUID(),expectedCheckpoint:beforeHumanOverdraw.at(-1).receipt.checkpointDigest,humanSeconds:5});assert.equal(overdrawHuman.status,409);assert.deepEqual(await protectedHistory(),beforeHumanOverdraw);
  const afterTakeover=await protectedHistory();assert.equal(afterTakeover.filter((r:any)=>r.event.type==='ATTEMPT').length,beforeTakeover.filter((r:any)=>r.event.type==='ATTEMPT').length);assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
  readFault='WRONG_RECORD';const wrong=await api(f,'reconcile-request',input,POST);assert.equal(wrong.status,200,JSON.stringify(wrong));assert.equal(wrong.body.status,'UNRESOLVED');
  readFault='NULL';const cleared=await api(f,'reconcile-request',input,POST);assert.equal(cleared.status,200,JSON.stringify(cleared));assert.equal(cleared.body.status,'UNRESOLVED');
  readFault='NONE';lostResponse=false;const recovered=await api(f,'reconcile-request',input,POST);assert.equal(recovered.status,200,JSON.stringify(recovered));assert.equal(recovered.body.status,'VERIFIED');assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
  const duplicate=await Promise.all(Array.from({length:8},()=>api(f,'execute-request',input,POST)));assert(duplicate.every(r=>r.status===200&&r.body.status==='VERIFIED'));assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
  const receipt=recovered.body.receipt;const {signature,...unsigned}=receipt;assert(verify(null,Buffer.from(canonical(unsigned)),publicPem(ledgerKey),Buffer.from(signature,'base64')));assert.equal(receipt.protectedExecution,true);
  const read=await call('/events/'+encodeURIComponent(receipt.identity),undefined,s5Token);assert.equal(read.status,200);assert.equal(read.body.event.detail.allocationRef.id,obligation.allocationRef.id);assert.equal(read.body.event.detail.consumptionRef.id,obligation.consumptionRef.id);assert.equal(read.body.event.detail.effectRef.id,obligation.effectRef.id);
  const allocationHandler=(await import('../../apps/api/app/api/allocations/[operation]/route.js')).POST;
  const reconciled=await api(f,'settle',{allocationRef:obligation.allocationRef,consumptionRef:obligation.consumptionRef,settlementEventId:receipt.identity},allocationHandler);assert.equal(reconciled.status,200,JSON.stringify(reconciled));assert.equal(reconciled.body.consumption.status,'RECONCILED');assert.equal(reconciled.body.reservation.status,'UNKNOWN_OUTCOME');assert.equal(reconciled.body.releaseGranted,false);assert.equal(reconciled.body.costs.status,'UNMETERED');
  const replay=await api(f,'settle',{allocationRef:obligation.allocationRef,consumptionRef:obligation.consumptionRef,settlementEventId:receipt.identity},allocationHandler);assert.equal(replay.status,200);assert.equal(replay.body.semanticReplay,true);
  const native=(await admin.query('SELECT st.*,r.status AS reservation_status,r.envelopes FROM finnor_os.s5_consumption_states st JOIN finnor_os.s5_consumptions co USING(tenant_id,consumption_id) JOIN finnor_os.s5_reservations r USING(tenant_id,reservation_id) WHERE st.tenant_id=$1',[f.tenant])).rows;
  const history=await protectedHistory(),wire= requests.find(r=>r.method==='PATCH'),authorityWitnesses=history.filter((r:any)=>r.event.type==='RECONCILIATION'&&r.event.detail.kind==='CURRENT_AUTHORITY');
  await artifact('protected-final-authority.json',{history,wire,authorityCalls});assert.equal(authorityWitnesses.length,1,'Final signed native authority assessment was not durably protected before provider egress');
  const witness=authorityWitnesses[0],assessment=witness.event.detail.assessment,{signature:ownerSignature,...ownerBody}=assessment;assert(verify(null,Buffer.from(canonical(ownerBody)),publicPem(ownerKey),Buffer.from(ownerSignature,'base64')),'Protected assessment signature does not authenticate the native owner');
  assert.deepEqual(assessment,authorityCalls.filter(c=>c.operation==='check-dispatch').at(-1).assessment);assert(Date.parse(witness.receipt.appendAt)<=Date.parse(wire.at));assert(Date.parse(assessment.validUntil)>Date.parse(wire.at));
  const attempt=history.find((r:any)=>r.event.type==='ATTEMPT');assert(attempt);assert(witness.receipt.sequence>attempt.receipt.sequence);assert(witness.receipt.parentCheckpoints.includes(attempt.receipt.checkpointDigest));
  steps.push({substituted,foreign,producerAppend,accepted,uncertain,killedPid,kill:{signal:killedProcess.signalCode,exitCode:killedProcess.exitCode,before:{exitCode:beforeKill.status,output:beforeKill.stdout},after:{exitCode:afterKill.status,output:afterKill.stdout}},restartedPid:processHandle!.pid,wrong,cleared,recovered,duplicate,read,reconciled,replay,native});
  const nativeHandoff=await api(f,'read-execution-handoff',{obligationRef:obligation.ref},POST);assert.equal(nativeHandoff.status,200,JSON.stringify(nativeHandoff));assert.equal(nativeHandoff.body.handoff.consumer.semanticOwner,'S6');
  const downstream=await call('/execution-handoff/'+encodeURIComponent(obligation.ref.id),undefined,consumerToken);assert.equal(downstream.status,200,JSON.stringify(downstream));
  assert(verify(null,Buffer.from(canonical(downstream.body.handoff)),publicPem(ledgerKey),Buffer.from(downstream.body.signature,'base64')));assert.deepEqual(downstream.body.handoff.history,history);assert.deepEqual(downstream.body.handoff.request,request);assert.equal(downstream.body.handoff.consumer.semanticOwner,'S7');assert.equal(downstream.body.handoff.attributionGranted,false);
  const deniedConsumerDispatch=await call('/dispatch',input,consumerToken);assert.equal(deniedConsumerDispatch.status,403);
  const finalBudgets=await api(f,'budget-status',{obligationRef:obligation.ref},POST);assert.equal(finalBudgets.status,200);const charged=(await admin.query('SELECT phase,resource_id,unit,units::text,body FROM finnor_os.s5_governed_resource_charges WHERE tenant_id=$1 ORDER BY created_at',[f.tenant])).rows;
  await artifact('s5-governed-budgets-before-storage-probe.json',{finalBudgets,charged});
  assert.equal(charged.filter((c:any)=>c.phase==='EXECUTION').length,1);assert.equal(charged.filter((c:any)=>c.phase==='RECOVERY').length,3);assert.equal(charged.filter((c:any)=>c.phase==='HUMAN').length,1);assert.equal(charged.find((c:any)=>c.phase==='HUMAN').units,'2');
  const executionCharge=charged.find((c:any)=>c.phase==='EXECUTION');
  assert.equal(finalBudgets.body.budgets.find((b:any)=>b.resourceId===executionCharge.resource_id&&b.unit===executionCharge.unit&&b.resourceClass==='COMPUTE').used,'4');
  const malformedCharge=charged[0],badStorageKey='storage-substitution:'+randomUUID();
  const {withTenantTransaction}=await import('@finnor/db');await withTenantTransaction(f.tenant,{userId:f.principal},async(_db,c)=>{await c.query('INSERT INTO finnor_os.s5_governed_resource_charges(tenant_id,principal_id,reservation_id,consumption_id,charge_key,phase,resource_id,unit,units,request_digest,body) VALUES($1,$2,$3,$4,$5,$6,$7,$8,1,$9,$10::jsonb)',[f.tenant,f.principal,obligation.reservationRef.id,obligation.consumptionRef.id,badStorageKey,malformedCharge.phase,'unregistered-budget-resource',malformedCharge.body.unit,malformedCharge.body.requestDigest,JSON.stringify(malformedCharge.body)]);});
  const storageRefusal=await api(f,'budget-status',{obligationRef:obligation.ref},POST);await artifact('s5-resource-storage-consistency.json',{badStorageKey,storageRefusal,requests,qualification:'ACTUAL_ORDINARY_APP_ROLE_INSERT; EXISTING_SCHEMA_ALLOWED_COLUMN_PREIMAGE_SUBSTITUTION'});assert.equal(storageRefusal.status,409,JSON.stringify(storageRefusal));assert.equal(storageRefusal.body.code,'S5_EXECUTION_RESOURCE_HISTORY_INCONSISTENT');assert.equal(requests.filter(r=>r.method==='PATCH').length,1);
  await artifact('contract-lifecycle-final.json',{downstream,deniedConsumerDispatch,takeover,takeoverReplay,alteredTakeover,finalBudgets,charged,history,requests});
  const proof={steps,requests,authorityCalls,current,history,authorityWitnesses,root,publicAuthorities:{owner:publicPem(ownerKey),method:publicPem(methodKey),business:publicPem(businessKey),ledger:publicPem(ledgerKey),reviewer:publicPem(reviewer)},sourceDigests,qualification:'ACTUAL_NATIVE_OWNERS; SEPARATE_PROTECTED_CANDIDATE_PROCESS; DISPOSABLE_AUTHORITY_AND_LOCAL_TLS_PROVIDER_CONTRACT; NO_PRODUCTION_ADMISSION_LIVE_PROVIDER_OR_RELEASE'};
  await artifact('governed-dispatch.json',proof);return proof;
 }finally{
  await stop();await close(provider);await close(authority);await artifact(workflowProof?`workflow-${workflowProof}-process.json`:revokeBeforeDispatch?'dispatch-revocation-process.json':'dispatch-process.json',{root,logs,requests,authorityCalls,steps,pid:processHandle?.pid,exitCode:processHandle?.exitCode,signal:processHandle?.signalCode});
  for(const [key,value] of Object.entries(originalEnvironment))if(value===undefined)delete process.env[key];else process.env[key]=value;
 }
}
