import { strict as assert } from 'node:assert';
/** Shared actual S1/S3/S4/S5 owner setup; no protected decisions or expected results. */
import { randomUUID, createHash } from 'node:crypto';
import { createMetricSeries, attachCanonicalEvidenceToWorld, type PeMutationContext } from '@finnor/private-equity';
import { createEvidenceSource } from '@finnor/memory';
import { configureTenantVertical } from '@finnor/db';
import { allocationRef } from '@finnor/epistemic-runtime';
import { POST as s3Post } from '../../apps/api/app/api/interventions/[operation]/route';
import { POST as s4Post } from '../../apps/api/app/api/policies/[operation]/route';
export function createUpstreamFixtureSupport(context:{admin:()=>any;generatedRows:any[];begin:string;day:number;fixtures:Record<string,any>;api:(...args:any[])=>Promise<any>;artifact:(...args:any[])=>Promise<any>}) {
const {generatedRows,begin,day,fixtures,api,artifact}=context;
const ref=(id:string,owner='SUPPLIED')=>({owner,id,version:'fixture-v1',contentDigest:createHash('sha256').update(id).digest('hex')});
const freezeRef=(body:any,owner:string,prefix:string,version:string)=>({...body,ref:allocationRef(owner,prefix,body,version)});
function successful(r:any){if(r.status!==200)throw new Error('OWNER_REQUEST_FAILED:'+JSON.stringify(r));return r.body;}
function decision(f:any,allocation:any):any{return {knowledgeAt:new Date().toISOString(),period:0,actionHistory:[],observations:[],rightsRef:f.mandate.rightsRef,obligations:[],allocationRefs:[allocation]};}
async function fixture(name:string,horizon:number,dimensions:any[],options:{nonlinear?:boolean;deadlineMs?:number;expiryMs?:number;additionalExposure?:boolean;identity?:{tenant:string;principal:string}}={}){
  const f:any={name,tenant:options.identity?.tenant??randomUUID(),principal:options.identity?.principal??randomUUID(),root:{entityType:'external_organization',entityId:randomUUID()},policies:[],labels:{},resources:[]};
  f.ctx={auth:{tenantId:f.tenant,userId:f.principal,employeeId:f.principal,role:'owner'}} as PeMutationContext;
  if(!options.identity){
  await context.admin().query("INSERT INTO finnor_os.tenants(id,client_key,name) VALUES($1,$2,$3)",[f.tenant,randomUUID(),name]);
  await context.admin().query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status) VALUES($1,$2,$3,'owner','active')",[f.principal,f.tenant,`${name}@s5.example.test`]);
  }
  await context.admin().query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,$3,$3,'other')",[f.root.entityId,f.tenant,name]);
  if(!options.identity)await configureTenantVertical({tenantId:f.tenant,verticalKey:'private_equity',expectedVersion:0,createdBy:f.principal,sourceSystem:'s5:e2e'});
  const source=(await createEvidenceSource(f.tenant,{sourceKey:`s5:${name}:${randomUUID()}`,sourceType:'pe_document_claim',title:'Generated qualification observations'})).id,version=randomUUID();
  await context.admin().query("INSERT INTO finnor_os.evidence_source_versions(id,source_id,scope,tenant_id,version_number,content_hash,content,snapshot,as_of,retrieved_at,created_at) VALUES($1,$2,'tenant',$3,1,$4,'Generated observations, no field identification',$5::jsonb,$6,clock_timestamp(),clock_timestamp())",[version,source,f.tenant,ref(name).contentDigest,JSON.stringify({worldRoot:f.root,claims:[{propositionId:'s5-input',predicate:'reported',value:'Generated hypothetical H1 data'}]}),begin]);
  const rows=structuredClone(generatedRows);
  f.additionalExposures=options.additionalExposure?['priceSecondary']:[];
  if(options.additionalExposure)for(const row of rows)row.exposures.priceSecondary=((row.period%17)-8)/10;
  if(options.nonlinear){let prior=0;for(let t=0;t<rows.length;t++){const price=t>=rows.length-4?0:rows[t].exposures.price,noise=t===rows.length-1?0:5*(generatedRows[t].states.outcome-generatedRows[t].exposures.price);rows[t].exposures.price=price;rows[t].states.outcome=2*prior*price+noise;prior=rows[t].states.outcome;}}
  const series:any={};for(const id of ['outcome','price',...f.additionalExposures]){const metric=await createMetricSeries(f.ctx,{subjectType:'external_organization',subjectId:f.root.entityId,metricKey:`s5-${id}`,name:id,unit:id==='outcome'?'normalized-value':'fraction',frequency:'daily'});series[id]=String(metric.row.id);
    await attachCanonicalEvidenceToWorld(f.ctx,{worldRoot:f.root,entity:{entityType:'pe_metric_series',entityId:series[id]},evidenceSourceId:source,evidenceVersionId:version,relationship:'supports'});
    for(const row of rows){const start=new Date(Date.parse(begin)+row.period*day).toISOString();await context.admin().query("INSERT INTO finnor_os.pe_metric_observations(id,tenant_id,metric_series_id,period_start,period_end,value_type,value_numeric,evidence_source_id,evidence_version_id,source_system,created_by) VALUES($1,$2,$3,$4,$5,'number',$6,$7,$8,'s5:generated',$9)",[randomUUID(),f.tenant,series[id],start,new Date(Date.parse(start)+day).toISOString(),String(row[id==='outcome'?'states':'exposures'][id]),source,version,f.principal]);}}
  const request={schema:'finnor.s3.fit-request.v1',modelKey:name,episodeId:`s5-${name}`,roots:[f.root],stateVariables:[{id:'outcome',root:f.root,seriesId:series.outcome,unit:'normalized-value',range:[-6,6],role:'ENTERPRISE_STATE'}],exposures:[{id:'price',root:f.root,seriesId:series.price,unit:'fraction',operation:'PRICE_CHANGE',measurement:{status:'MEASURED_ACTUAL',methodRef:ref('measurement'),qualification:'SUPPLIED_OWNER_MEASUREMENT_UNVERIFIED'}}],time:{startAt:begin,endAt:new Date(Date.parse(begin)+128*day).toISOString(),periodMs:day,trainingThrough:new Date(Date.parse(begin)+96*day).toISOString()},validity:{validUntil:new Date(Date.now()+3600000).toISOString(),maxBeliefAgeMs:3600000,regimes:['operating'],contexts:['public-price'],maximumHorizon:24},measurementPolicy:{selection:'COMPLETE_RECORDED_GRID_ASSUMED',missingness:'NONE',instrumentError:'ASSUMED_NEGLIGIBLE'},mechanisms:[{id:'registered',meaning:'Generated conditional response only',origin:'SUPPLIED_HYPOTHESIS',assumptions:['SEQUENTIAL_EXCHANGEABILITY','POSITIVITY','CONSISTENCY','MEASUREMENT','SELECTION','INTERFERENCE','STATIONARITY','FUNCTIONAL_FORM','ACTOR_INFORMATION'].map(category=>({id:category,category,status:'DECLARED',meaning:'Generated fixture assumption',evidenceRefs:[ref(category)]})),equations:[{variableId:'outcome',features:options.nonlinear?[{kind:'CONSTANT'},{kind:'PRODUCT',left:{kind:'STATE',id:'outcome',lag:1},right:{kind:'EXPOSURE',id:'price',lag:0}}]:[{kind:'CONSTANT'},{kind:'EXPOSURE',id:'price',lag:0}]}],counterparties:[]}],numerical:{bootstrapDraws:64,blockLength:4,seed:20261002}};
  if(options.additionalExposure){
    request.exposures.push({id:'priceSecondary',root:f.root,seriesId:series.priceSecondary,unit:'fraction',operation:'PRICE_CHANGE',measurement:{status:'MEASURED_ACTUAL',methodRef:ref('measurement-secondary'),qualification:'SUPPLIED_OWNER_MEASUREMENT_UNVERIFIED'}});
    request.mechanisms[0]!.equations[0]!.features.push({kind:'EXPOSURE',id:'priceSecondary',lag:0});
  }
  const fitted=successful(await api(f,'fit',{request},s3Post));assert.equal(fitted.status,'FITTED',JSON.stringify(fitted));f.model=fitted.model;f.series=series;
  const now=new Date(Date.now()-1).toISOString(),until=new Date(Date.now()+(options.expiryMs??3600000)).toISOString();
  const body={schema:'finnor.economic-mandate.v1',tenantId:f.tenant,principalId:f.principal,episodeId:request.episodeId,knowledgeAt:now,validUntil:until,businessOwnerRef:ref(f.principal,'BUSINESS_OWNER'),rightsRef:'s5-owner-rights',utilityRef:ref('supplied-joint-net-utility','BUSINESS_OWNER'),horizon:{startAt:request.time.endAt,periodMs:day,periods:horizon},utility:{unit:'USD',accountingConventionRef:ref('declared-complete-cost-net-utility','BUSINESS_OWNER'),periodTerms:[{variableId:'outcome',unit:'normalized-value',coefficient:100}],discountFactors:Array(horizon+1).fill(1),terminalTerms:[],tail:{status:'SUPPLIED_COMPLETE_FINITE_HORIZON',terminalLiability:0,ref:ref('finite-tail','BUSINESS_OWNER')}},risk:{kind:'HARD_WORST_PATH_UTILITY_FLOOR',minimumUtility:-1000},ambiguity:{kind:'ROBUST_FIXED_JOINT_SCENARIOS',authorizationRef:ref('common-paths-no-probabilities','BUSINESS_OWNER')},resources:{dimensions:dimensions.map((d:any)=>({...d,resourceClass:d.resourceClass??(d.id==='cash'?'CASH':d.id==='leverage'?'BORROWING_HEADROOM':'OPERATIONAL_CAPACITY')})),couplings:[]},search:{maxExpansions:50000,deadlineMs:options.deadlineMs??30000,maxWorlds:512,maxPolicyNodes:50000,maxHumanSeconds:900},scoring:{normalization:100,maxRegret:.05},authorization:{basis:'AUTHENTICATED_OWNER_ASSERTION_UNADMITTED',protectedReceipt:null}};
  // Bind the available owner-supplied utility preimage, rather than an opaque label.
  body.utilityRef={...body.utilityRef,contentDigest:allocationRef('BUSINESS_OWNER','utility',body.utility).contentDigest};
  f.mandate=freezeRef(body,'BUSINESS_OWNER','mandate','economic-mandate-v1');fixtures[name]=f;await artifact(`${name}/scientific-input.json`,{request,rows,fitted,mandate:f.mandate});return f;
}
async function policy(f:any,label:string,spends:Record<string,number>,occupancy:Record<string,number>={},options:{period?:number;tail?:number;contingent?:{HIGH:number;LOW:number};probe?:number}={}){
  const h=f.mandate.horizon.periods,d=f.mandate.resources.dimensions,zeros=Object.fromEntries(d.map((v:any)=>[v.id,0]));
  const a=(id:string,kind:string,period:number,last:number,amounts:any,dose:number,occupation:any={})=>({id,kind,cost:0,costUnit:'USD',resources:{...zeros,...amounts},occupancy:{...zeros,...occupation},occupationPeriods:h,tailLiability:kind==='INTERVENE'?(options.tail??0):0,earliestPeriod:period,lastPeriod:last,atMostOnce:kind==='INTERVENE',exposures:kind==='INTERVENE'?Object.fromEntries(['price',...(f.additionalExposures??[])].map(id=>[id,[dose]])):{},protocolRef:null,informationDelayPeriods:1,humanSeconds:0});
  let actions:any[],observations:any[]=[];
  if(options.contingent){actions=[a('probe','WAIT',0,0,{cash:options.probe??0},0),a('high','INTERVENE',1,1,{cash:options.contingent.HIGH},.2),a('low','INTERVENE',1,1,{cash:options.contingent.LOW},-.2),a('wait','WAIT',1,h-1,{},0),a('stop','STOP',0,h-1,{},0)];observations=[{schema:'finnor.s2.control-observation.v1',id:'public-signal',sourceRef:ref('shared-measurement','S2'),variableId:'outcome',unit:'normalized-value',delayPeriods:1,afterActionIds:['probe'],bins:[{category:'LOW',lowerInclusive:-6,upperExclusive:0},{category:'HIGH',lowerInclusive:0,upperExclusive:6}],qualification:'SUPPLIED_DETERMINISTIC_COARSENING_UNVERIFIED'}];}
  else actions=[a(`programme-${label}`,'INTERVENE',options.period??0,options.period??0,spends,.15,occupancy),a('wait','WAIT',0,h-1,{},0),a('stop','STOP',0,h-1,{},0)];
  const input={mandate:f.mandate,problem:{schema:'finnor.control-problem.v1',id:`${f.name}-${label}`,episodeId:f.mandate.episodeId,modelRef:f.model.ref,context:'public-price',regime:'operating',baselineExposures:Object.fromEntries(['price',...(f.additionalExposures??[])].map(id=>[id,Array(h).fill(0)])),actions,observations,obligations:[],validUntil:f.mandate.validUntil},protocols:[],scenarios:{pathsPerMechanism:4,seed:20261002}};
  const produced=successful(await api(f,'synthesize',input,s4Post));assert.equal(produced.status,'POLICY_AVAILABLE',JSON.stringify(produced));assert(produced.policy);
  const p=produced.policy;f.policies.push(p);f.labels[p.ref.id]=label;await artifact(`${f.name}/policy-${label}.json`,{input,produced});return p;
}
async function resource(f:any,id:string,unit:string,kind:string,availability:string[],existing?:string[],covenants:any[]=[],extra:any={}){
  const body={schema:'finnor.allocation-resource.v1',resourceId:id,tenantId:f.tenant,ownerRef:f.mandate.businessOwnerRef,legalEntityRef:ref(f.root.entityId,'S1'),scopeRef:ref(f.name,'BUSINESS_OWNER'),permittedRoots:[f.root],rightsRef:f.mandate.rightsRef,unit,currency:unit==='USD'?'USD':null,kind,resourceClass:f.mandate.resources.dimensions.find((d:any)=>d.id===id)?.resourceClass??'OTHER_RESTRICTED',horizon:f.mandate.horizon,sourceRef:ref(`source-${id}`,'BUSINESS_OWNER'),asOf:f.mandate.knowledgeAt,knowledgeAt:f.mandate.knowledgeAt,validUntil:f.mandate.validUntil,beliefPins:f.policies[0].bindings.beliefPins,availability:availability.map(amount=>({amount,basis:'REPORTED_AVAILABLE'})),existingUse:existing??Array(availability.length).fill('0'),safetyMargin:'0',covenants,revoked:false,qualification:'AUTHENTICATED_OWNER_ASSERTION_UNADMITTED',...extra};
  const r=successful(await api(f,'resource',{resource:body}));f.resources.push(r);return r;
}
function paths(p:any){const result:any[]=[];function visit(id:string,prefix:string[]){const node=p.nodes.find((v:any)=>v.id===id),next=[...prefix,id];if(!node.branches.length)result.push(next);else for(const b of node.branches)visit(b.childId,next);}visit(p.rootNodeId,[]);return result;}
function clearing(f:any,values:Record<string,string[]>,interactions:any[]=[],choiceConstraints:any[]=[],subset=f.policies){
  let combinations:any[]=[[]];for(const p of subset)combinations=combinations.flatMap(list=>paths(p).map(path=>[...list,{policyRef:p.ref,nodeIds:path}]));
  combinations=combinations.filter(list=>{const tokens=new Map();for(const path of list){const p=subset.find((v:any)=>v.ref.id===path.policyRef.id);for(const nid of path.nodeIds)for(const o of p.nodes.find((n:any)=>n.id===nid).observations){const key=o.instrumentId+'|'+o.availablePeriod;if(tokens.has(key)&&tokens.get(key)!==o.token)return false;tokens.set(key,o.token);}}return true;});
  const count=Math.max(...Object.values(values).map(v=>v.length),combinations.length);assert(count<=32);
  const jointBody={schema:'finnor.joint-allocation-model.v1',tenantId:f.tenant,principalId:f.principal,mandateRef:f.mandate.ref,rightsRef:f.mandate.rightsRef,sourceRefs:[f.model.ref],knowledgeAt:f.mandate.knowledgeAt,validUntil:f.mandate.validUntil,qualification:'SUPPLIED_JOINT_FINITE_SCENARIOS_UNADMITTED',ambiguity:'FIXED_COMPLETE_JOINT_PATHS_NO_PROBABILITIES',completeness:'ALL_MATERIAL_INTERFERENCE_AND_COMPATIBILITY_DECLARED',assumptions:['Hypothetical preregistered net payoffs; shared mechanism and complete observable paths supplied, no probabilities or field calibration.','Within this finite experiment the declared terms contain all value interactions; no standalone fitted forecast is imported as joint value.'],omittedModelGap:'UNKNOWN',identificationGap:'UNKNOWN',scenarios:Array.from({length:count},(_,i)=>({id:`common-${i}`,sharedMechanismRef:ref(`shared-mechanism-${i}`,'SUPPLIED'),policyPaths:combinations[i%combinations.length],baseValue:'0',terms:[...subset.map((p:any)=>({policyIds:[p.ref.id],value:values[f.labels[p.ref.id]]![i%values[f.labels[p.ref.id]]!.length],evidenceRef:ref('preregistered-payoffs','BUSINESS_OWNER')})),...interactions.map(term=>({policyIds:term.labels.map((label:string)=>subset.find((p:any)=>f.labels[p.ref.id]===label).ref.id),value:term.value,evidenceRef:ref('preregistered-interaction','BUSINESS_OWNER')}))]})),choiceConstraints:choiceConstraints.map(c=>({id:c.id,policyIds:c.labels.map((label:string)=>subset.find((p:any)=>f.labels[p.ref.id]===label).ref.id),minimum:c.minimum??0,maximum:c.maximum,sourceRef:ref('preregistered-choice','BUSINESS_OWNER')}))};
  const jointModel=freezeRef(jointBody,'BUSINESS_OWNER','joint-allocation-model','s5-joint-model-v1');
  const demandBindings:any[]=[];for(const p of subset)for(const d of f.mandate.resources.dimensions){
    const r=f.resources.find((r:any)=>r.resourceId===d.id);if(p.nodes.some((n:any)=>p.problem.actions.find((a:any)=>a.id===n.actionId).resources[d.id]!==0))demandBindings.push({policyRef:p.ref,dimensionId:d.id,component:'TOTAL',resourceId:d.id,conversion:'IDENTICAL_UNIT_NO_CONVERSION'});
    if(p.nodes.some((n:any)=>p.problem.actions.find((a:any)=>a.id===n.actionId).occupancy[d.id]!==0))demandBindings.push({policyRef:p.ref,dimensionId:d.id,component:'OCCUPANCY',resourceId:r.resourceId,conversion:'IDENTICAL_UNIT_NO_CONVERSION'});
  }
  return {mandate:f.mandate,policyRefs:subset.map((p:any)=>p.ref),resourceRefs:f.resources.map((r:any)=>r.ref),jointModel,demandBindings,funding:subset.map((p:any)=>({policyRef:p.ref,actionCostResourceId:null,terminalLiabilityResourceId:p.problem.actions.some((a:any)=>a.tailLiability)?'cash':null,humanSecondsResourceId:null})),idempotencyKey:`${f.name}-${randomUUID()}`};
}
return {fixture,policy,resource,clearing,paths,decision};
}
