import { createUpstreamFixtureSupport } from './owner-fixture.mjs';
/** Registered owner-boundary E2E proofs. No post-code unit tests or fake receipts. */
import { strict as assert } from 'node:assert';
import { randomUUID, createHash } from 'node:crypto';
import { readFile, writeFile, mkdir, mkdtemp, appendFile, rm, readdir, chmod } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { tmpdir } from 'node:os';
import { createServer } from 'node:net';
import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';
import { epistemicHash, allocationRef, certifyAllocationOptimization, verifyCanonicalAllocation, verifyAllocationCertificate, compileAllocationMilp } from '@finnor/epistemic-runtime';
import { migrate } from '../../packages/db/migrate';
import { configureTenantVertical, closePool, withTenantTransaction } from '@finnor/db';
import { createMetricSeries, attachCanonicalEvidenceToWorld, type PeMutationContext } from '@finnor/private-equity';
import { createEvidenceSource } from '@finnor/memory';
import { POST as s3Post } from '../../apps/api/app/api/interventions/[operation]/route';
import { POST as s4Post } from '../../apps/api/app/api/policies/[operation]/route';
import { POST } from '../../apps/api/app/api/allocations/[operation]/route';

const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../../..'),output=process.env.FINNOR_S5_EVIDENCE_DIR!;
await mkdir(output,{recursive:true});
const corpus=JSON.parse(await readFile(join(repo,'finnor-os/scripts/s5/corpus.json'),'utf8'));
const selectedCases=process.env.FINNOR_S5_CASE_FILTER?.split(',');
const cases:any[]=[],calls:any[]=[],manifest:any[]=[],children=new Set<ChildProcess>();const startedAt=new Date().toISOString();
const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
const ref=(id:string,owner='SUPPLIED')=>({owner,id,version:'fixture-v1',contentDigest:createHash('sha256').update(id).digest('hex')});
const freezeRef=(body:any,owner:string,prefix:string,version:string)=>({...body,ref:allocationRef(owner,prefix,body,version)});
const fixtures:Record<string,any>={};let admin:pg.Client|undefined,migrationCount=0;
async function artifact(name:string,value:any){const path=join(output,name);await mkdir(dirname(path),{recursive:true});await writeFile(path,JSON.stringify(value,null,2)+'\n');return path;}
async function save(){await artifact('results.json',{schema:'finnor.s5.e2e.v1',startedAt,finishedAt:new Date().toISOString(),cases,calls,manifest,migrationCount,versions:{node:process.version},preregistration:corpus,selection:selectedCases??'FULL_REGISTERED_RUN',
  qualification:'Generated S1 observations, real fitted S3 and issued S4 policies, supplied joint H1 values, actual ordinary-role S5 SQL/handlers. Header development identity, no hosted JWT or protected S6/S8/H2 qualification.',rerun:'python3 finnor-os/scripts/s5/run-local.py'});}
async function challenge(id:string,family:string,input:any,expected:string,fn:()=>Promise<any>){if(selectedCases&&!selectedCases.includes(id))return;const begun=performance.now();try{cases.push({id,family,input,expected,status:'PASS',observed:await fn(),elapsedMs:performance.now()-begun});}catch(e){cases.push({id,family,input,expected,status:'FAIL',observed:e instanceof Error?{message:e.message,stack:e.stack}:String(e),elapsedMs:performance.now()-begun});}console.log(JSON.stringify({id,status:cases.at(-1).status}));await save();}
async function api(f:any,op:string,body:any,handler=POST,headers:Record<string,string>={}){
  const began=performance.now(),response=await handler(new Request(`http://localhost/api/allocations/${op}`,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':f.tenant,'x-user-id':f.principal,...headers},body:JSON.stringify(body)}),{params:Promise.resolve({operation:op})});
  const result={status:response.status,body:await response.json() as any,elapsedMs:performance.now()-began};calls.push({tenantId:f.tenant,operation:op,httpStatus:result.status,state:result.body.status??null,elapsedMs:result.elapsedMs});return result;
}
function successful(r:any){assert.equal(r.status,200,JSON.stringify(r));return r.body;}
function currentResourceInput(r:any){const {ref,revision,priorRef,...body}=r;return body;}
function decision(f:any,allocation:any):any{return {knowledgeAt:new Date().toISOString(),period:0,actionHistory:[],observations:[],rightsRef:f.mandate.rightsRef,obligations:[],allocationRefs:[allocation]};}
const sources=['scope-5/scope-plan.md','scope-5/scope-evidence/test-registration.json','scope-5/scope-evidence/failure-model.md','scope-5/scope-evidence/test-selection.md','scope-5/scope-evidence/additional-challenge-registration.md',
 'finnor-os/scripts/s5/corpus.json','finnor-os/scripts/s5/reference.py','finnor-os/scripts/s5/run-local.py','finnor-os/scripts/s5/run-s5-e2e.mts','finnor-os/scripts/s5/run-s5-cold.mts','finnor-os/scripts/s5/owner-fixture.mts','finnor-os/scripts/s5/tsconfig.json',
 'finnor-os/packages/shared-types/src/allocation.ts','finnor-os/packages/shared-types/src/contingent-control.ts','finnor-os/packages/epistemic-runtime/src/allocation-contracts.ts','finnor-os/packages/epistemic-runtime/src/allocation-checker.ts','finnor-os/packages/epistemic-runtime/src/allocation-verifier.ts','finnor-os/packages/epistemic-runtime/src/allocation-verifier-worker.mjs','finnor-os/packages/epistemic-runtime/src/allocation-producer.ts','finnor-os/packages/epistemic-runtime/src/allocation-solver.py',
 'finnor-os/packages/private-equity/src/allocation-store.ts','finnor-os/packages/private-equity/src/enterprise-allocation.ts','finnor-os/packages/private-equity/src/enterprise-control.ts','finnor-os/apps/api/app/api/allocations/[operation]/route.ts','finnor-os/apps/api/app/api/policies/[operation]/route.ts','finnor-os/packages/db/index.ts','finnor-os/packages/db/migrate.ts','finnor-os/packages/db/migration-head.ts','finnor-os/packages/epistemic-runtime/src/contingent-control.ts','finnor-os/packages/epistemic-runtime/src/control-contracts.ts','finnor-os/packages/epistemic-runtime/src/intervention-control.ts','finnor-os/packages/epistemic-runtime/src/intervention-numerics.py','finnor-os/packages/private-equity/src/enterprise-interventions.ts','finnor-os/package-lock.json','finnor-os/packages/db/migrations-bundle.ts','finnor-os/openapi.json','finnor-os/scripts/generate-openapi.ts','infra/deployment/production.contract.json','scripts/release/validate-deployment-truth.mjs'];
for(const path of [...sources,...(await readdir(join(repo,'finnor-os/packages/db/migrations'))).filter(n=>n.endsWith('.sql')).map(n=>'finnor-os/packages/db/migrations/'+n)]){const bytes=await readFile(join(repo,path));const destination=join(output,'source-snapshot',path);await mkdir(dirname(destination),{recursive:true});await writeFile(destination,bytes);manifest.push({path,sha256:createHash('sha256').update(bytes).digest('hex')});}

const dir=await mkdtemp(join(tmpdir(),'finnor-s5-'));
const port=await new Promise<number>((yes,no)=>{const s=createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const a=s.address();if(!a||typeof a==='string')return no(Error('port'));s.close(()=>yes(a.port));});});
const postgres=new EmbeddedPostgres({databaseDir:dir,user:'finnor',password:'finnor',port,persistent:false,onLog:()=>undefined});
const day=86400000,begin=new Date(Math.floor(Date.now()/day)*day-128*day).toISOString();
const generated=spawnSync(process.env.FINNOR_S3_PYTHON!,[join(repo,'finnor-os/scripts/s3/reference.py')],{input:JSON.stringify({operation:'equivalent'}),encoding:'utf8'});assert.equal(generated.status,0,generated.stderr);const generatedRows=JSON.parse(generated.stdout).rows;

const {fixture,policy,resource,clearing,paths}=createUpstreamFixtureSupport({admin:()=>admin,generatedRows,begin,day,fixtures,api,artifact});
function oracle(p:any,boundProof?:any){const run=spawnSync(process.env.FINNOR_S5_PYTHON!,[join(repo,'finnor-os/scripts/s5/reference.py')],{input:JSON.stringify(boundProof?{problem:p,boundProof}:p),encoding:'utf8',timeout:35000,maxBuffer:16*1024*1024,env:{...process.env,OPENBLAS_NUM_THREADS:'1',OMP_NUM_THREADS:'1'}});assert.equal(run.status,0,run.stderr);return JSON.parse(run.stdout);}
async function readback(f:any){return withTenantTransaction(f.tenant,{userId:f.principal,readOnly:true},async(_db,c)=>({role:(await c.query('SELECT current_user,rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user')).rows[0],reservations:(await c.query('SELECT s.*,p.certificate FROM finnor_os.s5_reservations s JOIN finnor_os.s5_proposals p ON p.tenant_id=s.tenant_id AND p.content_digest=s.allocation_digest ORDER BY reservation_id')).rows,consumptions:(await c.query('SELECT co.body,st.status FROM finnor_os.s5_consumptions co JOIN finnor_os.s5_consumption_states st USING(tenant_id,consumption_id)')).rows,history:(await c.query('SELECT subject_id,revision,operation,body FROM finnor_os.s5_history ORDER BY id')).rows,experience:(await c.query('SELECT body FROM finnor_os.s5_experience ORDER BY recorded_at,event_id')).rows}));}
async function child(f:any,operation:string,body:any,options:{owner?:string;pauseAfterResult?:boolean;waitForStart?:boolean}={}){
  const file=await artifact(`${f.name}/child-${randomUUID()}.json`,{tenantId:f.tenant,principalId:f.principal,operation,body,...options});
  const cp=spawn(process.execPath,['--import=tsx',join(repo,'finnor-os/scripts/s5/run-s5-cold.mts'),file],{cwd:join(repo,'finnor-os'),env:process.env,stdio:['ignore','pipe','pipe','ipc']});children.add(cp);let stdout='',stderr='';cp.stdout!.on('data',b=>stdout+=b);cp.stderr!.on('data',b=>stderr+=b);
  const result=new Promise<any>((yes,no)=>{const timer=setTimeout(()=>{cp.kill('SIGKILL');no(Error('CHILD_WALL_LIMIT'));},120000);cp.on('message',(m:any)=>{if(m.kind==='RESULT'){clearTimeout(timer);void artifact(file.replace(output+'/','')+'.result.json',m.result).catch(()=>undefined);yes(m.result);}});cp.on('error',no);cp.on('exit',(code,signal)=>{clearTimeout(timer);children.delete(cp);if(code!==0||signal)no(Error(`CHILD_EXIT:${code}:${signal}:${stderr.slice(-2000)}`));else if(!stdout)no(Error('CHILD_EMPTY_RESULT'));});});
  const exit=new Promise<any>(yes=>cp.on('exit',(code,signal)=>yes({code,signal,stdout,stderr})));void result.catch(()=>undefined);
  return {cp,result,exit,file};
}
async function observeSleep(queryPart:string){for(let i=0;i<1500;i++){const rows=(await admin!.query("SELECT pid,query,wait_event FROM pg_stat_activity WHERE datname='s5_e2e' AND wait_event='PgSleep' AND query LIKE $1",['%'+queryPart+'%'])).rows;if(rows.length)return rows[0];await sleep(20);}throw Error('External fault boundary was not observed');}
try{
  await postgres.initialise();await appendFile(join(dir,'postgresql.conf'),'\ntrack_commit_timestamp=on\n');await postgres.start();await postgres.createDatabase('s5_e2e');const url=`postgres://finnor:finnor@127.0.0.1:${port}/s5_e2e`;migrationCount=(await migrate(url)).length;
  admin=new pg.Client({connectionString:url});await admin.connect();await admin.query("ALTER ROLE finnor_app LOGIN PASSWORD 'finnor_app'");await admin.query("SET app.test_vertical_mode='explicit'");process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/s5_e2e`;await closePool();

  await challenge('coupled-choice-original-covenant-and-bound','coupled-and-omitted-covenant',corpus.cases.coupled,'B+C=32, exact feasible optimum; covenant rejects A+C=11; corrupted producer/bound cannot clear',async()=>{
    const f=await fixture('coupled',3,[{id:'cash',unit:'USD',capacity:100,totalLimit:100},{id:'capacity',unit:'seat',capacity:2,totalLimit:100},{id:'leverage',unit:'debt-unit',capacity:100,totalLimit:100}]);
    for(const row of corpus.cases.coupled.programmes)await policy(f,row.label,{cash:row.capital,leverage:row.leverage},{capacity:row.capacity});
    await resource(f,'cash','USD','STOCK',Array(4).fill('100'));await resource(f,'capacity','seat','OCCUPANCY',Array(4).fill('2'));
    await resource(f,'leverage','debt-unit','CUMULATIVE_EXPENDITURE',Array(4).fill('100'),undefined,[{id:'leverage-covenant',sourceRef:ref('covenant','BUSINESS_OWNER'),rightsRef:f.mandate.rightsRef,unit:'leverage-unit',terms:[{resourceId:'leverage',coefficient:'1',coefficientUnit:'leverage-unit/debt-unit'}],periods:[0,1,2,3],maximum:'10',safetyMargin:'0',basis:'CANONICAL_RESOURCE_USAGE'}]);
    f.input=clearing(f,Object.fromEntries(corpus.cases.coupled.programmes.map((r:any)=>[r.label,r.values])),[corpus.cases.coupled.interaction]);
    const cleared=successful(await api(f,'clear',f.input));assert.equal(cleared.status,'FEASIBLE',JSON.stringify(cleared));assert.deepEqual(cleared.certificate.check.selectedPolicyIds.map((id:string)=>f.labels[id]).sort(),['B','C']);assert.equal(cleared.certificate.optimization.incumbent,'32');assert.equal(cleared.certificate.optimization.upperBound,'32');
    f.cleared=cleared;const issued=successful(await api(f,'read',{allocationRef:cleared.certificate.ref})),independent=oracle(issued.problem);assert.equal(independent.exact.optimum,'32');assert.equal(independent.numerical.originalExactCheck.value,'32');
    const invalidIds=f.policies.filter((p:any)=>['A','C'].includes(f.labels[p.ref.id])).map((p:any)=>p.ref.id),invalid=verifyCanonicalAllocation(issued.problem,invalidIds);assert.equal(invalid.feasible,false);assert(invalid.reasons.some(r=>r.startsWith('COVENANT_LIMIT:leverage-covenant')));
    const hostile=compileAllocationMilp(issued.problem,30000);hostile.input.rows=hostile.input.rows.filter(r=>!r.id.startsWith('covenant:'));hostile.policyColumns.forEach((id,i)=>{hostile.input.lowerBounds[i]=hostile.input.upperBounds[i]=invalidIds.includes(id)?'1':'0';});
    const numerical=spawnSync(process.env.FINNOR_S5_PYTHON!,[join(repo,'finnor-os/packages/epistemic-runtime/src/allocation-solver.py')],{input:JSON.stringify(hostile.input),encoding:'utf8',timeout:30000});assert.equal(numerical.status,0,numerical.stderr);const omitted=JSON.parse(numerical.stdout);assert.equal(omitted.status,'OPTIMAL_NUMERICAL');assert.equal(verifyCanonicalAllocation(issued.problem,hostile.policyColumns.filter((_,i)=>omitted.vector[i]>.5)).feasible,false);
    const falseBound=structuredClone(issued.certificate);falseBound.optimization.upperBound='31';const {ref:old,...body}=falseBound;falseBound.ref=allocationRef('S5','allocation-certificate',body);assert.throws(()=>verifyAllocationCertificate(issued.problem,falseBound),/False exact optimization/);
    const reverseCosts=structuredClone(issued.certificate);reverseCosts.optimization.opportunityCosts.reverse();const {ref:reverseRef,...reverseBody}=reverseCosts;reverseCosts.ref=allocationRef('S5','allocation-certificate',reverseBody);assert(verifyAllocationCertificate(issued.problem,reverseCosts).feasible);
    const persisted=await readback(f);assert.equal(persisted.role.rolsuper,false);assert.equal(persisted.role.rolbypassrls,false);assert(persisted.experience.some((e:any)=>e.body.type==='RESERVATION'));assert(persisted.history.some((e:any)=>e.operation==='s5_reservations'));
    await artifact('coupled/owner-and-reference.json',{input:f.input,cleared,issued,independent,invalid,hostileProducer:omitted,persisted});return {selected:['B','C'],exactOptimum:'32',independentRankingDiagnostic:'20',normalizedModelOnlyDelta:'0.12',ordinaryRole:persisted.role,artifact:'coupled/owner-and-reference.json'};
  });

  await challenge('issuer-identity-foreign-scope-and-revision','identity-authority-handoff',{},'Real issued positive control; forged/foreign scopes and suspended rights cannot gain clearance',async()=>{
    const f=fixtures.coupled;assert(f?.cleared);const certificate=f.cleared.certificate,validation=successful(await api(f,'validate',{allocationRef:certificate.ref}));assert.equal(validation.status,'CURRENT');assert.equal(validation.executionAuthorityGranted,false);
    const foreign=await fixture('foreign',3,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}]);const blocked=await api(foreign,'read',{allocationRef:certificate.ref});assert.equal(blocked.status,404);
    const forged=await api(f,'read',{allocationRef:{...certificate.ref,id:'allocation-certificate:'+'0'.repeat(64),contentDigest:'0'.repeat(64)}});assert.equal(forged.status,404);
    const changed=structuredClone(f.input);changed.jointModel.scenarios[0].baseValue='1';const {ref:old,...j}=changed.jointModel;changed.jointModel.ref=allocationRef('BUSINESS_OWNER','joint-allocation-model',j,'s5-joint-model-v1');const replay=await api(f,'clear',changed);assert.equal(replay.status,409);assert.equal(replay.body.code,'IDEMPOTENCY_CONFLICT');
    await admin!.query("UPDATE finnor_os.users SET status='suspended' WHERE id=$1",[f.principal]);const revoked=await api(f,'read',{allocationRef:certificate.ref});assert.equal(revoked.status,404);await admin!.query("UPDATE finnor_os.users SET status='active' WHERE id=$1",[f.principal]);
    const released=successful(await api(f,'release',{allocationRef:certificate.ref,idempotencyKey:'coupled-release'}));assert.equal(released.reservation.status,'RELEASED');const repeat=successful(await api(f,'release',{allocationRef:certificate.ref,idempotencyKey:'coupled-release'}));assert.equal(repeat.reservation.revision,released.reservation.revision);
    const after=await readback(f);await artifact('coupled/identity-release.json',{validation,blocked,forged,replay,revoked,released,repeat,after});return {artifact:'coupled/identity-release.json',noProtectedAuthority:true};
  });

  await challenge('liquidity-timing-uncertain-proceeds-and-existing-breach','temporal-and-optionality',corpus.cases.timing,'Future value cannot fund period0; the exact delayed S4 policy fits; uncertainty/breached obligations refuse',async()=>{
    const f=await fixture('timing',2,[{id:'cash',unit:'USD',capacity:200,totalLimit:200}]);await policy(f,'immediate',{cash:60});await policy(f,'delayed',{cash:60},{},{period:1});
    await resource(f,'cash','USD','STOCK',corpus.cases.timing.cashAvailability,corpus.cases.timing.existingUse);f.input=clearing(f,{immediate:['100'],delayed:['100']},[],[{id:'same-programme-timing',labels:['immediate','delayed'],maximum:1}]);
    const cleared=successful(await api(f,'clear',f.input));assert.equal(cleared.status,'FEASIBLE');assert.deepEqual(cleared.certificate.check.selectedPolicyIds.map((id:string)=>f.labels[id]),['delayed']);const issued=successful(await api(f,'read',{allocationRef:cleared.certificate.ref})),independent=oracle(issued.problem);assert.equal(independent.exact.optimum,'100');assert(independent.exact.rows.find((r:any)=>r.selected.length===1&&f.labels[r.selected[0]]==='immediate').reasons.some((r:string)=>r.startsWith('RESOURCE:cash')));
    assert.equal(successful(await api(f,'release',{allocationRef:cleared.certificate.ref,idempotencyKey:'timing-release'})).reservation.status,'RELEASED');const input=currentResourceInput(f.resources[0]);input.availability[1].basis='UNCERTAIN_PROCEEDS';const uncertain=successful(await api(f,'resource',{resource:input,expectedRef:f.resources[0].ref}));f.resources[0]=uncertain;
    const uncertainInput={...f.input,resourceRefs:[uncertain.ref],idempotencyKey:'uncertain-proceeds'},unresolved=successful(await api(f,'clear',uncertainInput));assert.equal(unresolved.status,'UNCERTAINTY_UNRESOLVED');assert.equal(unresolved.certificate,null);
    const broken=currentResourceInput(uncertain);broken.availability[1].basis='REPORTED_AVAILABLE';broken.existingUse[0]='80';const breach=successful(await api(f,'resource',{resource:broken,expectedRef:uncertain.ref}));f.resources[0]=breach;const refused=successful(await api(f,'clear',{...f.input,resourceRefs:[breach.ref],idempotencyKey:'existing-breach'}));assert.equal(refused.status,'INFEASIBLE');assert(refused.reasons.includes('EXISTING_OBLIGATIONS_ALREADY_VIOLATE_CANONICAL_LIMITS'));assert.equal(refused.reservation,null);
    await artifact('timing/results.json',{input:f.input,cleared,issued,independent,uncertainInput,unresolved,refused,readback:await readback(f)});return {artifact:'timing/results.json',delayedPolicyUnchanged:true};
  });

  await challenge('common-path-contingent-optionality','temporal-and-optionality',corpus.cases.optionality,'Actual S4 contingent policies P+Q preserve envelope[10,90,0]; coincident extra policy and incompatible common observations refuse',async()=>{
    const f=await fixture('optionality',2,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}],{nonlinear:true});
    await policy(f,'P',{}, {},{contingent:corpus.cases.optionality.P,probe:10});await policy(f,'Q',{}, {},{contingent:corpus.cases.optionality.Q});await policy(f,'X',{}, {},{contingent:{HIGH:30,LOW:0}});
    for(const p of f.policies){const root=p.nodes.find((n:any)=>n.id===p.rootNodeId);assert.equal(root.actionId,'probe');assert.deepEqual([...new Set(p.nodes.filter((n:any)=>n.period===1).flatMap((n:any)=>n.observations.map((o:any)=>o.token)))].sort(),['HIGH','LOW']);for(const n of p.nodes.filter((n:any)=>n.period===1))assert.equal(n.actionId,n.observations[0].token.toLowerCase());}
    await resource(f,'cash','USD','STOCK',Array(3).fill('100'));f.input=clearing(f,{P:['40'],Q:['35'],X:['10']});const cleared=successful(await api(f,'clear',f.input));assert.equal(cleared.status,'FEASIBLE',JSON.stringify(cleared));assert.deepEqual(cleared.certificate.check.selectedPolicyIds.map((id:string)=>f.labels[id]).sort(),['P','Q']);assert.deepEqual(cleared.certificate.check.envelopes[0].quantities,['10','90','0']);
    const issued=successful(await api(f,'read',{allocationRef:cleared.certificate.ref})),independent=oracle(issued.problem);assert.equal(independent.exact.optimum,'75');assert(independent.exact.rows.find((r:any)=>r.selected.length===3).reasons.some((r:string)=>r.startsWith('RESOURCE:cash')));
    const incompatible=structuredClone(f.input);const qpath=incompatible.jointModel.scenarios[0].policyPaths.find((p:any)=>p.policyRef.id===f.policies[1].ref.id),other=paths(f.policies[1]).find((v:any)=>v[1]!==qpath.nodeIds[1]);qpath.nodeIds=other;const {ref:old,...body}=incompatible.jointModel;incompatible.jointModel.ref=allocationRef('BUSINESS_OWNER','joint-allocation-model',body,'s5-joint-model-v1');incompatible.idempotencyKey='incompatible-common-path';const rejected=await api(f,'clear',incompatible);assert.equal(rejected.status,400);assert.match(rejected.body.error,/incompatible shared observations/);
    const p=f.policies[0],future=decision(f,cleared.certificate.ref);future.observations=[{instrumentId:'public-signal',token:'HIGH',availablePeriod:1,knowledgeAt:new Date().toISOString(),sourceRef:ref('not-an-actual-measurement','S2')}];const hindsight=await api(f,'decide',{policyRef:p.ref,decision:future,allocationRef:cleared.certificate.ref},s4Post);assert.equal(hindsight.status,400);assert.match(hindsight.body.error,/Observation|measurement|context|unavailable/i);
    const firstIntent=successful(await api(f,'consume',{allocationRef:cleared.certificate.ref,policyRef:p.ref,decision:decision(f,cleared.certificate.ref),idempotencyKey:'optionality-p-intent'}));
    const unknown=successful(await api(f,'reconcile',{allocationRef:cleared.certificate.ref}));assert.equal(unknown.reservation.status,'UNKNOWN_OUTCOME');
    const secondIntent=successful(await api(f,'consume',{allocationRef:cleared.certificate.ref,policyRef:f.policies[1].ref,decision:decision(f,cleared.certificate.ref),idempotencyKey:'optionality-q-intent'}));const afterCompatibleIntent=await readback(f);
    await artifact('optionality/results.json',{input:f.input,cleared,issued,independent,rejected,hindsight,firstIntent,unknown,secondIntent,afterCompatibleIntent,readback:afterCompatibleIntent});const held=afterCompatibleIntent.reservations.find((r:any)=>r.allocation_digest===cleared.certificate.ref.contentDigest);assert.equal(held.status,'UNKNOWN_OUTCOME');assert.deepEqual(held.envelopes,cleared.certificate.check.envelopes);
    const repeatedReconciliation=successful(await api(f,'reconcile',{allocationRef:cleared.certificate.ref})),afterRepeatedReconciliation=await readback(f);await artifact('optionality/repeated-reconciliation.json',{repeatedReconciliation,afterRepeatedReconciliation});assert(afterRepeatedReconciliation.consumptions.every((use:any)=>use.status==='UNKNOWN_OUTCOME'),JSON.stringify(afterRepeatedReconciliation.consumptions.map((use:any)=>({id:use.body.ref.id,status:use.status}))));assert.equal(repeatedReconciliation.reservation.revision,held.revision);assert.deepEqual(repeatedReconciliation.reservation.envelopes,held.envelopes);
    const storageAttacks:any[]=[];for(const [variant,sql,subject,expected]of [
      ['shrink-envelope',"UPDATE finnor_os.s5_reservations SET envelopes='[]'::jsonb,revision=revision+1 WHERE tenant_id=$1 AND reservation_id=$2",held.reservation_id,'accountable envelope are immutable'],
      ['downgrade-reservation',"UPDATE finnor_os.s5_reservations SET status='CONSUMPTION_PENDING',revision=revision+1 WHERE tenant_id=$1 AND reservation_id=$2",held.reservation_id,'reservation responsibility cannot regress'],
      ['downgrade-consumption',"UPDATE finnor_os.s5_consumption_states SET status='INTENDED_PENDING_S6',revision=revision+1 WHERE tenant_id=$1 AND consumption_id=$2",firstIntent.consumption.ref.id,'consumption responsibility cannot regress'],
    ] as const){let observed='';try{await withTenantTransaction(f.tenant,{userId:f.principal},async(_db,c)=>{await c.query(sql,[f.tenant,subject]);throw Error(`FORBIDDEN_WRITE_ALLOWED_ROLLED_BACK:${variant}`);});}catch(error){observed=error instanceof Error?error.message:String(error);}storageAttacks.push({variant,observed,blockedAtIntendedBoundary:observed.includes(expected),transactionRolledBack:true});}
    await artifact('optionality/storage-attacks.json',{storageAttacks,before:afterCompatibleIntent,after:await readback(f),qualification:'Actual ordinary-role storage protocol, every attempted mutation rolled back; no protected ledger/credential claim'});assert(storageAttacks.every(v=>v.blockedAtIntendedBoundary),JSON.stringify(storageAttacks));return {artifact:'optionality/results.json',storageArtifact:'optionality/storage-attacks.json',jointCommittedCash:'100',independentMaxDiagnostic:'120',allSiblingsDiagnostic:'190',unknownPreservedAfterCompatibleIntent:true};
  });

  await challenge('signed-covenant-contingent-lower-bound','temporal-and-optionality',{debt:'60',cashMinimum:'20',cashMaximum:'40',covenantMaximum:'30'},'Pending contingent cash uses20 in the negative covenant term; debt60 cannot pass by subtracting40',async()=>{
    const f=await fixture('signed-bounds',2,[{id:'cash',unit:'USD',capacity:100,totalLimit:100},{id:'leverage',unit:'debt-unit',capacity:100,totalLimit:100}],{nonlinear:true});const q=await policy(f,'Q',{}, {},{contingent:{HIGH:20,LOW:40}}),r=await policy(f,'R',{leverage:60});
    await resource(f,'cash','USD','STOCK',Array(3).fill('100'));await resource(f,'leverage','debt-unit','CUMULATIVE_EXPENDITURE',Array(3).fill('100'),undefined,[{id:'signed-covenant',sourceRef:ref('signed-covenant','BUSINESS_OWNER'),rightsRef:f.mandate.rightsRef,unit:'covenant-unit',terms:[{resourceId:'leverage',coefficient:'1',coefficientUnit:'covenant-unit/debt-unit'},{resourceId:'cash',coefficient:'-1',coefficientUnit:'covenant-unit/USD'}],periods:[1],maximum:'30',safetyMargin:'0',basis:'CANONICAL_RESOURCE_USAGE'}]);
    const firstInput=clearing(f,{Q:['100']},[],[],[q]),first=successful(await api(f,'clear',firstInput));assert.equal(first.status,'FEASIBLE');const envelope=first.certificate.check.envelopes.find((e:any)=>e.resourceId==='cash');assert.deepEqual(envelope.quantities,['0','40','0']);assert.deepEqual(envelope.minimumQuantities,['0','20','0']);
    const secondInput=clearing(f,{R:['100']},[],[],[r]),second=successful(await api(f,'clear',secondInput));assert.equal(second.status,'FEASIBLE');assert.equal(second.certificate.policyBindings.length,0);const issued=successful(await api(f,'read',{allocationRef:second.certificate.ref})),invalid=verifyCanonicalAllocation(issued.problem,[r.ref.id]),independent=oracle(issued.problem);assert(invalid.reasons.some(v=>v.startsWith('COVENANT_LIMIT:signed-covenant')));assert(invalid.witnesses.some(v=>v.constraintId==='covenant:signed-covenant'&&v.used==='40'));assert.equal(independent.exact.optimum,'0');
    await artifact('signed-bounds/results.json',{firstInput,first,secondInput,second,issued,invalid,independent,readback:await readback(f)});return {artifact:'signed-bounds/results.json',worstSignedLoad:'40',unsafeMaximumSubtractionDiagnostic:'20'};
  });

  await challenge('flow-stock-semantic-class-scope-and-terminal-debt','temporal-and-optionality',{datedPayments:['60','60'],flowPerPeriod:'100',stock:'100',terminalSpend:'95',tail:'10'},'Dated flow fits both programmes; stock permits one; terminal debt refuses95+10; borrowing and restricted entity scope cannot finance cash demand',async()=>{
    const f=await fixture('resource-meaning',3,[{id:'cash',unit:'USD',capacity:200,totalLimit:200}]);const a=await policy(f,'A',{cash:60}),b=await policy(f,'B',{cash:60},{},{period:1}),t=await policy(f,'T',{cash:95},{},{tail:10});
    await resource(f,'cash','USD','FLOW',Array(4).fill('100'));await resource(f,'stockcash','USD','STOCK',Array(4).fill('100'),undefined,[],{resourceClass:'CASH'});await resource(f,'borrowing','USD','STOCK',Array(4).fill('100'),undefined,[],{resourceClass:'BORROWING_HEADROOM'});await resource(f,'scopedcash','USD','STOCK',Array(4).fill('100'),undefined,[],{resourceClass:'CASH',permittedRoots:[{entityType:'external_organization',entityId:randomUUID()}]});
    const flowInput=clearing(f,{A:['20'],B:['30']},[],[],[a,b]),flow=successful(await api(f,'clear',flowInput));assert.equal(flow.status,'FEASIBLE');assert.equal(flow.certificate.policyBindings.length,2);assert.deepEqual(flow.certificate.check.envelopes.find((e:any)=>e.resourceId==='cash').quantities,['60','60','0','0']);assert.equal(successful(await api(f,'release',{allocationRef:flow.certificate.ref,idempotencyKey:'release-flow'})).reservation.status,'RELEASED');
    const stockInput=structuredClone(flowInput);stockInput.demandBindings.forEach((v:any)=>v.resourceId='stockcash');stockInput.idempotencyKey='stock-comparison';const stock=successful(await api(f,'clear',stockInput));assert.equal(stock.status,'FEASIBLE');assert.deepEqual(stock.certificate.policyBindings.map((v:any)=>f.labels[v.policyRef.id]),['B']);assert.equal(stock.certificate.optimization.upperBound,'30');const issued=successful(await api(f,'read',{allocationRef:stock.certificate.ref})),independent=oracle(issued.problem);assert.equal(independent.exact.optimum,'30');assert.equal(successful(await api(f,'release',{allocationRef:stock.certificate.ref,idempotencyKey:'release-stock'})).reservation.status,'RELEASED');
    const tailInput=clearing(f,{T:['100']},[],[],[t]);tailInput.demandBindings.forEach((v:any)=>v.resourceId='stockcash');tailInput.funding[0].terminalLiabilityResourceId='stockcash';const tail=successful(await api(f,'clear',tailInput));assert.equal(tail.status,'FEASIBLE');assert.equal(tail.certificate.policyBindings.length,0);const tailIssued=successful(await api(f,'read',{allocationRef:tail.certificate.ref})),terminal=verifyCanonicalAllocation(tailIssued.problem,[t.ref.id]);assert(terminal.witnesses.some(v=>v.constraintId==='resource:stockcash'&&v.period===3&&v.used==='105'&&v.margin==='-5'));assert.equal(terminal.feasible,false);
    const borrowing=structuredClone(flowInput);borrowing.demandBindings.forEach((v:any)=>v.resourceId='borrowing');borrowing.idempotencyKey='no-implicit-drawdown';const wrongClass=await api(f,'clear',borrowing);assert.equal(wrongClass.status,400);assert.match(wrongClass.body.error,/semantic class/);
    const scoped=structuredClone(flowInput);scoped.demandBindings.forEach((v:any)=>v.resourceId='scopedcash');scoped.idempotencyKey='no-implicit-entity-transfer';const wrongScope=await api(f,'clear',scoped);assert.equal(wrongScope.status,400);assert.match(wrongScope.body.error,/permitted resource scope/);
    await artifact('resource-meaning/results.json',{flowInput,flow,stockInput,stock,issued,independent,tailInput,tail,tailIssued,terminal,wrongClass,wrongScope,readback:await readback(f)});return {artifact:'resource-meaning/results.json',flowBoth:true,stockOne:true,terminalLiabilityRetained:true,classAndScopeBound:true};
  });

  await challenge('multi-process-concurrent-reservation-and-replay','durable-concurrency-crash-revision',corpus.cases.concurrency,'Four independent ordinary-role processes cannot jointly reserve more than100; semantic replay survives cold restart',async()=>{
    const f=await fixture('concurrent',3,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}]);for(let i=0;i<4;i++)await policy(f,`K${i}`,{cash:60});await resource(f,'cash','USD','STOCK',Array(4).fill('100'));
    const inputs=f.policies.map((p:any,i:number)=>clearing(f,{[`K${i}`]:['100']},[],[],[p]));const cs=await Promise.all(inputs.map((input:any)=>child(f,'clear',input)));const results=await Promise.all(cs.map(c=>c.result));await Promise.all(cs.map(c=>c.exit));
    const persisted=await readback(f),positive=persisted.reservations.filter((r:any)=>r.status!=='RELEASED'&&r.certificate.policyBindings.length);assert.equal(positive.length,1);const held=persisted.reservations.filter((r:any)=>r.status!=='RELEASED').reduce((n:number,r:any)=>n+Number(r.envelopes[0].quantities[0]),0);assert.equal(held,60);
    const winner=results.findIndex((r:any)=>r.body.certificate?.policyBindings.length),before=results[winner];f.input=inputs[winner];f.cleared=before.body;
    const cold=await child(f,'clear',f.input),replayed=await cold.result;await cold.exit;assert.equal(replayed.body.reservation.ref.id,before.body.reservation.ref.id);assert.equal((await readback(f)).reservations.length,persisted.reservations.length);
    const altered=structuredClone(f.input);altered.funding[0].actionCostResourceId='cash';const conflict=await api(f,'clear',altered);assert.equal(conflict.status,409);assert.equal(conflict.body.code,'IDEMPOTENCY_CONFLICT');
    await artifact('concurrent/results.json',{inputs,results,persisted,held,replayed,conflict,after:await readback(f),processes:cs.map(c=>({pid:c.cp.pid,inputFile:c.file}))});return {artifact:'concurrent/results.json',distinctPositiveHolds:positive.length,persistedCash:'60',coldSameReservation:true};
  });

  await challenge('transaction-abort-and-resource-revision-race','durable-concurrency-crash-revision',{resources:2},'A post-origin SQL abort rolls back the entire commitment; a real owner revision between proposal and commit rejects the stale snapshot',async()=>{
    const f=await fixture('faults',3,[{id:'cash',unit:'USD',capacity:100,totalLimit:100},{id:'capacity',unit:'seat',capacity:1,totalLimit:100}]);await policy(f,'K',{cash:60},{capacity:1});await resource(f,'cash','USD','STOCK',Array(4).fill('100'));await resource(f,'capacity','seat','OCCUPANCY',Array(4).fill('1'));f.input=clearing(f,{K:['100']});
    await admin!.query(`CREATE FUNCTION finnor_os.s5_e2e_abort() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.tenant_id='${f.tenant}'::uuid THEN RAISE EXCEPTION 'externally injected complete transaction abort' USING ERRCODE='40001'; END IF; RETURN NEW; END $$`);await admin!.query('CREATE TRIGGER s5_e2e_abort BEFORE INSERT ON finnor_os.s5_reservations FOR EACH ROW EXECUTE FUNCTION finnor_os.s5_e2e_abort()');
    let aborted:any;try{aborted=await api(f,'clear',f.input);assert.equal(aborted.status,500);const rows=await admin!.query('SELECT (SELECT count(*) FROM finnor_os.s5_reservation_origins WHERE tenant_id=$1)::int origins,(SELECT count(*) FROM finnor_os.s5_reservations WHERE tenant_id=$1)::int holds',[f.tenant]);assert.deepEqual(rows.rows[0],{origins:0,holds:0});}finally{await admin!.query('DROP TRIGGER s5_e2e_abort ON finnor_os.s5_reservations');await admin!.query('DROP FUNCTION finnor_os.s5_e2e_abort()');}
    const recovered=successful(await api(f,'clear',f.input));assert.equal(recovered.status,'FEASIBLE');assert.equal(successful(await api(f,'release',{allocationRef:recovered.certificate.ref,idempotencyKey:'faults-release'})).reservation.status,'RELEASED');
    await admin!.query(`CREATE FUNCTION finnor_os.s5_e2e_proposal_pause() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.tenant_id='${f.tenant}'::uuid THEN PERFORM pg_sleep(2); END IF; RETURN NEW; END $$`);await admin!.query('CREATE TRIGGER s5_e2e_proposal_pause AFTER INSERT ON finnor_os.s5_proposals FOR EACH ROW EXECUTE FUNCTION finnor_os.s5_e2e_proposal_pause()');
    let stale:any,revision:any,boundary:any;try{const c=await child(f,'clear',{...f.input,idempotencyKey:'race-snapshot'});boundary=await Promise.race([observeSleep('INSERT INTO finnor_os.s5_proposals'),c.result.then(result=>{throw Error('Child completed before expected DB fault boundary:'+JSON.stringify(result));})]);const next=currentResourceInput(f.resources[0]);next.availability=next.availability.map((v:any)=>({...v,amount:'90'}));revision=successful(await api(f,'resource',{resource:next,expectedRef:f.resources[0].ref}));stale=await c.result;await c.exit;assert.equal(stale.body.status,'STALE_INPUT',JSON.stringify(stale));const persisted=await readback(f);assert.equal(persisted.reservations.filter((r:any)=>r.status!=='RELEASED').length,0);}finally{await admin!.query('DROP TRIGGER s5_e2e_proposal_pause ON finnor_os.s5_proposals');await admin!.query('DROP FUNCTION finnor_os.s5_e2e_proposal_pause()');}
    await artifact('faults/results.json',{aborted,recovered,stale,revision,externallyObservedBoundary:boundary,readback:await readback(f)});return {artifact:'faults/results.json',partialCommitments:0,staleCommitRejected:true};
  });

  await challenge('actual-s4-handoff-crash-unknown-expiry-and-release','unknown-and-conservative-release',corpus.cases.unknown,'Handoff records intended consumption; real SIGKILL/cold reconciliation/expiry cannot release or double spend; protected settlement remains external',async()=>{
    assert(process.getuid&&process.getuid()!==0,'A real non-root uid is required to apply the read-only-directory fault');
    const f=await fixture('unknown',3,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}],{expiryMs:45000});const p=await policy(f,'K',{cash:60});await policy(f,'other',{cash:60});await resource(f,'cash','USD','STOCK',Array(4).fill('100'));f.input=clearing(f,{K:['100']},[],[],[p]);f.cleared=successful(await api(f,'clear',f.input));assert.equal(f.cleared.status,'FEASIBLE');
    const input={policyRef:p.ref,decision:decision(f,f.cleared.certificate.ref),allocationRef:f.cleared.certificate.ref};await admin!.query(`CREATE FUNCTION finnor_os.s5_e2e_intent_pause() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.tenant_id='${f.tenant}'::uuid THEN PERFORM pg_sleep(2); END IF; RETURN NEW; END $$`);await admin!.query('CREATE TRIGGER s5_e2e_intent_pause AFTER INSERT ON finnor_os.s5_consumptions FOR EACH ROW EXECUTE FUNCTION finnor_os.s5_e2e_intent_pause()');
    const c=await child(f,'handoff',input,{owner:'S4',pauseAfterResult:true}),eventDirectory=join(process.env.FINNOR_S4_POLICY_STORE!,f.tenant,f.principal,'prepared-experience');let handoff:any,latePersistenceFault:any;
    try{const boundary=await observeSleep('INSERT INTO finnor_os.s5_consumptions'),preparations=join(process.env.FINNOR_S4_POLICY_STORE!,f.tenant,f.principal,'handoff-preparations'),files=await readdir(preparations);assert.equal(files.length,1);const preparedAtBoundary=JSON.parse(await readFile(join(preparations,files[0]!),'utf8'));assert.equal(preparedAtBoundary.handoff.consumptionRef,null);await chmod(eventDirectory,0o500);handoff=await c.result;latePersistenceFault={boundary,eventDirectory,mode:'0500',uid:process.getuid(),preparationDigestAtBoundary:epistemicHash(preparedAtBoundary),response:handoff.status,durableReadback:await readback(f)};await artifact('unknown/late-persistence-fault.json',latePersistenceFault);assert.equal(handoff.status,200,JSON.stringify(handoff));}
    finally{try{await chmod(eventDirectory,0o700);}finally{try{await admin!.query('DROP TRIGGER s5_e2e_intent_pause ON finnor_os.s5_consumptions');}finally{await admin!.query('DROP FUNCTION finnor_os.s5_e2e_intent_pause()');}}}
    assert.equal(handoff.body.status,'BLOCKED_AUTHORITY');assert(handoff.body.consumptionRef);assert.equal(handoff.body.executionAuthorityGranted,false);
    assert(handoff.body.preparationRef);assert.equal(latePersistenceFault.preparationDigestAtBoundary,handoff.body.preparationRef.contentDigest);const preparation=JSON.parse(await readFile(join(process.env.FINNOR_S4_POLICY_STORE!,f.tenant,f.principal,'handoff-preparations',handoff.body.preparationRef.contentDigest+'.json'),'utf8'));assert.equal(epistemicHash(preparation),handoff.body.preparationRef.contentDigest);assert.equal(preparation.handoff.consumptionRef,null);assert.equal(preparation.qualification,'PREPARED_NOT_CONSUMED_NOT_PROTECTED');assert.equal(preparation.plannedConsumptionKey,`s4-handoff:${handoff.body.decision.contextDigest}`);await artifact('unknown/handoff-preparation-readback.json',preparation);
    c.cp.kill('SIGKILL');const killed=await c.exit;assert.equal(killed.signal,'SIGKILL');const before=await readback(f);assert.equal(before.consumptions.length,1);assert.equal(before.reservations[0].status,'CONSUMPTION_PENDING');
    const terminalNativeHistory=Array.from({length:257},(_,i)=>({id:randomUUID(),digest:epistemicHash({fixture:'unrelated-terminal-native-history',index:i,tenant:f.tenant})}));f.preexistingNativeEffects=terminalNativeHistory;await artifact('unknown/terminal-native-history-input.json',{rows:terminalNativeHistory,qualification:'GENERATED_UNRELATED_CANCELLED_NATIVE_ROWS_NOT_S5_EXECUTION_OR_CANCELLATION_EVIDENCE'});await admin!.query("INSERT INTO finnor_os.business_effects(id,tenant_id,semantic_hash,scope_hash,operation_class,effect,status) SELECT id,$1::uuid,digest,digest,'external_side_effect',$3::jsonb,'cancelled' FROM jsonb_to_recordset($2::jsonb) AS r(id uuid,digest text)",[f.tenant,JSON.stringify(terminalNativeHistory),JSON.stringify({schemaVersion:1,qualification:'GENERATED_UNRELATED_TERMINAL_NATIVE_HISTORY_NOT_S5_PROVIDER_EVIDENCE'})]);
    const cold=await child(f,'reconcile',{allocationRef:f.cleared.certificate.ref});const reconciled=await cold.result;await cold.exit;await artifact('unknown/terminal-native-history-response.json',{reconciled,nativeTerminalRows:257,originalS5Hold:before.reservations[0]});assert.equal(reconciled.body.status,'UNKNOWN_OUTCOME_RETAINED');assert.equal(reconciled.body.reservation.status,'UNKNOWN_OUTCOME');assert.equal(reconciled.body.observedNativeEffects.length,0);const second=successful(await api(f,'reconcile',{allocationRef:f.cleared.certificate.ref}));assert.equal(second.reservation.revision,reconciled.body.reservation.revision);
    const release=await api(f,'release',{allocationRef:f.cleared.certificate.ref,idempotencyKey:'unsafe-release'});assert.equal(release.status,422);assert.equal(release.body.code,'BLOCKED_AUTHORITY');
    const other=f.policies[1],attempt=successful(await api(f,'clear',clearing(f,{other:['100']},[],[],[other])));assert.equal(attempt.certificate?.policyBindings.length??0,0);const read=successful(await api(f,'read',{allocationRef:f.cleared.certificate.ref}));assert.equal(read.consumptions.length,1);
    const same={allocationRef:f.cleared.certificate.ref,policyRef:p.ref,decision:input.decision,idempotencyKey:`s4-handoff:${handoff.body.decision.contextDigest}`};const replay=successful(await api(f,'consume',same));assert.equal(replay.consumption.ref.id,handoff.body.consumptionRef.id);const changed=await api(f,'consume',{...same,decision:{...same.decision,knowledgeAt:new Date().toISOString()}});assert.equal(changed.status,409);
    await sleep(Math.max(0,Date.parse(f.mandate.validUntil)-Date.now()+20));const expired=successful(await api(f,'validate',{allocationRef:f.cleared.certificate.ref}));assert.equal(expired.status,'STALE_INPUT');assert(expired.reasons.includes('CERTIFICATE_EXPIRED_ACCOUNTABLE_EXPOSURE_RETAINED'));const expiredRelease=await api(f,'release',{allocationRef:f.cleared.certificate.ref,idempotencyKey:'expiry-is-not-settlement'});assert.equal(expiredRelease.status,422);
    const fakeSettlement=await api(f,'reconcile',{allocationRef:f.cleared.certificate.ref,settled:true});assert.equal(fakeSettlement.status,400);const after=await readback(f);const accountable=after.reservations.find((row:any)=>row.allocation_digest===f.cleared.certificate.ref.contentDigest);assert(accountable);assert.equal(accountable.status,'UNKNOWN_OUTCOME');assert.equal(accountable.envelopes[0].quantities[0],'60');assert.equal(after.consumptions.length,1);
    await artifact('unknown/results.json',{input,handoff,latePersistenceFault,killed:{pid:c.cp.pid,code:killed.code,signal:killed.signal},before,reconciled,second,release,attempt,replay,changed,expired,expiredRelease,fakeSettlement,after,protectedSettlement:'BLOCKED_EXTERNAL'});return {artifact:'unknown/results.json',retainedExposure:'60',actualProviderAttempts:'UNAVAILABLE_S6_BOUNDARY',protectedSettlement:'BLOCKED_EXTERNAL'};
  });

  await challenge('exact-margin-unavailable-solver-and-deadline','search-numerics-and-coupled-stress',corpus.cases.numerical,'Integer lattice translation preserves the tiny cash margin; backend failure and wall deadline produce no new reservation',async()=>{
    const f=await fixture('numerical',3,[{id:'cash',unit:'USD',capacity:1,totalLimit:1}],{deadlineMs:8000});await policy(f,'N',{cash:.3});await resource(f,'cash','USD','STOCK',Array(4).fill(corpus.cases.numerical.availability),undefined,[],{safetyMargin:corpus.cases.numerical.safetyMargin});f.input=clearing(f,{N:['100']});const cleared=successful(await api(f,'clear',f.input));assert.equal(cleared.status,'FEASIBLE',JSON.stringify(cleared));assert.deepEqual(cleared.certificate.policyBindings,[]);assert.equal(cleared.certificate.optimization.upperBound,'0');const issued=successful(await api(f,'read',{allocationRef:cleared.certificate.ref})),independent=oracle(issued.problem);assert.equal(independent.exact.optimum,'0');
    const python=process.env.FINNOR_S5_PYTHON;let missing:any,timed:any;try{process.env.FINNOR_S5_PYTHON=join(output,'missing-python');missing=successful(await api(f,'clear',{...f.input,idempotencyKey:'missing-solver'}));assert.equal(missing.status,'SOLVER_UNAVAILABLE');assert.equal(missing.reservation,null);
      const slow=join(output,'slow-configured-executable');await writeFile(slow,'#!/usr/bin/env python3\nimport time\ntime.sleep(60)\n');await chmod(slow,0o700);process.env.FINNOR_S5_PYTHON=slow;timed=successful(await api(f,'clear',{...f.input,idempotencyKey:'wall-budget'}));assert.equal(timed.status,'SEARCH_EXHAUSTED');assert.equal(timed.reservation,null);assert(timed.compute.usage.elapsedMs<8500);
    }finally{process.env.FINNOR_S5_PYTHON=python;}
    const impossible=structuredClone(f.input),{ref:oldJointRef,...jointBody}=impossible.jointModel;jointBody.choiceConstraints=[{id:'must-select-unfundable-programme',policyIds:[f.policies[0].ref.id],minimum:1,maximum:1,sourceRef:ref('explicit-require-selection','BUSINESS_OWNER')}];impossible.jointModel=freezeRef(jointBody,'BUSINESS_OWNER','joint-allocation-model','s5-joint-model-v1');impossible.idempotencyKey='require-infeasible-programme';const infeasible=successful(await api(f,'clear',impossible));assert.equal(infeasible.status,'INFEASIBLE');assert.equal(infeasible.reservation,null);const {ref:priorProblemRef,...originalBody}=issued.problem,impossibleProblem=freezeRef({...originalBody,jointModel:impossible.jointModel},'S5','allocation-problem','s5-joint-finite-v1');await artifact('numerical/infeasible-reference-input.json',{input:impossible,owner:infeasible,originalProblem:impossibleProblem});const infeasibleReference=oracle(impossibleProblem);assert.equal(infeasibleReference.numerical.status,2);assert.equal(infeasibleReference.numerical.upperEstimate,null);await artifact('numerical/infeasible-reference-result.json',infeasibleReference);
    const oversized=await POST(new Request('http://localhost/api/allocations/read',{method:'POST',headers:{'x-tenant-id':f.tenant,'x-user-id':f.principal},body:JSON.stringify({padding:'x'.repeat(2*1024*1024)})}),{params:Promise.resolve({operation:'read'})});assert.equal(oversized.status,413);
    await artifact('numerical/results.json',{input:f.input,cleared,issued,independent,missing,timed,oversized:{status:oversized.status,body:await oversized.json()},readback:await readback(f)});return {artifact:'numerical/results.json',zeroPrimalTolerance:true,exactOptimum:'0',failuresNoNewReservation:true};
  });

  await challenge('registered-coupled-stress-and-matched-reference','search-numerics-and-coupled-stress',corpus.cases.stress,'16 policies, four pools,24 periods,four common shocks remain feasible within the budget; numerical comparator and certified relaxation gap remain distinct',async()=>{
    const dimensions=[{id:'cash',unit:'USD',capacity:10000,totalLimit:10000},...Array.from({length:4},(_,i)=>({id:`pool${i}`,unit:`crew${i}`,capacity:3,totalLimit:1000}))];const f=await fixture('stress',24,dimensions);
    for(let i=0;i<16;i++)await policy(f,`F${i}`,{cash:10+i},{[`pool${i%4}`]:1});await resource(f,'cash','USD','STOCK',Array(25).fill('400'));
    const fleet={id:'fleet-covenant',sourceRef:ref('fleet','BUSINESS_OWNER'),rightsRef:f.mandate.rightsRef,unit:'crew',terms:Array.from({length:4},(_,i)=>({resourceId:`pool${i}`,coefficient:'1',coefficientUnit:`crew/crew${i}`})),periods:Array.from({length:25},(_,i)=>i),maximum:'10',safetyMargin:'0',basis:'CANONICAL_RESOURCE_USAGE'};
    for(let i=0;i<4;i++)await resource(f,`pool${i}`,`crew${i}`,'OCCUPANCY',Array(25).fill('3'),undefined,i===0?[fleet]:[]);
    const values=Object.fromEntries(Array.from({length:16},(_,i)=>[`F${i}`,Array.from({length:4},(_,s)=>String(10+i-(i%3)*s))])),interactions=[{labels:['F0','F1'],value:'25'},{labels:['F6','F7'],value:'-8'},{labels:['F12','F13'],value:'20'}];f.input=clearing(f,values,interactions,[{id:'substitute-pair',labels:['F2','F3'],maximum:1}]);
    const cleared=successful(await api(f,'clear',f.input));assert.equal(cleared.status,'FEASIBLE',JSON.stringify(cleared));assert(cleared.certificate.policyBindings.length>=2);assert.equal(cleared.certificate.optimization.strength,'EXACT_CANONICAL_LAGRANGIAN_BOUND');assert.equal(cleared.certificate.optimization.completeSearch,false);assert(cleared.compute.usage.elapsedMs<30000);
    const issued=successful(await api(f,'read',{allocationRef:cleared.certificate.ref})),independent=oracle(issued.problem,issued.certificate.optimization.boundProof);assert.equal(independent.dual.exactUpper,'215');assert.equal(cleared.certificate.optimization.upperBound,'215');assert.equal(cleared.certificate.optimization.gapUpperBound,'0');assert(independent.numerical.originalExactCheck.feasible);assert.equal(independent.numerical.originalExactCheck.value,cleared.certificate.optimization.incumbent);assert(Number(cleared.certificate.optimization.upperBound)>=Number(cleared.certificate.optimization.incumbent));
    const rejectedHint=certifyAllocationOptimization(issued.problem,issued.certificate.check.selectedPolicyIds,{deadlineAt:performance.now()+30000,searchTermination:'UNTRUSTED_OPTIONAL_HINT_CHALLENGE',solverUpperBoundEstimate:null,dualProposal:{schema:'finnor.s5.dual-proposal.v1',multipliers:[{rowId:'foreign-row',side:'upper',value:'1'}]}});assert.equal(rejectedHint.optimization.strength,'EXACT_ANALYTIC_RELAXATION_BOUND');assert.equal(rejectedHint.optimization.upperBound,'280');assert.equal(rejectedHint.optimization.boundProposalDisposition,'REJECTED_HINT_ANALYTIC_RETAINED');
    const boundAttacks:any[]=[];for(const variant of ['negative','unknown','missing-covenant','understated']){const bad=structuredClone(issued.certificate);const ms=bad.optimization.boundProof.proposal.multipliers;
      if(variant==='negative')ms[0].value='-1';if(variant==='unknown')ms[0].rowId='foreign-constraint';if(variant==='missing-covenant')bad.optimization.boundProof.proposal.multipliers=ms.filter((v:any)=>!v.rowId.startsWith('covenant:'));if(variant==='understated')bad.optimization.upperBound='214';
      const {ref:oldRef,...body}=bad;bad.ref=allocationRef('S5','allocation-certificate',body);assert.throws(()=>verifyAllocationCertificate(issued.problem,bad),/dual|Dual|canonical|Lagrangian/);boundAttacks.push({variant,rejected:true});}
    assert(cleared.decisionUsage.elapsedMs<30000);assert.equal(cleared.decisionUsage.scope,'WHOLE_S5_OWNER_INCLUDING_RESOLUTION_CONTENTION_COMMIT');
    const childRss=Number(cleared.compute.usage.backend.maxRssBytes??0),inclusive=childRss+Math.max(cleared.compute.usage.rssBeforeBytes,cleared.compute.usage.rssAfterBytes);assert(inclusive<16*1024**3);assert(cleared.compute.cost.money===null);await artifact('stress/results.json',{input:f.input,cleared,issued,independent,inclusiveMeasuredRssBytes:inclusive,boundAttacks,rejectedHint,readback:await readback(f)});return {artifact:'stress/results.json',incumbent:cleared.certificate.optimization.incumbent,upperBound:cleared.certificate.optimization.upperBound,gap:cleared.certificate.optimization.gapUpperBound,referenceQualification:independent.numerical.qualification,ownerElapsedMs:cleared.decisionUsage.elapsedMs,inclusiveMeasuredRssBytes:inclusive};
  });
  await challenge('bounded-registry-remains-operable','search-numerics-and-coupled-stress',{maximumResources:16},'17th resource rejects before insertion; all16 remain readable and an existing revision can still change',async()=>{
    const f=await fixture('registry-bound',1,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}]);await policy(f,'empty',{cash:0});await resource(f,'cash','USD','STOCK',['100','100']);
    const mismatchedCurrency=currentResourceInput(f.resources[0]);mismatchedCurrency.resourceId='unsupported-currency';mismatchedCurrency.currency='EUR';const currencyRefusal=await api(f,'resource',{resource:mismatchedCurrency});assert.equal(currencyRefusal.status,400);assert.match(currencyRefusal.body.error,/Currency/);
    for(let i=1;i<16;i++){const input=currentResourceInput(f.resources[0]);input.resourceId=`extra-${i}`;f.resources.push(successful(await api(f,'resource',{resource:input})));}
    const input=currentResourceInput(f.resources[0]);input.resourceId='seventeenth';const denied=await api(f,'resource',{resource:input});assert.equal(denied.status,413,JSON.stringify(denied));const current=successful(await api(f,'resources',{}));assert.equal(current.resources.length,16);
    const update=currentResourceInput(f.resources[0]);update.availability=[{amount:'90',basis:'REPORTED_AVAILABLE'},{amount:'90',basis:'REPORTED_AVAILABLE'}];const revised=successful(await api(f,'resource',{resource:update,expectedRef:f.resources[0].ref}));assert.equal(revised.revision,2);await artifact('registry-bound/results.json',{denied,current,revised,currencyRefusal});return {artifact:'registry-bound/results.json',resourcesRetained:16,existingRevisionAllowed:true};
  });
  await challenge('cold-exact-read-keeps-owner-io-live','search-numerics-and-coupled-stress',{policies:14,horizon:1,commonPaths:1,cash:'100',maximumEventLoopDelayMs:500},'Complete mathematical certification and cold read check the original constraints while authenticated owner I/O stays live',async()=>{
    const f=await fixture('cold-exact-read',1,[{id:'cash',unit:'USD',capacity:100,totalLimit:100}]);for(let i=0;i<14;i++)await policy(f,`P${i}`,{cash:1});await resource(f,'cash','USD','STOCK',['100','100']);f.input=clearing(f,Object.fromEntries(Array.from({length:14},(_,i)=>[`P${i}`,['1']])));
    let clearLastTick=performance.now(),clearMaximumDelay=0;const clearTimer=setInterval(()=>{const now=performance.now();clearMaximumDelay=Math.max(clearMaximumDelay,now-clearLastTick-20);clearLastTick=now;},20);
    let cleared:any;try{cleared=successful(await api(f,'clear',f.input));await sleep(25);}finally{clearInterval(clearTimer);}assert.equal(cleared.status,'FEASIBLE',JSON.stringify(cleared));assert.equal(cleared.certificate.optimization.strength,'EXACT_COMPLETE_SUBSET_CHECK');assert.equal(cleared.certificate.optimization.incumbent,'14');assert.equal(cleared.certificate.optimization.upperBound,'14');
    await artifact('cold-clear-owner-io.json',{clearMaximumDelay,contractMaximumDelayMs:500,certificateRef:cleared.certificate.ref,decisionUsage:cleared.decisionUsage,source:'Actual clear handler, timer starts after policy/resource fixtures and before issuance'});assert(clearMaximumDelay<500,`Clearing exact certification blocked owner I/O for ${clearMaximumDelay}ms`);
    const delays:number[]=[];let last=performance.now();const tick=setInterval(()=>{const now=performance.now();delays.push(Math.max(0,now-last-20));last=now;},20);let read:any,registry:any;
    try{await sleep(25);[read,registry]=await Promise.all([api(f,'read',{allocationRef:cleared.certificate.ref}),api(f,'resources',{})]);await sleep(25);}finally{clearInterval(tick);}
    assert.equal(read.status,200,JSON.stringify(read));assert.equal(registry.status,200,JSON.stringify(registry));const maxEventLoopDelayMs=Math.max(0,...delays);await artifact('cold-exact-read/results.json',{input:f.input,cleared,read,registry,delays,maxEventLoopDelayMs,readback:await readback(f),qualification:'Actual original complete14-policy proof on a cold read; operational liveness, not a new economic benchmark'});assert(maxEventLoopDelayMs<500,`Exact proof blocked owner event loop for ${maxEventLoopDelayMs}ms`);return {artifact:'cold-exact-read/results.json',maxEventLoopDelayMs,proofStrength:read.body.certificate.optimization.strength};
  });
  await challenge('independent-final-accountability-readback','identity-authority-handoff',{},'All ordinary commitments retain immutable history; no S5-created provider effect or protected receipt is booked',async()=>{
    const states:any[]=[];for(const f of Object.values(fixtures)){const persisted=await readback(f);const n=(await admin!.query('SELECT (SELECT count(*) FROM finnor_os.business_effects WHERE tenant_id=$1)::int effects,(SELECT count(*) FROM finnor_os.decision_receipts WHERE tenant_id=$1)::int receipts',[f.tenant])).rows[0];assert.deepEqual(n,{effects:f.preexistingNativeEffects?.length??0,receipts:0});const native=(await admin!.query('SELECT id,semantic_hash,status FROM finnor_os.business_effects WHERE tenant_id=$1 ORDER BY id',[f.tenant])).rows;assert.deepEqual(native,(f.preexistingNativeEffects??[]).map((e:any)=>({id:e.id,semantic_hash:e.digest,status:'cancelled'})).sort((a:any,b:any)=>a.id.localeCompare(b.id)));for(const r of persisted.reservations){assert(persisted.history.some((h:any)=>h.subject_id===r.reservation_id));assert.equal(persisted.experience.filter((e:any)=>e.body.type==='RESERVATION'&&e.body.revisionRef===r.reservation_id).length,1);}for(const co of persisted.consumptions)assert.equal(persisted.experience.filter((e:any)=>e.body.type==='CONSUMPTION'&&e.body.revisionRef===co.body.ref.id).length,1);states.push({name:f.name,tenantId:f.tenant,...n,nativeFixtureQualification:'UNCHANGED_GENERATED_UNRELATED_HISTORY_ZERO_S5_CREATED_EFFECTS',role:persisted.role,reservations:persisted.reservations.map((r:any)=>({id:r.reservation_id,status:r.status,revision:r.revision,envelopes:r.envelopes}))});}await artifact('final-independent-readback.json',states);return {artifact:'final-independent-readback.json',ordinaryRlsAllScopes:true,protectedExecutionCreated:false};
  });
}catch(e){cases.push({id:'setup-or-unhandled',status:'FAIL',observed:e instanceof Error?{message:e.message,stack:e.stack}:String(e)});}finally{
  for(const c of children)c.kill('SIGKILL');await save();await closePool().catch(()=>undefined);await admin?.end().catch(()=>undefined);await postgres.stop().catch(()=>undefined);await rm(dir,{recursive:true,force:true});
}
console.log(JSON.stringify({output,passed:cases.filter(x=>x.status==='PASS').length,failed:cases.filter(x=>x.status==='FAIL').length}));if(cases.some(x=>x.status==='FAIL'))process.exit(1);
