/** Ordinary P1 consumer. Generated bytes execute only in S6's isolated cell;
 * original whole-program acceptance remains the independent verification owner. */
import type { PoolClient } from 'pg';
import type { PeMutationContext } from '../types';
import type { Expression, HarnessProgram, HarnessRequest, HarnessValue, NativeModule } from '../program-synthesis/contracts';
import type { ProgramRow } from '../program-synthesis/store';
import { assertProgramCurrent, trace } from '../program-synthesis/store';
import { constructModules } from '../program-synthesis/compiler';
import { executeTypeScriptModule } from '../program-synthesis/typescript';
import { checkNumericalAcceptance } from '../program-synthesis/checker';
import { assertDependencies, codeIdentity, principal, revisions, sha, stable, tx, unavailable } from '../evidence-execution/store';
import { invariant, type ProcedureUse, type StructuralTemplate } from './contracts';
import { checkProcedureUse, requireProcedureMode } from './admission';
import { currentCapsule } from './store';
import { templateRequest } from './induction';
import { capsuleDependencyKey } from './lifecycle';

interface Match { bindings: Record<string, string>; paths: string[] }
function children(e: Expression): Array<[string, Expression]> {
  if (e.kind === 'if') return [['condition.left', e.condition!.left], ['condition.right', e.condition!.right],
    ['whenTrue', e.whenTrue!], ['whenFalse', e.whenFalse!]];
  return e.left && e.right ? [['left', e.left], ['right', e.right]] : [];
}
export function matchProcedure(template: StructuralTemplate, request: HarnessRequest): Match | null {
  if (request.operations?.length || request.ownerBindings || request.computeSearch) return null;
  const sources = new Map(request.sources.map(s => [s.key, s.source]));
  const nodes: Array<{ path: string; expression: Expression }> = [];
  let visits = 0;
  function visit(e: Expression, path: string) {
    if (++visits > 1024) throw Error('P6_COMPOSITION_EXPANSION_BOUND');
    nodes.push({ path, expression: e });
    for (const [key, child] of children(e)) visit(child, path + '.' + key);
  }
  request.acceptance.targets.forEach((t, i) => visit(t.expression, String(i)));
  function unify(expected: Expression, actual: Expression, bindings: Record<string, string>): boolean {
    if (++visits > 32768) throw Error('P6_COMPOSITION_SEARCH_BOUND');
    if (expected.kind !== actual.kind) return false;
    if (expected.kind === 'literal') return stable(expected) === stable(actual);
    if (expected.kind === 'input') {
      const slot = expected.key!, key = actual.key!, source = sources.get(key);
      if (!source || source.kind !== 'metric' && source.kind !== 'artifact') return false;
      if (stable(invariant(source)) !== stable(template.inputs.find(i => i.key === slot)?.semantics)) return false;
      if (bindings[slot]) return bindings[slot] === key;
      if (Object.values(bindings).includes(key)) return false;
      bindings[slot] = key; return true;
    }
    if (expected.kind === 'if' && expected.condition!.comparison !== actual.condition!.comparison) return false;
    const a = children(expected), b = children(actual);
    return a.length === b.length && a.every(([key, child], i) =>
      key === b[i]![0] && unify(child, b[i]![1], bindings));
  }
  function select(index: number, bindings: Record<string, string>, paths: string[]): Match | null {
    if (index === template.outputs.length) return Object.keys(bindings).length === template.inputs.length ? { bindings, paths } : null;
    for (const node of nodes) {
      if (paths.some(path => path === node.path || path.startsWith(node.path + '.') || node.path.startsWith(path + '.'))) continue;
      const next = { ...bindings };
      if (!unify(template.outputs[index]!.expression, node.expression, next)) continue;
      const found = select(index + 1, next, [...paths, node.path]);
      if (found) return found;
    }
    return null;
  }
  return select(0, {}, []);
}

function residualRequest(request: HarnessRequest, template: StructuralTemplate, match: Match) {
  const reserved = new Set(request.sources.map(s => s.key));
  const keys = template.outputs.map((_, i) => {
    let key = 'p6Core' + i;
    while (reserved.has(key)) key += '_';
    reserved.add(key); return key;
  });
  const replacements = new Map(match.paths.map((path, i) => [path, keys[i]!]));
  function replace(e: Expression, path: string): Expression {
    const key = replacements.get(path); if (key) return { kind: 'input', key };
    if (e.kind === 'input' || e.kind === 'literal') return { ...e };
    if (e.kind === 'if') return {
      kind: 'if', condition: { comparison: e.condition!.comparison,
        left: replace(e.condition!.left, path + '.condition.left'), right: replace(e.condition!.right, path + '.condition.right') },
      whenTrue: replace(e.whenTrue!, path + '.whenTrue'), whenFalse: replace(e.whenFalse!, path + '.whenFalse'),
    };
    return { kind: e.kind, left: replace(e.left!, path + '.left'), right: replace(e.right!, path + '.right') };
  }
  const targets = request.acceptance.targets.map((t, i) => ({ ...t, expression: replace(t.expression, String(i)) }));
  const used = new Set<string>();
  function inputs(e: Expression) {
    if (e.kind === 'input') used.add(e.key!);
    for (const [, child] of children(e)) inputs(child);
  }
  for (const target of targets) inputs(target.expression);
  const first = request.sources.find(s => s.key === match.bindings[template.inputs[0]!.key])!;
  if (first.source.kind !== 'metric' && first.source.kind !== 'artifact') throw Error('P6_MATERIAL_SCHEMA_UNSUPPORTED');
  // Synthetic ports describe an ALREADY derived value within the same module
  // type context. They are never passed to P4 as a claimed enterprise metric.
  const coreSources = template.outputs.map((output, i) => ({
    key: keys[i]!, source: { ...first.source, unit: output.unit, currencyCode: output.currencyCode,
      scale: '1' as const, sign: 'AS_RECORDED' as const },
  }));
  const sources = [...request.sources, ...coreSources].filter(s => used.has(s.key));
  return { request: { ...request, sources, acceptance: { ...request.acceptance,
    requiredSourceKeys: sources.map(s => s.key), targets } }, keys };
}

export async function assertProcedureProgrammeCurrent(ctx: PeMutationContext, q: ProgramRow, c?: PoolClient, lock = false) {
  const use = (q.request as HarnessRequest & { procedure?: ProcedureUse }).procedure;
  if (!use) return;
  requireProcedureMode(use);
  // A fresh fallback does not depend on invalid capsule bytes. Only actual
  // transfer adds the capsule revision to the immutable programme dependencies.
  const read = async (client: PoolClient) =>
    (await client.query('SELECT 1 FROM finnor_os.p1_events WHERE tenant_id=$1 AND principal_id=$2 AND request_id=$3 AND kind=\'P6_EXECUTABLE_TRANSFER\' LIMIT 1',
      [ctx.auth.tenantId, principal(ctx), q.id])).rowCount! > 0;
  const transferred = c ? await read(c) : await tx(ctx, read, true);
  if (transferred) await currentCapsule(ctx, use.capsuleId, c, lock);
}

export async function tryProcedureCandidate(ctx: PeMutationContext, q: ProgramRow, program: HarnessProgram,
  input: Record<string, string>, derivation: any, use: ProcedureUse):
Promise<{ moduleId: string; values: Record<string, HarnessValue>; checks: unknown[] } | null> {
  requireProcedureMode(use);
  const begun = performance.now();
  // Charge every lookup on the original Work, including incompatibility and
  // revocation. A retry cannot create a new budget or extend its deadline.
  await tx(ctx, async c => {
    const charged = await c.query(`UPDATE finnor_os.p1_episodes SET steps_used=steps_used+1
      WHERE id=$1 AND tenant_id=$2 AND principal_id=$3 AND steps_used<max_steps AND deadline_at>clock_timestamp()`,
    [q.episode_id, q.tenant_id, q.principal_id]);
    if (!charged.rowCount) throw Error('P6_ORIGINAL_LOOKUP_GRANT_EXHAUSTED');
  });
  let capsule: Awaited<ReturnType<typeof currentCapsule>>;
  let match: Match | null;
  try {
    capsule = (await checkProcedureUse(ctx, use)).capsule;
    match = matchProcedure(capsule.template, q.request);
    if (!match) throw Error('P6_SCHEMA_SEMANTICS_OR_COMPOSITION_MISMATCH');
  } catch (error) {
    // Rights loss is not permission to synthesize against foreign sources.
    if ((error as { code?: string }).code === 'PE_ENTITY_NOT_FOUND') throw unavailable();
    await trace(ctx, q, 'P6_FRESH_FALLBACK', {
      capsuleId: use.capsuleId, predicate: (error as Error).message.match(/^[A-Z][A-Z0-9_]{0,159}$/)?.[0] ?? 'P6_CURRENTNESS_UNAVAILABLE',
      lookupWallMs: performance.now() - begun, dollars: null, fallback: 'ACTUAL_P1_BASELINE_EXECUTION_REQUIRED',
      originalEpisode: q.episode_id, deadlineAt: program.bounds.deadlineAt, admission: null,
    });
    return null;
  }
  const expected = constructModules(templateRequest(capsule.template), capsule.producer.codeDigest)[0]!;
  if (stable(expected) !== stable(capsule.components.module)) throw Error('P6_REGISTERED_TEMPLATE_EMISSION_SUBSTITUTION');
  const coreInput: Record<string, string> = {};
  for (const [slot, key] of Object.entries(match!.bindings)) {
    const value = derivation.result.outputs[key];
    if (!value || value.kind !== 'scalar' || value.value === null || !value.semantics ||
      stable(invariant(q.request.sources.find(s => s.key === key)!.source)) !==
      stable(capsule.template.inputs.find(i => i.key === slot)!.semantics))
      throw Error('P6_ACTUAL_P4_VALUE_SEMANTICS_UNAVAILABLE');
    coreInput[slot] = input[key]!;
  }
  const residual = residualRequest(q.request, capsule.template, match!);
  const module = constructModules(residual.request, program.producer.codeDigest)[0]!;
  await tx(ctx, async c => {
    const charged = await c.query(`UPDATE finnor_os.p1_episodes SET steps_used=steps_used+$4,attempts_used=attempts_used+1
      WHERE id=$1 AND tenant_id=$2 AND principal_id=$3 AND steps_used+$4<=max_steps
        AND attempts_used<max_attempts AND deadline_at>clock_timestamp()`,
    [q.episode_id, q.tenant_id, q.principal_id, expected.bounds.steps + module.bounds.steps + program.graph.length + 1]);
    if (!charged.rowCount) throw Error('P6_ORIGINAL_EXECUTION_GRANT_EXHAUSTED');
    await c.query(`INSERT INTO finnor_os.p1_modules(tenant_id,principal_id,digest,body)
      VALUES($1,$2,$3,$4::jsonb) ON CONFLICT DO NOTHING`,
    [q.tenant_id, q.principal_id, module.compiledDigest, stable(module)]);
  });
  const deadline = Date.parse(program.bounds.deadlineAt);
  try {
    await assertProgramCurrent(ctx, q);
    const core = await executeTypeScriptModule(expected, coreInput, deadline - Date.now());
    await trace(ctx, q, 'ISOLATED_MODULE_EXECUTION', core);
    if (!core.outputs) throw Error('P6_CORE_ISOLATED_EXECUTION_FAILED');
    const remaining: Record<string, string> = { ...input };
    capsule.template.outputs.forEach((output, i) => remaining[residual.keys[i]!] = core.outputs![output.key]!);
    const result = await executeTypeScriptModule(module, remaining, deadline - Date.now());
    await trace(ctx, q, 'ISOLATED_MODULE_EXECUTION', result);
    if (!result.outputs) throw Error('P6_RESIDUAL_ISOLATED_EXECUTION_FAILED');
    const values: Record<string, HarnessValue> = {};
    const source = derivation.result.outputs[Object.keys(match!.bindings).map(k => match!.bindings[k]!)[0]!];
    for (const target of q.request.acceptance.targets) values[target.key] = {
      value: result.outputs[target.key]!, semantics: { ...source.semantics,
        unit: target.unit, currencyCode: target.currencyCode, scale: '1', sign: 'AS_RECORDED' },
      truthClass: 'DERIVED_VALUE', witnessIds: derivation.witnesses.map((w: any) => w.id),
    };
    const checks = await tx(ctx, c => checkNumericalAcceptance(c, q.request.acceptance, input, values), true);
    if (checks.some(check => check.status !== 'PASS')) throw Error('P6_ORIGINAL_WHOLE_ACCEPTANCE_FAILED');
    await currentCapsule(ctx, capsule.id);
    await assertDependencies(ctx, derivation.invalidationKeys);
    program.modules.push(module);
    program.candidates.push({ id: 'candidate:' + module.structureDigest, moduleId: module.id,
      structureDigest: module.structureDigest, status: 'CHECKED', counterexamples: [] });
    const key = capsuleDependencyKey(principal(ctx), capsule.id);
    program.dependencies.push(...await revisions(ctx, [key]));
    program.semanticBindings.push({
      producer: 'P6', capsuleId: capsule.id, capsuleDigest: sha(capsule), moduleRef: capsule.module,
      originalAcceptanceDigest: program.acceptanceDigest, composition: match, residualModuleId: module.id,
      protectedEligible: false, admission: null,
    });
    await trace(ctx, q, 'P6_EXECUTABLE_TRANSFER', {
      capsuleId: capsule.id, capsuleDigest: sha(capsule), coreModuleId: expected.id, residualModuleId: module.id,
      fabricInvocationId: (core.execution.provenance.compute as { id?: string })?.id ?? null,
      invocationId: core.invocationId, residualInvocationId: result.invocationId,
      inputDigest: sha(coreInput), resultDigest: sha(values), checks, originalAcceptanceDigest: program.acceptanceDigest,
      lookupAndUseWallMs: performance.now() - begun, dollars: null, originalEpisode: q.episode_id,
      qualification: 'PUBLIC_ORDINARY_EXECUTABLE_COMPOSITION_NOT_S8_ADMITTED_TRANSFER',
    });
    return { moduleId: module.id, values, checks };
  } catch (error) {
    await trace(ctx, q, 'P6_FAILED_TRANSFER', {
      capsuleId: capsule.id, predicate: (error as Error).message.match(/^[A-Z][A-Z0-9_]{0,159}$/)?.[0] ?? 'P6_EXECUTION_FAILED',
      elapsedMs: performance.now() - begun, dollars: null, costsRetained: true,
    });
    if ((error as { code?: string }).code === 'PE_ENTITY_NOT_FOUND') throw error;
    // Output/core receipts are never returned as a labelled fallback. The
    // caller now runs its real fresh baseline, subject to the remaining grant.
    await trace(ctx, q, 'P6_FRESH_FALLBACK', { capsuleId: capsule.id,
      predicate: 'P6_FAILED_TRANSFER_REQUIRES_REAL_FRESH_BASELINE', dollars: null,
      originalEpisode: q.episode_id, deadlineAt: program.bounds.deadlineAt });
    return null;
  }
}
