import {chromium,expect} from '../../../node_modules/@playwright/test/index.mjs';
import {strict as assert} from 'node:assert';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
const repo=resolve(import.meta.dirname,'../../..'),base=join(repo,'scope-pm/phase-04-p1-program-synthesis/scope-evidence/browser'),fixture=JSON.parse(await readFile(join(base,'fixture.json'),'utf8'));
const output=join(base,process.env.FINNOR_P1_BROWSER_RUN??'run-verified-1');await mkdir(output,{recursive:true});
const pins=await Promise.all(['src/components/centropy/canvas/ProgramSynthesisPanel.tsx','src/components/centropy/canvas/program-grammar.ts','src/components/centropy/canvas/CanvasDocument.tsx','src/components/centropy/canvas/canvas-contract.ts','src/components/centropy/canvas/canvas-compose.ts','src/components/centropy/shell/CentropyWorkspace.tsx','src/components/jarvis/pe/contracts.ts','finnor-os/scripts/p1/browser-e2e.mjs'].map(async path=>({path,sha256:createHash('sha256').update(await readFile(join(repo,path))).digest('hex')})));await writeFile(join(output,'pre-run-freeze.json'),JSON.stringify({pins,fixture,startedAt:new Date().toISOString(),runtime:process.version,browser:chromium.executablePath(),independentSealed:false},null,2));
const startedAt=new Date().toISOString(),browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage(),steps=[],errors=[],requests=[];
context.setDefaultTimeout(15000);const panel=()=>page.locator('.ct-program'),value=key=>panel().getByRole('button',{name:'Inspect programme evidence for '+key,exact:true});
page.on('pageerror',error=>errors.push(error.message));page.on('response',async response=>{if(response.url().includes('/api/jarvis/')){const url=new URL(response.url());requests.push({path:url.pathname,status:response.status(),method:response.request().method(),bearer:Boolean(response.request().headers().authorization),...(url.pathname.includes('/program-')?{response:await response.json().catch(()=>null)}:{})});}});
async function record(){await writeFile(join(output,'results.json'),JSON.stringify({schema:'finnor.p1.browser-e2e.v1',startedAt,status:steps.some(s=>s.status==='FAIL')?'FAIL':'PASS_LOCAL',profile:fixture.profile,hostedSupabaseQualified:false,expected:fixture.expected,steps,pageErrors:errors,requests,rerun:'Start P1 disposable browser fixture and frontend; node finnor-os/scripts/p1/browser-e2e.mjs',generatedAt:new Date().toISOString()},null,2));}
async function step(id,inputs,run){try{steps.push({id,inputs,status:'PASS',observed:await run()});}catch(error){steps.push({id,inputs,status:'FAIL',error:String(error),stack:error.stack});throw error;}finally{await page.screenshot({path:join(output,id+'.png'),fullPage:true}).catch(()=>{});await writeFile(join(output,id+'.dom.txt'),await page.locator('body').ariaSnapshot().catch(()=>''));await record();}}
const instruction='Create a source-cited equity analysis after debt and liability, together with leverage.',formula='netEquity = if(EV > debt, EV - debt - liability, USD(0)); leverage = if(EBITDA > USD(0), debt / EBITDA, 0 / 0)';
async function fill(){await panel().getByLabel('Desired analytical outcome',{exact:true}).fill(instruction);await panel().getByLabel('Observable calculations',{exact:true}).fill(formula);}
try{
 await step('sign-in-and-registered-canvas',{url:fixture.url},async()=>{await page.goto('http://127.0.0.1:4590/centropy/login');await page.getByLabel('Email',{exact:true}).fill(fixture.email);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/centropy',{timeout:30000});await page.goto(fixture.url);await expect(panel().getByLabel('Desired analytical outcome',{exact:true})).toBeVisible({timeout:30000});assert.equal(await page.locator('[data-nextjs-dialog]').count(),0);return {registeredCanvas:true,localBearer:true};});
 await step('protected-default-refusal',{funding:null,admission:null},async()=>{await fill();await panel().getByRole('button',{name:'Construct and check method',exact:true}).click();await expect(panel().getByRole('status')).toContainText('Protected funding',{timeout:30000});assert.equal(await value('netEquity').count(),0);return {unavailablePredicateVisible:true};});
 await step('ordinary-liability-composition',{instruction,formula,expected:{netEquity:'43',leverage:'3.5'}},async()=>{await panel().getByRole('combobox',{name:'Execution scope',exact:true}).selectOption('ordinary_disposable');await panel().getByRole('button',{name:'Construct and check method',exact:true}).click();await expect(value('netEquity')).toHaveText('43',{timeout:40000});await expect(value('leverage')).toHaveText('3.5');return {url:page.url(),nativeWork:await panel().getAttribute('data-program-work'),values:{netEquity:'43',leverage:'3.5'},billingUSD:null};});
 await step('keyboard-witness-stays-current',{output:'netEquity'},async()=>{await value('netEquity').focus();await page.keyboard.press('Enter');const proof=panel().locator('[data-program-proof]');await expect(proof).toBeVisible();await expect(proof).toBeFocused();await page.waitForResponse(r=>r.url().endsWith('/program-read')&&r.status()===200,{timeout:12000});await expect(proof).toBeVisible();const text=await proof.innerText();assert(text.includes('liability'));assert(text.includes('POSTGRES_NUMERIC'));assert(text.includes('43'));await proof.getByRole('button',{name:'Close programme witness',exact:true}).click();return {keyboardFocus:true,proofSurvivesBackgroundCurrentnessRead:true,liabilityAndIndependentCheck:true};});
 await step('actual-draft-download',{qualification:'ANALYTICAL_DRAFT'},async()=>{const downloadPromise=page.waitForEvent('download');await panel().getByRole('button',{name:'Download checked analytical draft',exact:true}).click();const download=await downloadPromise,path=join(output,'downloaded-analytical-draft.docx');await download.saveAs(path);const bytes=await readFile(path),sha256=createHash('sha256').update(bytes).digest('hex');const response=requests.filter(r=>r.path.endsWith('/program-artifact')&&r.status===200).at(-1)?.response;assert.equal(sha256,response.sha256);return {fileName:download.suggestedFilename(),bytes:bytes.length,sha256,selectedVersion:response.versionId};});
 await step('reload-native-Work-continuity',{reload:true},async()=>{const work=await panel().getAttribute('data-program-work');await page.reload();await expect(value('netEquity')).toHaveText('43',{timeout:30000});assert.equal(await panel().getAttribute('data-program-work'),work);return {workId:work,restoredFromNativeSelectedThread:true};});
 await step('mobile-375',{viewport:{width:375,height:812}},async()=>{const mobile=await browser.newContext({viewport:{width:375,height:812},storageState:await context.storageState()});const p=await mobile.newPage();try{await p.goto(page.url());await p.getByRole('button',{name:'Canvas',exact:true}).click();await expect(p.getByRole('button',{name:'Inspect programme evidence for netEquity',exact:true})).toHaveText('43',{timeout:30000});const size=await p.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=size.client+1,JSON.stringify(size));await p.screenshot({path:join(output,'mobile-375.png'),fullPage:true});return {size};}finally{await mobile.close();}});
 await step('late-native-response-cannot-cross-Work',{equalValues:true,transportFault:'Hold an actual authenticated read response before network delivery'},async()=>{const oldWork=await panel().getAttribute('data-program-work'),oldProgramme=new URL(page.url()).searchParams.get('programId');assert(oldProgramme);const armed=await fetch('http://127.0.0.1:4593/delay-read',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({programId:oldProgramme})});assert.equal(armed.status,200);let delayed;for(let i=0;i<100;i++){delayed=await (await fetch('http://127.0.0.1:4593/delay-status')).json();if(delayed.waiting)break;await new Promise(r=>setTimeout(r,100));}assert(delayed.waiting);await page.getByRole('button',{name:'Investigations',exact:true}).click();await page.getByRole('dialog',{name:'Recent Investigations',exact:true}).getByRole('button',{name:new RegExp('^'+fixture.other.instruction)}).click();await expect(panel()).toHaveAttribute('data-program-work',fixture.other.workId,{timeout:30000});await expect(value('netEquity')).toHaveText('43',{timeout:30000});const released=await fetch('http://127.0.0.1:4593/release-read',{method:'POST'});assert.equal(released.status,200);await new Promise(r=>setTimeout(r,2500));assert.equal(await panel().getAttribute('data-program-work'),fixture.other.workId);assert.equal(new URL(page.url()).searchParams.get('programId'),fixture.other.programId);assert(!await panel().innerText().then(t=>t.includes('Native Work '+oldWork)));await page.getByRole('button',{name:'Investigations',exact:true}).click();await page.getByRole('dialog',{name:'Recent Investigations',exact:true}).getByRole('button',{name:/^Create a source-cited equity analysis/}).click();await expect(panel()).toHaveAttribute('data-program-work',oldWork,{timeout:30000});await expect(value('netEquity')).toHaveText('43',{timeout:30000});return {oldWork,oldProgramme,other:fixture.other,delayed,lateResultRefused:true,originalNativeWorkRestored:true};});
 await step('source-correction-invalidates',{debt:'80'},async()=>{const correction=await fetch('http://127.0.0.1:4593/correct',{method:'POST'});assert.equal(correction.status,200);await expect(value('netEquity')).toHaveCount(0,{timeout:15000});await expect(panel().getByRole('status')).toContainText(/changed|superseded|invalidated/i);assert.equal(await panel().getByRole('button',{name:'Download checked analytical draft',exact:true}).count(),0);return {oldValuesAbsent:true,oldDownloadAbsent:true};});
 await step('rerun-corrected-same-native-Work',{formula,netEquity:'33',leverage:'4'},async()=>{const work=await panel().getAttribute('data-program-work');await fill();await panel().getByRole('combobox',{name:'Execution scope',exact:true}).selectOption('ordinary_disposable');await panel().getByRole('button',{name:'Construct and check method',exact:true}).click();await expect(value('netEquity')).toHaveText('33',{timeout:30000});await expect(value('leverage')).toHaveText('4');assert.equal(await panel().getAttribute('data-program-work'),work);return {workId:work,values:{netEquity:'33',leverage:'4'}};});
 await step('access-revocation-removes-private-draft',{status:'suspended'},async()=>{const response=await fetch('http://127.0.0.1:4593/revoke',{method:'POST'});assert.equal(response.status,200);await expect(value('netEquity')).toHaveCount(0,{timeout:15000});await expect(panel().getByRole('button',{name:'Download checked analytical draft',exact:true})).toHaveCount(0);assert.equal(await panel().locator('[data-program-proof]').count(),0);return {valuesAbsent:true,witnessesAbsent:true,downloadAbsent:true,bearerRefusal:requests.some(r=>[401,403,404].includes(r.status))};});
 assert.equal(errors.length,0,JSON.stringify(errors));
}catch(error){console.error(String(error));process.exitCode=1;}finally{await record();await browser.close();await fetch('http://127.0.0.1:4593/release-read',{method:'POST'}).catch(()=>null);const response=await fetch('http://127.0.0.1:4593/stop',{method:'POST'}).catch(()=>null);await writeFile(join(output,'fixture-shutdown.json'),JSON.stringify({status:response?.status??null},null,2));console.log(JSON.stringify({output,steps:steps.map(s=>({id:s.id,status:s.status,error:s.error})),pageErrors:errors}));}
