/** Authentic S6 refusal for exact USD fee/null semantics absent from its port. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {strict as assert} from 'node:assert';
import {createHash} from 'node:crypto';
import pg from 'pg';
import {closePool} from '@finnor/db';
import {POST} from '../../apps/api/app/api/obligations/[operation]/route';
const source=resolve(process.argv[2]),output=resolve(process.argv[3]);await mkdir(output,{recursive:false});
if(process.env.NODE_ENV!=='test'||!['127.0.0.1','localhost'].includes(new URL(process.env.DATABASE_URL!).hostname))throw Error('OWN_DISPOSABLE_DATABASE_REQUIRED');
const evidence=JSON.parse(await readFile(join(source,'results.json'),'utf8')),first=evidence.results.find((v:any)=>v.id==='actual-upstream-handoff-and-one-native-responsibility').observed,obligation=first.obligation,channel=obligation.intervention.channels[0],methodDigest='1'.repeat(64),admin=new pg.Client({connectionString:process.env.FINNOR_S6_ADMIN_DATABASE_URL});await admin.connect();
const count=async()=>(await admin.query('SELECT (SELECT count(*) FROM finnor_os.external_operations WHERE tenant_id=$1)::int operations,(SELECT count(*) FROM finnor_os.business_effects WHERE tenant_id=$1)::int effects',[obligation.tenantId])).rows[0];const before=await count(),results:any[]=[];
try{for(const [recordKey,value,operation]of[['C_01','20.00','set'],['C_010','200.00','set'],['C_01',null,'clear']] as const){const request={obligationRef:obligation.ref,bindings:[{exposureId:channel.exposureId,methodRef:{owner:'S8',id:'method:'+methodDigest,version:'json-field-replace-v1',contentDigest:methodDigest},providerOrigin:'https://staging.provider.example',applicationAccountId:obligation.tenantId,recordKey,field:'feeUSD',expectedVersion:'etag-test-1',unit:'USD',value,operation}]};const response=await POST(new Request('http://localhost/api/obligations/compile-request',{method:'POST',headers:{'content-type':'application/json','x-tenant-id':obligation.tenantId,'x-user-id':obligation.principalId},body:JSON.stringify(request)}),{params:Promise.resolve({operation:'compile-request'})});const body=await response.json();results.push({id:recordKey+':'+operation,value,status:response.status,body,request});assert.equal(response.status,400,JSON.stringify(body));}const after=await count();assert.deepEqual(after,before);await writeFile(join(output,'results.json'),JSON.stringify({schema:'finnor.p1.exact-fee-owner-port.v1',results,before,after,source,sourceManifestDigest:createHash('sha256').update(await readFile(join(source,'manifest.json'))).digest('hex'),supportedIntervention:channel,qualification:'AUTHENTIC_S6_STRICT_PORT_REFUSAL; EXACT_P1_PROPOSALS_DO_NOT_SUPPLY_A_USD_FEE_OR_NULL_CLEAR_INTERVENTION_ADAPTER; NO_EXTERNAL_EGRESS',requiredNextObjects:['S3_REGISTERED_USD_FEE_INTERVENTION_SEMANTICS','S6_OWNER_APPROVED_EXACT_SET_CLEAR_ADAPTER_AND_FIELD_MAPPING','S8_ADMITTED_METHOD_DOMAIN'],passed:results.length,failed:0},null,2));console.log(JSON.stringify({output,PASS:results.length,FAIL:0,externalEgress:0}));}finally{await admin.end();await closePool();}
