/** All six user-facing owner operations through the actual P1 route/queue. */
import {strict as assert} from 'node:assert';
import {createHash,randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {join} from 'node:path';
import {OPERATIONS} from '../../packages/private-equity/src/program-synthesis/contracts';

export async function runOwnerOperations(e:any,f:any,baseRequest:any,api:any,artifact:any){
 const ref=(id:string)=>({owner:'SUPPLIED',id,version:'p1-public-development-v1',contentDigest:createHash('sha256').update(id).digest('hex')}),start=new Date().toISOString(),end=new Date(Date.now()+3600000).toISOString();
 const inquiry={schema:'finnor.s2.design-request.v1',inquiryId:'p1-native-inquiry',episodeId:'p1-public-native-inquiry',mandateRef:ref('mandate'),decisionContext:{ref:ref('decision'),utilityRef:ref('utility'),horizonEnd:end,lossUnit:'normalized-loss',actionIds:['a0','a1'],lossByHypothesis:[['0','1'],['1','0']]},hypotheses:[{ref:ref('h0'),prior:'0.5',meaning:'Supplied synthetic H0'},{ref:ref('h1'),prior:'0.5',meaning:'Supplied synthetic H1'}],requiredClaimRefs:[],validUntil:end,maxBeliefAgeMs:3600000,
  constraints:{maxSamples:24,maxElapsedMs:3600000,maxExposureUnits:'24',maxPrivacyUnits:'0',moneyLimit:{value:'0',unit:'USD'},permittedPopulationRefs:[ref('population')],permittedInstrumentRefs:[ref('informative')]},
  candidates:[{id:'informative',instrumentRef:ref('informative'),endpoint:{id:'binary-measurement',unit:'category',categories:['negative','positive']},populationRef:ref('population'),measurementUnit:'independent-item',assignment:{kind:'OBSERVATIONAL',unit:'independent-item',probability:'1'},timing:{startAt:start,endAt:end,minimumIntervalMs:0},process:{methodRef:ref('measurement-method'),instrumentError:'IN_LIKELIHOOD',missingness:'NONE',dependence:'CONDITIONAL_IID',interference:'NONE',reactivity:'NONE',nuisance:'FIXED_SUPPLIED'},likelihood:{status:'SUPPLIED_CONDITIONAL',probabilities:[['0.8','0.2'],['0.2','0.8']],calibrationRef:null,assumptions:['Public hypothetical supplied IID law; no field calibration']},samples:2,stopping:{method:'FIXED_SAMPLE',alpha:'0.05',beta:'0.05',minimumPower:'0'},costEstimate:{money:{value:'0',unit:'USD'},elapsedMs:100,humanSeconds:0,dataBytes:1024,integrationUnits:0,computeMs:null},exposure:{unitsPerSample:'1',privacyUnitsPerSample:'0',riskAssumptions:['Local development fixture only']}}]};
 const specification=(dose:number)=>({schema:'finnor.intervention-specification.v1',vocabularyVersion:'s3-intervention-v1',targets:[f.root],context:'public-price',timing:{startAt:f.mandate.horizon.startAt,periodMs:f.mandate.horizon.periodMs,durationMs:f.mandate.horizon.periodMs},channels:[{exposureId:'price',operation:'PRICE_CHANGE',unit:'fraction',target:f.root,doses:[dose],intendedExposure:'REGISTERED_DOSE',permittedRefinements:[]}]});
 const query={schema:'finnor.s3.response-query.v1',id:'p1-model-relative-response',episodeId:f.mandate.episodeId,kind:'POPULATION_INTERVENTION',targets:[f.root],context:'public-price',regime:'operating',horizon:1,intervention:specification(.15),comparator:specification(0),simulations:256,seed:20261003};
 const effect=(key:string,recordId:string,value:string|null)=>({op:'propose_effect',key,target:{account:'DISPOSABLE_AUTHORIZED_FIXTURE_REQUIRED',recordId,field:'feeUSD',version:'v1'},operation:value===null?'clear':'set',value,unit:'USD',idempotencyKey:'p1-proposal-'+key,policyRef:baseRequest.ownerBindings.policyRef,reservationRef:baseRequest.ownerBindings.allocationRef,observation:{resourceId:f.root.entityId,eventType:'p1.fixture.fee_observed',correlationId:recordId}});
 const operations=[{op:'propose_model',key:'mechanismProposal',assumptions:['Supplied mechanism; identification must be resolved by S3'],units:['fraction','normalized-value'],mechanism:'A recorded price exposure may change the outcome. This is an untested hypothesis.'},{op:'design_inquiry',key:'inquiryDesign',request:inquiry},{op:'simulate',key:'modelRelativeRehearsal',modelRef:f.model.ref,query},effect('fee20','C_01','20.00'),effect('fee200','C_010','200.00'),effect('feeClear','C_01',null)];
 const request={...baseRequest,workId:undefined,workInputId:undefined,parentProgramId:undefined,instruction:'Produce the owner bound analytical draft, an unadmitted mechanism proposal, a valid supplied-law inquiry design, a model-relative rehearsal and exact fee/clear proposals. No live collection, dispatch or scientific/business admission is requested.',idempotencyKey:randomUUID(),operations};
 const submitted=await api(f,'program-submit',request);assert.equal(submitted.status,202,JSON.stringify(submitted));const p=submitted.body;let read:any;
 for(let i=0,until=Date.now()+180000;i<600&&Date.now()<until;i++){await e.queue.tick();read=(await api(f,'program-read',{programId:p.programId})).body;if(['TESTED','FAILED','INVALIDATED','PARTIAL'].includes(read.status))break;await new Promise(r=>setTimeout(r,50));}
 await artifact('all-owner-operations-boundary.json',{request,p,read,events:(await e.admin.query('SELECT kind,body FROM finnor_os.p1_events WHERE request_id=$1 ORDER BY created_at,id',[p.programId])).rows});assert.equal(read.status,'TESTED',JSON.stringify({status:read.status,reason:read.reason}));
 const bindings=read.program.semanticBindings,proposal=bindings.find((b:any)=>b.nodeId===read.program.graph.find((n:any)=>n.op==='propose_model').id);assert(proposal);assert.equal(proposal.value.identification,'UNIDENTIFIED_PROPOSAL');assert.equal(proposal.value.admitted,false);
 const design=bindings.find((b:any)=>b.nodeId===read.program.graph.find((n:any)=>n.op==='design_inquiry').id).value;assert.equal(design.measurementOrAssignmentExecuted,false);assert(design.proposal.designs[0].protocol);const independent=spawnSync(process.env.FINNOR_S3_PYTHON!,[join(e.repo,'finnor-os/scripts/s2/reference.py')],{input:JSON.stringify(inquiry),encoding:'utf8'});assert.equal(independent.status,0,independent.stderr);const oracle=JSON.parse(independent.stdout).informative;
 const q=(x:any)=>({numerator:x.numerator,denominator:x.denominator});for(const metric of ['baselineRisk','terminalRisk','riskReduction','expectedSamples'])assert.deepEqual(q(design.proposal.designs[0].protocol.metrics[metric]),oracle[metric]);
 const simulation=bindings.find((b:any)=>b.nodeId===read.program.graph.find((n:any)=>n.op==='simulate').id).value;assert.equal(simulation.evidenceClass,'MODEL_RELATIVE');assert.equal(simulation.liveObservation,false);assert.equal(simulation.response.admission.executionAuthorityGranted,false);assert.equal(simulation.response.admission.methodAdmitted,false);assert.equal(simulation.response.identification.fieldIdentified,false);assert.equal(simulation.response.handoffs.S5.reservationGranted,false);assert.equal(simulation.response.handoffs.S7.creditGranted,false);
 const proposals=read.program.effectProposals;assert.equal(proposals.length,3);assert.deepEqual(proposals.map((v:any)=>({record:v.target.recordId,value:v.value,operation:v.operation})),[{record:'C_01',value:'20.00',operation:'set'},{record:'C_010',value:'200.00',operation:'set'},{record:'C_01',value:null,operation:'clear'}]);assert(new Set(proposals.map((p:any)=>p.requestDigest)).size===3);assert(proposals.every((v:any)=>v.executionAuthorityGranted===false&&v.dispatched===false));
 const counts=(await e.admin.query('SELECT (SELECT count(*) FROM finnor_os.business_effects WHERE tenant_id=$1)::int effects,(SELECT count(*) FROM finnor_os.s5_consumptions WHERE tenant_id=$1)::int consumptions',[f.tenant])).rows[0];assert.equal(counts.effects,0);assert.equal(counts.consumptions,0);
 const malformed=await api(f,'program-submit',{...request,idempotencyKey:randomUUID(),operations:[{...effect('badClear','C_01',null),value:'0.00'}]});assert.equal(malformed.status,422);assert.equal(malformed.body.predicate,'EXACT_NULL_OPERATION_MISMATCH');
 const emitted=new Set(read.program.graph.map((n:any)=>n.op));assert(OPERATIONS.filter(op=>!['await_observation','stop'].includes(op)).every(op=>emitted.has(op)));return {p,read,inquiryOracle:oracle,counts,malformed,qualification:'OWNER_NATIVE_PROPOSALS_DESIGN_AND_MODEL_RELATIVE_REHEARSAL; NO_SCIENTIFIC_ADMISSION_OR_EFFECT_EGRESS'};
}
