import {chromium,expect} from '../../../node_modules/@playwright/test/index.mjs';
import {strict as assert} from 'node:assert';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
const repo=resolve(import.meta.dirname,'../../..'),base=join(repo,'scope-pm/phase-01-p4-evidence-execution/scope-evidence/browser'),fixture=JSON.parse(await readFile(join(base,'fixture.json'),'utf8'));
const output=join(base,process.env.FINNOR_P4_BROWSER_RUN??'run-01');await mkdir(output,{recursive:true});
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),steps=[],errors=[],requests=[];
context.setDefaultTimeout(15000);
page.on('pageerror',error=>errors.push(error.message));page.on('response',async response=>{if(response.url().includes('/api/jarvis/')){const url=new URL(response.url());requests.push({path:url.pathname,status:response.status(),method:response.request().method(),bearer:Boolean(response.request().headers().authorization),...(url.pathname.includes('/evidence-')?{response:await response.json().catch(()=>null)}:{})});}});
async function record(){await writeFile(join(output,'results.json'),JSON.stringify({schema:'finnor.p4.browser-e2e.v1',profile:fixture.profile,hostedSupabaseQualified:false,expected:fixture.expected,steps,pageErrors:errors,requests,rerun:'Start disposable browser fixture and frontend; node finnor-os/scripts/p4/browser-e2e.mjs',generatedAt:new Date().toISOString()},null,2));}
async function step(id,inputs,run){try{const observed=await run();steps.push({id,inputs,status:'PASS',observed});}catch(error){steps.push({id,inputs,status:'FAIL',error:String(error),stack:error.stack});throw error;}finally{await page.screenshot({path:join(output,id+'.png'),fullPage:true}).catch(()=>{});await writeFile(join(output,id+'.dom.txt'),await page.locator('body').ariaSnapshot().catch(()=>''));await record();}}
try{
 await step('sign-in-and-registered-canvas',{url:fixture.url},async()=>{await page.goto('http://127.0.0.1:4590/centropy/login');await page.getByLabel('Email',{exact:true}).fill(fixture.email);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/centropy',{timeout:30000});await page.goto(fixture.url);await expect(page.getByRole('textbox',{name:'Financial question',exact:true})).toBeVisible({timeout:30000});assert.equal(await page.locator('[data-nextjs-dialog]').count(),0);return {registeredControl:true,bearerRouteRequests:requests.filter(r=>r.bearer).length};});
 await step('protected-default-refusal',{admission:null,funding:null},async()=>{await page.getByLabel('Period start',{exact:true}).fill('2025-01-01');await page.getByLabel('Period end',{exact:true}).fill('2025-12-31');await page.getByRole('button',{name:'Ask and calculate',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'protected funding'})).toBeVisible({timeout:30000});assert.equal(await page.getByRole('button',{name:'Inspect evidence for equity',exact:true}).count(),0);return {message:await page.getByRole('status').filter({hasText:'protected funding'}).innerText()};});
 await step('ordinary-current-50-and-3point5',{periodStart:'2025-01-01',periodEnd:'2025-12-31',formula:'equity = EV - debt; leverage = debt / EBITDA'},async()=>{await page.getByRole('combobox',{name:'Execution scope',exact:true}).selectOption('ordinary_disposable');await page.getByRole('button',{name:'Ask and calculate',exact:true}).click();await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveText('50',{timeout:40000});await expect(page.getByRole('button',{name:'Inspect evidence for leverage',exact:true})).toHaveText('3.5');const ack=Number(await page.locator('.ct-evidence').getAttribute('data-ack-ms'));assert(ack<=100,'Local acknowledgment '+ack+' ms exceeds 100 ms');return {ackMs:ack,url:page.url(),values:{equity:'50',leverage:'3.5'},costStatus:'LOCAL_COST_UNMETERED'};});
 await step('one-click-keyboard-witness',{output:'equity'},async()=>{await page.getByRole('button',{name:'Inspect evidence for equity',exact:true}).focus();await page.keyboard.press('Enter');const proof=page.getByRole('region',{name:'Exact evidence witness',exact:true});await expect(proof).toBeVisible();await expect(proof).toBeFocused();await expect(proof.getByText('Source witnesses',{exact:true})).toBeVisible();await expect(proof.getByText('Transformations and independent checks',{exact:true})).toBeVisible();const text=await proof.innerText();assert(text.includes('value_numeric = 120'));assert(text.includes('value_numeric = 70'));assert(text.includes('POSTGRES_NUMERIC'));await proof.getByRole('button',{name:'Close evidence witness',exact:true}).click();return {exactRecordFields:true,independentCheckVisible:true,keyboardFocus:true};});
 await step('reload-revalidates',{reload:true},async()=>{await page.reload();await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveText('50',{timeout:30000});return {restoredFromAuthenticatedAPI:true,url:page.url()};});
 await step('mobile-375',{viewport:{width:375,height:812}},async()=>{const mobile=await browser.newContext({viewport:{width:375,height:812},storageState:await context.storageState()});const p=await mobile.newPage();try{await p.goto(page.url());await p.getByRole('button',{name:'Canvas',exact:true}).click();await expect(p.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveText('50',{timeout:30000});const size=await p.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=size.client+1,JSON.stringify(size));await p.screenshot({path:join(output,'mobile-375-evidence.png'),fullPage:true});await writeFile(join(output,'mobile-375-evidence.dom.txt'),await p.locator('body').ariaSnapshot());return {size,value:'50'};}finally{await mobile.close();}});
 await step('partial-ui-and-return',{absentPeriod:'2024',currentPeriod:'2025'},async()=>{await page.getByRole('combobox',{name:'Execution scope',exact:true}).selectOption('ordinary_disposable');await page.getByLabel('Period start',{exact:true}).fill('2024-01-01');await page.getByLabel('Period end',{exact:true}).fill('2024-12-31');const acceptedResponse=page.waitForResponse(r=>r.url().endsWith('/evidence-submit')&&r.request().method()==='POST');await page.getByRole('button',{name:'Ask and calculate',exact:true}).click();const accepted=await acceptedResponse;assert.equal(accepted.status(),202);const missingQuery=await accepted.json();const partialReadResponse=await page.waitForResponse(async r=>r.url().endsWith('/evidence-read')&&r.status()===200&&(await r.json()).queryId===missingQuery.queryId&&(await r.json()).status==='PARTIAL',{timeout:30000});const partialRead=await partialReadResponse.json();await expect(page.locator('.ct-evidence').getByRole('status')).toHaveText(/partial/i,{timeout:30000});await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveCount(0);const partialMessage=await page.locator('.ct-evidence').getByRole('status').innerText();await page.getByLabel('Period start',{exact:true}).fill('2025-01-01');await page.getByLabel('Period end',{exact:true}).fill('2025-12-31');await page.getByRole('button',{name:'Ask and calculate',exact:true}).click();await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveText('50',{timeout:30000});const workIds=[...new Set(requests.filter(r=>r.path.endsWith('/evidence-submit')&&r.status===202).map(r=>r.response.workId))];assert.equal(workIds.length,1,'Repeated questions must retain the actual Work');return {partialMessage,missingQueryId:missingQuery.queryId,actualStatus:partialRead.status,oldMaterialAbsent:true,current:'50',workIds};});
 await step('correction-clears-and-replays',{debt:'80',expected:{equity:'40',leverage:'4'}},async()=>{const correction=await fetch('http://127.0.0.1:4593/correct',{method:'POST'});assert.equal(correction.status,200);await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveCount(0,{timeout:15000});await expect(page.getByText('Source, access, Work, or runtime changed. The earlier values are invalidated.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Recheck current sources',exact:true}).click();await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveText('40',{timeout:30000});await expect(page.getByRole('button',{name:'Inspect evidence for leverage',exact:true})).toHaveText('4');return {oldValueAbsent:true,newValues:{equity:'40',leverage:'4'}};});
 await step('access-revocation-clears',{status:'suspended'},async()=>{const response=await fetch('http://127.0.0.1:4593/revoke',{method:'POST'});assert.equal(response.status,200);await expect(page.getByRole('button',{name:'Inspect evidence for equity',exact:true})).toHaveCount(0,{timeout:15000});assert.equal(await page.getByRole('region',{name:'Exact evidence witness',exact:true}).count(),0);return {privateValuesAbsent:true,bearerRefusal:requests.some(r=>r.status===403)};});
 assert.equal(errors.length,0,JSON.stringify(errors));
}catch(error){console.error(String(error));process.exitCode=1;}finally{await record();await browser.close();let fixtureStop;try{const response=await fetch('http://127.0.0.1:4593/stop',{method:'POST'});fixtureStop={status:response.status,method:'POST',path:'/stop'};}catch(error){fixtureStop={error:String(error)};process.exitCode=1;}await writeFile(join(output,'fixture-shutdown.json'),JSON.stringify(fixtureStop,null,2));console.log(JSON.stringify({output,steps:steps.map(s=>({id:s.id,status:s.status,error:s.error})),pageErrors:errors,fixtureStop}));}
