import {strict as assert} from 'node:assert';
import {randomUUID,createHash} from 'node:crypto';
const stable=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(stable).join(',')+']':'{'+Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+':'+stable(x)).join(',')+'}';
const sha=(v:any)=>createHash('sha256').update(stable(v)).digest('hex');
export async function incrementalE2E(e:any){const {test,api,submit,finish,original,admin,tenant,actor}=e;
 await test('precise-node-reuse-and-full-recompute',{kept:['evrows','ev','erows','ebitda'],computed:['drows','debt','equity','leverage'],expected:{equity:'40',leverage:'4'}},'correction reuses exactly four unchanged native nodes, records old/new digests and agrees with fully recomputed identical source handles',async()=>{
  const corrected=original.corrected;assert.equal(corrected.status,'TESTED');const report=corrected.derivation.recomputation;
  assert.deepEqual(report.nodes.filter((n:any)=>n.state==='KEPT').map((n:any)=>n.id).sort(),['evrows','ev','erows','ebitda'].sort());
  assert.deepEqual(report.nodes.filter((n:any)=>n.state==='COMPUTED').map((n:any)=>n.id).sort(),['drows','debt','equity','leverage'].sort());
  for(const n of report.nodes.filter((n:any)=>n.state==='KEPT')){assert.equal(n.oldDigest,n.newDigest);assert(n.originDerivationId);assert.match(n.validityReason,/CURRENT_AUTHORIZED/);}
  process.env.FINNOR_P4_DISABLE_NODE_REUSE='1';let full:any;try{full=await finish(await submit('A',{handles:corrected.derivation.sourceHandles,knowledgeAt:corrected.derivation.knowledgeAt}));}finally{delete process.env.FINNOR_P4_DISABLE_NODE_REUSE;}
  assert.equal(full.status,'TESTED');assert.equal(full.derivation.result.digest,corrected.derivation.result.digest);assert(full.derivation.recomputation.nodes.every((n:any)=>n.state==='COMPUTED'));
  const expectedNodes=(await admin.query('SELECT node_id,digest FROM finnor_os.p4_nodes WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 ORDER BY node_id',[tenant,actor,corrected.derivation.id])).rows;
  const fullNodes=(await admin.query('SELECT node_id,digest FROM finnor_os.p4_nodes WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 ORDER BY node_id',[tenant,actor,full.derivation.id])).rows;assert.deepEqual(fullNodes,expectedNodes);
  const retained=(await admin.query("SELECT body FROM finnor_os.p4_attempt_events WHERE query_id=$1 AND kind='KEPT_VALIDITY'",[corrected.queryId])).rows;assert.equal(retained.length,1);return {report,full,expectedNodes,fullNodes,retained};
 });
 await test('node-cache-independent-oracle-mutant',{scalar:'999',expected:'independent original-source SQL rejects'},'matching cache checksum cannot replace independent original-operand numerical checking',async()=>{
  const current=await finish(await submit('A'));assert.equal(current.status,'TESTED');
  const row=(await admin.query('SELECT * FROM finnor_os.p4_nodes WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'equity\'',[tenant,actor,current.derivation.id])).rows[0];assert(row.cache_key);
  const body={...row.body,value:'999'};
  await admin.query('BEGIN');try{await admin.query('ALTER TABLE finnor_os.p4_nodes DISABLE TRIGGER p4_immutable');await admin.query('UPDATE finnor_os.p4_nodes SET body=$4::jsonb,digest=$5 WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'equity\'',[tenant,actor,current.derivation.id,stable(body),sha(body)]);await admin.query('ALTER TABLE finnor_os.p4_nodes ENABLE TRIGGER p4_immutable');await admin.query('COMMIT');}catch(error){await admin.query('ROLLBACK');throw error;}
  const refused=await finish(await submit('A'));assert.equal(refused.status,'FAILED');assert.equal(refused.derivation.result,null);assert(refused.derivation.independentChecks.some((c:any)=>c.id==='numeric:equity'&&c.status==='FAIL'&&c.expected==='40'&&c.actual==='999'));
  await admin.query('BEGIN');try{await admin.query('ALTER TABLE finnor_os.p4_nodes DISABLE TRIGGER p4_immutable');await admin.query('UPDATE finnor_os.p4_nodes SET body=$4::jsonb,digest=$5 WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'equity\'',[tenant,actor,current.derivation.id,stable(row.body),row.digest]);await admin.query('ALTER TABLE finnor_os.p4_nodes ENABLE TRIGGER p4_immutable');await admin.query('COMMIT');}catch(error){await admin.query('ROLLBACK');throw error;}
  const source=(await admin.query('SELECT * FROM finnor_os.p4_nodes WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'evrows\'',[tenant,actor,current.derivation.id])).rows[0];const sourceBody={...source.body,rows:source.body.rows.map((r:any)=>({...r,value:'999',fields:{...r.fields,value:'999'}}))};
  await admin.query('BEGIN');try{await admin.query('ALTER TABLE finnor_os.p4_nodes DISABLE TRIGGER p4_immutable');await admin.query('UPDATE finnor_os.p4_nodes SET body=$4::jsonb,digest=$5 WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'evrows\'',[tenant,actor,current.derivation.id,stable(sourceBody),sha(sourceBody)]);await admin.query('ALTER TABLE finnor_os.p4_nodes ENABLE TRIGGER p4_immutable');await admin.query('COMMIT');}catch(error){await admin.query('ROLLBACK');throw error;}
  const tableResult=await finish(await submit('A',{handles:current.derivation.sourceHandles,program:{schema:'finnor.derivation-ir.v1',nodes:[{id:'evrows',op:'source',inputId:'EV'}],outputs:['evrows']},acceptance:{selectedUniverse:'COMPLETE',absoluteTolerance:'0',materialOutputs:['evrows']}}));assert.equal(tableResult.status,'FAILED');assert.equal(tableResult.derivation.result,null);assert(tableResult.derivation.independentChecks.some((c:any)=>c.id==='source-table:evrows'&&c.status==='FAIL'));
  await admin.query('BEGIN');try{await admin.query('ALTER TABLE finnor_os.p4_nodes DISABLE TRIGGER p4_immutable');await admin.query('UPDATE finnor_os.p4_nodes SET body=$4::jsonb,digest=$5 WHERE tenant_id=$1 AND principal_id=$2 AND derivation_id=$3 AND node_id=\'evrows\'',[tenant,actor,current.derivation.id,stable(source.body),source.digest]);await admin.query('ALTER TABLE finnor_os.p4_nodes ENABLE TRIGGER p4_immutable');await admin.query('COMMIT');}catch(error){await admin.query('ROLLBACK');throw error;}
  return {administratorOnlyMutant:true,cacheKey:row.cache_key,refused,tableResult};
 });
}
