import {strict as assert} from 'node:assert';
import {randomUUID} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {createDeal,createInvestmentCase,createUnderwritingModel,createUnderwritingModelVersion,createUnderwritingRun,explainUnderwritingOutput} from '@finnor/private-equity';
export async function incumbentComparison(e:any){const {test,ctx,actor,companies,sourceRef,submit,finish,expected}=e;
 await test('actual-incumbent-paired-native-comparison',{tasks:['A','B','C'],reuseTrials:2,expected},'actual completed-S equipped numerical incumbent and P4 complete paired exact public fixture tasks; timing is diagnostic, total-dollar superiority unqualified',async()=>{const prepared:any={},preparationStarted=performance.now();
  for(const name of ['A','B','C']){const deal=await createDeal(ctx,{targetOrganizationId:companies[name],name:'P4 incumbent '+name,dealLeadEmployeeId:actor,signedLoiAt:new Date('2025-01-01'),targetClosingAt:new Date('2027-01-01')});const c=await createInvestmentCase(ctx,{dealId:String(deal.row.id),title:'Paired ordinary incumbent'});const investmentCaseId=String(c.row.id),m=await createUnderwritingModel(ctx,{investmentCaseId,modelKey:'p4-incumbent',name:'Reusable exact incumbent procedure'});const inputs=[['ev','EV'],['debt','debt'],['ebitda','EBITDA']].map(([id,metric])=>({id,kind:'input',dependencies:[],valueType:'decimal',unit:'money',currency:'USD',shape:'scalar',required:true,source:{kind:'evidence_version',evidenceVersionId:sourceRef.evidenceVersionId,valuePath:name+'.'+metric}}));const expr=(id:string,op:string,left:string,right:string,unit:string)=>({id,kind:'expression',dependencies:[left,right],valueType:'decimal',unit,...(unit==='money'?{currency:'USD'}:{}),shape:'scalar',expression:{op,args:[{op:'ref',nodeId:left},{op:'ref',nodeId:right}]}});const outputs=['equity','leverage'].map(id=>({id,kind:'output',dependencies:[id+'_calc'],sourceNodeId:id+'_calc',valueType:'decimal',unit:id==='equity'?'money':'ratio',...(id==='equity'?{currency:'USD'}:{}),shape:'scalar'}));const version=await createUnderwritingModelVersion(ctx,{modelId:String(m.id),definition:{schemaVersion:'underwriting-model-ir.v1',modelKey:'p4-incumbent',modelVersion:'1',financialConventionVersion:'finnor-pe-lbo/1.0.0',minimumEngineVersion:'finnor-underwriting-engine/1.0.0',periodDefinition:{frequency:'annual',forecastStart:'2026-01-01',count:1},nodes:[...inputs,expr('equity_calc','subtract','ev','debt','money'),expr('leverage_calc','divide','debt','ebitda','ratio'),...outputs],circularBlocks:[]}} as any);prepared[name]={investmentCaseId,modelVersionId:String(version.id)};}
  const preparationMs=performance.now()-preparationStarted,pairs:any[]=[];
  for(let trial=0;trial<2;trial++)for(const name of ['A','B','C']){const at=new Date().toISOString();let incumbent:any,p4:any;const times:any={};const incumbentRun=async()=>{const t=performance.now(),cpu=process.cpuUsage();incumbent=await createUnderwritingRun(ctx,{...prepared[name],worldAt:at,idempotencyKey:randomUUID()});await explainUnderwritingOutput(ctx,String(incumbent.id),'equity');times.incumbent={wallMs:performance.now()-t,parentCpuMicros:process.cpuUsage(cpu).user+process.cpuUsage(cpu).system,rssBytes:process.memoryUsage().rss};};const candidateRun=async()=>{const t=performance.now();p4=await finish(await submit(name,{validAt:at}));times.p4={wallMs:performance.now()-t,costs:p4.derivation?.costs??null};};if(trial===0){await incumbentRun();await candidateRun();}else{await candidateRun();await incumbentRun();}assert.equal(p4.status,'TESTED',JSON.stringify(p4));for(const key of ['equity','leverage']){assert.equal(incumbent.result.outputs[key].value,expected[name][key]);assert.equal(p4.derivation.result.outputs[key].value,expected[name][key]);}assert(Object.values(incumbent.inputSnapshot.values).every((v:any)=>v.provenance.some((p:any)=>p.kind==='evidence_version')));pairs.push({name,trial:trial===0?'cold-task':'amortized-task',validAt:at,times,incumbent:{runId:incumbent.id,inputSnapshot:incumbent.inputSnapshot,result:incumbent.result},p4});}
  return {preparationMs,prepared,pairs,costUSD:null,costStatus:'LOCAL_COST_UNMETERED',qualifiedFrontierDelta:'INCONCLUSIVE',scope:'Actual public finite native procedures; no equipped frontier-model trial or total-dollar confidence interval.'};
 });
}
