/** New frontier E2E harness with the already verified real fixture bootstrap.
 * Supplemental protocol/failure model was frozen before this harness. */
import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';
import {strict as assert} from 'node:assert';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,appendFile,readFile,rm,readdir,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {createServer} from 'node:net';
import {performance} from 'node:perf_hooks';
import {migrate} from '../../packages/db/migrate';
import {closePool,configureTenantVertical,withTenantTransaction} from '@finnor/db';
import {createEvidenceSource,appendEvidenceVersion} from '@finnor/memory';
import {createMetricSeries,recordMetricObservation,restateMetricObservation,type PeMutationContext} from '@finnor/private-equity';

const repo=resolve(import.meta.dirname,'../../..');
const evidence=resolve(process.env.FINNOR_P4_EVIDENCE_DIR??join(repo,'scope-pm/phase-01-p4-evidence-execution/scope-evidence',`run-${new Date().toISOString().replace(/[:.]/g,'-')}`));
await mkdir(evidence,{recursive:true});
const productionIdentity=await (await import('../../packages/private-equity/src/evidence-execution/store')).currentCodeIdentity();
const testPaths=(await readdir(import.meta.dirname)).filter(p=>/\.(mts|mjs|py|json)$/.test(p)).sort();
const tests=await Promise.all(testPaths.map(async path=>({path:'finnor-os/scripts/p4/'+path,sha256:createHash('sha256').update(await readFile(join(import.meta.dirname,path))).digest('hex')})));
const installedPackages=await Promise.all(['next','tsx','pg','embedded-postgres','typescript','playwright'].map(async name=>{try{const file=join(repo,'finnor-os/node_modules',name,'package.json'),bytes=await readFile(file);return {name,version:JSON.parse(bytes.toString()).version,packageJsonSha256:createHash('sha256').update(bytes).digest('hex'),resolvedPath:await realpath(file)};}catch{return {name,status:'UNAVAILABLE_IN_BACKEND_RESOLUTION'};}}));
await writeFile(join(evidence,'pre-run-freeze.json'),JSON.stringify({schema:'finnor.p4.run-freeze.v1',frozenAt:new Date().toISOString(),command:'node --import=tsx scripts/p4/run-frontier-comparison.mts',cwd:process.cwd(),environmentNames:Object.keys(process.env).filter(k=>/^(FINNOR_P4_|AUTH_DEV_BYPASS|DATABASE_URL|NODE_ENV)/.test(k)).sort(),productionIdentity,tests,installedPackages,node:{version:process.version,executable:await realpath(process.execPath),sha256:createHash('sha256').update(await readFile(process.execPath)).digest('hex')},imageAttestation:null,oracle:'Predeclared public A/B/C constants and separate SQL numeric source path; no independent sealed split',inputCorpus:'fixture/constants below; generated byte fixtures retained with actual source SHA witnesses',qualification:'Installed package manifest identities and real linked paths, not a clean-install or transitive dependency byte attestation'},null,2)+'\n');
const results:any[]=[]; const startedAt=new Date().toISOString();
const start=performance.now();
const tenant=randomUUID(),actor=randomUUID(),foreignTenant=randomUUID(),foreignActor=randomUUID();
const companies={A:'11111111-1111-4111-8111-111111111111',B:randomUUID(),C:randomUUID(),foreign:randomUUID()};
const ctx:PeMutationContext={auth:{tenantId:tenant,userId:actor,employeeId:actor,role:'owner'},provenance:{sourceSystem:'p4:e2e',createdBy:actor}};
const periodStart='2025-01-01T00:00:00.000Z',periodEnd='2025-12-31T00:00:00.000Z',validAt='2026-01-01T00:00:00.000Z';
const root=(name:keyof typeof companies)=>({entityType:'external_organization',entityId:companies[name]});
const series:Record<string,string>={},observations:Record<string,string>={};
const fixture={A:{EV:'120',EBITDA:'20',debt:'70'},B:{EV:'100',EBITDA:'25',debt:'50'},C:{EV:'90',EBITDA:'15',debt:'45'}};
const expected={A:{equity:'50',leverage:'3.5'},B:{equity:'50',leverage:'2'},C:{equity:'45',leverage:'3'}};
let postgres!:EmbeddedPostgres,admin!:pg.Client,post:any,queue:any,handler:any,migrationCount=0;
const directory=await mkdtemp(join(tmpdir(),'finnor-p4-'));
const save=async()=>writeFile(join(evidence,'results.json'),JSON.stringify({schema:'finnor.p4.frontier-runner.v1',startedAt,generatedAt:new Date().toISOString(),durationMs:performance.now()-start,
 status:results.some(x=>x.status==='FAIL')?'FAIL':'PASS_LOCAL',runtime:process.version,migrationCount,profile:'disposable actual PostgreSQL ordinary finnor_app / existing nonproduction auth bypass / actual Company Brain POST / actual JobQueue',
 independentAdmission:false,billingUSD:null,costStatus:'LOCAL_COST_UNMETERED',fixture,expected,results,rerun:'cd finnor-os && node --import=tsx scripts/p4/run-frontier-comparison.mts'},null,2)+'\n');
async function test(id:string,input:unknown,predicate:string,fn:()=>Promise<unknown>){if(process.env.FINNOR_P4_CASE_FILTER&&!id.includes(process.env.FINNOR_P4_CASE_FILTER)){results.push({id,status:'NOT_RUN',predicate,input});await save();return;}const t=performance.now();try{results.push({id,input,predicate,status:'PASS',observed:await fn(),durationMs:performance.now()-t});}catch(e){results.push({id,input,predicate,status:'FAIL',observed:{message:String((e as Error).message),stack:(e as Error).stack},durationMs:performance.now()-t});}await save();}
async function api(operation:string,body:unknown,identity={tenant,actor}){const response=await post(new Request('http://localhost/api/company-brain/'+operation,{method:'POST',headers:{'content-type':'application/json','x-tenant-id':identity.tenant,'x-user-id':identity.actor},body:JSON.stringify(body)}),{params:Promise.resolve({operation})});return {status:response.status,body:await response.json()};}
const descriptor=(name:keyof typeof companies,metricKey:string,overrides:any={})=>({kind:'metric',subject:root(name),metricKey,periodStart,periodEnd,unit:'currency',currencyCode:'USD',frequency:'annual',calendar:'OWNER_RECORDED',consolidation:'OWNER_SUBJECT_ONLY',instrument:'UNSPECIFIED',scale:'1',sign:'AS_RECORDED',...overrides});
const program={schema:'finnor.derivation-ir.v1',nodes:[{id:'evrows',op:'source',inputId:'EV'},{id:'ev',op:'unique',input:'evrows'},{id:'drows',op:'source',inputId:'debt'},{id:'debt',op:'unique',input:'drows'},{id:'erows',op:'source',inputId:'EBITDA'},{id:'ebitda',op:'unique',input:'erows'},{id:'equity',op:'subtract',left:'ev',right:'debt'},{id:'leverage',op:'ratio',left:'debt',right:'ebitda',decimalPlaces:18}],outputs:['equity','leverage']};
async function handles(name:keyof typeof companies,descriptors:any[]=['EV','debt','EBITDA'].map(m=>({inputId:m,source:descriptor(name,m)}))){const h=await api('evidence-handles',{root:root(name),validAt,inputs:descriptors});assert.equal(h.status,200,JSON.stringify(h.body));return h.body.handles;}
async function submit(name:keyof typeof companies,options:any={}){const hs=options.handles??await handles(name);const request={schema:'finnor.evidence-request.v1',question:'Calculate equity as EV minus debt and leverage as debt divided by EBITDA for the exact registered annual subject.',root:root(name),validAt,idempotencyKey:randomUUID(),mode:'ordinary_disposable',inputs:hs.map((h:any)=>({inputId:h.inputId,handleId:h.id})),program,acceptance:{selectedUniverse:'COMPLETE',absoluteTolerance:'0',materialOutputs:['equity','leverage']},...options};delete request.handles;const response=await api('evidence-submit',request);assert.equal(response.status,202,JSON.stringify(response.body));return response.body;}
async function finish(submitted:any){for(let i=0;i<12;i++){await queue.tick();const r=await api('evidence-read',{queryId:submitted.queryId});assert.equal(r.status,200,JSON.stringify(r.body));if(['TESTED','FAILED','INVALIDATED','CANCELLED','PARTIAL'].includes(r.body.status)){const events=(await admin.query('SELECT kind,body FROM finnor_os.p4_attempt_events WHERE query_id=$1 ORDER BY created_at',[submitted.queryId])).rows;await writeFile(join(evidence,'trace-'+submitted.queryId+'.json'),JSON.stringify(events,null,2));return r.body;}await new Promise(r=>setTimeout(r,25));}throw new Error('Real queue did not complete bounded query');}
const value=(result:any,key:string)=>result.derivation?.result?.outputs?.[key]?.value;
try{
 process.env.FINNOR_TEST_MANAGED_EXTENSIONS='omit'; process.env.AUTH_DEV_BYPASS='1';process.env.NODE_ENV='test'; process.env.FINNOR_P4_PROFILE='ordinary_disposable';
 const port=await new Promise<number>((yes,no)=>{const s=createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const a=s.address();if(!a||typeof a==='string')return no(Error('port'));s.close(()=>yes(a.port));});});
 postgres=new EmbeddedPostgres({databaseDir:directory,user:'finnor',password:'finnor',port,persistent:false,onLog:()=>undefined});
 await postgres.initialise();await appendFile(join(directory,'postgresql.conf'),'\ntrack_commit_timestamp='+(process.env.FINNOR_P4_TRACK_COMMITS==='off'?'off':'on')+'\n');await postgres.start();await postgres.createDatabase('p4_e2e');
 const adminUrl=`postgres://finnor:finnor@127.0.0.1:${port}/p4_e2e`;migrationCount=(await migrate(adminUrl)).length;
 admin=new pg.Client({connectionString:adminUrl});await admin.connect();await admin.query("INSERT INTO finnor_os.compute_resource_policies(resource_key,capacity,per_tenant_capacity,interactive_reserve,lease_seconds,source) VALUES('native:p4',2,2,0,60,'explicit disposable P4 fixture; unmetered engineering capacity, not protected funding')");await admin.query("ALTER ROLE finnor_app LOGIN PASSWORD 'finnor_app'");await admin.query("SET app.test_vertical_mode='explicit'");
 await admin.query("INSERT INTO finnor_os.tenants(id,client_key,name) VALUES($1,$2,'P4 ordinary'),($3,$4,'P4 foreign')",[tenant,randomUUID(),foreignTenant,randomUUID()]);
 await admin.query("INSERT INTO finnor_os.users(id,tenant_id,email,role,status,display_name) VALUES($1,$2,$3,'owner','active','P4 ordinary'),($4,$5,$6,'owner','active','P4 foreign')",[actor,tenant,`${actor}@test.invalid`,foreignActor,foreignTenant,`${foreignActor}@test.invalid`]);
 process.env.DATABASE_URL=`postgres://finnor_app:finnor_app@127.0.0.1:${port}/p4_e2e`;await closePool();
 await configureTenantVertical({tenantId:tenant,verticalKey:'private_equity',expectedVersion:0,createdBy:actor,sourceSystem:'p4:e2e'});await configureTenantVertical({tenantId:foreignTenant,verticalKey:'private_equity',expectedVersion:0,createdBy:foreignActor,sourceSystem:'p4:e2e'});
 for(const name of ['A','B','C'] as const)await admin.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,$3,$4,'other')",[companies[name],tenant,'p4-'+name.toLowerCase(),'P4 '+name]);
 await admin.query("INSERT INTO finnor_os.external_organizations(id,tenant_id,organization_key,name,kind) VALUES($1,$2,'p4-foreign','P4 FOREIGN SECRET','other')",[companies.foreign,foreignTenant]);
 const evidenceSource=await createEvidenceSource(tenant,{sourceKey:'p4-original',sourceType:'manual',title:'Predeclared source fixture'});
 const evidenceVersion=await appendEvidenceVersion(tenant,evidenceSource.id,{content:'A EV120 EBITDA20 debt70; B EV100 EBITDA25 debt50; C EV90 EBITDA15 debt45',snapshot:fixture,asOf:new Date(periodStart)});
 const sourceRef={evidenceSourceId:evidenceSource.id,evidenceVersionId:evidenceVersion.versionId};
 for(const [name,metrics] of Object.entries(fixture))for(const [metric,val] of Object.entries(metrics)){const key=name+'.'+metric;series[key]=String((await createMetricSeries(ctx,{subjectType:'external_organization',subjectId:companies[name as 'A'],metricKey:metric,name:metric,unit:'currency',currencyCode:'USD',frequency:'annual'})).row.id);observations[key]=String((await recordMetricObservation(ctx,{metricSeriesId:series[key],periodStart:new Date(periodStart),periodEnd:new Date(periodEnd),value:{type:'number',value:val},evidence:sourceRef})).row.id);}
 post=(await import('../../apps/api/app/api/company-brain/[operation]/route')).POST;

 await test('frontier-ordinary-role',{},'actual ordinary PostgreSQL role has no superuser or BYPASSRLS',async()=>withTenantTransaction(tenant,{userId:actor,readOnly:true},async(_db,c)=>{const role=(await c.query('SELECT current_user,rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user')).rows[0];assert.equal(role.current_user,'finnor_app');assert.equal(role.rolsuper,false);assert.equal(role.rolbypassrls,false);return role;}));
 const {JobQueue}=await import('../../apps/worker/src/queue');
 handler=(await import('../../packages/private-equity/src/evidence-execution/worker')).runEvidenceDerivationJob;
 queue=new JobQueue('p4-frontier-worker',3);queue.register('run_evidence_derivation_v1',handler,(await import('../../packages/db/compute-contract')).PRODUCTION_JOB_CONTRACTS.run_evidence_derivation_v1);
 const comparison=await (await import('./frontier-comparison.mts')).frontierComparison({test,api,handles,submit,finish,root,ctx,admin,tenant,actor,companies,series,observations,sourceRef,evidence,repo,periodStart,periodEnd,validAt,fixture,expected,program});
 results.push({id:'actual-equipped-frontier-comparator',status:comparison.status==='PASS_LOCAL_PUBLIC_TASKS'?'PASS':comparison.status==='BLOCKED_EXTERNAL_PROVIDER'?'NOT_RUN_EXTERNAL':'FAIL',observed:{status:comparison.status,completedModelTasks:comparison.completedModelTasks,completedDirectTasks:comparison.completedDirectTasks,reason:comparison.externalBlock,qualification:comparison.qualification},predicate:'actual provider model selects and executes native tools and completes witnessed typed same-Work consumer on paired public tasks'});
  await writeFile(join(evidence,'runtime-manifests.json'),JSON.stringify((await admin.query('SELECT digest,body,created_at FROM finnor_os.p4_runtime_manifests ORDER BY created_at')).rows,null,2));
  await writeFile(join(evidence,'acquisition-attempts.json'),JSON.stringify((await admin.query('SELECT body FROM finnor_os.p4_acquisition_attempts ORDER BY created_at')).rows,null,2));
  await writeFile(join(evidence,'fixture-ids.json'),JSON.stringify({tenant,actor,companies,series,observations},null,2));
}catch(e){results.push({id:'runner-boundary',status:'FAIL',observed:{message:String((e as Error).message),stack:(e as Error).stack}});}
finally{await save();await closePool().catch(()=>undefined);await admin?.end().catch(()=>undefined);await postgres?.stop().catch(()=>undefined);if(process.env.FINNOR_P4_KEEP_DB!=='1')await rm(directory,{recursive:true,force:true});}
const terminalExitCode=results.some(x=>x.status==='FAIL')?1:0;
// Close the runner explicitly after its durable results/stdout flush. Imported
// service lifecycle hooks cannot override the authoritative scored exit code.
await new Promise<void>(yes=>process.stdout.write(JSON.stringify({evidence,status:terminalExitCode?'FAIL':'PASS_LOCAL',cases:results.map(x=>({id:x.id,status:x.status,reason:x.status==='FAIL'?x.observed?.message:undefined}))})+'\n',()=>yes()));
process.exit(terminalExitCode);
