"use client"

import {useCallback,useEffect,useRef,useState} from "react"
import {usePathname,useRouter,useSearchParams} from "next/navigation"
import {centropyPost as jarvisPost,CentropyApiError as JarvisApiError} from "@/components/centropy/lib/api"
import {useCentropyAuth as useJarvisAuth} from "@/components/centropy/lib/centropy-auth"

type Root={entityType:string;entityId:string}
type Witness={id:string;recordId:string;version:string;contentDigest:string;rawValue:string;field:string;anchor:{sheet?:string;cell?:string;page?:number;quote?:string;region?:number[]};modulePath:string[];uncertainty:string[]}
type Output={kind:"scalar"|"table";value:string|null;semantics:{unit:string;currencyCode:string|null}|null;truthClass:"DERIVED_VALUE";witnessIds:string[]}
type Read={queryId:string;workId:string;status:string;reason?:string;derivation:null|{id:string;knowledgeAt:string;validAt:string;coverage:{status:string;globalAbsenceClaimsPermitted:false;reasons:string[]};failure:{predicate:string}|null;result:null|{outputs:Record<string,Output>};independentChecks:Array<{status:string}>;costs:{usd:null;status:string};admission:null;funding:null}}
type Proof={output:Output;witnesses:Witness[];checks:Array<{id:string;method:string;status:string;expected:string|null;actual:string|null;predicate:string}>;program:{nodes:Array<{id:string;op:string}>};coverage:{status:string;reasons:string[]}}
type Program={schema:"finnor.derivation-ir.v1";nodes:Array<Record<string,unknown>>;outputs:string[]}
/** Finite financial grammar, never a host-language expression or execution tool. */
function compileCalculations(text:string):{program:Program;metrics:string[]}{
 const equations=text.split(";").map(s=>s.trim()).filter(Boolean)
 if(!equations.length||equations.length>8)throw Error("Use one to eight calculations separated by semicolons.")
 const parsed=equations.map(s=>{const m=s.match(/^([a-zA-Z][a-zA-Z0-9_]{0,31})\s*=\s*([a-zA-Z][a-zA-Z0-9_]{0,31})\s*([+\-*/])\s*([a-zA-Z][a-zA-Z0-9_]{0,31})$/);if(!m)throw Error("Supported calculation: name = metric +, −, ×, or / metric. Supply an exact period and currency below.");return m})
 const outputs=parsed.map(m=>m[1]);if(new Set(outputs).size!==outputs.length)throw Error("Each calculation needs a unique name.")
 const metrics=[...new Set(parsed.flatMap(m=>[m[2],m[4]]))]
 const nodes:Array<Record<string,unknown>>=metrics.flatMap((metric,i)=>[{id:"rows"+i,op:"source",inputId:"metric"+i},{id:"value"+i,op:"unique",input:"rows"+i}])
 parsed.forEach(m=>nodes.push({id:m[1],op:({"+":"add","-":"subtract","*":"multiply","/":"ratio"} as Record<string,string>)[m[3]],left:"value"+metrics.indexOf(m[2]),right:"value"+metrics.indexOf(m[4]),decimalPlaces:18}))
 if(outputs.some(id=>nodes.slice(0,metrics.length*2).some(n=>n.id===id)))throw Error("Calculation name conflicts with a reserved source name.")
 return {program:{schema:"finnor.derivation-ir.v1",nodes,outputs},metrics}
}

export function EvidenceWorkbench({root,workId}:{root:Root;workId:string|null}){
 const {session}=useJarvisAuth(),router=useRouter(),pathname=usePathname(),search=useSearchParams()
 const identity=(session?.user.id??"signed-out")+":"+root.entityType+":"+root.entityId
 const queryParameter=search.get("evidenceQuery")
 const [question,setQuestion]=useState("Calculate equity and leverage for this company.")
 const [calculations,setCalculations]=useState("equity = EV - debt; leverage = debt / EBITDA")
 const [periodStart,setStart]=useState(""),[periodEnd,setEnd]=useState(""),[currency,setCurrency]=useState("USD")
 const [frequency,setFrequency]=useState("annual"),[mode,setMode]=useState("protected")
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("Choose the exact reporting period.")
 const [queryId,setQueryId]=useState<string|null>(null),[read,setRead]=useState<{identity:string;data:Read}|null>(null),[proof,setProof]=useState<{identity:string;data:Proof}|null>(null)
 const [ackMs,setAckMs]=useState<number|null>(null),generation=useRef(0),identityRef=useRef(identity),container=useRef<HTMLDivElement>(null)
 identityRef.current=identity
 const clear=useCallback(()=>{setRead(null);setProof(null)},[])
 const pin=(id:string)=>{const params=new URLSearchParams(search.toString());params.set("evidenceQuery",id);router.replace(`${pathname}?${params}`,{scroll:false});setQueryId(id)}
 const acknowledge=(text:string)=>{const started=performance.now();clear();setMessage(text);setBusy(true);requestAnimationFrame(()=>setAckMs(performance.now()-started))}
 useEffect(()=>{generation.current++;clear();setQueryId(null);setBusy(false);setMessage("Choose the exact reporting period.");const id=queryParameter;if(id&&/^[0-9a-f-]{36}$/i.test(id))setQueryId(id)},[identity,queryParameter,clear])
 const refresh=useCallback(async(id:string,epoch:number)=>{try{const result=await jarvisPost<Read>("company-brain/evidence-read",{queryId:id});if(epoch!==generation.current||identityRef.current!==identity||document.visibilityState!=="visible")return;setRead({identity,data:result});setMessage(result.status==="TESTED"?"Checked calculation for the selected sources.":result.reason??result.derivation?.failure?.predicate??result.status);setBusy(["QUEUED","RUNNING"].includes(result.status));if(result.status!=="TESTED")setProof(null)}catch(error){if(epoch!==generation.current)return;clear();setBusy(false);setMessage(error instanceof JarvisApiError&&[401,403,404].includes(error.status)?"Evidence is unavailable in your current access scope.":"Evidence could not be revalidated. Values cleared.")}},[identity,clear])
 useEffect(()=>{if(!queryId||!session)return;let timer:ReturnType<typeof setTimeout>;let active=true;const tick=async()=>{if(!active)return;await refresh(queryId,generation.current);if(active)timer=setTimeout(tick,2000)};void tick();const hide=()=>{generation.current++;clear()};const visible=()=>{hide();if(document.visibilityState==="visible")void refresh(queryId,generation.current)};window.addEventListener("pagehide",hide);document.addEventListener("visibilitychange",visible);return()=>{active=false;hide();clearTimeout(timer);window.removeEventListener("pagehide",hide);document.removeEventListener("visibilitychange",visible)}},[queryId,session,refresh,clear])
 const current=read?.identity===identity?read.data:null,shownProof=proof?.identity===identity?proof.data:null
 const result=current?.status==="TESTED"&&current.derivation?.result?current.derivation.result:null
 async function ask(event:React.FormEvent){event.preventDefault();const boundWorkId=workId??current?.workId;const epoch=++generation.current;acknowledge("Question accepted locally. Reading permitted sources…");try{if(!periodStart||!periodEnd||periodStart>periodEnd)throw Error("Select an ordered reporting period.");const {program,metrics}=compileCalculations(calculations);const validAt=new Date(Date.UTC(Number(periodEnd.slice(0,4)),Number(periodEnd.slice(5,7))-1,Number(periodEnd.slice(8,10))+1)).toISOString();const inputs=metrics.map((metricKey,i)=>({inputId:"metric"+i,source:{kind:"metric",subject:root,metricKey,periodStart:periodStart+"T00:00:00.000Z",periodEnd:periodEnd+"T00:00:00.000Z",unit:"currency",currencyCode:currency,frequency,calendar:"OWNER_RECORDED",consolidation:"OWNER_SUBJECT_ONLY",instrument:"UNSPECIFIED",scale:"1",sign:"AS_RECORDED"}}));const handles=await jarvisPost<{handles:Array<{id:string;inputId:string}>}>("company-brain/evidence-handles",{root,validAt,inputs});if(epoch!==generation.current)return;const accepted=await jarvisPost<{queryId:string;workId:string}>("company-brain/evidence-submit",{schema:"finnor.evidence-request.v1",question,root,...(boundWorkId?{workId:boundWorkId}:{}),validAt,idempotencyKey:crypto.randomUUID(),mode,inputs:handles.handles.map(h=>({inputId:h.inputId,handleId:h.id})),program,acceptance:{selectedUniverse:"COMPLETE",absoluteTolerance:"0",materialOutputs:program.outputs}});if(epoch!==generation.current)return;pin(accepted.queryId);setMessage("Durable Work accepted. Calculation pending…")}catch(error){if(epoch!==generation.current)return;clear();setBusy(false);const details=error instanceof JarvisApiError?error.details as {predicate?:string}:null;setMessage(details?.predicate==="PROTECTED_FUNDING_ADMISSION_AND_RUNTIME_BINDINGS_UNAVAILABLE"?"This calculation requires protected funding and runtime admission that are currently unavailable.":error instanceof Error?error.message:"Calculation unavailable.")}}
 async function replay(){if(!queryId)return;const epoch=++generation.current;acknowledge("Rechecking current sources…");try{const accepted=await jarvisPost<{queryId:string}>("company-brain/evidence-replay",{queryId,idempotencyKey:crypto.randomUUID()});if(epoch===generation.current)pin(accepted.queryId)}catch{if(epoch===generation.current){clear();setBusy(false);setMessage("Current source replay unavailable.")}}}
 async function inspect(output:string){if(!queryId)return;setProof(null);const epoch=generation.current;try{const evidence=await jarvisPost<Proof>("company-brain/evidence-witness",{queryId,output});if(epoch===generation.current&&identityRef.current===identity){setProof({identity,data:evidence});requestAnimationFrame(()=>container.current?.querySelector<HTMLElement>("[data-evidence-proof]")?.focus())}}catch{clear();setMessage("The calculation is no longer current. Recheck its sources.")}}
 return <div ref={container} className="ct-evidence" data-ack-ms={ackMs===null?undefined:ackMs.toFixed(2)}>
  <form onSubmit={ask}><label>Financial question<textarea value={question} onChange={e=>setQuestion(e.target.value)} required maxLength={4000}/></label><label>Calculations<input value={calculations} onChange={e=>setCalculations(e.target.value)} required maxLength={1000}/></label><p>Use recorded metric names. Every calculation keeps its exact company, reporting period, currency, and source scope.</p><div className="ct-evidence__fields"><label>Period start<input type="date" value={periodStart} onChange={e=>setStart(e.target.value)} required/></label><label>Period end<input type="date" value={periodEnd} onChange={e=>setEnd(e.target.value)} required/></label><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} pattern="[A-Z]{3}" maxLength={3} required/></label><label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="annual">Annual</option><option value="quarterly">Quarterly</option><option value="monthly">Monthly</option></select></label><label>Execution scope<select value={mode} onChange={e=>setMode(e.target.value)}><option value="protected">Protected execution</option><option value="ordinary_disposable">Disposable local evaluation</option></select></label></div><button type="submit" disabled={busy||!session}>Ask and calculate</button></form>
  <p role="status" aria-live="polite">{message.replaceAll("_"," ").toLowerCase()}</p>
  {queryId?<div className="ct-evidence__actions"><button type="button" disabled={busy} onClick={replay}>Recheck current sources</button><button type="button" disabled={!busy} onClick={async()=>{generation.current++;clear();try{const cancelled=await jarvisPost<{status:string}>("company-brain/evidence-cancel",{queryId});setMessage("Calculation "+cancelled.status.toLowerCase()+". Values cleared.")}catch{setMessage("Cancellation could not be confirmed. Values cleared.")}finally{setBusy(false)}}}>Cancel calculation</button></div>:null}
  {result?<><dl className="ct-evidence__values">{Object.entries(result.outputs).map(([name,output])=><div key={name}><dt>{name}</dt><dd><button type="button" onClick={()=>void inspect(name)} aria-label={`Inspect evidence for ${name}`}>{output.value??"Tabular result"}</button><span>{output.semantics?.currencyCode??output.semantics?.unit} · derived value</span></dd></div>)}</dl><p>Complete for the selected sources. Enterprise-wide coverage is partial. Local cost is unmetered; this result carries no funding or admission.</p><p>Valid at {current?.derivation?.validAt}. Known at {current?.derivation?.knowledgeAt}.</p></>:current?.status==="INVALIDATED"?<p>Source, access, Work, or runtime changed. The earlier values are invalidated.</p>:null}
  {shownProof?<section data-evidence-proof tabIndex={-1} aria-label="Exact evidence witness"><h4>Source witnesses</h4>{shownProof.witnesses.map(w=><article key={w.id}><strong>{w.anchor.sheet&&w.anchor.cell?`${w.anchor.sheet}!${w.anchor.cell}`:w.anchor.page?`Page ${w.anchor.page}`:`Record ${w.recordId}`}</strong><p>{w.field} = {w.rawValue} · version {w.version}</p>{w.anchor.quote?<blockquote>{w.anchor.quote}</blockquote>:null}<small>Digest {w.contentDigest}</small><p>{w.modulePath.join(" → ")}</p><p>{w.uncertainty.join(" · ").replaceAll("_"," ").toLowerCase()}</p></article>)}<h4>Transformations and independent checks</h4><p>{shownProof.program.nodes.map(n=>`${n.id}: ${n.op}`).join(" → ")}</p><ul>{shownProof.checks.map(c=><li key={c.id}>{c.status} · {c.method} · {c.predicate}{c.expected!==null?` · expected ${c.expected}, observed ${c.actual}`:""}</li>)}</ul><button type="button" onClick={()=>setProof(null)}>Close evidence witness</button></section>:null}
 </div>
}
