/** A bounded expression parser. Accepted targets are data, never host code. */
export type ProgramExpression = {kind:'input';key:string}|{kind:'literal';value:string;unit:'multiple'|'currency';currencyCode:string|null}|{kind:'add'|'subtract'|'multiply'|'ratio'|'min'|'max';left:ProgramExpression;right:ProgramExpression}|{kind:'if';condition:{comparison:'lt'|'lte'|'eq'|'gte'|'gt';left:ProgramExpression;right:ProgramExpression};whenTrue:ProgramExpression;whenFalse:ProgramExpression}
type Measure={unit:'currency'|'multiple';currencyCode:string|null}
export function compileProgramTargets(text:string,currencyCode:string){
 if(text.length>4000)throw Error('Calculations exceed the request limit.');
 const definitions=new Map<string,ProgramExpression>(),metrics=new Set<string>(),targets:Array<{key:string;expression:ProgramExpression}&Measure>=[];
 for(const equation of text.split(';').map(v=>v.trim()).filter(Boolean)){
  if(targets.length>=8)throw Error('Use at most eight observable calculations.');
  const assignment=equation.match(/^([A-Za-z][A-Za-z0-9_]{0,63})\s*=\s*(.+)$/);if(!assignment||definitions.has(assignment[1]))throw Error('Each calculation needs a unique name and an expression.');
  const body=assignment[2],tokens:string[]=[];let offset=0;
  while(offset<body.length){if(/\s/.test(body[offset])){offset++;continue;}const token=body.slice(offset).match(/^(?:[A-Za-z][A-Za-z0-9_]{0,63}|\d+(?:\.\d+)?|<=|>=|==|[<>()+\-*/,])/);if(!token||tokens.length>=256)throw Error('Use recorded metrics, numbers, parentheses, min, max, if, comparisons, and arithmetic operators.');tokens.push(token[0]);offset+=token[0].length;}
  let at=0,nodes=0;const take=()=>tokens[at++],peek=()=>tokens[at];
  function factor(depth:number):ProgramExpression{if(depth>12||++nodes>256)throw Error('Calculation expansion exceeds its bound.');const token=take();if(token==='('){const value=expression(depth+1);if(take()!==')')throw Error('Close every parenthesis.');return value;}
   if(token==='if'){if(take()!=='(')throw Error('Use if(comparison, true value, false value).');const left=expression(depth+1),operator=take(),comparison=({'<':'lt','<=':'lte','==':'eq','>=':'gte','>':'gt'} as const)[operator as '<'|'<='|'=='|'>='|'>'];if(!comparison)throw Error('Use <, <=, ==, >= or > in an if condition.');const right=expression(depth+1);if(take()!==',')throw Error('Provide the true result.');const whenTrue=expression(depth+1);if(take()!==',')throw Error('Provide the false result.');const whenFalse=expression(depth+1);if(take()!==')')throw Error('Close the conditional.');return {kind:'if',condition:{comparison,left,right},whenTrue,whenFalse};}
   if(token==='min'||token==='max'){if(take()!=='(')throw Error('Use min(a,b) or max(a,b).');const left=expression(depth+1);if(take()!==',')throw Error('Provide both values.');const right=expression(depth+1);if(take()!==')')throw Error('Close the function.');return {kind:token,left,right};}
   if(token==='USD'||token===currencyCode){if(take()!=='(')throw Error('Use a currency literal such as USD(7).');let value=take();if(value==='-')value='-'+take();if(!/^-?\d+(?:\.\d+)?$/.test(value??'')||take()!==')')throw Error('Provide a finite currency amount.');return {kind:'literal',value,unit:'currency',currencyCode};}
   if(/^\d+(?:\.\d+)?$/.test(token??''))return {kind:'literal',value:token,unit:'multiple',currencyCode:null};
   if(token==='-'){const value=take();if(!/^\d+(?:\.\d+)?$/.test(value??''))throw Error('Unary minus requires a numeric literal.');return {kind:'literal',value:'-'+value,unit:'multiple',currencyCode:null};}
   if(!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(token??'')||token===assignment![1])throw Error('Use an exact metric or an earlier calculated value.');const prior=definitions.get(token);if(prior)return prior;metrics.add(token);return {kind:'input',key:token};}
  function product(depth:number):ProgramExpression{let left=factor(depth);while(peek()==='*'||peek()==='/'){const op=take();left={kind:op==='*'?'multiply':'ratio',left,right:factor(depth+1)};}return left;}
  function expression(depth:number):ProgramExpression{let left=product(depth);while(peek()==='+'||peek()==='-'){const op=take();left={kind:op==='+'?'add':'subtract',left,right:product(depth+1)};}return left;}
  const expr=expression(1);if(at!==tokens.length)throw Error('Unexpected calculation token.');
  function measure(e:ProgramExpression,depth=0):Measure{if(depth>12)throw Error('Expanded calculation exceeds its depth bound.');if(e.kind==='input')return {unit:'currency',currencyCode};if(e.kind==='literal')return e;if(e.kind==='if'){const a=measure(e.condition.left,depth+1),b=measure(e.condition.right,depth+1),yes=measure(e.whenTrue,depth+1),no=measure(e.whenFalse,depth+1);if(a.unit!==b.unit||a.currencyCode!==b.currencyCode||yes.unit!==no.unit||yes.currencyCode!==no.currencyCode)throw Error('Conditional comparisons and alternative results need matching units.');return yes;}const a=measure(e.left,depth+1),b=measure(e.right,depth+1);if(e.kind==='ratio'){if(a.unit!==b.unit||a.currencyCode!==b.currencyCode)throw Error('Ratios need matching units.');return {unit:'multiple',currencyCode:null};}if(e.kind==='multiply'){if(a.unit==='currency'&&b.unit==='currency')throw Error('Multiply a monetary value by a dimensionless value.');return a.unit==='currency'?a:b;}if(a.unit!==b.unit||a.currencyCode!==b.currencyCode)throw Error('Addition and comparison require matching units. Use a currency literal for an amount.');return a;}
  const type=measure(expr);definitions.set(assignment[1],expr);targets.push({key:assignment[1],expression:expr,...type});
 }
 if(!targets.length||!metrics.size||metrics.size>16)throw Error('Use one to sixteen recorded source metrics.');return {targets,metrics:[...metrics]};
}
